### PR TITLE
doc: SCMP authentication specs

### PR DESCRIPTION
**Pull request by matzf**
Add specification for SCMP authentication, following the design proposed in #3969.

References the `Authenticator` End-to-End option header specified in #4014.

[doc]

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)

### CODE REVIEW

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: all files reviewed, 9 unresolved discussions (waiting on @matzf)

___
*[doc/protocols/scmp.rst, line 122 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMAvvg44qBgktxsOlD:-MdMAvvg44qBgktxsOlE:b-w8y5ca) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L122)):*
> ```
> DRKey infrastructure
> ```
This needs a reference.
___
*[doc/protocols/scmp.rst, line 127 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMB6EH4zSQHx7EHme1:-MdMB6EH4zSQHx7EHme2:b-r18r8b) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L127)):*
> ```
> are always
> ```
MUST always be
___
*[doc/protocols/scmp.rst, line 128 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMB9o7CxRyv8o7v_Lj:-MdMB9o7CxRyv8o7v_Lk:bf8pkfw) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L128)):*
> ```
> are optionally
> ```
CAN optionally be
___
*[doc/protocols/scmp.rst, line 129 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBFuk8rHdUGoDxmWZ:-MdMBFuk8rHdUGoDxmW_:bkedv2c) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L129)):*
> ```
> authenticated
> ```
MUST be authenticated if and only if ...
___
*[doc/protocols/scmp.rst, line 132 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBOMADoT3U0SfFJFb:-MdMBOMADoT3U0SfFJFc:bsy8cul) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L132)):*
> ```
> All DRKey keys used here are derived with protocol identifier :code:`scmp`.
> ```
This needs to be explained in more detail with references to the DRKey spec. Also, the "protocol identifier" needs to be made explicit, but that also depends on #4039
___
*[doc/protocols/scmp.rst, line 134 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMByvt7hRT-HXyuk5Q:-MdMByvt7hRT-HXyuk5R:b-jouhrp) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L134)):*
> ```
> AS-to-Host keys
> ```
reference if possible
___
*[doc/protocols/scmp.rst, line 137 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBv32E0NJU57DpTrz:-MdMBv32E0NJU57DpTs-:b-knmxqo) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L137)):*
> ```
> to
> ```
to a router

Also, I think it would make sense to explain why this is different from a packet that is addressed to the router directly.
___
*[doc/protocols/scmp.rst, line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMC0-X0FF8mETxybox:-MdMC0-X0FF8mETxyboy:b-r4ih7) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L140)):*
> ```
> Host-to-Host keys
> ```
reference if possible
___
*[doc/protocols/scmp.rst, line 147 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMCK5g7Z9yxJjfg60G:-MdMCK5g7Z9yxJjfg60H:b-p8y2jt) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L147)):*
> ```
> Echo request
> ```
references

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @matzf and @shitz)

___
*[doc/protocols/scmp.rst, line 122 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMAvvg44qBgktxsOlD:-Me-QZm8Ca1Okx-hNkPZ:bq4ggf) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L122)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> DRKey infrastructure
> ```
This needs a reference.
</blockquote></details>

Done. The DRKey docs are markdown and there does not appear to be a way to create a proper reference here though.
___
*[doc/protocols/scmp.rst, line 127 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMB6EH4zSQHx7EHme1:-Me-Qogm9S33tCCsDS8o:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L127)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> are always
> ```
MUST always be
</blockquote></details>

Done.
___
*[doc/protocols/scmp.rst, line 128 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMB9o7CxRyv8o7v_Lj:-Me-R-hLANBHxoagh2Pj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L128)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> are optionally
> ```
CAN optionally be
</blockquote></details>

Done.
___
*[doc/protocols/scmp.rst, line 129 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBFuk8rHdUGoDxmWZ:-Me-R0JM37TgcIoGrrlR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L129)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> authenticated
> ```
MUST be authenticated if and only if ...
</blockquote></details>

Done.
___
*[doc/protocols/scmp.rst, line 132 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBOMADoT3U0SfFJFb:-Me-qocNBbeu6zhkdlmy:b-jvzrqs) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L132)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> All DRKey keys used here are derived with protocol identifier :code:`scmp`.
> ```
This needs to be explained in more detail with references to the DRKey spec. Also, the "protocol identifier" needs to be made explicit, but that also depends on #4039
</blockquote></details>

Ok. I'll leave this open until the docs for DRKey are updated, as the docs will have to be converted to rst to allow referencing individual terms; I've added a note to the DRKey discussion. 

The changes proposed in #4062 might also clear up the use of the protocol identifier.
___
*[doc/protocols/scmp.rst, line 137 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMBv32E0NJU57DpTrz:-Me-zFZyCnV0YMvX6V7q:b-2vl4dl) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L137)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> to
> ```
to a router

Also, I think it would make sense to explain why this is different from a packet that is addressed to the router directly.
</blockquote></details>

Done (added note after paragraph discussing packets addressed to the router).
___
*[doc/protocols/scmp.rst, line 147 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMCK5g7Z9yxJjfg60G:-Me-zEND3bW6IIhYhajH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L147)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Echo request
> ```
references
</blockquote></details>

Done.

**Comment by marcfrei** [comment]
___
*[doc/protocols/scmp.rst, line 134 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMByvt7hRT-HXyuk5Q:-Mj6-29N6BK9jsG_80eQ:beydc3) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L134)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> AS-to-Host keys
> ```
reference if possible
</blockquote></details>

In the DRKey doc these are now called `AS-host keys`

**Comment by marcfrei** [comment]
___
*[doc/protocols/scmp.rst, line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4017#-MdMC0-X0FF8mETxybox:-Mj6-d-C9TDOJnYxG0-3:b-x07h1b) ([raw file](https://github.com/scionproto/scion/blob/fd2582e2abeb4c13f30d9203fe69b33b2e6be316/doc/protocols/scmp.rst#L140)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Host-to-Host keys
> ```
reference if possible
</blockquote></details>

Now called "host-host keys".

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @shitz)

___
*[`doc/protocols/scmp.rst` line 210 at r2](https://reviewable.io/reviews/scionproto/scion/4017#-N2l3Pg-9eRfld44YeYN:-N2l3Pg-9eRfld44YeYO:bnzqz5r) ([raw file](https://github.com/scionproto/scion/blob/d0cf792a4ee5a493528f74e6428b3dbaa9031fa1/doc/protocols/scmp.rst#L210)):*
> ```reStructuredText
>         during which receivers may accept SCMP error messages without authentication.
> 
>    - The receiver derives or fetches the relevant key for validation, by
> ```

The receiver should also check the SPI information to have the complete information about the intended key to be used, right?
___
*[`doc/protocols/scmp.rst` line 554 at r2](https://reviewable.io/reviews/scionproto/scion/4017#-N2l2qcC80Og7VIPGk8n:-N2l2qcC80Og7VIPGk8o:b-xnbi8h) ([raw file](https://github.com/scionproto/scion/blob/d0cf792a4ee5a493528f74e6428b3dbaa9031fa1/doc/protocols/scmp.rst#L554)):*
> ```reStructuredText
> +--------------+---------------------------------------------------------------+
> 
> Every node MUST implement a SCMP Echo responder function that receives Echo
> ```

This message seems to be duplicated below.
___
*[`doc/protocols/scmp.rst` line 680 at r2](https://reviewable.io/reviews/scionproto/scion/4017#-N2l3BGP2r7omKjqc1R5:-N2l3BGP2r7omKjqc1R6:b-nlqjhg) ([raw file](https://github.com/scionproto/scion/blob/d0cf792a4ee5a493528f74e6428b3dbaa9031fa1/doc/protocols/scmp.rst#L680)):*
> ```reStructuredText
> +--------------+---------------------------------------------------------------+
> 
> The border router is alerted of the Traceroute Request message through the
> ```

Same message above (the first part of this message).

**Review by shitz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @JordiSubira and @shitz)

___
*[`doc/protocols/scmp.rst` line 680 at r2](https://reviewable.io/reviews/scionproto/scion/4017#-N2l3BGP2r7omKjqc1R5:-N6cUGoZBQmQlOAczf00:b-7srhxh) ([raw file](https://github.com/scionproto/scion/blob/d0cf792a4ee5a493528f74e6428b3dbaa9031fa1/doc/protocols/scmp.rst#L680)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Yes that is indeed an oversight. Could you change the type? I don't mind it being part of this PR, but if you prefer doing in a separate one, that's obviously fine as well.
</blockquote></details>

I fixed it.

**Review by shitz — COMMENTED** [review]
> Dismissed @JordiSubira from a discussion.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @JordiSubira and @shitz)

**Review by shitz — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

**Review by shitz — APPROVED** [review]
> Dismissed @JordiSubira from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
