### PR TITLE
Add flag to choose a path in pingpong

### PR DESCRIPTION
**Pull request by sgmonroy**
Basically adding 'interactive' mode, to choose a path.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1429)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/examples/pingpong/pingpong.go, line 299 at r1](https://reviewable.io:443/reviews/scionproto/scion/1429#-L6ufOAlaUQUE-Zel2X4:-L6ufOAlaUQUE-Zel2X5:b5hwl0y) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/pingpong.go#L299)):*
> choosePath
I think you can avoid having to iterate twice over the pathSet
See the PR I did on your branch (feel free to ignore it if you think it does not apply)

---

*[go/examples/pingpong/Readme.md, line 16 at r1](https://reviewable.io:443/reviews/scionproto/scion/1429#-L6ufpzUtg88vPTsWVrQ:-L6ufpzVJ4RCDGdQtMld:bf7qq1f) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/Readme.md#L16)):*
> ```Markdown
> When running the client in interactive mode, the user would be able to choose
> the path used. A side effect is that the application will not adapt to path
> updates, whereas snet will manage path updates whn running in non-interactive
> ```

typo:
when

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1429)*

**Comment by FR4NK-W** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1429)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/examples/pingpong/pingpong.go, line 299 at r1](https://reviewable.io:443/reviews/scionproto/scion/1429#-L6ufOAlaUQUE-Zel2X4:-L6vlvRJJhHDbVn3NH3x:b-vzny0x) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/pingpong.go#L299)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> choosePath
I think you can avoid having to iterate twice over the pathSet
See the PR I did on your branch (feel free to ignore it if you think it does not apply)
</blockquote></details>

This can definitely be simplified. See my comments on #1428 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1429)*

**Comment by sgmonroy** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/examples/pingpong/pingpong.go, line 299 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1429#-L6ufOAlaUQUE-Zel2X4:-L6vsp953_swewWCNaiZ:b-5jux08) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/pingpong.go#L299)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can definitely be simplified. See my comments on #1428 
</blockquote></details>

Agree, will simplify it as suggested.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1429)*

**Comment by sgmonroy** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/examples/pingpong/pingpong.go, line 299 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1429#-L6ufOAlaUQUE-Zel2X4:-L7-tb4k5JfKBTJY_NC0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/pingpong.go#L299)):*
<details><summary><i>Previously, sgmonroy wrote…</i></summary><blockquote>

Agree, will simplify it as suggested.
</blockquote></details>

Done.

---

*[go/examples/pingpong/Readme.md, line 16 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1429#-L6ufpzUtg88vPTsWVrQ:-L7-tbPrArKCAjh3fU2j:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e2c74f9a20664603ed752ae9ea50007c160c5d5/go/examples/pingpong/Readme.md#L16)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

typo:
when
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1429)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1429#-:-L79c37G1NlyTc0_D9YW:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1429)*

**Pull request merged**
