### PR TITLE
Update python infra to use CtrlPld.reqId

### PR DESCRIPTION
**Pull request by kormat**
Also:
- Obsolete SegReq.id, as it's no longer useful.
- Removed a now-unsed random_uint64() function from util, and made a
  similar one in ctrl_pld.py (which specifically avoids 0 as a value).

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1403)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[proto/path_mgmt.capnp, line 11 at r1](https://reviewable.io:443/reviews/scionproto/scion/1403#-L4k5SsxrcD4sZCP7O_k:-L4k5SsxrcD4sZCP7O_l:b-vhbu9v) ([raw file](https://github.com/scionproto/scion/blob/35a1c58c5b765ab6aaff7544bb06d8ea9291a2a2/proto/path_mgmt.capnp#L11)):*
> ```
> 
> struct SegReq {
>     id @0 :UInt64;  # Obsolete.
> ```

Since we are still making breaking changes, why not just remove it from the schema?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1403)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[proto/path_mgmt.capnp, line 11 at r1](https://reviewable.io:443/reviews/scionproto/scion/1403#-L4k5SsxrcD4sZCP7O_k:-L4kx7qfh_1Hx5svP3bt:bkznarb) ([raw file](https://github.com/scionproto/scion/blob/35a1c58c5b765ab6aaff7544bb06d8ea9291a2a2/proto/path_mgmt.capnp#L11)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Since we are still making breaking changes, why not just remove it from the schema?
</blockquote></details>

I had been thinking that we could batch cosmetic breaking changes, but i've just realised that this PR is not actually backwards compatible anyway. Old clients won't be able to talk to new servers, and new clients won't be able to talk to old servers, as they will be looking for request ids in different places. So, removing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1403)*

**Comment by shitz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1403)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1403#-:-L4l9_wr9KHvF-J6p4bF:bnfp4nl)*

**Pull request merged**
