### PR TITLE
cleanup: drop libraries used by old sig

### PR DESCRIPTION
**Pull request by matzf**
Drop various libraries that were exclusively used by the old SIG
implementation and are consequently unused now:
* lib/pathmgr
* lib/pktdisp
* lib/sigdisp
* lib/sigjson
* lib/spath/spathmeta (begone, AppPathSet!)
* pkg/sig

Drop other unused libraries:
* lib/util/bufpool
* lib/xtest/loader
* lib/xtest/loopback
* lib/xtest/p2p

Finally, drop some ancient misc files (vagrant setup related to SIG, topology/PathPolicy.yml).

Note that `proto/sig.capnp` and `lib/ctrl/sig_mgtmt` are not removed here -- it seems to make more sense to remove the entire capn'proto setup in one swoop.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3934)

### CODE REVIEW

**Comment by scrye** [comment]
*[a discussion](https://reviewable.io/reviews/scionproto/scion/3934#-MMteWZt6zlb8Fr0NJR3:-MMteWZt6zlb8Fr0NJR4:bfx0tgk) (no related file):*
Haven't looked at the PR yet, but just want to say from the description this is :100:.

Thanks for submitting this!

---

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3934)* status: 0 of 47 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3934#-MN9MZvnCZ7fmAI-2z1X:-MN9MZvoDID-tKpMcTPM:bs8g8ta) (no related file):*
awesome stuff :100: thank you

---

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 47 of 48 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3934)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
