### PR TITLE
Switch AS representation to v6-style hex encoding.

### LINKED ISSUE #1512: Proposal: Change human-readable formatting of SCION AS numbers
The move to 48bit, globally unique AS identifiers and a numbering scheme that reserves the range`0x000000000000` - `0x0000FFFFFFFF`for BGP AS numbers, has lead to hard to read AS identifiers. E.g., for internal testing we use AS numbers such as `4295002011` which we format as `4_295_002_011`. AS identifiers are ubiquitous in configuration files, file system paths, and log files. Thus, it's of utmost importance that they are easy to read and parse for humans.

I propose a new human-readable formatting scheme for AS identifiers:
* The 48bit AS number is formatted as follows `<upper 16bits as decimal number>.<lower 32bits as decimal number>`, e.g., `4295002011` would be formatted as `1.34715`.
* All grandfathered-in BGP AS numbers would be in the `0.X` range for which we could even drop the `0.` prefix (i.e., no prefix means implicitly `0.`), such that those numbers would be formatted just as current BGP AS identifiers.

Advantages:
I claim that this format is much easier to read for humans. Even though the lower 32 bits could become a large and unwieldy number it's easy to just increase the 16bit 'prefix' to keep numbers small. With current formatting, there is no way around large numbers in the first place. Besides, current AS identifiers could theoretically also span the full 32bit range. Furthermore, it has many practical advantages for testing, development, and local setups, since we could reserve a small range in the `1.` prefix for testing purposes.

### PR DESCRIPTION
**Pull request by kormat**
The full format details are documented here:
https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering

Note that ':' is not a valid path character on windows or OSX, so the
filesystem-representation of an AS number uses '_' instead. The same
applies to supervisor group/program names.

All AS numbers have been mechanically translated:
- The example IA is now 4-ff00:0:2f
- 4_295_00Y_0XX is now AS ff00:0:YXX (test topo addresses)
- 4_294_967_XXX is now AS ff00:0:XXX (examples in code/tests)
The go sciond mock topology's interfaces have been translated from
X0XXY0YY to XXXYYY (i.e. the 0's have been removed).

This fixes #1512

Also:
- Some parts of the hpkt unit tests aren't maintainable as the data they
  are checking is not predictable, so i've commented them out for now.
- Made pktgen.py use a fixed source port, to make it more usable for
  generating testdata.
- Remove the managed-zk functionality from zkls.py as that is no longer
  supported by the generator.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1515)

### CODE REVIEW

**Comment by shitz** [comment]
I like this a lot. Big improvement over the current formatting! :100: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515#-:-L9xwXQK9bVU9jARvpQu:b-vzq4ba)*

**Comment by scrye** [comment]
Reviewed 2 of 91 files at r1.
Review status: 46 of 83 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/README.md, line 27 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWvlP84_tztecxrYTI:-LAWvlP84_tztecxrYTJ:bd5clbf) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/tools/scion-pki/README.md#L27)):*
> ```Markdown
>         ISD1/
>             isd.ini
>             ASff00:0:010/
> ```

This is a bit misleading, because the 010 at the end should have its leading 0 stripped (since folder ..._010 is not the same as ..._10). This is probably an issue in multiple places in this file.

---

*[go/tools/scion-pki/README.md, line 41 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWvwin1KblcgeNcYwA:-LAWvwin1KblcgeNcYwB:b-z74ove) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/tools/scion-pki/README.md#L41)):*
> ```Markdown
> example that `<root>` is the current directory, i.e., `.`.
> 
> `mkdir -p ISD1/ASff00:0:0{10,20,30,11,21,31}`
> ```

Strip leading 0 again?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by kormat** [comment]
Review status: 44 of 84 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/addr/isdas.go, line 57 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWmW2AEJwwE-mG48KU:-LAX3Nn-EmEdNVMt6RZB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/lib/addr/isdas.go#L57)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

A small docstring here would be useful, especially because it isn't immediately obvious what `prefix` does.
</blockquote></details>

Done.

---

*[go/lib/addr/isdas.go, line 76 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWmknG2BgFQUMBHQMt:-LAX3O7e7gRkIUIQJw6L:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/lib/addr/isdas.go#L76)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Same comment as for `ISDFromFileFmt`.
</blockquote></details>

Done.

---

*[go/lib/xtest/graph/graph.go, line 276 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWuXOU4LfpMnL1FXob:-LAX3fmJ6QPg08M8h0GT:b5z5htx) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/lib/xtest/graph/graph.go#L276)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

I realized recently that the IFIDs here overflow 12 bits, which makes them unusable in some tests (e.g., the path combinator tests wants to build Hop Fields from these IFIDs and it can't). They should be changed to smaller numbers. Since ASes are unique, dropping the ISD from the values should be enough.
</blockquote></details>

The ASes are _made_ unique by including the ISD in the AS number. Hence `110` is 'ISD1, core 1'. `210` is 'ISD2, core 1'. We can't map this to 12-bit space directly. We'd have to switch to ~non-obvious IFIDs.

---

*[go/tools/scion-pki/README.md, line 27 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWvlP84_tztecxrYTI:-LAX63pv-JEcAoQC5lNF:b-1do8jy) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/tools/scion-pki/README.md#L27)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

This is a bit misleading, because the 010 at the end should have its leading 0 stripped (since folder ..._010 is not the same as ..._10). This is probably an issue in multiple places in this file.
</blockquote></details>

Good catch, fixed to file-format names too.

---

*[go/tools/scion-pki/README.md, line 41 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWvwin1KblcgeNcYwA:-LAX66n5-OSyq0xf4dbi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/tools/scion-pki/README.md#L41)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Strip leading 0 again?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by shitz** [comment]
Reviewed 25 of 91 files at r1, 3 of 4 files at r2.
Review status: 50 of 84 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/border/rpkt/testdata/README.md, line 5 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAXFSr-9demYZzz5LuO:-LAXFSr-9demYZzz5LuP:b-9pv5jc) ([raw file](https://github.com/scionproto/scion/blob/297bafb5943702ee039f9cdf2a72a6ca48d51249/go/border/rpkt/testdata/README.md#L5)):*
> ```Markdown
> ./tools/pktcap 127.2.2.222 go/border/rpkt/testdata/udp-scion.bin &
> # Wait for it to say Capturing on 'Loopback'
> ./tools/pktgen.py 1-ff00:0:133 127.1.1.111 2-ff00:0:222 127.2.2.222
> ```

Hmm there is a chance that people will interpret `222` as a decimal number and think this would be equivalent to `0xDE`. Do we care about that?

---

*[go/lib/addr/isdas.go, line 75 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAXH7d8A1bMxWfKDIXh:-LAXH7d8A1bMxWfKDIXi:b-bycfp1) ([raw file](https://github.com/scionproto/scion/blob/297bafb5943702ee039f9cdf2a72a6ca48d51249/go/lib/addr/isdas.go#L75)):*
> ```Go
> type AS uint64
> 
> // ASFromString parses an AS from a decimal (in the case of BGP AS numbers) or
> ```

BGP AS numbers is a bit misleading. In this context they are SCION AS numbers, thus I'd probably say something like "... from decimal (in the case where the AS number is < 2**32, i.e., the BGP AS number space)"

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by shitz** [comment]
Reviewed 59 of 91 files at r1, 1 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by scrye** [comment]
Reviewed 34 of 91 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/xtest/graph/graph.go, line 276 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWuXOU4LfpMnL1FXob:-LAXaMpO9Rs-a8Hp-OvV:b-597rus) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/lib/xtest/graph/graph.go#L276)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The ASes are _made_ unique by including the ISD in the AS number. Hence `110` is 'ISD1, core 1'. `210` is 'ISD2, core 1'. We can't map this to 12-bit space directly. We'd have to switch to ~non-obvious IFIDs.
</blockquote></details>

Ok, then in that case let's just use non-obvious IFIDs; mapping the hex encoding of the as number to the base 10 encoding of the IFID is a bit misleading anyway. You don't have to do it here, I can update them when rebasing the path combinator PR on master.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by scrye** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515#-:-LAXcDJx7kQPZfnmWhlQ:bnfp4nl)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/border/rpkt/testdata/README.md, line 5 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAXFSr-9demYZzz5LuO:-LAXacP663rTxmIHjSHY:b-d7maow) ([raw file](https://github.com/scionproto/scion/blob/297bafb5943702ee039f9cdf2a72a6ca48d51249/go/border/rpkt/testdata/README.md#L5)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Hmm there is a chance that people will interpret `222` as a decimal number and think this would be equivalent to `0xDE`. Do we care about that?
</blockquote></details>

Not really, i think? The numbers have the following meaning in our test topo:
- the ISD
- the core AS
- child number
So `222` is ISD 2, core 2, child 2.

It's definitely desirable to keep this scheme (or a similar one), as it makes working with the test topo Much easier.

---

*[go/lib/addr/isdas.go, line 75 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAXH7d8A1bMxWfKDIXh:-LAXcoLkAPuVXphtLFPr:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/297bafb5943702ee039f9cdf2a72a6ca48d51249/go/lib/addr/isdas.go#L75)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

BGP AS numbers is a bit misleading. In this context they are SCION AS numbers, thus I'd probably say something like "... from decimal (in the case where the AS number is < 2**32, i.e., the BGP AS number space)"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by kormat** [comment]
Review status: 83 of 84 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/xtest/graph/graph.go, line 276 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1515#-LAWuXOU4LfpMnL1FXob:-LAXcwxYEFYhqLSPBdya:b-8fx2u7) ([raw file](https://github.com/scionproto/scion/blob/371fa467b93481d4bee5ac6949f84ac7712af660/go/lib/xtest/graph/graph.go#L276)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Ok, then in that case let's just use non-obvious IFIDs; mapping the hex encoding of the as number to the base 10 encoding of the IFID is a bit misleading anyway. You don't have to do it here, I can update them when rebasing the path combinator PR on master.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1515#-:-LAXdnVa3-hx_XOo-yw2:bnfp4nl)*

**Pull request merged**
