### PR TITLE
Initial work of Hidden Path for scionproto/scion

### PR DESCRIPTION
**Pull request by jonghoonkwon**
- .capnp files for hidden path packets
 - python packet libs for hidden path
 - hidden path config class

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1511)

### CODE REVIEW

**Comment by jonghoonkwon** [comment]
@shitz, @juagargi, I just made a PR for the hidden path as an initial work that only includes packet-related codes. It would be nice if you have a time to look at it.
And also, if you don't mind, I can quickly add more commits which are about changes on BS and PS.

**Comment by juagargi** [comment]
Pass done, some comments

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[proto/hp_cfg.capnp, line 7 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9sxJPi8y88qkTEVWVp:-L9sxJPi8y88qkTEVWVq:b-jt3hp0) ([raw file](https://github.com/scionproto/scion/blob/0fbe458f7ea8c8a166988138b2b7e0931db5cf3c/proto/hp_cfg.capnp#L7)):*
> ```
> 
> struct HPCfgId {
>     masterIA @0 :Data;
> ```

It seems we use UInt64 in some other places to identify ASes (e.g. path_mgmt.capnp).

---

*[python/lib/hpcfg_store.py, line 115 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u-sg3CX-_NNBsfjjW:-L9u-sg3CX-_NNBsfjjX:b9esuhv) ([raw file](https://github.com/scionproto/scion/blob/0fbe458f7ea8c8a166988138b2b7e0931db5cf3c/python/lib/hpcfg_store.py#L115)):*
> ```Python
>     def get_hpcfgs(self):
>         res = []
>         for id in self._hpcfgs:
> ```

Maybe you want to lock also here, to have a consistent view of self._hpcfgs

---

*[python/lib/hpcfg_store.py, line 127 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u1FWb7Xt5MdB1xY-u:-L9u1FWb7Xt5MdB1xY-v:b9px3xj) ([raw file](https://github.com/scionproto/scion/blob/0fbe458f7ea8c8a166988138b2b7e0931db5cf3c/python/lib/hpcfg_store.py#L127)):*
> ```Python
>     def get_hpcfg_ids(self):
>         res = []
>         for id in self._hpcfg_ids:
> ```

Maybe you want to lock also here

---

*[python/lib/packet/packet_base.py, line 137 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u5g27B7_A9Gb30zhk:-L9u5g27B7_A9Gb30zhl:b3kre) ([raw file](https://github.com/scionproto/scion/blob/0fbe458f7ea8c8a166988138b2b7e0931db5cf3c/python/lib/packet/packet_base.py#L137)):*
> ```Python
> 
>     def __eq__(self, other):  # pragma: no cover
>         raise self.p == other.p
> ```

?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1511#-:-L9u4NdCByr0TcvGMt12:b27zpc)*

**Comment by jonghoonkwon** [comment]
@juagargi, I addressed the issue for the AS address type in the .capnp file.
I left what I think about the other comments you made.
Thanks for the comments.

---

Review status: 13 of 15 files reviewed at latest revision, 4 unresolved discussions.

---

*[proto/hp_cfg.capnp, line 7 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9sxJPi8y88qkTEVWVp:-L9yLHwnAob5kBoafxKP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/771bb419ab359da399cb0aca3a88248234334e1c/proto/hp_cfg.capnp#L7)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

It seems we use UInt64 in some other places to identify ASes (e.g. path_mgmt.capnp).
</blockquote></details>

Done.

---

*[python/lib/hpcfg_store.py, line 115 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u-sg3CX-_NNBsfjjW:-L9yLIwJD1yHrooQ4FyR:b91monc) ([raw file](https://github.com/scionproto/scion/blob/771bb419ab359da399cb0aca3a88248234334e1c/python/lib/hpcfg_store.py#L115)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Maybe you want to lock also here, to have a consistent view of self._hpcfgs
</blockquote></details>

Main Scion codebase works in the way that doesn't lock in an iterator, so I'd like to follow the same convention here.

---

*[python/lib/hpcfg_store.py, line 127 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u1FWb7Xt5MdB1xY-u:-L9yM36nDgvlQlAi-UxG:b-3cz4ey) ([raw file](https://github.com/scionproto/scion/blob/771bb419ab359da399cb0aca3a88248234334e1c/python/lib/hpcfg_store.py#L127)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

Maybe you want to lock also here
</blockquote></details>

Same above.

---

*[python/lib/packet/packet_base.py, line 137 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1511#-L9u5g27B7_A9Gb30zhk:-L9yM5xV1uwAgfO0fS8v:b-ukmukh) ([raw file](https://github.com/scionproto/scion/blob/771bb419ab359da399cb0aca3a88248234334e1c/python/lib/packet/packet_base.py#L137)):*
<details><summary><i>Previously, juagargi (Juan A. García Pardo Giménez de los Galanes) wrote…</i></summary><blockquote>

?
</blockquote></details>

It's my mistake. I changed it to how it looks like previously.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1511#-:-L9yMUAT78oM8oo23u2b:b-v7vkv1)*

**Comment by lukedirtwalker** [comment]
The design is now agreed upon and merged into the Repo. The implementation will only be done in go code. And is currently being worked on. So I think we can close this.

**Pull request closed without merging**
