### PR TITLE
build: generate docs with write_source_files

### PR DESCRIPTION
**Pull request by oncilla**
Use write_source_files to generate the docs. The write_source_files comes with automatic tests that the generated files are up to date. We create a wrapper in tools/lint which checks that the generated files are up to date if we run bazel test with --config=lint.

`make lint` checks that the `write_all` target is up to date with all the additional targets to run.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 7 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: 7 of 53 files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`BUILD.bazel` line 122 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYF6EF6SOdIViuqbHJ:-NYYF6EF6SOdIViuqbHK:bf4n74c) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/BUILD.bazel#L122)):*
> ```Starlark
> updatesrc_update_all(
>     name = "update_all",
> )
> ```

Can we remove this now?
___
*[`BUILD.bazel` line 127 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYKbTX7S_5oIO9xCLf:-NYYKbTX7S_5oIO9xCLg:bxwxukk) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/BUILD.bazel#L127)):*
> ```Starlark
> # bazel run @com_github_bazelbuild_buildtools//buildozer -- --root_dir $PWD  "add additional_update_targets $( bazel query 'filter("^.*[^\d]$", kind(_write_source_file, //...)) except //:write_all' | tr '\n' ' ')" //:write_all
> write_source_files(
>     name = "write_all",
> ```

I see this is the target name suggested in the documentation for `write_source_files` but I find this rather cryptic. 
Could we make it `write_all_source_files` or `write_source_files` or something else that hints at the idea of generated source files?
___
*[`Makefile` line 67 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYNUnAD27egiujgwtl:-NYYNUnAD27egiujgwtm:b6bybhf) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L67)):*
> ```Makefile
> 
> antlr:
> 	antlr/generate.sh $(GAZELLE_MODE)
> ```

Is the idea that we'll eventually transition the existing ad-hoc source-file generation scripts (`protobuf`, `mocks`, `antlr`, `licenses`?) over to this new mechanism?
___
*[`Makefile` line 70 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYK9Kv0cPKHpmORA2Y:-NYYK9Kv0cPKHpmORA2Z:b-d4or33) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L70)):*
> ```Makefile
> 
> write_all:
> 	bazel run //:write_all
> ```

Same comment as on `write_all` bazel target, this make target name is a bit nondescript. If we want to keep this generic, my suggestion would be something along the lines of `make generated-source-files`.

Also: this is `.PHONY` and should be inserted to `all:`.
___
*[`Makefile` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYDHOTAmE7QNQqJuFe:-NYYDHOTAmE7QNQqJuFf:undefined) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L102)):*
> ```Makefile
> 		tools/quiet docker run --tty=$$tty --rm -v "${PWD}:/src" returntocorp/semgrep@sha256:3bef9d533a44e6448c43ac38159d61fad89b4b57f63e565a8a55ca265273f5ba semgrep --config=/src/tools/lint/semgrep --error
> 
> lint-bazel: lint-bazel-buildifier
> ```





_Suggestion:_
```Makefile
lint-bazel: lint-bazel-buildifier lint-bazel-writeall
```
___
*[`tools/lint/write_source_files_sync` line 4 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYDSu3De08GcxRIyfF:-NYYDSu3De08GcxRIyfG:b-6g2wa8) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/tools/lint/write_source_files_sync#L4)):*
> ```
> 
> ROOT="$(bazel info workspace 2> /dev/null)"
> diff -Nu3 <(cat $ROOT/BUILD.bazel) <(bazel run  @com_github_bazelbuild_buildtools//buildozer -- --root_dir $ROOT --stdout "add additional_update_targets $(bazel query  'filter("^.*[^\d]$", kind(_write_source_file, //...)) except //:write_all' | tr '\n' ' ')" //:write_all)
> ```

Can you add a brief comment on what this does please. Without context, this is cryptic as...

The `<(cat  filename)` is just `filename`, or what is happening here?

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: all files reviewed, 7 unresolved discussions (waiting on @oncilla)

___
*[`WORKSPACE` line 36 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYOYuU9lWCMrOF57NT:-NYYOYuU9lWCMrOF57NU:bqnkbhz) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/WORKSPACE#L36)):*
> ```Starlark
>     sha256 = "be236556c7b9c7b91cb370e837fdcec62b6e8893408cd4465ae883c9d7c67024",
>     strip_prefix = "bazel-lib-1.18.0",
>     url = "https://github.com/aspect-build/bazel-lib/archive/refs/tags/v1.18.0.tar.gz",
> ```

why no use the latest version? https://github.com/aspect-build/bazel-lib/releases/tag/v1.32.1?

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: 48 of 53 files reviewed, 7 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[`BUILD.bazel` line 122 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYF6EF6SOdIViuqbHJ:-NYb3_sbES2CvhdisqB3:bgksp71) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/BUILD.bazel#L122)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Can we remove this now?
</blockquote></details>

This is still used to update all the openapi specs AFAIU.
But it would be neat to transition that also to the aspect library.
___
*[`BUILD.bazel` line 127 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYKbTX7S_5oIO9xCLf:-NYb4yRp7p7zaSXURDdQ:bzeyi24) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/BUILD.bazel#L127)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I see this is the target name suggested in the documentation for `write_source_files` but I find this rather cryptic. 
Could we make it `write_all_source_files` or `write_source_files` or something else that hints at the idea of generated source files?
</blockquote></details>

Sure. 
___
*[`Makefile` line 67 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYNUnAD27egiujgwtl:-NYb5GcN6Iqcpeng_5aL:blqcc6c) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L67)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Is the idea that we'll eventually transition the existing ad-hoc source-file generation scripts (`protobuf`, `mocks`, `antlr`, `licenses`?) over to this new mechanism?
</blockquote></details>

I think eventually we should not have an ad-hoc source copying of source files anymore.
But I would leave this for follow ups. TBH, they are very low friction given how rarely the source files change.

The docs are a good place to start the transition, because I see them changing the most.
___
*[`Makefile` line 70 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYK9Kv0cPKHpmORA2Y:-NYb5wNk-Bpp5sxoNCP1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L70)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Same comment as on `write_all` bazel target, this make target name is a bit nondescript. If we want to keep this generic, my suggestion would be something along the lines of `make generated-source-files`.

Also: this is `.PHONY` and should be inserted to `all:`.
</blockquote></details>

Done.
___
*[`Makefile` line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYDHOTAmE7QNQqJuFe:-NYb63LR0SwS2bXTQX2l:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L102)):*
> ```Makefile
> 		tools/quiet docker run --tty=$$tty --rm -v "${PWD}:/src" returntocorp/semgrep@sha256:3bef9d533a44e6448c43ac38159d61fad89b4b57f63e565a8a55ca265273f5ba semgrep --config=/src/tools/lint/semgrep --error
> 
> lint-bazel: lint-bazel-buildifier
> ```

Done.
___
*[`WORKSPACE` line 36 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYOYuU9lWCMrOF57NT:-NYb64WDAluUJzloenAc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/WORKSPACE#L36)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why no use the latest version? https://github.com/aspect-build/bazel-lib/releases/tag/v1.32.1?
</blockquote></details>

Done.
___
*[`tools/lint/write_source_files_sync` line 4 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYDSu3De08GcxRIyfF:-NYbIwaH86h1FDDyZS1J:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/tools/lint/write_source_files_sync#L4)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Can you add a brief comment on what this does please. Without context, this is cryptic as...

The `<(cat  filename)` is just `filename`, or what is happening here?


</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: all files reviewed, 6 unresolved discussions (waiting on @matzf)

**Review by matzf — APPROVED** [review]
> Reviewed 46 of 53 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

___
*[`BUILD.bazel` line 122 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYF6EF6SOdIViuqbHJ:-NYq_ZAN3g_6-cL-5gYt:bhsimv2) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/BUILD.bazel#L122)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This is still used to update all the openapi specs AFAIU.
But it would be neat to transition that also to the aspect library.
</blockquote></details>

All clear, thanks :thumbsup: 
___
*[`Makefile` line 67 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYNUnAD27egiujgwtl:-NYq_g4p0GryvyMLrkOz:b4c9lyr) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/Makefile#L67)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I think eventually we should not have an ad-hoc source copying of source files anymore.
But I would leave this for follow ups. TBH, they are very low friction given how rarely the source files change.

The docs are a good place to start the transition, because I see them changing the most.
</blockquote></details>

:thumbsup: 
___
*[`tools/lint/write_source_files_sync` line 4 at r1](https://reviewable.io/reviews/scionproto/scion/4357#-NYYDSu3De08GcxRIyfF:-NYqb4RX1I6aIx4EbQ6w:bjwa7hh) ([raw file](https://github.com/scionproto/scion/blob/c65111cab549f840d3b6c41dfe116b0535d3d3d0/tools/lint/write_source_files_sync#L4)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:tada:

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4357)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
