### PR TITLE
scion-pki: enable kms support

### PR DESCRIPTION
**Pull request by oncilla**
Enable the scion-pki tool to interact with various cloud KMS and HSMs through the step-kms-plugin. The step-kms-plugin must be installed and available in the PATH.

For more information about step-kms-plugin, please refer to the documentation at https://github.com/smallstep/step-kms-plugin.

To see example usage of step-kms-plugin, please
refer to
https://smallstep.com/docs/step-ca/cryptographic-protection

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4617)

**Comment by oncilla** [comment]
FWIW. I think longterm we should just migrate to using step directly and provide scion specific things via plugins, rather than maintain our own scion-pki tool.

**Review by jiceatscion — CHANGES_REQUESTED** [review]
> Reviewed 28 of 32 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4617)* status: all files reviewed, 7 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`doc/command/scion-pki/scion-pki_kms.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78L27JCsOKY7TgL8tv:-O78L27K2if8pUXDIqp9:b-14ih8l) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/doc/command/scion-pki/scion-pki_kms.rst#L14)):*
> ```reStructuredText
> 
> 
> This command leverages the step-kms-plugin to interact with the cloud KMS and HSMs.
> ```

Spell out KMS and HSM at least once:
"This command leverages the step-kms-plugin to interact with cloud Key Management Systems (KMS) and Hardware Security Modules (HSM)."
___
*[`scion-pki/certs/create.go` line 210 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78M1n_Ekt9CP7-G6Sg:-O78M1n_Ekt9CP7-G6Sh:b3dkq06) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L210)):*
> ```Go
> 			}
> 			if flags.existingKey == "" && flags.kms != "" {
> 				return serrors.New("kms flag is only allowed with existing key")
> ```

"The kms flag is only allowed with an existing key."
___
*[`scion-pki/certs/create.go` line 244 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MGtVB36Zpcc6hNtJ:-O78MGtVB36Zpcc6hNtK:b-opgkme) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L244)):*
> ```Go
> 			}
> 			if !key.IsX509Signer(privKey) {
> 				return serrors.New("private key cannot be used in X.509 certificates",
> ```

"A private key cannot be used in X.509 certificates."
___
*[`scion-pki/certs/create.go` line 267 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MQNE2bmOgHSFbOGM:-O78MQNE2bmOgHSFbOGN:b-jhjg8t) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L267)):*
> ```Go
> 			}
> 			if !key.IsX509Signer(caKey) {
> 				return serrors.New("CA key cannot be used to create X.509 certificates",
> ```

"A CA key cannot be used to create X.509 certificates."
___
*[`scion-pki/certs/sign.go` line 125 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MmxZBjohTEIcLJ1w:-O78MmxZBjohTEIcLJ1x:b-5t85w2) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/sign.go#L125)):*
> ```Go
> 			}
> 			if !key.IsX509Signer(caKey) {
> 				return serrors.New("CA key cannot be used to create X.509 certificates",
> ```

Ditto; use articles.
___
*[`scion-pki/cmd/scion-pki/kms.go` line 1 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78Mzyd0ftyINWDKOPt:-O78Mzyd0ftyINWDKOPu:bb6ht39) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/cmd/scion-pki/kms.go#L1)):*
> ```Go
> // Copyright 2020 Anapaya Systems
> ```

2024
___
*[`scion-pki/cmd/scion-pki/kms.go` line 111 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78Np6KBuxQhErz-VeS:-O78Np6KBuxQhErz-VeT:b-dd39t1) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/cmd/scion-pki/kms.go#L111)):*
> ```Go
> func rpad(s string, padding int) string {
> 	formattedString := fmt.Sprintf("%%-%ds", padding)
> 	return fmt.Sprintf(formattedString, s)
> ```

I think there's a linter check that objects to not using litteral strings as formats. (With some good reasons, albeit not applicable here). May-be there's way around that with a "*", like Sprintf("%-*s", padding, s) (I honestly never used that, just found it in the fmt pkg doc)

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4617)* status: all files reviewed, 7 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`doc/command/scion-pki/scion-pki_kms.rst` line 14 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78L27JCsOKY7TgL8tv:-O79dmyQ9IxVNus_uh0s:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/doc/command/scion-pki/scion-pki_kms.rst#L14)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Spell out KMS and HSM at least once:
"This command leverages the step-kms-plugin to interact with cloud Key Management Systems (KMS) and Hardware Security Modules (HSM)."
</blockquote></details>

Done.
___
*[`scion-pki/certs/create.go` line 210 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78M1n_Ekt9CP7-G6Sg:-O79doSBDnZ_QWqxQnXv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L210)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

"The kms flag is only allowed with an existing key."
</blockquote></details>

Done.
___
*[`scion-pki/certs/create.go` line 244 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MGtVB36Zpcc6hNtJ:-O79duTqD1LZKuquhyZ8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L244)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

"A private key cannot be used in X.509 certificates."
</blockquote></details>

Done.
___
*[`scion-pki/certs/create.go` line 267 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MQNE2bmOgHSFbOGM:-O79dvCCAYgXxHlcMuIB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/create.go#L267)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

"A CA key cannot be used to create X.509 certificates."
</blockquote></details>

Done.
___
*[`scion-pki/certs/sign.go` line 125 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78MmxZBjohTEIcLJ1w:-O79dwTZ7qknbh0d_rNH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/certs/sign.go#L125)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Ditto; use articles.
</blockquote></details>

Done.
___
*[`scion-pki/cmd/scion-pki/kms.go` line 1 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78Mzyd0ftyINWDKOPt:-O79dx75B72q_Rwi5NMj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/cmd/scion-pki/kms.go#L1)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done.
___
*[`scion-pki/cmd/scion-pki/kms.go` line 111 at r3](https://reviewable.io/reviews/scionproto/scion/4617#-O78Np6KBuxQhErz-VeS:-O79dxLT0h00wHvDKqXo:b-ubtfne) ([raw file](https://github.com/scionproto/scion/blob/0ea2b3a832baec3bc0d8e3f424df0186dd4a2370/scion-pki/cmd/scion-pki/kms.go#L111)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I think there's a linter check that objects to not using litteral strings as formats. (With some good reasons, albeit not applicable here). May-be there's way around that with a "*", like Sprintf("%-*s", padding, s) (I honestly never used that, just found it in the fmt pkg doc)
</blockquote></details>

Done. (originally copied from cobra source)

**Review by jiceatscion — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by oncilla — COMMENTED** [review]
> Reviewed 22 of 32 files at r1, 2 of 4 files at r3, 4 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Pull request merged**
