### PR TITLE
[doc] BFD/SCION protocol specification

### PR DESCRIPTION
**Pull request by sustrik**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 1 unresolved discussion (waiting on @sustrik)

___
*[doc/protocols/scion-header.rst, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/3873#-MGwEWMaEwk88N9ok9Uk:-MGwEWMaEwk88N9ok9Ul:b-1scmbg) ([raw file](https://github.com/scionproto/scion/blob/5dfb0525b0c8c436155f6c7bdab6f249bc967580/doc/protocols/scion-header.rst#L58)):*
> ```reStructuredText
>     The PathType specifies the SCION path type with up to 256 different types.
>     The format of each path type is independent of each other. The initially
>     proposed SCION path types are SCION (0), OneHopPath (1), EPIC (2) and
> ```

Can we also change this here? Empty = 0, SCION = 1, OHP = 2, etc ?

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[doc/protocols/scion-header.rst, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/3873#-MGwEWMaEwk88N9ok9Uk:-MGwIhU_2XNsqLijTAKs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5dfb0525b0c8c436155f6c7bdab6f249bc967580/doc/protocols/scion-header.rst#L58)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Can we also change this here? Empty = 0, SCION = 1, OHP = 2, etc ?
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by karampok** [comment]
___
*[doc/protocols/bfd.rst, line 45 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwPG0-8x08rr4Dm-gG:-MGwPG008nJzjSpu3w_k:bmbdwwt) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L45)):*
> ```reStructuredText
> SCION router instance creates one "external" BFD session for each SCION
> interface that it owns. Its BFD peer is the SCION router in the neighbouring
> AS. The associated BFD packets must use SCION OneHopPath type.
> ```

what is the content of the OneHopPath? and how is it being used?

**Comment by karampok** [comment]
___
*[doc/protocols/bfd.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwQbx-6BdmmgUMl5af:-MGwQbx07jFnCP6lODj2:b2imljf) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L54)):*
> ```reStructuredText
> EmptyPath type.
> 
> These BFD sessions are uniquely identified by the source address, as it appears
> ```

The source address as it appears in the SCION header is the same address we have when we initialize the  router?
https://github.com/Anapaya/scion/blob/anapaya/go/pkg/router/connector.go#L63

**Comment by karampok** [comment]
___
*[doc/protocols/bfd.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwRPvy7fkoEf7zIPnT:-MGwRPvy7fkoEf7zIPnU:bdh1pax) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L54)):*
> ```reStructuredText
> EmptyPath type.
> 
> These BFD sessions are uniquely identified by the source address, as it appears
> ```

 The source address as it appears in the SCION header is the same address we have when we initialize the  router?

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 3 unresolved discussions (waiting on @karampok, @sgmonroy, and @shitz)

___
*[doc/protocols/bfd.rst, line 45 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwPG0-8x08rr4Dm-gG:-MGwez5L82UNgA4F6-7q:b-z5748q) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L45)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

what is the content of the OneHopPath? and how is it being used?
</blockquote></details>

That's part of SCION header specification: https://internal.docs.anapaya.net/en/latest/src/protocols/scion-header.html#path-type-onehoppath
___
*[doc/protocols/bfd.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwQbx-6BdmmgUMl5af:-MGwevQs8imtzCiSZafh:b2nign6) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L54)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

The source address as it appears in the SCION header is the same address we have when we initialize the  router?
https://github.com/Anapaya/scion/blob/anapaya/go/pkg/router/connector.go#L63
</blockquote></details>

yes
___
*[doc/protocols/bfd.rst, line 54 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwRPvy7fkoEf7zIPnT:-MGwewA6-fxKQfoajJl4:b2nign6) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L54)):*
<details><summary><i>Previously, karampok (Konstantinos) wrote…</i></summary><blockquote>

 The source address as it appears in the SCION header is the same address we have when we initialize the  router?
</blockquote></details>

yes

**Review by shitz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 11 unresolved discussions (waiting on @karampok, @sgmonroy, and @sustrik)

___
*[doc/protocols/bfd.rst, line 24 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnMYsAn6W0ncVSuHz:-MGwnMYsAn6W0ncVSuI-:b-pxb19q) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L24)):*
> ```reStructuredText
>     | SCION address header |
>     +----------------------+
>     |      SCION path      |
> ```

header
___
*[doc/protocols/bfd.rst, line 35 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnS6rCqKSBjpEb0El:-MGwnS6rCqKSBjpEb0Em:b-9mhki1) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L35)):*
> ```
> be
> ```
by
___
*[doc/protocols/bfd.rst, line 45 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwPG0-8x08rr4Dm-gG:-MGwnbm-C76QfL-iLZex:b6ddcc7) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L45)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

That's part of SCION header specification: https://internal.docs.anapaya.net/en/latest/src/protocols/scion-header.html#path-type-onehoppath
</blockquote></details>

Maybe add a link to the spec. Also, use https://scion.docs.anapaya.net/...
___
*[doc/protocols/bfd.rst, line 48 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoh4S1eUVxdFRIJN2:-MGwoh4S1eUVxdFRIJN3:b-8pb06b) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L48)):*
> ```
> was received on.
> ```
Theoretically, you could have multiple remote IFIDs per local IFID, thus it's the combination of IFIDs that uniquely identify the session.
___
*[doc/protocols/bfd.rst, line 50 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnqi9DO7HKxsJ5Q3n:-MGwnqi9DO7HKxsJ5Q3o:b-xl10jf) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L50)):*
> ```
> SCION border router
> ```
SCION router
___
*[doc/protocols/bfd.rst, line 52 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnvZr-YSh-EEI-2vE:-MGwnvZr-YSh-EEI-2vF:b-w6mtdj) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L52)):*
> ```
> EmptyPath type
> ```
Also add a link to the spec.
___
*[doc/protocols/bfd.rst, line 58 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwo3fIEmXAdvUOgalC:-MGwo3fIEmXAdvUOgalD:btk6moz) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L58)):*
> ```
> border router.
> ```
SCION router
___
*[doc/protocols/scion-header.rst, line 411 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoKLD-Pj3SG9i0unm:-MGwoKLEAT3jdZVcKjN1:babhv8z) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/scion-header.rst#L411)):*
> ```
> It has no additional fields.
> ```
..., i.e., it consumes 0 bytes on the wire.
___
*[doc/protocols/scion-header.rst, line 412 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoPs179j3_8sdLgOG:-MGwoPs179j3_8sdLgOH:b-se3e9k) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/scion-header.rst#L412)):*
> ```
> Keep in mind that address header is still present and must be correctly filled in.
> ```
This sentence is superfluous. The path has nothing to do with the address header.

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 10 unresolved discussions (waiting on @karampok, @sgmonroy, and @shitz)

___
*[doc/protocols/bfd.rst, line 24 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnMYsAn6W0ncVSuHz:-MGwzD5B9coasEqFzwOg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L24)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

header
</blockquote></details>

Done.
___
*[doc/protocols/bfd.rst, line 35 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnS6rCqKSBjpEb0El:-MGwziBn1rHSyC8m1vYD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L35)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> be
> ```
by
</blockquote></details>

Done.
___
*[doc/protocols/bfd.rst, line 48 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoh4S1eUVxdFRIJN2:-MGx0xM494nzUH_tOsX7:b-pc4o74) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L48)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> was received on.
> ```
Theoretically, you could have multiple remote IFIDs per local IFID, thus it's the combination of IFIDs that uniquely identify the session.
</blockquote></details>

There's only one remote IFID, as discussed in person.
___
*[doc/protocols/bfd.rst, line 50 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnqi9DO7HKxsJ5Q3n:-MGx-1u02dvTVlgr3z-U:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L50)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> SCION border router
> ```
SCION router
</blockquote></details>

Done.
___
*[doc/protocols/bfd.rst, line 52 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwnvZr-YSh-EEI-2vE:-MGx3OPD3o-QncOGSV14:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L52)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> EmptyPath type
> ```
Also add a link to the spec.
</blockquote></details>

Done.
___
*[doc/protocols/bfd.rst, line 58 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwo3fIEmXAdvUOgalC:-MGx-4qi9AkagIbGioKp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/bfd.rst#L58)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> border router.
> ```
SCION router
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 411 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoKLD-Pj3SG9i0unm:-MGx-IoA1dZ6yNk-K8Zo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/scion-header.rst#L411)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> It has no additional fields.
> ```
..., i.e., it consumes 0 bytes on the wire.
</blockquote></details>

Done.
___
*[doc/protocols/scion-header.rst, line 412 at r2](https://reviewable.io/reviews/scionproto/scion/3873#-MGwoPs179j3_8sdLgOG:-MGx-J5-2XrwCbkcu8uy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/352abaa52ce778447a93cca207ce419c7e925810/doc/protocols/scion-header.rst#L412)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Keep in mind that address header is still present and must be correctly filled in.
> ```
This sentence is superfluous. The path has nothing to do with the address header.
</blockquote></details>

Done.

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 3 unresolved discussions (waiting on @karampok, @sgmonroy, and @sustrik)

___
*[doc/protocols/bfd.rst, line 40 at r3](https://reviewable.io/reviews/scionproto/scion/3873#-MGxHMqE4vAiIBLGkFAb:-MGxHMqFBVKfxiwbVPTH:b-agv8lf) ([raw file](https://github.com/scionproto/scion/blob/586f73ef6c498adafd42a2a966c6b097b5cd3f91/doc/protocols/bfd.rst#L40)):*
> ```
> Bootstrapping in SCION Router
> ```
Somewhere you should mention that `Your Discrimantor` (or `My Discriminator` in the reply packet) is chosen randomly.

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @karampok, @sgmonroy, and @shitz)

___
*[doc/protocols/bfd.rst, line 40 at r3](https://reviewable.io/reviews/scionproto/scion/3873#-MGxHMqE4vAiIBLGkFAb:-MGxJekd9bqN0dHF_X9F:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/586f73ef6c498adafd42a2a966c6b097b5cd3f91/doc/protocols/bfd.rst#L40)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> Bootstrapping in SCION Router
> ```
Somewhere you should mention that `Your Discrimantor` (or `My Discriminator` in the reply packet) is chosen randomly. 
</blockquote></details>

Done.

**Review by karampok — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873)* status: all files reviewed, 1 unresolved discussion (waiting on @sgmonroy and @shitz)

**Review by shitz — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3873#-:-MHFTJV-0bg-v6SLAVn9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sgmonroy)

**Pull request merged**
