### PR TITLE
Make it easy for an app to get the local ASInfo from sciond.

### PR DESCRIPTION
**Pull request by kormat**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1442)

### CODE REVIEW

**Comment by scrye** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/snet/snet.go, line 95 at r1](https://reviewable.io:443/reviews/scionproto/scion/1442#-L75SF07ObSYSfR1U9EO:-L75SF08y85f_zIS78nn:b-8a4a8m) ([raw file](https://github.com/scionproto/scion/blob/5c942173a05dc7f503d2f387d6837c2c68d0e365/go/lib/snet/snet.go#L95)):*
> ```Go
> // Path resolver.
> type Network struct {
> 	sciond         *sciond.Service
> ```

A pointer is not needed here, as `sciond.Service` is an interface.

---

*[go/lib/snet/snet.go, line 259 at r2](https://reviewable.io:443/reviews/scionproto/scion/1442#-L75TBL8G04qj3lo_HyK:-L75TBL8G04qj3lo_HyL:b2nreh6) ([raw file](https://github.com/scionproto/scion/blob/e57865ff1ca215754284c56c39436e309b9d027b/go/lib/snet/snet.go#L259)):*
> ```Go
> 
> // Sciond returns the sciond.Service that the network is using.
> func (n *Network) Sciond() *sciond.Service {
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1442)*

**Comment by kormat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/snet/snet.go, line 95 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1442#-L75SF07ObSYSfR1U9EO:-L75TaUz3hBuxQ01AxUy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5c942173a05dc7f503d2f387d6837c2c68d0e365/go/lib/snet/snet.go#L95)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

A pointer is not needed here, as `sciond.Service` is an interface.
</blockquote></details>

Done.

---

*[go/lib/snet/snet.go, line 259 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1442#-L75TBL8G04qj3lo_HyK:-L75Tb0RAYAE4VrbV1eJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e57865ff1ca215754284c56c39436e309b9d027b/go/lib/snet/snet.go#L259)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1442)*

**Comment by scrye** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1442#-:-L75UrAf7eeY2NTSa_fW:bnfp4nl)*

**Comment by scrye** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1442)*

**Pull request merged**
