### PR TITLE
scion-pki: Add option to configure signing algorithms for online/offline keys

### LINKED ISSUE #1492: Make the signing algorithms for online/offline keys configurable.
Currently, the signing algorithms that are used with the online/offline keys are hardcoded to `ed25519`. The AS configuration (`as.ini`) should have a fields to make this configurable.

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #1492

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmwhlP-nkH7aPTpRiE:-LAmwhlP-nkH7aPTpRiF:bd5tegi) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/conf/as.go#L83)):*
> ```Go
> 	if core {
> 		ibc := NewTemplateCertConf(trcVer)
> 		a.IssuerCert = &IssuerCert{BaseCert: ibc, OnlineKeyAlg: "ed25519", OfflineKeyAlg: "ed25519"}
> ```

Use `crypto.Ed25519` constant here.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 107 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmwsXAC-NTh89TFGTl:-LAmwsXAC-NTh89TFGTm:b-do5lvs) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L107)):*
> ```Go
> 		cpath := filepath.Join(aspath, conf.AsConfFileName)
> 		if _, err = os.Stat(cpath); os.IsNotExist(err) {
> 			return nil, common.NewBasicError("Configuration file missing for AS", err, "path", aspath)
> ```

`conf.LoadAsConf` should throw already an error if the file doesn't exist, so this isn't needed.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 114 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmzaln2B9TWxp5S19Y:-LAmzaln2B9TWxp5S19Z:b-sp1ky8) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L114)):*
> ```Go
> 			return nil, common.NewBasicError("Error loading as.ini", err, "path", cpath)
> 		}
> ```

Please remove the empty lines between the different blocks. We usually don't add them for simple code.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 120 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmzq4U2R_gKVu6Q3mZ:-LAmzq4U2R_gKVu6Q3m_:bbqw6f4) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L120)):*
> ```Go
> 		}
> 
> 		if a.IssuerCert.OnlineKeyAlg == "" {
> ```

```
as.OnlineKeyAlg = crypto.Ed25519
if a.IssuerCert.OnlineKeyAlg != "" {
    as.OnlineKeyAlg = a.IssuerCert.OnlineKeyAlg
}
```
is more idiomatic and a bit shorter (same below)

---

*[go/tools/scion-pki/internal/trc/gen.go, line 144 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn-500CDUSqngX2YIe:-LAn-500CDUSqngX2YIf:bh3o6fy) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L144)):*
> ```Go
> 		ases = append(ases, as)
> 	}
> ```

remove empty line

---

*[go/tools/scion-pki/internal/trc/gen.go, line 147 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn06E3-y0xwyGlBd9Q:-LAn06E3-y0xwyGlBd9R:bhpmxav) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L147)):*
> ```Go
> 	for _, as := range ases {
> 		t.CoreASes[as.IA] = &trc.CoreAS{
> 			OnlineKey:     common.RawBytes(as.Online.Public().(ed25519.PublicKey)),
> ```

This is too simply now. You need to create a method that does the conversion from the private key to the public key for you, e.g., 
```
func getPubKey(privKey common.RawBytes, keyType string) (common.RawBytes, error) {
    switch keyType {
    case crypto.Ed25519:
         return common.RawBytes(ed25519.PrivateKey(privKey).Public().(ed25519.PublicKey)), nil
    default:
    }
    return nil, common.NewBasicError("Unsupported key type", nil, "type", keyType)
}
```
This can then easily be extended with new key types and signing algorithms in the future.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 164 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn-F7v4Z1JDGP6e0u3:-LAn-F7v4Z1JDGP6e0u4:b93yw92) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L164)):*
> ```Go
> type coreAS struct {
> 	IA            addr.IA
> 	Online        ed25519.PrivateKey
> ```

This cannot be `ed25519.PrivateKey` anymore, since that would imply `OnlineKeyAlg` to always be `ed25519`. Make it `common.RawBytes`. Also rename `Online` to `OnlineKey`. Same for offline.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmwhlP-nkH7aPTpRiE:-LAn2vt00syGdm9pwNCs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/conf/as.go#L83)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Use `crypto.Ed25519` constant here.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 107 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmwsXAC-NTh89TFGTl:-LAn3ERT6yllfr3ju3eh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L107)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`conf.LoadAsConf` should throw already an error if the file doesn't exist, so this isn't needed.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 114 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmzaln2B9TWxp5S19Y:-LAn3O2P7vv_rmhcbnF2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L114)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please remove the empty lines between the different blocks. We usually don't add them for simple code.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 120 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAmzq4U2R_gKVu6Q3mZ:-LAn3_IZBiJapuqHM5VD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L120)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

```
as.OnlineKeyAlg = crypto.Ed25519
if a.IssuerCert.OnlineKeyAlg != "" {
    as.OnlineKeyAlg = a.IssuerCert.OnlineKeyAlg
}
```
is more idiomatic and a bit shorter (same below)
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 144 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn-500CDUSqngX2YIe:-LAn3hRR91BrklENWsSv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L144)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 147 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn06E3-y0xwyGlBd9Q:-LAnF3H8AissKds4bxxy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L147)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This is too simply now. You need to create a method that does the conversion from the private key to the public key for you, e.g., 
```
func getPubKey(privKey common.RawBytes, keyType string) (common.RawBytes, error) {
    switch keyType {
    case crypto.Ed25519:
         return common.RawBytes(ed25519.PrivateKey(privKey).Public().(ed25519.PublicKey)), nil
    default:
    }
    return nil, common.NewBasicError("Unsupported key type", nil, "type", keyType)
}
```
This can then easily be extended with new key types and signing algorithms in the future.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 164 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1520#-LAn-F7v4Z1JDGP6e0u3:-LAnF3yd3Bblnr6_zE3u:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L164)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This cannot be `ed25519.PrivateKey` anymore, since that would imply `OnlineKeyAlg` to always be `ed25519`. Make it `common.RawBytes`. Also rename `Online` to `OnlineKey`. Same for offline.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1520#-LAmwhlP-nkH7aPTpRiE:-LArj4-OD-ulaGjZDjfQ:b-zd4nar) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/conf/as.go#L83)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

line is too long now

---

*[go/tools/scion-pki/internal/trc/gen.go, line 120 at r1](https://reviewable.io/reviews/scionproto/scion/1520#-LAmzq4U2R_gKVu6Q3mZ:-LArjNNo8yiEchGvCaIa:b5n2z6j) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/trc/gen.go#L120)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also do it for `OnlineKeyAlg`

---

*[go/tools/scion-pki/internal/trc/gen.go, line 175 at r2](https://reviewable.io/reviews/scionproto/scion/1520#-LArk8AB7vl5Kn0gHCp6:-LArk8AB7vl5Kn0gHCp7:b-izi5cc) ([raw file](https://github.com/scionproto/scion/blob/0cda2f61386b2bb3c65c1f5ff7ea66367a033ca8/go/tools/scion-pki/internal/trc/gen.go#L175)):*
> ```Go
> }
> 
> func getPrivKey(asKey common.RawBytes, keyType string) (common.RawBytes, error) {
> ```

This shouldn't be needed as `trust.LoadKey` will already give you the private key in a canonical format. `getPubKey` is only there since computing the public key from the private key differs between different algorithms.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1520#-LAmwhlP-nkH7aPTpRiE:-LAwbFuMClc-oNWrKzMw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/878dff8cc2c618dc88de4d55dc6641c3e59c9088/go/tools/scion-pki/internal/conf/as.go#L83)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

We format this like:
```
a.IssuerCert = &IssuerCert{
    BaseCert: ibc,
    OnlineKeyAlg: crypto.Ed25519,
    OfflineKeyAlg: crypto.Ed25519,
}
```
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 122 at r3](https://reviewable.io/reviews/scionproto/scion/1520#-LAwW66jAZizBxgE4abb:-LAwbIPl-QAChNb0d7ku:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5ef68a3044bc4b39fea9eb9fe394e42ae51c6dfd/go/tools/scion-pki/internal/trc/gen.go#L122)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You still need to check for errors.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 155 at r3](https://reviewable.io/reviews/scionproto/scion/1520#-LAwWUWY2E19D17QYVBN:-LAwbKgh6X1IJ3xP8yJA:b-s1niyl) ([raw file](https://github.com/scionproto/scion/blob/5ef68a3044bc4b39fea9eb9fe394e42ae51c6dfd/go/tools/scion-pki/internal/trc/gen.go#L155)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You don't need the `default` here. Sorry, that was my mistake.
</blockquote></details>

My mistake as well. But Done!

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 122 at r3](https://reviewable.io/reviews/scionproto/scion/1520#-LAwW66jAZizBxgE4abb:-LAwbxpJAnEPE7YtbX-k:bi759kt) ([raw file](https://github.com/scionproto/scion/blob/5ef68a3044bc4b39fea9eb9fe394e42ae51c6dfd/go/tools/scion-pki/internal/trc/gen.go#L122)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please restore the previous errors, i.e., `common.NewBasicError("Error loading online key", err)`. Same for offline.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 122 at r3](https://reviewable.io/reviews/scionproto/scion/1520#-LAwW66jAZizBxgE4abb:-LAwdEnPCNbXy_1ehoGX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5ef68a3044bc4b39fea9eb9fe394e42ae51c6dfd/go/tools/scion-pki/internal/trc/gen.go#L122)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please restore the previous errors, i.e., `common.NewBasicError("Error loading online key", err)`. Same for offline.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/internal/conf/as.go, line 130 at r5](https://reviewable.io/reviews/scionproto/scion/1520#-LAwfwBqANn82Kq5mZ5H:-LAwfwBqANn82Kq5mZ5I:b-orb08p) ([raw file](https://github.com/scionproto/scion/blob/d5fb79e91c70f350247314da49381c6290abc30e/go/tools/scion-pki/internal/conf/as.go#L130)):*
> ```Go
> type IssuerCert struct {
> 	*BaseCert     `ini:"Issuer Certificate"`
> 	OnlineKeyAlg  string `comment:"Signing algorithm used by Online Key, e.g., ed25519"`
> ```

Actually, `OnlineKeyAlg` and `OfflineKeyAlg` should be in `As` and not in `IssuerCert`. Sorry for missing that this long.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/conf/as.go, line 130 at r5](https://reviewable.io/reviews/scionproto/scion/1520#-LAwfwBqANn82Kq5mZ5H:-LAwkxEc8btHXiYevana:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d5fb79e91c70f350247314da49381c6290abc30e/go/tools/scion-pki/internal/conf/as.go#L130)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Actually, `OnlineKeyAlg` and `OfflineKeyAlg` should be in `As` and not in `IssuerCert`. Sorry for missing that this long.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/README.md, line 103 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6Kjp6ghiJ6FmgD2b:-LAx6Kjp6ghiJ6FmgD2c:b-p4rwb3) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/README.md#L103)):*
> ```Markdown
> Validity      = 3d
> 
> [Signing Algorithm]
> ```

Only `as.ini` for core ASes should have this section.

---

*[go/tools/scion-pki/internal/conf/as.go, line 33 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4A7v5bEeXHM784tX:-LAx4A7v5bEeXHM784tY:byw9n6p) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L33)):*
> ```Go
> const (
> 	AsConfFileName           = "as.ini"
> 	SignAlgorithmSectionName = "Signing Algorithm"
> ```

Lets call the section "Key Algorithms" and the variable "KeyAlgSectionName"

---

*[go/tools/scion-pki/internal/conf/as.go, line 39 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6u_uDr5QO5MjwpEo:-LAx6u_uDr5QO5MjwpEp:b8n6knc) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L39)):*
> ```Go
> 
> // As contains the as.ini configuration parameters.
> type As struct {
> ```

You also need to update the long description in `certs/cmd.go` and mention the new section.

---

*[go/tools/scion-pki/internal/conf/as.go, line 42 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6UKw7fFeI_PpCudY:-LAx6UKw7fFeI_PpCudZ:b92nto) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L42)):*
> ```Go
> 	*AsCert        `ini:"AS Certificate"`
> 	*IssuerCert    `ini:"Issuer Certificate,omitempty"`
> 	*SignAlgorithm `ini:"Signing Algorithm"`
> ```

This also need as `omitempty`

---

*[go/tools/scion-pki/internal/conf/as.go, line 45 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4S0PBpnhs1ep5EDE:-LAx4S0PBpnhs1ep5EDF:b-cwuq6g) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L45)):*
> ```Go
> }
> 
> type SignAlgorithm struct {
> ```

`KeyAlgorithms`

---

*[go/tools/scion-pki/internal/conf/as.go, line 46 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4ctk0P-nQVM8u51L:-LAx4ctk0P-nQVM8u51M:b-16r44u) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L46)):*
> ```Go
> 
> type SignAlgorithm struct {
> 	OnlineKeyAlg  string `comment:"Signing algorithm used by Online Key, e.g., ed25519"`
> ```

If the type is called `KeyAlgorithms` you can just name the members `Online` and `Offline`

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6bvIBmVs2O-dWDex:-LAx6bvIBmVs2O-dWDey:b-q5nng9) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L83)):*
> ```Go
> 	a := &As{}
> 	bc := NewTemplateCertConf(trcVer)
> 	a.SignAlgorithm = &SignAlgorithm{
> ```

Only add this section if `core == true`.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 111 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx5K2u99GF4VZ0K4iW:-LAx5K2u99GF4VZ0K4iX:b-p6bx7i) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/trc/gen.go#L111)):*
> ```Go
> 		}
> 		as.OnlineKeyAlg = crypto.Ed25519
> 		if a.SignAlgorithm.OnlineKeyAlg != "" {
> ```

This will crash if the `as.ini` does not contain the corresponding section. You can use the previous check that you deleted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[go/tools/scion-pki/README.md, line 103 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6Kjp6ghiJ6FmgD2b:-LAxHk1jD752yt9kB085:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/README.md#L103)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Only `as.ini` for core ASes should have this section.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 33 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4A7v5bEeXHM784tX:-LAxHi9-CAvsXKtRTShJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L33)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Lets call the section "Key Algorithms" and the variable "KeyAlgSectionName"
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 39 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6u_uDr5QO5MjwpEo:-LAxHlsuDap8hR6OlFUi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L39)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You also need to update the long description in `certs/cmd.go` and mention the new section.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 42 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6UKw7fFeI_PpCudY:-LAxG7SY1tUnKHlpr1Fv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L42)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This also need as `omitempty`
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 45 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4S0PBpnhs1ep5EDE:-LAxHnDlDFkRaglV88QL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L45)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`KeyAlgorithms`
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 46 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx4ctk0P-nQVM8u51L:-LAxG6WN5RVA2WM4eBkw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L46)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

If the type is called `KeyAlgorithms` you can just name the members `Online` and `Offline`
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 83 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx6bvIBmVs2O-dWDex:-LAxG5SN3aGa9TQlkru3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/conf/as.go#L83)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Only add this section if `core == true`.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/trc/gen.go, line 111 at r6](https://reviewable.io/reviews/scionproto/scion/1520#-LAx5K2u99GF4VZ0K4iW:-LAxG4ZU6uxSI5iZ6FpI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/4e9340ac229b55484b09b00dc7fecb409c4ef151/go/tools/scion-pki/internal/trc/gen.go#L111)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This will crash if the `as.ini` does not contain the corresponding section. You can use the previous check that you deleted.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Reviewed 4 of 4 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/internal/certs/cmd.go, line 58 at r7](https://reviewable.io/reviews/scionproto/scion/1520#-LAxJWyA1XUajg8d7Ckv:-LAxJWyA1XUajg8d7Ckw:b-1dotw1) ([raw file](https://github.com/scionproto/scion/blob/ba89568027ee3ff6bb823b8eff296e74dc367a2c/go/tools/scion-pki/internal/certs/cmd.go#L58)):*
> ```Go
> as.ini contains the preconfigured parameters according to which 'certs' generates
> the certificates. It follows the ini format and must contain a "AS Certificate"
> section and in case of a core AS there are two additional section
> ```

"It follows the ini format and contain up to three sections: "AS Certificate", "Issuer Certificate" (if also an issuer), "Key Algorithms" (if also a core). The AS Certificate and Issuer Certificate sections can contain the following values: 
...
The Key Algorithms section can contain the following values:
..."

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by jinankjain** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/certs/cmd.go, line 58 at r7](https://reviewable.io/reviews/scionproto/scion/1520#-LAxJWyA1XUajg8d7Ckv:-LAxMs4P-4J8wZ_rSMS8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ba89568027ee3ff6bb823b8eff296e74dc367a2c/go/tools/scion-pki/internal/certs/cmd.go#L58)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

"It follows the ini format and contain up to three sections: "AS Certificate", "Issuer Certificate" (if also an issuer), "Key Algorithms" (if also a core). The AS Certificate and Issuer Certificate sections can contain the following values: 
...
The Key Algorithms section can contain the following values:
..."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/internal/certs/cmd.go, line 57 at r8](https://reviewable.io/reviews/scionproto/scion/1520#-LAxNj883T7E48OjPn_I:-LAxNj883T7E48OjPn_J:b-gbqfxi) ([raw file](https://github.com/scionproto/scion/blob/52c71212e6c407984c99416c1eec84a48e53a872/go/tools/scion-pki/internal/certs/cmd.go#L57)):*
> ```Go
> 
> as.ini contains the preconfigured parameters according to which 'certs' generates
> the certificates. It follows the ini format and contain up to three sections:
> ```

'contains' (sorry)

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520#-:-LAxPkcU-Ezdl8NNx40_:bnfp4nl)*

**Comment by jinankjain** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/certs/cmd.go, line 57 at r8](https://reviewable.io/reviews/scionproto/scion/1520#-LAxNj883T7E48OjPn_I:-LAxZwca52vvkZEzhkIq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/52c71212e6c407984c99416c1eec84a48e53a872/go/tools/scion-pki/internal/certs/cmd.go#L57)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

'contains' (sorry)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Comment by shitz** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1520)*

**Pull request merged**
