### PR TITLE
snet: PathInterface struct

### PR DESCRIPTION
**Pull request by matzf**
Use a simple struct for `snet.PathInterface` directly instead of an interface.

Contrary to what was implied by code comments, this does not appear to
introduce any problematic dependencies.

Contributes to #3872 

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3879)

### CODE REVIEW

**Review by Oncilla — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3879#-:-MIJgaxfAAbJbthligyk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/cs/segutil/router.go, line 105 at r1](https://reviewable.io/reviews/scionproto/scion/3879#-MIJfjE7Bs2NM5F-GYRT:-MIJfjE81KkVFH9H5Lmh:b-qkwgmb) ([raw file](https://github.com/scionproto/scion/blob/80aec0ee2cb1bd2383d8b9f59c89ec38a6131d29/go/cs/segutil/router.go#L105)):*
> ```Go
> }
> 
> type path struct {
> ```

AFAIU, there is no longer a need for this struct.

Can you maybe elaborate a bit on the plan for this and future PRs?

I assume this is some preparation PR, and then there will be a follow-up that cleans up the uneccessary structs.
Is that correct?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3879)* status: all files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[go/cs/segutil/router.go, line 105 at r1](https://reviewable.io/reviews/scionproto/scion/3879#-MIJfjE7Bs2NM5F-GYRT:-MIO4Mqj7KNRYdidU5kf:b-vn96tt) ([raw file](https://github.com/scionproto/scion/blob/80aec0ee2cb1bd2383d8b9f59c89ec38a6131d29/go/cs/segutil/router.go#L105)):*
> I assume this is some preparation PR, and then there will be a follow-up that cleans up the uneccessary structs.

Yup.

In the current state, this is implementation of the `Path` interface is still used/needed. This PR only removes the `PathInterface` interface type.

The next step will be to combine the `sciond` and `segutil` implementations of path, i.e. the main part of #3872. This is when I will remove this type here.

**Review by Oncilla — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3879)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
