### PR TITLE
Update README (#1311)

### PR DESCRIPTION
**Pull request by jinankjain**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1506)

### CODE REVIEW

**Comment by Oncilla** [comment]
*[README.md, line 88 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9e0ucKE3nIiKHrQP9l:-L9e0ucKE3nIiKHrQP9m:b-d1hht9) ([raw file](https://github.com/scionproto/scion/blob/3247158fd21d36f6dc85492dc13f6ef39c0684d0/README.md#L88)):*
> ```Markdown
>                     as-sig.key
> 
>    The default topology looks like [this](doc/fig/default-topo.pdf).
> ```

change `default-topo.pdf` to `default_topo.png`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by kormat** [comment]
Thanks for doing this :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 17 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9eaXQ-BlIt9cGH26cq:-L9eaXQ-BlIt9cGH26cr:b-tb15z) ([raw file](https://github.com/scionproto/scion/blob/0b23bcd2db03ac6628c47d818b1cbc5f8b8f1cab/README.md#L17)):*
> ```Markdown
>   * [certificate_server](/python/cert_server): Certificate Server
>   * [path_server](/python/path_server): Path Server
> * [lib/](/lib): the most relevant SCION libraries.
> ```

This dir is gone. Maybe mention `python/lib` instead.

---

*[README.md, line 25 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9eag9RABV3dZ0dNovH:-L9eag9RABV3dZ0dNovI:b5utxh7) ([raw file](https://github.com/scionproto/scion/blob/0b23bcd2db03ac6628c47d818b1cbc5f8b8f1cab/README.md#L25)):*
> ```Markdown
> * [supervisor/](/supervisor): the configuration for
>   [supervisord](http://supervisord.org/).
> * [test/](/test): the unit tests for the Python code.
> ```

Also gone.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506#-:-L9eaW02EqSZc_oQ6Pqu:b-stmt6p)*

**Comment by Oncilla** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by jinankjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 88 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9e0ucKE3nIiKHrQP9l:-L9ebzo1D_q0pxpG8B2Y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3247158fd21d36f6dc85492dc13f6ef39c0684d0/README.md#L88)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

change `default-topo.pdf` to `default_topo.png`
</blockquote></details>

Done.

---

*[README.md, line 25 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9eag9RABV3dZ0dNovH:-L9ebz2c7bd8kNVW6E_I:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0b23bcd2db03ac6628c47d818b1cbc5f8b8f1cab/README.md#L25)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Also gone.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 10 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jKZ11-juKErsEOAKN:-L9jKZ1255uWQYhz4op1:bru2juo) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L10)):*
> ```Markdown
>   containers.
> * [go/](/go): parts of the implementation that are written in
>   [Go](http://golang.org).
> ```

Please add the following entries:
* [certificate_server](/go/cert_serv): Certificate Server
* [scion_ip_gateway](/go/sig): SCION IP Gateway
* [lib](/go/lib): shared SCION libraries

---

*[README.md, line 17 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jLILeCmGExeUQ1XrZ:-L9jLILeCmGExeUQ1Xr_:b-e37blu) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L17)):*
> ```Markdown
>   * [certificate_server](/python/cert_server): Certificate Server
>   * [path_server](/python/path_server): Path Server
> * [python/lib/](python/lib): the most relevant SCION libraries.
> ```

This should be added under `python`. Use the same format as proposed above for Go.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by jinankjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 10 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jKZ11-juKErsEOAKN:-L9jN_5PE3W9RKAxWqcy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L10)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please add the following entries:
* [certificate_server](/go/cert_serv): Certificate Server
* [scion_ip_gateway](/go/sig): SCION IP Gateway
* [lib](/go/lib): shared SCION libraries
</blockquote></details>

Done.

---

*[README.md, line 17 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jLILeCmGExeUQ1XrZ:-L9jNa-L0ZPTNMzmdipN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L17)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This should be added under `python`. Use the same format as proposed above for Go.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 17 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jLILeCmGExeUQ1XrZ:-L9jPTq-6RiDCtzcjYb7:b-t207a) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L17)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Use the same wording as above `shared SCION Python  libraries`. Also add one more item:
* [topology](/python/topology) generator for generating a local topology, including all the necessary configuration, key, and certificate files

---

*[README.md, line 11 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jPieyCeyIcU7lYMZV:-L9jPieyCeyIcU7lYMZW:b-fae8m1) ([raw file](https://github.com/scionproto/scion/blob/fa0bd7e8253d7babceadc2aa0f7811e72cd9f241/README.md#L11)):*
> ```Markdown
> * [go/](/go): parts of the implementation that are written in
>   [Go](http://golang.org).
>   * [border_router](/go/border): Border Router.
> ```

Please remove all fullstops at the end of a line to make it consistent. There are no full sentences.

---

*[README.md, line 29 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jQnsZ5Uimx3Wh2V9R:-L9jQnsZ5Uimx3Wh2V9S:b4aqafa) ([raw file](https://github.com/scionproto/scion/blob/fa0bd7e8253d7babceadc2aa0f7811e72cd9f241/README.md#L29)):*
> ```Markdown
>   [supervisord](http://supervisord.org/).
> * [tools/](/tools): assorted support tools.
> * [topology/](/topology): the scripts to generate the SCION
> ```

Change this to: `various topology definitions and configurations`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by jinankjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 17 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9eaXQ-BlIt9cGH26cq:-L9jU_hT55WrtJgbw_1u:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0b23bcd2db03ac6628c47d818b1cbc5f8b8f1cab/README.md#L17)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This dir is gone. Maybe mention `python/lib` instead.
</blockquote></details>

Done.

---

*[README.md, line 17 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jLILeCmGExeUQ1XrZ:-L9jUaZy895rNF_APWsG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d271ce2c2f9f19758c6cd016a2ab6289ca46005a/README.md#L17)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Use the same wording as above `shared SCION Python  libraries`. Also add one more item:
* [topology](/python/topology) generator for generating a local topology, including all the necessary configuration, key, and certificate files
</blockquote></details>

Done.

---

*[README.md, line 11 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jPieyCeyIcU7lYMZV:-L9jUZ630l3J1OCd7TZn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fa0bd7e8253d7babceadc2aa0f7811e72cd9f241/README.md#L11)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please remove all fullstops at the end of a line to make it consistent. There are no full sentences.
</blockquote></details>

Done.

---

*[README.md, line 29 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1506#-L9jQnsZ5Uimx3Wh2V9R:-L9jUbnJDL-oJT33AvAZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fa0bd7e8253d7babceadc2aa0f7811e72cd9f241/README.md#L29)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Change this to: `various topology definitions and configurations`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by Oncilla** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506)*

**Comment by shitz** [comment]
:lgtm:
Please rebase on master so we can get this merged.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1506#-:-LA8IDh21Fgqcps9aLWI:bc6tpdw)*

**Comment by jinankjain** [comment]
@shitz Rebased with master 😄

**Pull request merged**
