### PR TITLE
drkey: integration test

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR includes an integration test for the DRKey feature. For the test to run correctly, it is necessary that the provided topology has enabled DRKey on the two involved endpoints.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)

### CODE REVIEW

**Review by shitz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @shitz)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NAGAg3uCAn-TfWHt8Cz:-NAGAg3uCAn-TfWHt8D-:b-4hnw86) (no related file):*
I suggest you take the approach of the `demo/file_transfer` and create a `demo/drkey` that uses the acceptance test framework to spin up a topology with two ASes and a client and server that establish a secret key. For that you can then use your example here. Ideally, this we would be a small command line utility that you can use with `./hellodrkey server <flags>` and `./hellodrkey client <flags>` and use a small python utility that calls those to run the demo.

I'd also appreciate if you'd do proper error handling and write clean code. These little programs have a representative function for users that browse the repo for the first time.

___

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @shitz)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NAGAg3uCAn-TfWHt8Cz:-NCQ2RKw2M9CxGpggK7k:b-896fix) (no related file):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I suggest you take the approach of the `demo/file_transfer` and create a `demo/drkey` that uses the acceptance test framework to spin up a topology with two ASes and a client and server that establish a secret key. For that you can then use your example here. Ideally, this we would be a small command line utility that you can use with `./hellodrkey server <flags>` and `./hellodrkey client <flags>` and use a small python utility that calls those to run the demo.

I'd also appreciate if you'd do proper error handling and write clean code. These little programs have a representative function for users that browse the repo for the first time.
</blockquote></details>

Done.

___

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NCUT52S0E-NiaQkJKlt:-NCUT52S0E-NiaQkJKlu:b6huosb) (no related file):*
Running `bazel test //demo/drkey:test` I consistently get the following error:
```
STDERR:Error fetching key: rpc error: code = Unknown desc = getting Host-Host from client store: fetching Host-Host key from local CS: requesting Host-Host key: rpc error: code = Unknown desc = deriving Host-Host request: computing intermediate Host-AS key: getting  level1 key: obtaining level 1 key from CS: level1 fetch failed {err=remote not reachable: fetching failed: processing reply: all segments failed to verify: [ segment verification error {as=1-ff00:0:112; seg=ID: 70958b6a45507ef53d822a6f Timestamp: 2022-09-21 09:51:51+0000 Hops: 1-ff00:0:110 2>1 1-ff00:0:112}: getting chains {query.date=2022-09-21 09:51:54.220674+0000; query.isd_as=1-ff00:0:112; query.subject_key_id=8228543ac26a13de0ea504624427a25d03cd1919}: fetching chains from remote {server=1-ff00:0:110,172.20.0.20:32768}: receiving chains: rpc error: code = Unavailable desc = connection closed before server preface received ]; peer=1-ff00:0:112; try=1}
```

Did you experience that before?

___
___
*[`demo/drkey/main.go` line 50 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPujY8jJ0FEoZ1Jlk:-NCUPujY8jJ0FEoZ1Jll:bfg3z4v) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L50)):*
> ```Go
> 
> 	scionEnv.Register(flag.CommandLine)
> 	flag.StringVar(&mode, "mode", "", "Mode for obtaining the key (server or client mode")
> ```

Non-blocking - Instead of `mode` I'd have an explicit `--server` flag and by default be the client.
___
*[`demo/drkey/main.go` line 155 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPhHL-UppssqmPCTT:-NCUPhHL-UppssqmPCTU:b-plawpd) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L155)):*
> ```Go
> }
> 
> func (c Client) HostHostKey(
> ```

Would rename this to make it clear that this is a fetching operation (vs deriving for the server)



_Suggestion:_
```Go
FetchHostHostKey
```
___
*[`demo/drkey/main.go` line 170 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUQ9bY7FEciBV2Pxim:-NCUQ9bY7FEciBV2Pxin:b8zr374) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L170)):*
> ```Go
> // The IP address of the server must be explicitly allowed to abtain this SV
> // from the the control server.
> func (s Server) fetchSV(
> ```

nit - In newer code we use a different formatting for multiline function definitions



_Code snippet:_
```Go
func (s Server) fetchSV(
	ctx context.Context,
	meta drkey.SecretValueMeta,
) (drkey.SecretValue, error) {

	// Start of implementation after a blank line	
}
```
___
*[`demo/drkey/main.go` line 207 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPrH39ilZh5Qnkfmr:-NCUPrH46KgHCNlceVII:undefined) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L207)):*
> ```Go
> }
> 
> func (s Server) HostHostKey(
> ```





_Suggestion:_
```Go
DeriveHostHostKey
```
___
*[`demo/drkey/main.go` line 207 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUQVdP0GhTMVL3bgeR:-NCUQVdQCsLuADCRMmVq:bi62dg2) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L207)):*
> ```Go
> }
> 
> func (s Server) HostHostKey(
> ```

Nit - move this above `fetchSV` because it's the public method of `Server`
___
*[`demo/drkey/test.py` line 35 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCURZsJCS49lfllBdz8:-NCURZsJCS49lfllBdz9:binlx6i) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/test.py#L35)):*
> ```Python
> class Test(base.TestTopogen):
>     """
>     Demonstrate and test DRKey.
> ```

It would be great to have this info also in a `README.md` together with instructions how to run the test.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: all files reviewed, 5 unresolved discussions (waiting on @JordiSubira and @shitz)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NCUT52S0E-NiaQkJKlt:-NC_ofZJ3AhFF1aZPt0C:b28dx6x) (no related file):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Running `bazel test //demo/drkey:test` I consistently get the following error:
```
STDERR:Error fetching key: rpc error: code = Unknown desc = getting Host-Host from client store: fetching Host-Host key from local CS: requesting Host-Host key: rpc error: code = Unknown desc = deriving Host-Host request: computing intermediate Host-AS key: getting  level1 key: obtaining level 1 key from CS: level1 fetch failed {err=remote not reachable: fetching failed: processing reply: all segments failed to verify: [ segment verification error {as=1-ff00:0:112; seg=ID: 70958b6a45507ef53d822a6f Timestamp: 2022-09-21 09:51:51+0000 Hops: 1-ff00:0:110 2>1 1-ff00:0:112}: getting chains {query.date=2022-09-21 09:51:54.220674+0000; query.isd_as=1-ff00:0:112; query.subject_key_id=8228543ac26a13de0ea504624427a25d03cd1919}: fetching chains from remote {server=1-ff00:0:110,172.20.0.20:32768}: receiving chains: rpc error: code = Unavailable desc = connection closed before server preface received ]; peer=1-ff00:0:112; try=1}
```

Did you experience that before?
</blockquote></details>

I tried out all the 2-ASes permutations and I got the following results running `bazel test //demo/drkey:test --cache_test_results=no`.
```
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:111 = OK
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:112 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:111 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:112 = KO
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:111 = KO
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:112 = OK
```
The test client cannot retrieve paths to the server in `control/drkey/grpc/fetcher.go:128`. I don't see a straightforward reason why the segment verification is failing for this test, probably must be some configuration issue, I will look into that more carefully. 

___

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: 0 of 11 files reviewed, 4 unresolved discussions (waiting on @shitz)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NCUT52S0E-NiaQkJKlt:-NCtdjtJ0oWhgV7GulRM:b-9b21v) (no related file):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I tried out all the 2-ASes permutations and I got the following results running `bazel test //demo/drkey:test --cache_test_results=no`.
```
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:111 = OK
Server addr:  1-ff00:0:110 ; Client addr:  1-ff00:0:112 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:111 = OK
Server addr:  1-ff00:0:111 ; Client addr:  1-ff00:0:112 = KO
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:110 = OK
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:111 = KO
Server addr:  1-ff00:0:112 ; Client addr:  1-ff00:0:112 = OK
```
The test client cannot retrieve paths to the server in `control/drkey/grpc/fetcher.go:128`. I don't see a straightforward reason why the segment verification is failing for this test, probably must be some configuration issue, I will look into that more carefully. 

</blockquote></details>

This is a great finding observation, I had completely missed this.
This seems to be an actual problem with the implementation, not the demo or the test. There appears to be some general issue with path segment registration and requests that is somehow related to DRKey -- when DRKey is enabled in the configuration, the control services in the non-core ASes keep reporting errors about registering segments and when running the DRKey demo also for requesting path segments for the DRKey requests (which is the error that shitz saw above).  Weirdly, this stops as soon as a "proper" path request is made using e.g. showpaths.
I'll dig a bit further because I have no clue yet how to tie this together.

___
___
*[`demo/drkey/main.go` line 50 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPujY8jJ0FEoZ1Jlk:-NCslYXsA-2_wW1UKZ83:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L50)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Non-blocking - Instead of `mode` I'd have an explicit `--server` flag and by default be the client.
</blockquote></details>

Done.
___
*[`demo/drkey/main.go` line 155 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPhHL-UppssqmPCTT:-NCsmXIP-pkCSY8WGjkE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L155)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Would rename this to make it clear that this is a fetching operation (vs deriving for the server)
</blockquote></details>

Done.
___
*[`demo/drkey/main.go` line 170 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUQ9bY7FEciBV2Pxim:-NCslrFdDlpjdE1g1D0B:bicfg3i) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L170)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

nit - In newer code we use a different formatting for multiline function definitions
</blockquote></details>

Done. I'll update the style guide.
___
*[`demo/drkey/main.go` line 207 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUPrH39ilZh5Qnkfmr:-NCslfkY1bB2EZL5hhdK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L207)):*
> ```Go
> }
> 
> func (s Server) HostHostKey(
> ```

Done.
___
*[`demo/drkey/main.go` line 207 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCUQVdP0GhTMVL3bgeR:-NCsmUzY4h-yJfB3rQyG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/main.go#L207)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Nit - move this above `fetchSV` because it's the public method of `Server`
</blockquote></details>

Done.
___
*[`demo/drkey/test.py` line 35 at r3](https://reviewable.io/reviews/scionproto/scion/4244#-NCURZsJCS49lfllBdz8:-NCt0W-g9SHBiIIkLeIR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d707d03110ce57a84c21c073cd032948496eff9d/demo/drkey/test.py#L35)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

It would be great to have this info also in a `README.md` together with instructions how to run the test.
</blockquote></details>

Done.

**Review by shitz — APPROVED** [review]
> Reviewed 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4244#-NCUT52S0E-NiaQkJKlt:-ND4ctuc4pZdcdR6yG4M:b-hk2x7w) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is a great finding observation, I had completely missed this.
This seems to be an actual problem with the implementation, not the demo or the test. There appears to be some general issue with path segment registration and requests that is somehow related to DRKey -- when DRKey is enabled in the configuration, the control services in the non-core ASes keep reporting errors about registering segments and when running the DRKey demo also for requesting path segments for the DRKey requests (which is the error that shitz saw above).  Weirdly, this stops as soon as a "proper" path request is made using e.g. showpaths.
I'll dig a bit further because I have no clue yet how to tie this together.
</blockquote></details>

We discussed offline that this will be dealt with properly in a follow up, because it requires bigger changes. For now, we'll live with the showpaths workaround

___

**Pull request merged**
