### PR TITLE
brload: fix premature socket closure

### LINKED ISSUE #4590: brload: socket closes early in some cases, causing benchmark to fail
Brload uses the raw sendmmsg system call in order to send packets in batches over a packet socket.
In order to do that, it steals the file descriptor from inside the TPacket structure (as TPacket itself doesn't support sendmmsg).
Downstream from that, the TPacket object is only referenced by the receiving side which can terminate early (it is happy with receiving a single packet). As a result the TPacket object is exposed to garbage collection before the end of the benchmark run, which results in closing the socket.

The fix is to retain a reference to the TPacket object within the mm sender.

### PR DESCRIPTION
**Pull request by jiceatscion**
Brload borrows the file descriptor from a af_packet.TPacket structure in order to use it with sendmmsg (not available via TPacket). In the process it left the original TPacket, only used on the receiving side, exposed to garbage collection, resulting in the premature closure of the socket. Fixed it by keeping a reference to TPacket on the sending side.

In passing:
* temporarily increase the benchmark packet size to 1500 bytes, to show bandwidth (~10Gb/s) with normal frames.
* display brload's output to help in diagnosing issues.

Fixes #4590

### CODE REVIEW

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4591)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`acceptance/router_benchmark/brload/mmsg.go` line 28 at r2](https://reviewable.io/reviews/scionproto/scion/4591#-O4FdCvF1hc_8zesJZC2:-O4FdCvF1hc_8zesJZC3:b32wdi) ([raw file](https://github.com/scionproto/scion/blob/f8de9c7e0f38e680e6321ec9f5428a7107c4358b/acceptance/router_benchmark/brload/mmsg.go#L28)):*
> ```Go
> 	hdr unix.Msghdr
> 	len uint32
> 	pad [4]byte
> ```

_ 



_Code quote:_
```Go
	pad 
```

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4591)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @FR4NK-W and @JordiSubira)

___
*[`acceptance/router_benchmark/brload/mmsg.go` line 28 at r2](https://reviewable.io/reviews/scionproto/scion/4591#-O4FdCvF1hc_8zesJZC2:-O4Fzd0z1I2A8N36QNQC:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/f8de9c7e0f38e680e6321ec9f5428a7107c4358b/acceptance/router_benchmark/brload/mmsg.go#L28)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

_
</blockquote></details>

done

**Comment by jiceatscion** [comment]
Saving everyone's time by bypassing re-review for this.

**Review by jiceatscion — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4591)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
