### PR TITLE
snet/sciond: add static info metadata fields to snet.PathMetadata

### PR DESCRIPTION
**Pull request by matzf**
Add static info metadata fields, from their temporary location in the path combinator to `snet.PathMetadata`. Add these fields to the sciond protobuf protocol definitions to transport this information along with sciond path replies.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3924)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3924)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[go/lib/snet/path.go, line 70 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw4V_pBakrEbMu2iyy:-MLw4V_q0bhBlseB2BJj:bysd52d) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L70)):*
> ```
> these entries are signed is signed
> ```
I think the `is signed` needs to be dropped. Also this comment doesn't really hold true for the existing information, for example MTU can't be attributed to each AS, since it's a result of a calculation. I think it would be nice to clarify this in some way.
___
*[go/lib/snet/path.go, line 134 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw5GmoCA_ppsUmhrGQ:-MLw5GmoCA_ppsUmhrGR:botyys0) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L134)):*
> ```Go
> type LinkType uint8
> 
> const (
> ```

add a comment to this block. `// LinkType values`
___
*[go/lib/snet/path.go, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw6zAiAlavJjWRjGLX:-MLw6zAiAlavJjWRjGLY:b-b411ym) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L141)):*
> ```Go
> )
> 
> type GeoCoordinates struct {
> ```

Add a comment.

**Review by lukedirtwalker — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3924)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3924)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/lib/snet/path.go, line 70 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw4V_pBakrEbMu2iyy:-MLwFHdLE5BwmJNdNzM9:bg98a4y) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L70)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> these entries are signed is signed
> ```
I think the `is signed` needs to be dropped. Also this comment doesn't really hold true for the existing information, for example MTU can't be attributed to each AS, since it's a result of a calculation. I think it would be nice to clarify this in some way.
</blockquote></details>

You're right, not really clear what it was trying to say. Rephrased it, better?
___
*[go/lib/snet/path.go, line 134 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw5GmoCA_ppsUmhrGQ:-MLwBkCX6Km4Ozvk0LdM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L134)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

add a comment to this block. `// LinkType values`
</blockquote></details>

Done.
___
*[go/lib/snet/path.go, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/3924#-MLw6zAiAlavJjWRjGLX:-MLwCneKDSCCuB9uyaso:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/dcb5e8ef1a2e33fa46904a7cec42e3e7c7079c5a/go/lib/snet/path.go#L141)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Add a comment.
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3924)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
