### PR TITLE
bazel: cleanup bazelrc, add config acceptance_all

### PR DESCRIPTION
**Pull request by matzf**
Cleanup the .bazelrc file, in particular set bazel-remote connection for
`common` so that it also applies to the `query` subcommand, and set
sensible defaults for test outputs. Generally declutter and document
options.

Add a make target `test-acceptance` using a new bazel config
`acceptance_all` to have a simple entrypoint to run all (bazel-based)
acceptance tests, including the filetransfer demo.
For this, specify the `exclusive` tag in the acceptance test rule
definitions to enforce that tests are run sequentially -- the test
environment cannot be setup for multiple tests concurrently. 
Fix the filetransfer demo.
Fix the false-positive result of sig_short_exp_time, and explicitly skip
the now failing test from running.

Finally, fix a small mistake in tools/BUILD.bazel that caused bazel
query to report errors.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4182#-Mz5yUCdDG6jI7vDXJ-0:-Mz5yUCe-Tw7P6vxp0nq:b-64e4it) (no related file):*
cool stuff :100: 

---
___
*[.bazelrc, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/4182#-Mz5yx673EwjWa_kVf_L:-Mz5yx673EwjWa_kVf_M:b-qlrc7y) ([raw file](https://github.com/scionproto/scion/blob/c39271a251605a6bc24b04847f1c4a9819290f80/.bazelrc#L20)):*
> ```
> test:race --@io_bazel_rules_go//go/config:race
> test:unit --test_tag_filters=unit
> test:unit_all --test_tag_filters=unit -- //...
> ```

why are the `--` needed?



_Code quote:_
```
 -- 
```

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: 3 of 14 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[.bazelrc, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/4182#-Mz5yx673EwjWa_kVf_L:-MzEZViJ9XQHyCnIwUZJ:b-wmexq7) ([raw file](https://github.com/scionproto/scion/blob/c39271a251605a6bc24b04847f1c4a9819290f80/.bazelrc#L20)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why are the `--` needed?
</blockquote></details>

You're right, it is not needed here, it is only needed further down in `integration_go` where the "negation operator" is used. I've removed it again.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[.bazelrc, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/4182#-MzKgibRE3vA-CgIzQn1:-MzKgibS-MhKl4vH_SSi:b-prjo6i) ([raw file](https://github.com/scionproto/scion/blob/52e3cb4b50977d90bf279797ded6adaf9325b138/.bazelrc#L4)):*
> ```
> common --show_timestamps
> # connect to buchgr/bazel-remote cache
> common --remote_cache=grpc://localhost:9092 --experimental_remote_downloader=grpc://localhost:9092
> ```

I just noticed that this breaks `bazel help`.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[.bazelrc, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/4182#-MzKgibRE3vA-CgIzQn1:-MzLeRdR9N2tAeT_My6A:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/52e3cb4b50977d90bf279797ded6adaf9325b138/.bazelrc#L4)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I just noticed that this breaks `bazel help`.
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
