### PR TITLE
BR: single internal interface per overlay

### PR DESCRIPTION
**Pull request by sgmonroy**
This removes support for multiple internal interfaces (of the same overlay type) in the Border Router.

When the BR is in a host with multiple internal interfaces, there are different solutions:
- Virtual IP
- Interface Bonding
- Bind to a loopback address using a routing protocol to advertise the route.

PS: For supporting dual stack, we can have a dedicated internal interface per overlay.
ie. localSockIPv4, localSockIPv6

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)

### CODE REVIEW

**Comment by sgmonroy** [comment]
Review status: 0 of 32 files reviewed at latest revision, all discussions resolved.

---

*[go/border/rpkt/rpkt.go, line 165 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEAC3L2ENt27GIX8P7w:-LEAC3L2ENt27GIX8P7x:b-xwmcp6) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/rpkt.go#L165)):*
> ```Go
> 	Src    *topology.AddrInfo
> 	IfID   common.IFIDType
> 	LocIdx int // only set for packets from the local AS.
> ```

This should go away

---

*[go/border/rpkt/rpkt.go, line 225 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEAC6lsDRWtdn2nucX0:-LEAC6lsDRWtdn2nucX1:b-xwmcp6) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/rpkt.go#L225)):*
> ```Go
> 	rp.Ingress.Src = nil
> 	rp.Ingress.IfID = 0
> 	rp.Ingress.LocIdx = -1
> ```

This should go away

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
Review status: 31 of 32 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/border/router.go, line 131 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKh45bDASHA66gbkB4:-LEKh45c0hZ4iSz75vHU:b-y2hvki) ([raw file](https://github.com/scionproto/scion/blob/7f8139e89cb8b26d722eceeefa540bcf63a6d374/go/border/router.go#L131)):*
> ```Go
> 		assert.Must(rp.Ingress.Dst != nil, "Ingress.Dst must be set")
> 		assert.Must(rp.Ingress.Src != nil, "Ingress.Src must be set")
> 		assert.Must(len(rp.Ingress.IfIDs) > 0, "Ingress.IfIDs must not be empty")
> ```

Suggestion, replace the old assert with:
```
if rp.DirFrom == rp.DirLocal {
   assert.Must(rp.Ingress.IfID == 0, "Ingress.IfID must not be set for DirFrom==DirLocal")
} else {
  assert.Must(rp.Ingress.IfID > 0, "Ingress.IfID must be set for DirFrom==DirRemote")
}
```

---

*[go/border/setup.go, line 223 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKfMze-8eIpjiYy-zG:-LEKfMze-8eIpjiYy-zH:bcmtx5u) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/setup.go#L223)):*
> ```Go
> 		}
> 		// XXX We assume both In/Out are using the same unserlying Conn/Socket
> 		// but shouldn't we do proper clean up anyway? ie. SockOut go routine
> ```

`sock.Stop()` closes the ringbuf, which causes the sockout go routine to exit once the ringbuf is empty. This way it gets cleaned up without dropping any packets that are currently being processed.

---

*[go/border/setup.go, line 236 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKgWakD9XDExqCmg-J:-LEKgWakD9XDExqCmg-K:b-wv6vqb) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/setup.go#L236)):*
> ```Go
> 	if oldCtx != nil {
> 		oldBai := oldCtx.Conf.Net.LocAddr.BindAddrInfo(oldCtx.Conf.Topo.Overlay)
> 		if bai.IP.Equal(oldBai.IP) {
> ```

This should also check the port.

---

*[go/border/netconf/interface.go, line 36 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKecTP3Taqy7lBtDqH:-LEKecTP3Taqy7lBtDqI:bqpy4ro) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/netconf/interface.go#L36)):*
> ```Go
> // accessing these by different methods.
> type NetConf struct {
> 	// LocAddr is a slice containing the local addresses in order from the
> ```

Comment oudated.

---

*[go/border/netconf/interface.go, line 55 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeluc2XA4N5r1Skza:-LEKeluc2XA4N5r1Skzb:byw9rww) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/netconf/interface.go#L55)):*
> ```Go
> 			n.LocAddr = ifinfo.InternalAddr
> 		} else if n.LocAddr != ifinfo.InternalAddr {
> 			return nil, common.NewBasicError("Duplicate local address index", nil,
> ```

Error message outdated.

---

*[go/border/rctx/io.go, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeYUU4oOBemBpuhTr:-LEKeYUU4oOBemBpuhTs:b-klp2ny) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rctx/io.go#L99)):*
> ```Go
> 			<-s.readerStopped
> 		}
> 		s.Ring.Close()
> ```

Why move this block?

---

*[go/border/rctx/rctx.go, line 32 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeG2aDrbgtiaeiMqZ:-LEKeG2aDrbgtiaeiMq_:b49i7hw) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rctx/rctx.go#L32)):*
> ```Go
> 	Conf *conf.Conf
> 	// LockSockIn is a slice of Sock's for receiving packets from the local AS,
> 	// indexed by the local address index.
> ```

Comment needs updating. Same for LocSockOut.

---

*[go/border/rpkt/route.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKkxZ44g6VlD6HGJH4:-LEKkxZ44g6VlD6HGJH5:bhhbpap) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/route.go#L83)):*
> ```Go
> 			"actual", rp.dstHost, "type", fmt.Sprintf("%T", rp.dstHost))
> 	}
> 	// Use any local output sock in case the packet has no path (e.g., ifstate requests)
> ```

Obsolete comment.

---

*[go/border/rpkt/route.go, line 84 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKkdkC0YXPpQRUWxvx:-LEKkdkC0YXPpQRUWxvy:b-lrftxd) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/route.go#L84)):*
> ```Go
> 	}
> 	// Use any local output sock in case the packet has no path (e.g., ifstate requests)
> 	// FIXME Choose LocSock based on overlay type
> ```

`FIXME(sgmonroy)`

Hmm. If we have a `Sock` per overlay type, then it's back to being a bit more complex :)

---

*[go/lib/topology/addr.go, line 142 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKcX0D4rwbBne8IjrG:-LEKcX0EAigymAHO0aNl:bov1pdo) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/lib/topology/addr.go#L142)):*
> ```Go
> 
> // Extract the relevant (v4 or v6) L4Port from a TopoAddr
> func (t *TopoAddr) PubL4PortFromAddr(a addr.HostAddr) (int, error) {
> ```

It looks like this isn't used any more?

```
$ git grep PubL4PortFromAddr
go/lib/topology/addr.go:func (t *TopoAddr) PubL4PortFromAddr(a addr.HostAddr) (int, error) {
go/lib/topology/topology_test.go:func Test_PubL4PortFromAddr(t *testing.T) {
go/lib/topology/topology_test.go:                               oi, _ := tt.intopo.PubL4PortFromAddr(tt.inae)
```

---

*[go/lib/topology/topology.go, line 118 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKdCBq6V3jBedZ562n:-LEKdCBr526Zil-QVkci:bo7qcj8) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/lib/topology/topology.go#L118)):*
> ```Go
> 		brInfo := BRInfo{}
> 		var intAddr *TopoAddr
> 		if rawBr.InternalAddr != nil {
> ```

It seems like it should be an error if it _was_ `nil`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by sgmonroy** [comment]
*[go/border/rctx/io.go, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeYUU4oOBemBpuhTr:-LEP4bIf0_qr6Zbv5ME_:btprw9a) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rctx/io.go#L99)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why move this block?
</blockquote></details>

shouldn't we stopped the go routines before closing the ringbuf? otherwise the writer might try to queue packets to a closed ringbuf?

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by sgmonroy** [comment]
*[go/border/rpkt/route.go, line 84 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKkdkC0YXPpQRUWxvx:-LEP5YW44y_e1RF65IRb:bqxhshu) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/route.go#L84)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`FIXME(sgmonroy)`

Hmm. If we have a `Sock` per overlay type, then it's back to being a bit more complex :)
</blockquote></details>

How would you implement dual stack without having two Sock?

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by sgmonroy** [comment]
Review status: 31 of 32 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[go/border/router.go, line 131 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKh45bDASHA66gbkB4:-LEOqminCLwdc3LhWnWU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7f8139e89cb8b26d722eceeefa540bcf63a6d374/go/border/router.go#L131)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Suggestion, replace the old assert with:
```
if rp.DirFrom == rp.DirLocal {
   assert.Must(rp.Ingress.IfID == 0, "Ingress.IfID must not be set for DirFrom==DirLocal")
} else {
  assert.Must(rp.Ingress.IfID > 0, "Ingress.IfID must be set for DirFrom==DirRemote")
}
```
</blockquote></details>

Done.

---

*[go/border/setup.go, line 223 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKfMze-8eIpjiYy-zG:-LEP1ECPDm9mJPlqqG0m:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/setup.go#L223)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`sock.Stop()` closes the ringbuf, which causes the sockout go routine to exit once the ringbuf is empty. This way it gets cleaned up without dropping any packets that are currently being processed.
</blockquote></details>

Done.

---

*[go/border/setup.go, line 236 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKgWakD9XDExqCmg-J:-LEP2ou18jHwudQtYQFX:b-hz1q1n) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/setup.go#L236)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should also check the port.
</blockquote></details>

I'll compare TopoAddr instead

---

*[go/border/netconf/interface.go, line 36 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKecTP3Taqy7lBtDqH:-LEP354m2tFFGsQmHNJS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/netconf/interface.go#L36)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Comment oudated.
</blockquote></details>

Done.

---

*[go/border/netconf/interface.go, line 55 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeluc2XA4N5r1Skza:-LEP43sP0iWAVOfSfh6I:bl8perb) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/netconf/interface.go#L55)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Error message outdated.
</blockquote></details>

replaced with assert as this should never happen. We already generate ifinfo from topology.

---

*[go/border/rctx/rctx.go, line 32 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeG2aDrbgtiaeiMqZ:-LEP5MagCyyFDLwGwdbr:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rctx/rctx.go#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Comment needs updating. Same for LocSockOut.
</blockquote></details>

Done.

---

*[go/border/rpkt/route.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKkxZ44g6VlD6HGJH4:-LEP5Uy98PB8oYdA6hAw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/route.go#L83)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Obsolete comment.
</blockquote></details>

Done.

---

*[go/border/rpkt/rpkt.go, line 165 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEAC3L2ENt27GIX8P7w:-LEP6Ib-CNbZpsc3PGTH:b-896fjx) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/rpkt.go#L165)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

This should go away
</blockquote></details>

Done

---

*[go/border/rpkt/rpkt.go, line 225 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEAC6lsDRWtdn2nucX0:-LEP6JbBAcKp-EURDOJM:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/rpkt.go#L225)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

This should go away
</blockquote></details>

Done

---

*[go/lib/topology/addr.go, line 142 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKcX0D4rwbBne8IjrG:-LEP6ukA9qsJozTtV39H:b-rkdjm0) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/lib/topology/addr.go#L142)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It looks like this isn't used any more?

```
$ git grep PubL4PortFromAddr
go/lib/topology/addr.go:func (t *TopoAddr) PubL4PortFromAddr(a addr.HostAddr) (int, error) {
go/lib/topology/topology_test.go:func Test_PubL4PortFromAddr(t *testing.T) {
go/lib/topology/topology_test.go:                               oi, _ := tt.intopo.PubL4PortFromAddr(tt.inae)
```
</blockquote></details>

True, I'll remove it then.:tab

---

*[go/lib/topology/topology.go, line 118 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKdCBq6V3jBedZ562n:-LEP8_Li4hwaaDyNRTKz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/lib/topology/topology.go#L118)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It seems like it should be an error if it _was_ `nil`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/border/rctx/io.go, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKeYUU4oOBemBpuhTr:-LEPltvs6Uwf-x44CC67:bvu1hoy) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rctx/io.go#L99)):*
<details><summary><i>Previously, sgmonroy wrote…</i></summary><blockquote>

shouldn't we stopped the go routines before closing the ringbuf? otherwise the writer might try to queue packets to a closed ringbuf?
</blockquote></details>

As discussed offline - this deadlocks.

---

*[go/border/rpkt/route.go, line 84 at r1](https://reviewable.io/reviews/scionproto/scion/1587#-LEKkdkC0YXPpQRUWxvx:-LEPm5MQ4DD6uogfC4U2:ba37w0n) ([raw file](https://github.com/scionproto/scion/blob/275e9c6d212c2f286abde2e330b1ef1c36f62406/go/border/rpkt/route.go#L84)):*
<details><summary><i>Previously, sgmonroy wrote…</i></summary><blockquote>

How would you implement dual stack without having two Sock?
</blockquote></details>

It would work IF `Sock` could abstract the details away, but i don't know how messy that would get.

---

*[go/lib/topology/topology_test.go, line 251 at r2](https://reviewable.io/reviews/scionproto/scion/1587#-LEPajzU8QkqNvK69u64:-LEPajzU8QkqNvK69u65:b-asdrzn) ([raw file](https://github.com/scionproto/scion/blob/3af28327f40127180696b16d38ea3c7537b07ddf/go/lib/topology/topology_test.go#L251)):*
> ```Go
> }
> 
> var l4port_extract_cases = []struct {
> ```

This was only used by the unit test that was just removed, so it can be dropped too.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587#-:-LEhtjw8BoVP3KIyIAUf:bnfp4nl)*

**Comment by kormat** [comment]
`python/topology/generator.py` needs updating.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587#-:-LEhu2mP67RNnPbVxQ3S:b-k3ax6v)*

**Comment by kormat** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @sgmonroy)

---

*[python/topology/generator.py, line 703 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhuUOF6xJVNynmo1Fm:-LEhuUOF6xJVNynmo1Fn:bae4wcb) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/python/topology/generator.py#L703)):*
> ```Python
>             'Interfaces': {
>                 ifid: {  # Interface ID.
>                     'InternalAddrIdx': 0,
> ```

This should be dropped.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
Review status: all files reviewed, 3 unresolved discussions (waiting on @sgmonroy)

---

*[go/lib/topology/testdata/basic.json, line 58 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhumIp1LZq-AymUPC-:-LEhumIp1LZq-AymUPC0:b-48a1n1) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/go/lib/topology/testdata/basic.json#L58)):*
> ```JSON
>         "bs1-ff00:0:311-2": {"Public": [{"Addr": "2001:db8:f00:b43::65", "L4Port": 30054}]},
>         "bs1-ff00:0:311-3": {"Public": [
> 		{"Addr": "2001:db8:f00:b43::123", "L4Port": 10054},
> ```

Tabs (not added by you).

---

*[go/lib/topology/testdata/core.json, line 18 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhuphB9C1LB8mpNskD:-LEhuphB9C1LB8mpNskE:b5j8ewj) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/go/lib/topology/testdata/core.json#L18)):*
> ```JSON
>             "Interfaces": {
>                 "91": {
>                     "InternalAddrIdx": 0,
> ```

Needs to be updated.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by sgmonroy** [comment]
Review status: 29 of 32 files reviewed, 3 unresolved discussions (waiting on @kormat)

---

*[go/lib/topology/testdata/basic.json, line 58 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhumIp1LZq-AymUPC-:-LEjKOHCC5nxkHY6y9Sa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/go/lib/topology/testdata/basic.json#L58)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Tabs (not added by you).
</blockquote></details>

Done.

---

*[go/lib/topology/testdata/core.json, line 18 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhuphB9C1LB8mpNskD:-LEjKY7e405qR4GGeWdm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/go/lib/topology/testdata/core.json#L18)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Needs to be updated.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 703 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhuUOF6xJVNynmo1Fm:-LEjKrPWEAi1g2km2VlG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/python/topology/generator.py#L703)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be dropped.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---

*[python/topology/generator.py, line 703 at r3](https://reviewable.io/reviews/scionproto/scion/1587#-LEhuUOF6xJVNynmo1Fm:-LEjMBjW5bHznIN2Y0FP:brnnuyr) ([raw file](https://github.com/scionproto/scion/blob/955dde692497f86754489f1258db90787b269339/python/topology/generator.py#L703)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One more in the unit tests:
```
python/test/lib/topology_test.py:            'InternalAddrIdx': 0,
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1587)*

**Pull request merged**
