### PR TITLE
deps: use v2 of go-toml

### PR DESCRIPTION
**Pull request by lukedirtwalker**
v1 is no longer maintained.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4342)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4342#-:-NU0J0ZyCxdn-M5Y7pQK:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4342#-NU0GuXM35zidIwtVHIL:-NU0GuXN5-6nRSqqMaaG:bg3nqgz) (no related file):*
In `control/config/config.go`:161, in `struct BSConfig`, we have `EPIC bool` with the tag `toml:"epic,omitempty" default:"false"`.
According to the migration guide, the `default` tag is no longer supported.  I think we can just remove it.

___
___
*[`private/trust/config/config.go` line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4342#-NU0Fp2M3SEAH_y4sz2D:-NU0Fp2M3SEAH_y4sz2E:b30f6wu) ([raw file](https://github.com/scionproto/scion/blob/83bbe9cabbcf45f06a287314cb57e79355f15c65/private/trust/config/config.go#L52)):*
> ```Go
> type Cache struct {
> 	Disable    bool         `toml:"disable,omitempty"`
> 	Expiration util.DurWrap `toml:"expiration,omitempty"`
> ```

Good fix. Just for completeness, please note in the PR/commit description that this is a breaking change of the configuration format in this particular field.

**Review by oncilla — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4342)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4342)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`private/trust/config/config.go` line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4342#-NU0Fp2M3SEAH_y4sz2D:-Ngt-m5JCJC44bLvMddk:b-ufr8zv) ([raw file](https://github.com/scionproto/scion/blob/83bbe9cabbcf45f06a287314cb57e79355f15c65/private/trust/config/config.go#L52)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Good fix. Just for completeness, please note in the PR/commit description that this is a breaking change of the configuration format in this particular field.
</blockquote></details>

This has been changed in #4417, so nevermind.

**Review by matzf — APPROVED** [review]
> Reviewed 4 of 7 files at r2, 3 of 3 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4342)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4342)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Pull request merged**
