### PR TITLE
build: bump go version to 1.23

### PR DESCRIPTION
**Pull request by jiceatscion**
This required upgrading rules_go to 0.47.0 because of some magic parameter that must now be passed to the go assembler in support of the internal/V0 ABI split in go 1.22.

It wasn't possible to upgrade rules_go further without also upgrading bazel and other stuff. So... one problem at a time.

As a result of rules_go upgrade, the proto generation has changed, hence the other diffs.

Contributes to #4555

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4603)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4603)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
