### PR TITLE
scion-pki: Remove dead code

### PR DESCRIPTION
**Pull request by jinankjain**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1541)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/internal/base/base.go, line 22 at r1](https://reviewable.io/reviews/scionproto/scion/1541#-LB-mkcX3YI6l0HCdXQQ:-LB-mkcX3YI6l0HCdXQR:b-3vgujm) ([raw file](https://github.com/scionproto/scion/blob/524bd0d431522ac2c555bf7d25aa0743b01bfe01/go/tools/scion-pki/internal/base/base.go#L22)):*
> ```Go
> )
> 
> func ErrorAndExit(format string, a ...interface{}) {
> ```

The 'base' package is now so small, I think we can move this function to `pkicmn` and remove the `base` package entirely.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1541)*

**Comment by shitz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1541)*

**Comment by jinankjain** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/base/base.go, line 22 at r1](https://reviewable.io/reviews/scionproto/scion/1541#-LB-mkcX3YI6l0HCdXQQ:-LB-t2fL9Nlyy6vKthxp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/524bd0d431522ac2c555bf7d25aa0743b01bfe01/go/tools/scion-pki/internal/base/base.go#L22)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

The 'base' package is now so small, I think we can move this function to `pkicmn` and remove the `base` package entirely.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1541)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1541#-:-LBLAZ69-jKLn4xuL3-f:bnfp4nl)*

**Pull request merged**
