### PR TITLE
slayers: add Authenticator end-to-end option

### PR DESCRIPTION
**Pull request by matzf**
Add Authenticator end-to-end option, as described in doc/protocols/authenticator-option.rst (see #4014).

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf and @shitz)

___
*[go/lib/slayers/extn.go, line 374 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_R9s0o2YqthUIjns6E:-M_UsmxtAnHGlHexLARa:b-gkr2fd) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L374)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Why make this part of the type? I'd prefer
`func NewPacketAuthenticatorOption(alg, data) *EndToEndOption`
</blockquote></details>

Sure, that would seem more natural. The idea was that this allows to reuse the `EndToEndOption` and so reuse the internal buffer. When returning a new `EndToEndOption` there is no way to reuse the option or avoid the allocation for the internal buffer.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @matzf and @shitz)

___
*[go/lib/slayers/extn.go, line 374 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_R9s0o2YqthUIjns6E:-M_UwKmp7LUDUoKOiCCT:bbchqit) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L374)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Sure, that would seem more natural. The idea was that this allows to reuse the `EndToEndOption` and so reuse the internal buffer. When returning a new `EndToEndOption` there is no way to reuse the option or avoid the allocation for the internal buffer.
</blockquote></details>

I had a simple idea; with a small wrapper type it seems we can get both a simple `NewPacketAuthenticatorOption` and also conveniently reuse the buffer later with a `Reset` method on this `PacketAuthenticatorOption` type -- even better, we can have a method that returns the slice for the Authenticator data so we could even write to this directly. It also makes the parsing nicer as it can now return the same wrapper type instead of the individual fields.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @shitz)

___
*[go/lib/slayers/extn.go, line 354 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_R8W1m2R7LZEgc5P2q:-M_V0_0M8CiYRTU0dVlx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L354)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

I suggest a slightly different API:

```
var ErrOptionNotFound = serrors.New("Option not found")

func (e *EndToEndExtn) FindOption(typ OptionType) (*EndToEndOption, error) {
	for _, o := range e.Options {
		if o.OptType == typ {
			return o, nil
		}
	}
	return nil, ErrOptionNotFound
}
```

This can then be used for any option. 
We could drop it entirely, since it doesn't prevent a whole lot of boilerplate.


</blockquote></details>

Done.
___
*[go/lib/slayers/extn.go, line 363 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_RAny28tZ4_nBeCF1w:-M_V0b7Z9M2dL3yocmtq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L363)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

`PacketAuthAlg` would be more concise
</blockquote></details>

Done.
___
*[go/lib/slayers/extn.go, line 394 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_RAKgh70uDFR2gFTTR:-M_VNkNf9baAfSh8Uwhf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L394)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Same as above. Would make this a separate function (and public) that takes an `*EndToEndOption`
</blockquote></details>

Done.
___
*[go/lib/slayers/extn.go, line 396 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_RAT6f0N8duGiQlGdN:-M_VNjYs9-Py6SRsfdr8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L396)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Return an error instead of Panicking, especially if you make it public.
</blockquote></details>

Done.

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/lib/slayers/extn.go, line 374 at r1](https://reviewable.io/reviews/scionproto/scion/4036#-M_R9s0o2YqthUIjns6E:-M_WBuyeEc1XB74qe0y_:bco11k8) ([raw file](https://github.com/scionproto/scion/blob/1e15a85cc658f772634dc213144ae23b34acba8d/go/lib/slayers/extn.go#L374)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I had a simple idea; with a small wrapper type it seems we can get both a simple `NewPacketAuthenticatorOption` and also conveniently reuse the buffer later with a `Reset` method on this `PacketAuthenticatorOption` type -- even better, we can have a method that returns the slice for the Authenticator data so we could even write to this directly. It also makes the parsing nicer as it can now return the same wrapper type instead of the individual fields. 
</blockquote></details>

Yup I like it. :+1: 
___
*[go/lib/slayers/extn.go, line 410 at r2](https://reviewable.io/reviews/scionproto/scion/4036#-M_WC5upE7uNRb0011Hr:-M_WC5upE7uNRb0011Hs:bkt97j3) ([raw file](https://github.com/scionproto/scion/blob/015784f9c85e91437ff99dfb7752088eac2cd635/go/lib/slayers/extn.go#L410)):*
> ```Go
> }
> 
> func (o PacketAuthenticatorOption) Authenticator() []byte {
> ```

Add a docstring explaining that this will return the underlying buffer and that changing it will be reflected on the wire once the extension gets serialized. I'm not really sure if there is a usecase for writing directly to this buffer (maybe when reverting a packet and updating the authenticator?). In any case, writing to the buffer should be done with care.

**Review by shitz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036#-:-M_eLqfh48FkjTIwQ47t:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/lib/slayers/extn.go, line 377 at r3](https://reviewable.io/reviews/scionproto/scion/4036#-M_eIIFvAE0cdUpfoDNP:-M_eIIFw1VO7R2bCuhrL:b-v0e277) ([raw file](https://github.com/scionproto/scion/blob/7d44252e6f64caba1b2af2b07ad43a0dc3eb8c0e/go/lib/slayers/extn.go#L377)):*
> ```
> EndTOEndOption
> ```
nit - EndToEndOption

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4036)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @shitz)

___
*[go/lib/slayers/extn.go, line 410 at r2](https://reviewable.io/reviews/scionproto/scion/4036#-M_WC5upE7uNRb0011Hr:-M_dxW1u8nVcwZIirRRa:b-ece4xg) ([raw file](https://github.com/scionproto/scion/blob/015784f9c85e91437ff99dfb7752088eac2cd635/go/lib/slayers/extn.go#L410)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Add a docstring explaining that this will return the underlying buffer and that changing it will be reflected on the wire once the extension gets serialized. I'm not really sure if there is a usecase for writing directly to this buffer (maybe when reverting a packet and updating the authenticator?). In any case, writing to the buffer should be done with care.
</blockquote></details>

Done, added docs.

The use case I had in mind is for authenticated SCMP reply messages created in the router: we can create the PacketAuthenticatorOption once and write the MAC directly to this buffer. It's probably not a big win, but still nice.
___
*[go/lib/slayers/extn.go, line 377 at r3](https://reviewable.io/reviews/scionproto/scion/4036#-M_eIIFvAE0cdUpfoDNP:-M_esXaq9JznqJpxHopb:bo3vl6y) ([raw file](https://github.com/scionproto/scion/blob/7d44252e6f64caba1b2af2b07ad43a0dc3eb8c0e/go/lib/slayers/extn.go#L377)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> EndTOEndOption
> ```
nit - EndToEndOption
</blockquote></details>

Thanks, done.

**Pull request closed without merging**
