### PR TITLE
router: small refactoring to remove the need for a batchconn.WriteTo

### PR DESCRIPTION
**Pull request by jiceatscion**
WriteTo needs to be given the destination address explicitly. WriteBatch, on the other end, can either find it in each packet structure, or rely on the connection's destination. WriteTo is only used to send BFD packets. It turns out that BFD packets can also very easily be sent via the regular forwarders that use WriteBtach.

The motivation to do that is to simplify the interface between the dataplane and the forwarders, in view of supporting multiple underlays with possibly very different interfaces. So the channels around the processor tasks seems like a good universal interface.

In passing, also removed a duplicate field. Slightly off-topic but still in the spirit of noise abatement.

As this is to facilitate the necessary refactoring...
Contributes to #4593

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @marcfrei)

___
*[`router/dataplane.go` line 1830 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HWvS94iRIvdwnkTe:-OB_pYBo14Vlu5BpdqgI:b-z65wrh) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L1830)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Comment doesn't contribute much, imo. Could be removed.
</blockquote></details>

I found it a useful reminder to understand what's happening. I find the name external misleading in that context (like the interface is somewhere else, which is the exact opposite of the truth). So, even though it's a note-to-self, it may help others.
___
*[`router/dataplane.go` line 2423 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HP6iEp_8PSlgb3c2:-OB_qM-m8arO_Q_GKoeB:b-oy1oe7) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2423)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Remove comment.
</blockquote></details>

This was intended to trigger an opinion in the reviewer. Apparently yours is that it shouldn't be a panic-able offense, right?
___
*[`router/dataplane.go` line 2430 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KLGl6p0Jrwhb9Ech:-OB_qogSBGrcLuu6seNq:bxadom7) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2430)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Since this is new code, I would either do it or remove the comment.
</blockquote></details>

Fair point. I do not have a simple solution right now - it might become easier as refactoring progresses. However, I'd like to leave this as a hint for a future maintainer (most likely me). Would a TODO be more acceptable here?
___
*[`router/dataplane.go` line 2441 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KpV37Aoqp9BfDrlb:-OB_uRM_3qxYhwg6HmU0:b-62x01c) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2441)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Same. Either do it or remove the comment.
</blockquote></details>

As before... what's your opinion? Does it mater? Before we didn't have the potential for a queue full.

**Comment by marcfrei** [comment]
*[`router/dataplane.go` line 2430 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KLGl6p0Jrwhb9Ech:-OBaCkLI5la81knycZEz:bqa7r3k) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2430)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Fair point. I do not have a simple solution right now - it might become easier as refactoring progresses. However, I'd like to leave this as a hint for a future maintainer (most likely me). Would a TODO be more acceptable here?
</blockquote></details>

Ok, if it's not actually clear how to do this well, a `TODO` would be fine, imo.

**Review by marcfrei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @jiceatscion)

___
*[`router/dataplane.go` line 2423 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HP6iEp_8PSlgb3c2:-OBaC3IQ2zhKXUr6ul1c:b-lo5e2k) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2423)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

This was intended to trigger an opinion in the reviewer. Apparently yours is that it shouldn't be a panic-able offense, right?
</blockquote></details>

No, didn't get that this is a meta-comment intended to be removed before merging. I think we could indeed panic here.
___
*[`router/dataplane.go` line 2441 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KpV37Aoqp9BfDrlb:-OBaDos7E59YZqG_r93D:biwi8c4) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2441)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

As before... what's your opinion? Does it mater? Before we didn't have the potential for a queue full.
</blockquote></details>

I'm not sure actually about incrementing a metric. Up till now we don't do the increment on the slow path, as far as I can see. So maybe this is similar to that case?

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @jiceatscion and @marcfrei)

___
*[`router/dataplane.go` line 2423 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HP6iEp_8PSlgb3c2:-OBakJr52_XO9_IX3L-z:b-sdqmec) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2423)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

No, didn't get that this is a meta-comment intended to be removed before merging. I think we could indeed panic here.
</blockquote></details>

I think so too. I'll change the code to let-it-crash.
___
*[`router/dataplane.go` line 2430 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KLGl6p0Jrwhb9Ech:-OBaj9Lp-C68yLp4cG-q:b-qqw06a) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2430)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Ok, if it's not actually clear how to do this well, a `TODO` would be fine, imo.
</blockquote></details>

Will do. In the meantime I figured how to do it, but it's a bit ugly and I'd rather wait until more refactoring allows it more cleanly.
___
*[`router/dataplane.go` line 2441 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KpV37Aoqp9BfDrlb:-OBajZMH-oEPfijBI3mg:bo6hpqe) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2441)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

I'm not sure actually about incrementing a metric. Up till now we don't do the increment on the slow path, as far as I can see. So maybe this is similar to that case?
</blockquote></details>

I'm leaning that way too. So, I'll ditch the comment.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @marcfrei)

___
*[`router/dataplane.go` line 2441 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KpV37Aoqp9BfDrlb:-OBaovP07oh59XUgKgr6:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2441)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I'm leaning that way too. So, I'll ditch the comment.
</blockquote></details>

done

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @marcfrei)

___
*[`router/dataplane.go` line 2430 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_KLGl6p0Jrwhb9Ech:-OBaoyc_2K9XNTvLFkie:bb7f2mf) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2430)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Will do. In the meantime I figured how to do it, but it's a bit ugly and I'd rather wait until more refactoring allows it more cleanly.
</blockquote></details>

done

**Review by marcfrei — APPROVED** [review]
Thank you!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651#-:-OBb-qa14BS0gT9rq2MA:b-9755fn)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`router/dataplane.go` line 2423 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HP6iEp_8PSlgb3c2:-OBiGz_S5BKZt7DgPsSy:b-j5iqkz) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2423)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

done
</blockquote></details>

Does it actually panic if you just assign the ok to `_`, let's drop the `, _`

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @marcfrei)

___
*[`router/dataplane.go` line 2423 at r2](https://reviewable.io/reviews/scionproto/scion/4651#-OB_HP6iEp_8PSlgb3c2:-OBjGRWZ9ECvzzULEl8K:b14u0qi) ([raw file](https://github.com/scionproto/scion/blob/2ac2725663d199cb4c73df0f6ab175e4700ed50a/router/dataplane.go#L2423)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Does it actually panic if you just assign the ok to `_`, let's drop the `, _`
</blockquote></details>

You're right; it would panic a few lines down, which isn't helpful.
Fixed.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4651)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
