### PR TITLE
bazel: update bazelisk and support arm64

### PR DESCRIPTION
**Pull request by mlegner**
Bazel and bazilisk do support ARM64 by now. Unfortunately, I get an error when building `//:scion-ci`, but building `//:scion` works perfectly (after applying #4446). So I suggest to lift the restriction on AMD64 and, while we're at it, update bazelisk to the latest version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4447)

### CODE REVIEW

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4447#-:-Nk0HdoCD4CYrTEurthB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mlegner)

**Review by mlegner — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mlegner)

**Comment by mlegner** [comment]
@oncilla Is there anything further I need to do for this PR?

**Comment by matzf** [comment]
Nope, all good :)

**Pull request merged**
