### PR TITLE
build: update to Go 1.21.1

### PR DESCRIPTION
**Pull request by uniquefine**
Update Go version to 1.21.1
Additionally, upgrade various build dependencies.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4378)

### CODE REVIEW

**Comment by uniquefine** [comment]
Please don't review until I get CI to pass

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4378)* status: 0 of 59 files reviewed, 1 unresolved discussion (waiting on @uniquefine)

___
*[`WORKSPACE` line 43 at r6](https://reviewable.io/reviews/scionproto/scion/4378#-NdfG4zHEbpuP0VL18uz:-NdfG4zI8uKQhi4IFx82:b-pee4m9) ([raw file](https://github.com/scionproto/scion/blob/9bdd29ccfe7994e50a689d4d0fe9f7b8c43de3ca/WORKSPACE#L43)):*
> ```Starlark
> aspect_bazel_lib_dependencies()
> 
> # Bazel rules for Golang
> ```

Reminder: drop x/sys introduced in #4385

**Review by matzf — COMMENTED** [review]
> Reviewed 8 of 23 files at r1, 17 of 21 files at r2, 8 of 23 files at r4, 4 of 13 files at r5, 10 of 11 files at r6, 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4378)* status: all files reviewed, 3 unresolved discussions (waiting on @uniquefine)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4378#-NdkIeN6BjE_sb8ed-qe:-NdkIeN6BjE_sb8ed-qf:b-jxc3z7) (no related file):*
I've attempted to build with the sqlite library toggle in `.bazelrc` set to `sqlite_mattn`.
This broke my build and it remains broken after switching back. Once I'll have fixed my normal build, I'll try to find out if this is a real issue or if it was just a freak incident.

___
___
*[`go.mod` line 52 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndk8cbw88oWz7vaCrJI:-Ndk8cbw88oWz7vaCrJJ:b-90tg6b) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/go.mod#L52)):*
> ```XML
> 	google.golang.org/grpc/examples v0.0.0-20230222033013-5353eaa44095
> 	// Necessary so @org_golang_google_genproto is included in the go_deps.bzl.
> 	google.golang.org/protobuf v1.31.0
> ```

This `google.golang.org/protobuf` dependency is added by `go mod tidy` anyways, because we use it directly in the code. I'm a bit confused what this comment is trying to say.
___
*[`pkg/snet/squic/net.go` line 27 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndk8v8D4Dsb8yxuwNEd:-Ndk8v8D4Dsb8yxuwNEe:b-aof3yd) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/pkg/snet/squic/net.go#L27)):*
> ```Go
> 	"time"
> 
> 	quic "github.com/quic-go/quic-go"
> ```

Why the alias?

**Review by matzf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4378)* status: all files reviewed, 3 unresolved discussions (waiting on @uniquefine)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4378#-NdkIeN6BjE_sb8ed-qe:-Ndl4UHAC07pnft1aFQ2:b-ggjlwd) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I've attempted to build with the sqlite library toggle in `.bazelrc` set to `sqlite_mattn`.
This broke my build and it remains broken after switching back. Once I'll have fixed my normal build, I'll try to find out if this is a real issue or if it was just a freak incident.
</blockquote></details>

Nevermind, it seems to be working consistently now, must have been some strange accident.

___
___
*[`Makefile` line 33 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndkxp4S63MDRO3jlICr:-Ndkxp4S63MDRO3jlICs:bxsuw96) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/Makefile#L33)):*
> ```Makefile
> 
> go_deps.bzl: go.mod
> 	@# gazelle is run with "-args"; so our arguments are added to those from the gazelle() rule. 
> ```

Remove the outdated comment.

Btw. this `-args` is a bit odd. Luckily, everything seems to work, but it appears to have been an internal thing that we should perhaps not have used: https://github.com/bazelbuild/bazel-gazelle/pull/1546. In the old gazelle version, things did _not_ work without the -args flag.
If I understood correctly, the original "need" for this was that some of the "args" for the gazelle commands where specified in the gazelle rule (to help doing the dance with the gotags buildflags), but some had been defined in the Makefile. Mostly things have just been moved into the BUILD file, but the update-repos thing was left in a mixed state.
We could clean this up completely , either by removing the `gazelle_update_repos` entirely and moving the entire call into the Makefile, or the other way around, by moving all the parameters into the `gazelle_update_repos` definition.

**Review by oncilla — COMMENTED** [review]
> Reviewed 2 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4378)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`go.mod` line 52 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndk8cbw88oWz7vaCrJI:-Ndoo5BR0NRUZ_8FpSdd:b-51ay9j) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/go.mod#L52)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This `google.golang.org/protobuf` dependency is added by `go mod tidy` anyways, because we use it directly in the code. I'm a bit confused what this comment is trying to say.
</blockquote></details>

Yeah. Also not sure. I dropped it.
___
*[`Makefile` line 33 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndkxp4S63MDRO3jlICr:-Ndoq5zUChZxp18yAhv4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/Makefile#L33)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Remove the outdated comment.

Btw. this `-args` is a bit odd. Luckily, everything seems to work, but it appears to have been an internal thing that we should perhaps not have used: https://github.com/bazelbuild/bazel-gazelle/pull/1546. In the old gazelle version, things did _not_ work without the -args flag.
If I understood correctly, the original "need" for this was that some of the "args" for the gazelle commands where specified in the gazelle rule (to help doing the dance with the gotags buildflags), but some had been defined in the Makefile. Mostly things have just been moved into the BUILD file, but the update-repos thing was left in a mixed state.
We could clean this up completely , either by removing the `gazelle_update_repos` entirely and moving the entire call into the Makefile, or the other way around, by moving all the parameters into the `gazelle_update_repos` definition.
</blockquote></details>

Done.
___
*[`pkg/snet/squic/net.go` line 27 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndk8v8D4Dsb8yxuwNEd:-NdoqKeB-Cp5Cvujf7w4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/pkg/snet/squic/net.go#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Why the alias?
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4378#-:-Ne25nNj4QEMc650l4W8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uniquefine)

___
*[`Makefile` line 33 at r7](https://reviewable.io/reviews/scionproto/scion/4378#-Ndkxp4S63MDRO3jlICr:-Ne25ZcfDE3uPXrDranD:bmi8ppe) ([raw file](https://github.com/scionproto/scion/blob/e745e56d5d60a3aba149f548229969dfd9e16d64/Makefile#L33)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:100:

**Pull request merged**
