### PR TITLE
router: clarified cryptic comment

### PR DESCRIPTION
**Pull request by jiceatscion**
This was noticed by a reviewer of #4579

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4580)

**Review by JordiSubira — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4580#-:-O24_cZK7GPxR0PLtG6D:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by jiceatscion — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4580)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Comment by jiceatscion** [comment]
Took the liberty of approving the one file change on behalf of Jordi.

**Pull request merged**
