### PR TITLE
repo: consolidate tools

### PR DESCRIPTION
**Pull request by matzf**
Follow up on #4163, further consolidate tools under `tools/`.

- `lint/` -> `tools/lint/`
- `scripts/cryptoplayground/` -> `tools/cryptoplayground/`
- `env/` -> `tools/env/`, `tools/install_deps`
- `supervisor/` -> `tools/`
- `python/` -> `tools/topology/`, `tools/topogen.py`
- `integration/` -> `tools/integration/`

Also includes some housekeeping 
- further reduce python library code, by simplifying the ISD_AS (no integer representation needed) and LinkType enum
- remove left-over integration bash scripts
- remove topogentar and the related bazel infrastructure

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)

### CODE REVIEW

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)* status: 0 of 378 files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4167#-MyHZDg89-dC7Gw-JXPH:-MyHZDg9DvgqfUDQis1a:bab2g4r) (no related file):*
Regarding topogentar:

This was a convenience tool to run the docker topology with bazel.
But internally, we usually just start up an acceptance test topology, instead of one of the defined topologies.
Rendering the topology rules obsolete.

You can drop it IMO.

Note that you also want to drop the following:
- https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/topology/BUILD.bazel#L18-L21
- https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/python/topology/topology.bzl
- 

---

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)* status: 0 of 378 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[acceptance/common/topogen.bzl, line 55 at r1](https://reviewable.io/reviews/scionproto/scion/4167#-MyHaHpO1Gjt7KhMsCWq:-MyHaHpO1Gjt7KhMsCWr:b-k55mfv) ([raw file](https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/acceptance/common/topogen.bzl#L55)):*
> ```Starlark
>     ]
>     common_data = [
>         "//scion-pki/cmd/scion-pki",
> ```

From CI output:
```
./acceptance/common/topogen.bzl # reformat
 
to fix run:
bazel run //:buildifier
 ````

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)* status: 0 of 378 files reviewed, 2 unresolved discussions (waiting on @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4167#-MyHZDg89-dC7Gw-JXPH:-MyI1gKwBdUwxFQxBtPa:bkm0upe) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Regarding topogentar:

This was a convenience tool to run the docker topology with bazel.
But internally, we usually just start up an acceptance test topology, instead of one of the defined topologies.
Rendering the topology rules obsolete.

You can drop it IMO.

Note that you also want to drop the following:
- https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/topology/BUILD.bazel#L18-L21
- https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/python/topology/topology.bzl
- 
</blockquote></details>

All clear, thanks, done.

---
___
*[acceptance/common/topogen.bzl, line 55 at r1](https://reviewable.io/reviews/scionproto/scion/4167#-MyHaHpO1Gjt7KhMsCWq:-MyI1jMt4ukgV6U-Tlv5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb4dd91c0790a1671ba0c5d95ba7589bdfd3356a/acceptance/common/topogen.bzl#L55)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

From CI output:
```
./acceptance/common/topogen.bzl # reformat
 
to fix run:
bazel run //:buildifier
 ````
</blockquote></details>

Done.

**Review by oncilla — COMMENTED** [review]
> Reviewed 372 of 378 files at r1, 1 of 1 files at r2, 2 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167#-:-MyIeoWTCM8D_y58A3U6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by oncilla — COMMENTED** [review]
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4167)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @matzf)

**Pull request closed without merging**
