### PR TITLE
tools: support 16bit interface IDs in topo files

### PR DESCRIPTION
**Pull request by tzaeschke**
Change the limit for interface IDs in topofiles from 12bit to 16bit.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4636)

**Review by FR4NK-W — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4636#-:-O8gZ9fn6oBl_wtnEUhZ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tzaeschke)

**Comment by tzaeschke** [comment]
@jiceatscion @FR4NK-W 
I am still unsure about this "reviewable" application.
Why does it say "waiting on @tzaeschke"? 
I probably shouldn't mark it as "reviewed¨ myself....?

**Review by FR4NK-W — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4636)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tzaeschke)

**Pull request merged**
