### PR TITLE
ci: changes for new buildkite stack

### PR DESCRIPTION
**Pull request by matzf**
The new setup uses the default buildkite Elastic CI Stack machine image, based on Amazon Linux 2 (a Red Hat derivative), instead of a custom ubuntu based runner image. This requires installing some of the tooling on agent startup; we only need bazel, a C compiler toolchain and a few python packages. Obviously this causes a small overhead for agent startup (around 1 minute), but it makes the setup simpler and more transparent.

* Simplify the existing dependency installation scripts and add a new one for "rhel" (anything with `yum`). This installs the missing dependencies for the current buildkite runner machine image, so some dependencies might be missing for other Red Hat derivatives.
* Install dependencies in buildkite pre-command hook; a checksum ensures that the setup is only re-run if the scripts change between checkouts.
* Add overview documentation for buildkite CI setup. Document the most relevant settings and parameters that are not otherwise visible to contributors without special access rights to our buildkite organisation or the AWS account.

Additional changes related to running builds and tests on RHEL:
* Demo file_transfer: replace `bbcp` file transfer with `iperf3` simulation

  Cannot run `bbcp` built on RHEL in the debian-based tester container image. 
  As this links against system libraries, the dynamically loaded shared libraries don't match at runtime. 
  The same issue will occur when building `bbcp` on newer versions of Ubuntu, or any other system that does not closely match the tester image. 

  To avoid this problem properly, building bbcp would have to happen within a docker container. 
  Implementing this would seem to require different infrastructure than what we currently are using for building docker images.
  This seems too much of a hassle for such a small demo; for all demo-purposes, iperf3 "looks" exactly the same.

* SIG docker setup: temporarily run `/app/gateway` as root user in sig container.

  The gateway binary is `setcap`-ed to obtain the required capabilities. This _should_ allow running it as unprivileged user, and  it _does_ work on ubuntu. For some unknown reason, the `setcap` is just ineffective when running this docker container on RHEL (it will say "ioctl: operation not permitted" when trying to open the tun device). This will need to be investigated and fixed.

This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)

### CODE REVIEW

**Review by sustrik — COMMENTED** [review]
> Reviewed 4 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)* status: 4 of 25 files reviewed, all discussions resolved

**Review by marcfrei — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 21 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297#-:-NHZGmD74IiICFt7onby:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`doc/testing/buildkite.rst` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4297#-NHZF0qvA4k5aw4NnKxE:-NHZF0qvA4k5aw4NnKxF:bv30ylb) ([raw file](https://github.com/scionproto/scion/blob/3c7630aee9901926f418bc6b815cef3d5cd51631/doc/testing/buildkite.rst#L27)):*
> ```reStructuredText
> 8. The agent runs its job and uploads the output to buildkite.
> 
> Importantly, buildkite jobs can spawn new jobs by uploading (from the agent to the central buildkite service) more pipeline steps.
> ```

rearrange the sentence a bit?
buildkite jobs can spawn new jobs by uploading more pipeline steps (from the agent to the central buildkite service).



_Code quote:_
```reStructuredText
buildkite jobs can spawn new jobs by uploading (from the agent to the central buildkite service) more pipeline steps
```
___
*[`doc/testing/buildkite.rst` line 28 at r2](https://reviewable.io/reviews/scionproto/scion/4297#-NHZFRZZ3jh3oCpWtWsj:-NHZFRZZ3jh3oCpWtWsk:b7u9ejf) ([raw file](https://github.com/scionproto/scion/blob/3c7630aee9901926f418bc6b815cef3d5cd51631/doc/testing/buildkite.rst#L28)):*
> ```reStructuredText
> 
> Importantly, buildkite jobs can spawn new jobs by uploading (from the agent to the central buildkite service) more pipeline steps.
> The first job of a pipeline is configured in the buildkite pipeline, and it's usually a dummy step that loads or expands the pipeline config file from the repository, spawning all the jobs that will then do perform the actual build tasks.
> ```

delete "do"?
the jobs that will then perform the actual build tasks



_Code quote:_
```reStructuredText
the jobs that will then do perform the actual build tasks
```

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)* status: 24 of 25 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @marcfrei)

___
*[`doc/testing/buildkite.rst` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4297#-NHZF0qvA4k5aw4NnKxE:-NHZN7BN9uEyai_GfFJC:bo3vl6y) ([raw file](https://github.com/scionproto/scion/blob/3c7630aee9901926f418bc6b815cef3d5cd51631/doc/testing/buildkite.rst#L27)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

rearrange the sentence a bit?
buildkite jobs can spawn new jobs by uploading more pipeline steps (from the agent to the central buildkite service).
</blockquote></details>

Thanks, done.
___
*[`doc/testing/buildkite.rst` line 28 at r2](https://reviewable.io/reviews/scionproto/scion/4297#-NHZFRZZ3jh3oCpWtWsj:-NHZN8wX8T7OUA3oRxEv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3c7630aee9901926f418bc6b815cef3d5cd51631/doc/testing/buildkite.rst#L28)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

delete "do"?
the jobs that will then perform the actual build tasks
</blockquote></details>

Done.

**Review by marcfrei — COMMENTED** [review]
> Reviewed 2 of 23 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 22 of 23 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[`.buildkite/provision-agent.sh` line 5 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZYZrrAxwxYBsLUrfn:-NHZYZrrAxwxYBsLUrfo:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/.buildkite/provision-agent.sh#L5)):*
> ```Shell
> set -euo pipefail
> 
> # The installation scripts are no-ops when nothing has changed. 
> ```

trailing space



_Suggestion:_
```Shell
.
```
___
*[`doc/testing/buildkite.rst` line 78 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZalCLAyuEU2INhR0G:-NHZalCLAyuEU2INhR0H:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L78)):*
> ```reStructuredText
> 
> The secrets to access the S3 buckets for the caches mentioned above are injected as environment variables from this ``env`` script.
> See `.buildkite/hooks/bazel-remote.yml <https://github.com/scionproto/scion/blob/master/.buildkite/hooks/bazel-remote.yml>`_ 
> ```

trailing space



_Suggestion:_
```reStructuredText
_
```
___
*[`doc/testing/buildkite.rst` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZai0fEC74QeBXrahn:-NHZai0gCGGeKSk1gePS:bn6g6rr) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L86)):*
> ```reStructuredText
> .. important::
> 
>    The agent cluster is operated by the SCION Association, in the AWS account ``scion-association``. 
> ```

trailing space



_Suggestion:_
```reStructuredText
.
```
___
*[`doc/testing/buildkite.rst` line 99 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZauBHEAEPmpghwGZb:-NHZauBHEAEPmpghwGZc:bsawith) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L99)):*
> ```reStructuredText
>    ImageId: ""               # use default machine image based on Amazon Linux 2
>    InstanceType: t3.2xlarge  # 8 vCPUs, 32GiB memory
>    RootVolumeSize: 250
> ```

I don't think you need that much tbh, we run with 100GB which is probably even too much.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4297)* status: 23 of 25 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @marcfrei)

___
*[`.buildkite/provision-agent.sh` line 5 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZYZrrAxwxYBsLUrfn:-NHZnPB65NjYbgG4lX_W:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/.buildkite/provision-agent.sh#L5)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.
___
*[`doc/testing/buildkite.rst` line 78 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZalCLAyuEU2INhR0G:-NHZnQ-MEJDsNFxVIM8k:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L78)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.
___
*[`doc/testing/buildkite.rst` line 86 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZai0fEC74QeBXrahn:-NHZnQZn9BrVBiKacPxF:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L86)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

trailing space
</blockquote></details>

Done.
___
*[`doc/testing/buildkite.rst` line 99 at r3](https://reviewable.io/reviews/scionproto/scion/4297#-NHZauBHEAEPmpghwGZb:-NHZnQsu4sgpkBq_ZFB3:b-wzg0xs) ([raw file](https://github.com/scionproto/scion/blob/3e729b2f534e4f0fb461eaa9441dcc171ff6539e/doc/testing/buildkite.rst#L99)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I don't think you need that much tbh, we run with 100GB which is probably even too much.
</blockquote></details>

Excellent, great to know, thanks! I've changed to 100GB as well.

**Pull request merged**
