### PR TITLE
Make up/down ingress/egress less ambiguous for paths

### LINKED ISSUE #1479: Make up/down ingress/egress less ambiguous for paths
Currently the terms up/down ingress/egress are used regarding paths, but mean different things in different contexts.

In an `InfoField`, the `Up` flag indicates the _opposite_ direction to which the path was constructed.
An "Up-segment" refers to a segment heading towards the core from a non-core AS.

In a `HopField`, the `ingress` ifid indicates the interface from which path construction came (for beaconing this is the up-stream interface; for one-hop-path or (conceptually) SIBRA, there is no beaconing).
In forwarding, `ingress` refers to the interface through which the packet entered the local AS.

My proposal is to change the terms that are relative to path construction as follows:
- `up` becomes `!consDir` (as the current "up" is the opposite of the construction direction)
- `ingress` becomes `consIngress`
- `egress` becomes `consEgress`

That should make it a lot easier to reason about data-plane path handling.

### PR DESCRIPTION
**Pull request by worxli**
Make up/down ingress/egress less ambiguous for paths, fixes #1479

- `up` becomes `!consDir` (as the current "up" is the opposite of the construction direction)
- `ingress` becomes `consIngress`
- `egress` becomes `consEgress`

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1527)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 27 files at r1.
Review status: 1 of 27 files reviewed at latest revision, all discussions resolved.

---

*[go/lib/spath/info.go, line 48 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1527#-LAXLYxu5_U7RINkWVa0:-LAXLYxu5_U7RINkWVa1:b8xayze) ([raw file](https://github.com/scionproto/scion/blob/ef7c600d57439b2547f9c54df2b72f1a9ee0b521/go/lib/spath/info.go#L48)):*
> ```Go
> 	inf := &InfoField{}
> 	flags := b[0]
> 	inf.ConsDir = flags&0x1 == 0
> ```

My intention with this proposal was to change the _concept_, not just the name. Meaning, `inf.ConsDir = flags&01 != 0`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1527)*

**Comment by kormat** [comment]
Review status: 1 of 27 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/spath/info.go, line 48 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1527#-LAXLYxu5_U7RINkWVa0:-LAXMhD44DoO7WSer8Ya:b-t8t7lu) ([raw file](https://github.com/scionproto/scion/blob/ef7c600d57439b2547f9c54df2b72f1a9ee0b521/go/lib/spath/info.go#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

My intention with this proposal was to change the _concept_, not just the name. Meaning, `inf.ConsDir = flags&01 != 0`.
</blockquote></details>

(And yes, this is a breaking change)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1527)*

**Comment by kormat** [comment]
Review status: 19 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[python/lib/packet/path.py, line 198 at r3](https://reviewable.io/reviews/scionproto/scion/1527#-LEAJwj_9B1vOWALo24C:-LEAJwjaAI5QKxBpD0wa:bv1jt74) ([raw file](https://github.com/scionproto/scion/blob/0e38ed1f60f7b8a26523ed21c0eaf2576525be2e/python/lib/packet/path.py#L198)):*
> ```Python
>             # interface, and another from the upstream interface, used for
>             # verification only.
>             ingress_up = {(True, False): +2, (True, True): +1,
> ```

The var needs to be renamed. The `up` refers to the old Up flag. Same below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1527)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[python/lib/packet/opaque_field.py, line 159 at r2](https://reviewable.io/reviews/scionproto/scion/1527#-LCiVeJF79HsLobPg7r_:-LEANJkzAsAhK2G3oP5f:b9eoyud) ([raw file](https://github.com/scionproto/scion/blob/af2a52a7a62bb3d6e18ad057ddbb8d448ed54216/python/lib/packet/opaque_field.py#L159)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

Integration tests fail, when it is set to `True`. Unfortunately I couldn't find the exact cause.
</blockquote></details>

Ahh, i see it. `False` is correct. `_parse_flags` only sets it to `True` if `CONS_DIR` is set, so the default has to be the opposite.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1527)*

**Comment by worxli** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[python/lib/packet/path.py, line 198 at r3](https://reviewable.io/reviews/scionproto/scion/1527#-LEAJwj_9B1vOWALo24C:-LEECB5iAYD4gF9YrrZf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0e38ed1f60f7b8a26523ed21c0eaf2576525be2e/python/lib/packet/path.py#L198)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The var needs to be renamed. The `up` refers to the old Up flag. Same below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1527)*

**Comment by kormat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1527#-:-LEEEAgY0FECRYPgAR6z:bnfp4nl)*

**Pull request merged**
