### PR TITLE
router: serialize directly into packet buffers

### PR DESCRIPTION
**Pull request by jiceatscion**
In every case where the router modified packets it would serialize updated headers to a temporary buffer and then copy that to the packet buffer.

To avoid this extra copy, replaced gopacket.serializeBuffer with a custom implementation that writes to a given buffer. In this case, the packet's raw buffer.

There is one remaining copy for some SCMP messages because we have to move the existing packet to the payload. This too could be avoided but that's for another PR; it would require to leave headroom in received packets.

The performance impact is very small since, on the critical path, it just avoids copying a scion hdr per packet, but it is a simplification. It also pays back the copy added by a previous simplification of the BFD code. As such...

Contributes to #4593

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4654)

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4654)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @FR4NK-W, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`router/dataplane.go` line 2299 at r2](https://reviewable.io/reviews/scionproto/scion/4654#-OCnS1DK9-Ud-BwpIHVl:-OCnXXhn1h_Nwgq3Zdeu:bvfk1d0) ([raw file](https://github.com/scionproto/scion/blob/67295230fa95c888e0fddb6f4e6aeee1280136e7/router/dataplane.go#L2299)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Wouldn't it be cleaner to provide a special factory function for this use case instead of using `serializeProxy.clear`?
</blockquote></details>

Yeah, I wasn't sure that I wanted to add a constructor for such a minority use case. Although it might become more frequent...So, reworked along those lines. I've changed initStart to restart speculatively.
___
*[`router/serializeProxy.go` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4654#-OCnCHZD3y3ZNYmjYqiB:-OCnV93ICH3vYXAlZ3sm:b-h9hd4q) ([raw file](https://github.com/scionproto/scion/blob/67295230fa95c888e0fddb6f4e6aeee1280136e7/router/serializeProxy.go#L27)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

How about `serializeBuffer` instead of `serializeProxy`. "Proxy" can have so many meanings, not sure that the name helps here.
</blockquote></details>

I chose the name to distinguish it from the default implementation. The default implementation does supply the buffer, which is its main downside. This one acts as an intermediary between the using code and the actual buffer. So, a buffer-by-proxy. Of cause proxy is overloaded, but serializeBuffer is already taken and misleading. I have searched for a better name but couldn't find anything that wasn't just as overused. Ideas welcome.
___
*[`router/serializeProxy.go` line 28 at r2](https://reviewable.io/reviews/scionproto/scion/4654#-OCnIivkEO1UyNLKexaa:-OCnVxg4DfGpvLbKVms7:b-uzx7de) ([raw file](https://github.com/scionproto/scion/blob/67295230fa95c888e0fddb6f4e6aeee1280136e7/router/serializeProxy.go#L28)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

`orig` or `origStart`?
</blockquote></details>

uh, initStart is bad, but so is origStart. We reset to that value at the next Clear()... how about clearStart or resetStart or ...how about restart?
___
*[`router/serializeProxy.go` line  at r2](https://reviewable.io/reviews/scionproto/scion/4654#-OCnCDqz2GKloekwgtMr:-OCnV3eHBNOhqzyHfagd:b4h0aoo) ([raw file](https://github.com/scionproto/scion/blob/67295230fa95c888e0fddb6f4e6aeee1280136e7/router/serializeProxy.go#L)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

We don't usually have file names in camel case, right?
</blockquote></details>

oops, fixed

**Review by marcfrei — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4654#-:-OCqycXo-kOAGSwNYFCj:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @FR4NK-W, @jiceatscion, @lukedirtwalker, and @oncilla)

___
*[`router/serialize_proxy.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4654#-OCqxBr94Mjn9hPh1cxG:-OCqxBr94Mjn9hPh1cxH:b-w8b2vg) ([raw file](https://github.com/scionproto/scion/blob/dfe7a6a67ec229af84131ec688a3bd3bd2fc81de/router/serialize_proxy.go#L47)):*
> ```Go
> // newSerializeProxyOffset returns a new serializeProxy. The initial prepend/append point is set to
> // the given start value. This has the same effect as calling clear(statr).
> func newSerializeProxyOffset(buf []byte, start int) serializeProxy {
> ```

NIT: either name the function `newSerializeProxyStart` or rename the parameter from `start` to `offset`  



_Code quote:_
```Go
Offset
```
___
*[`router/#connector.go#` line 0 at r3](https://reviewable.io/reviews/scionproto/scion/4654#-OCqyTzL8w2ACLCfsgrU:-OCqyTzL8w2ACLCfsgrV:b-g31lsc) ([raw file](https://github.com/scionproto/scion/blob/dfe7a6a67ec229af84131ec688a3bd3bd2fc81de/router/%23connector.go%23#L0)):*
Shouldn't be part of this commit, right?

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4654)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W, @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`router/#connector.go#` line  at r3](https://reviewable.io/reviews/scionproto/scion/4654#-OCqyTzL8w2ACLCfsgrU:-OCrvN1R3fV-O-Nepk4T:b-thl87a) ([raw file](https://github.com/scionproto/scion/blob/dfe7a6a67ec229af84131ec688a3bd3bd2fc81de/router/%23connector.go%23#L)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

Shouldn't be part of this commit, right?
</blockquote></details>

nope. I was wondering where that file had gone (in another branch - expected to be stashed) :-) removed.
___
*[`router/serialize_proxy.go` line 47 at r3](https://reviewable.io/reviews/scionproto/scion/4654#-OCqxBr94Mjn9hPh1cxG:-OCrvkLi1SBb6U3g6V9f:bb7f2mf) ([raw file](https://github.com/scionproto/scion/blob/dfe7a6a67ec229af84131ec688a3bd3bd2fc81de/router/serialize_proxy.go#L47)):*
<details><summary><i>Previously, marcfrei (Marc Frei) wrote…</i></summary><blockquote>

NIT: either name the function `newSerializeProxyStart` or rename the parameter from `start` to `offset`
</blockquote></details>

done
___
*[`router/serializeProxy.go` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4654#-OCnCHZD3y3ZNYmjYqiB:-OCrw8Dm6UmzWMP6F4Xc:butcfzy) ([raw file](https://github.com/scionproto/scion/blob/67295230fa95c888e0fddb6f4e6aeee1280136e7/router/serializeProxy.go#L27)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I chose the name to distinguish it from the default implementation. The default implementation does supply the buffer, which is its main downside. This one acts as an intermediary between the using code and the actual buffer. So, a buffer-by-proxy. Of cause proxy is overloaded, but serializeBuffer is already taken and misleading. I have searched for a better name but couldn't find anything that wasn't just as overused. Ideas welcome.
</blockquote></details>

I guess you have accepted my reasons.

**Review by jiceatscion — COMMENTED** [review]
> Dismissed @marcfrei from a discussion.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4654)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @FR4NK-W, @lukedirtwalker, and @oncilla)

___
*[`router/#connector.go#` line  at r3](https://reviewable.io/reviews/scionproto/scion/4654#-OCqyTzL8w2ACLCfsgrU:-OCrx51QCywrjUu7tFDs:b-gdkzfx) ([raw file](https://github.com/scionproto/scion/blob/dfe7a6a67ec229af84131ec688a3bd3bd2fc81de/router/%23connector.go%23#L)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

nope. I was wondering where that file had gone (in another branch - expected to be stashed) :-) removed.
</blockquote></details>

so, done

**Review by marcfrei — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4654)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @FR4NK-W, @lukedirtwalker, and @oncilla)

**Pull request merged**
