### PR TITLE
colibri: e2e admission

### PR DESCRIPTION
**Pull request by juagargi**
Do the end to end admission.
This PR also introduces some small changes to the app messages and capnp for e2e setup messages.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)

### CODE REVIEW

**Review by Oncilla — CHANGES_REQUESTED** [review]
> Reviewed 23 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)* status: 23 of 24 files reviewed, 5 unresolved discussions (waiting on @juagargi and @Oncilla)

___
*[go/cs/reservation/request.go, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkfFaCBaYEFzvSLYOi:-MHkfFaCBaYEFzvSLYOj:b-8pifg0) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/request.go#L44)):*
> ```Go
> 
> // IsHopByHop returns true. If a subtype needs not to be hop by hop, it can override the function.
> func (m *RequestMetadata) IsHopByHop() bool {
> ```

What requests are planned to not be hop by hop?
___
*[go/cs/reservation/e2e/request.go, line 57 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkfSBhE9ss1N8WbdHy:-MHkfSBhE9ss1N8WbdHz:brzr1il) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/e2e/request.go#L57)):*
> ```Go
> // SetupRequest represents all possible e2e setup requests.
> type SetupRequest interface {
> 	IsThisASTheSrc() bool
> ```

The names are not that great.

Also, this could just be `Location() PathLocation`

with
```
type PathLocation int
const (
    UnknownPathLocation PathLocation = iota
    Source
    Transit
    Transfer
    Destination
)
```

(or similar)
___
*[go/cs/reservation/e2e/request.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkg78115BI47DszIKV:-MHkg78115BI47DszIKW:b-zg11xw) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/e2e/request.go#L71)):*
> ```Go
> 	RequestedBW              reservation.BWCls
> 	AllocationTrail          []reservation.BWCls
> 	totalAScount             int
> ```

totalASCount (could also be a function that operates on SegmentResvASCount)
___
*[go/cs/reservationstore/store.go, line 410 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjHGe3ZeTPO_Xx3pJ:-MHkjHGe3ZeTPO_Xx3pK:b-pyo4oi) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L410)):*
> ```Go
> 
> 	// admitted so far
> 	// TODO(juagargi) update token here
> ```

Will you address that TODO as part of this PR?
___
*[go/cs/reservationstore/store.go, line 422 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjU743CZCryq-ZeB1:-MHkjU743CZCryq-ZeB2:bdpv0gk) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L422)):*
> ```Go
> 	var msg base.MessageWithPath
> 	if req.IsThisASTheDst() {
> 		asAResponse := failedResponse.(*e2e.ResponseSetupFailure)
> ```

Why is this done?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)* status: 23 of 24 files reviewed, 5 unresolved discussions (waiting on @Oncilla)

___
*[go/cs/reservation/request.go, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkfFaCBaYEFzvSLYOi:-MHoi7Qe3hKpuTA8FFlK:b-go98wh) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/request.go#L44)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

What requests are planned to not be hop by hop?
</blockquote></details>

Function removed: if the new header is approved, all control messages will be hopping from COLIBRI service to the next.
___
*[go/cs/reservation/e2e/request.go, line 57 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkfSBhE9ss1N8WbdHy:-MHoq_ZD5KkSjYt_BoJa:bpkz3rz) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/e2e/request.go#L57)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

The names are not that great.

Also, this could just be `Location() PathLocation`

with
```
type PathLocation int
const (
    UnknownPathLocation PathLocation = iota
    Source
    Transit
    Transfer
    Destination
)
```

(or similar)
</blockquote></details>

Done. The enum is slightly different since *Transfer* is not a location, and a transit node may be also a transfer one. The function for checking if it's a transfer node is now called `Transfer()`
___
*[go/cs/reservation/e2e/request.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkg78115BI47DszIKV:-MHolBSU9ohxPh_GT0Ne:b-stmh96) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/e2e/request.go#L71)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

totalASCount (could also be a function that operates on SegmentResvASCount)
</blockquote></details>

Done. The value is *pre-computed* on construction to allow cheap calls to get it.
___
*[go/cs/reservationstore/store.go, line 410 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjHGe3ZeTPO_Xx3pJ:-MHolTNA0slptXuy0OTy:b-u0ucva) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L410)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Will you address that TODO as part of this PR?
</blockquote></details>

The token needs to be updated also in the segment admission. I want to soon open a PR with the changes to handle the MACs and token, and take care of both *TODO*s.
___
*[go/cs/reservationstore/store.go, line 422 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjU743CZCryq-ZeB1:-MHonNlv5-hW21scTPHj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L422)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Why is this done?
</blockquote></details>

Done.

**Review by Oncilla — CHANGES_REQUESTED** [review]
> Reviewed 1 of 24 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)* status: all files reviewed, 2 unresolved discussions (waiting on @juagargi)

___
*[go/cs/reservation/e2e/request.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkg78115BI47DszIKV:-MHoteKG0j28BKBzcsqj:b-uwfhlh) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservation/e2e/request.go#L71)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done. The value is *pre-computed* on construction to allow cheap calls to get it.
</blockquote></details>

right. Although there is much more optimization potential elsewhere :) 
___
*[go/cs/reservation/e2e/request.go, line 122 at r2](https://reviewable.io/reviews/scionproto/scion/3863#-MHouTdq82GpEUb9jQRn:-MHouTdq82GpEUb9jQRo:b-5ao3v0) ([raw file](https://github.com/scionproto/scion/blob/0067f6d7a234d530567681f7db15c17bc3ce8c63/go/cs/reservation/e2e/request.go#L122)):*
> ```Go
> }
> 
> type PathLocation int
> ```

consider adding a string method
___
*[go/cs/reservation/e2e/request.go, line 125 at r2](https://reviewable.io/reviews/scionproto/scion/3863#-MHouXzr5lRzzBtq2t-G:-MHouXzr5lRzzBtq2t-H:b-h9t54t) ([raw file](https://github.com/scionproto/scion/blob/0067f6d7a234d530567681f7db15c17bc3ce8c63/go/cs/reservation/e2e/request.go#L125)):*
> ```Go
> 
> const (
> 	Source PathLocation = iota
> ```

It would be best to have the zero value be unknown, such that bugs are easier to detect.
Like this, when you forget to set the PathLocation somewhere, it looks valid.
___
*[go/cs/reservationstore/store.go, line 422 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjU743CZCryq-ZeB1:-MHovDf83JeXrOhOivoV:b5pv38q) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L422)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, I don't understand the intuition behind it. Why do we use the response for failure here?

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)* status: all files reviewed, 2 unresolved discussions (waiting on @Oncilla)

___
*[go/cs/reservation/e2e/request.go, line 125 at r2](https://reviewable.io/reviews/scionproto/scion/3863#-MHouXzr5lRzzBtq2t-G:-MHoxifK3bHKYi3UNV_i:bsxcn2v) ([raw file](https://github.com/scionproto/scion/blob/0067f6d7a234d530567681f7db15c17bc3ce8c63/go/cs/reservation/e2e/request.go#L125)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

It would be best to have the zero value be unknown, such that bugs are easier to detect.
Like this, when you forget to set the PathLocation somewhere, it looks valid.
</blockquote></details>

I though about it, but the location is a derived value, it only depends on `len(r.AllocationTrail)` and it always has a value, i.e. it can never be unknown.
___
*[go/cs/reservationstore/store.go, line 422 at r1](https://reviewable.io/reviews/scionproto/scion/3863#-MHkjU743CZCryq-ZeB1:-MHozSM51ccN8vte5WI-:b-pk7rwm) ([raw file](https://github.com/scionproto/scion/blob/e9a73ea3743dda5182d05146da4c89b712e900bb/go/cs/reservationstore/store.go#L422)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

No, I don't understand the intuition behind it. Why do we use the response for failure here?
</blockquote></details>

You are right: the failed response has to be transformed to a success response.

**Review by Oncilla — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3863)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
