### PR TITLE
SCIOND: Do not add revoked segments

### LINKED ISSUE #1564: sciond fails to filter known-revoked segments from PS
Here's an example:
```
2018-05-18 08:09:37.333369+0000 [DEBUG] (MainThread) Received revocation: SignedRevInfo:
> RevInfo: 2-ff00:0:221 IF: 19 Link type: CHILD Timestamp: 2018-05-18 08:09:32+00:00 TTL: 10s
> ProtoSign: type: ed25519 src: b'DEFAULT: IA: 2-ff00:0:221 CHAIN: 1 TRC: 1' ts: 2018-05-18 08:09:32+00:00 from Unix Socket: Fd: -1
2018-05-18 08:09:37.334303+0000 [DEBUG] (MainThread) Successfully validated and verified RevInfo RevocationInfo: RevInfo: 2-ff00:0:221 IF: 19 Link type: CHILD Timestamp: 2018-05-18 08:09:32+00:00 TTL: 10s
2018-05-18 08:09:37.335268+0000 [DEBUG] (MainThread) Removing segment: f2eb00e0d801, 2018-05-18 08:08:56+00:00, 2-ff00:0:220 58>72 2-ff00:0:221 19>31 2-ff00:0:222
2018-05-18 08:09:37.335737+0000 [INFO] (MainThread) Removed 0 UP- 0 CORE- and 1 DOWN-Segments.
2018-05-18 08:09:37.336071+0000 [ERROR] (MainThread) error in send: [Errno 9] Bad file descriptor
2018-05-18 08:09:38.330756+0000 [DEBUG] (SCIONDaemon API id:140419685308160 1-ff00:0:132 -> 2-ff00:0:222) Paths requested for ISDAS=2-ff00:0:222, flags=(), flush=False
2018-05-18 08:09:38.331417+0000 [DEBUG] (SCIONDaemon API id:140419685308160 1-ff00:0:132 -> 2-ff00:0:222) Sending path request (1-ff00:0:132 -> 2-ff00:0:222  ()) to [127.0.0.166]:30089 [id: bf6cb859ab3a7fef]
2018-05-18 08:09:38.340275+0000 [DEBUG] (MainThread) Handling PCB from UDPMetadata: (1-ff00:0:132 (IPV4) 127.0.0.166):30089: d6dfde2ea149, 2018-05-18 08:09:30+00:00, 1-ff00:0:130 57>99 1-ff00:0:131 46>17 1-ff00:0:132 [id:             ↳ bf6cb859ab3a7fef]
2018-05-18 08:09:38.343657+0000 [DEBUG] (MainThread) Handling PCB from UDPMetadata: (1-ff00:0:132 (IPV4) 127.0.0.166):30089: f2eb00e0d801, 2018-05-18 08:08:56+00:00, 2-ff00:0:220 58>72 2-ff00:0:221 19>31 2-ff00:0:222 [id:             ↳ bf6cb859ab3a7fef]
2018-05-18 08:09:38.346566+0000 [DEBUG] (MainThread) Added segment from 2-ff00:0:220 to 2-ff00:0:222: f2eb00e0d801, 2018-05-18 08:08:56+00:00, 2-ff00:0:220 58>72 2-ff00:0:221 19>31 2-ff00:0:222
2018-05-18 08:09:38.347047+0000 [DEBUG] (MainThread) Down segment added: f2eb00e0d801, 2018-05-18 08:08:56+00:00, 2-ff00:0:220 58>72 2-ff00:0:221 19>31 2-ff00:0:222
```

### PR DESCRIPTION
**Pull request by worxli**
Fixes #1564 .

This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[python/sciond/sciond.py, line 244 at r1](https://reviewable.io/reviews/scionproto/scion/1567#-LDBbnzOCT7ymGeS4_Ju:-LDBbnzP29-LuzYy3RQz:brvuxio) ([raw file](https://github.com/scionproto/scion/blob/415261d1a631b85540c35f150775db4037ecd9ae/python/sciond/sciond.py#L244)):*
> ```Python
>             r.verified_segment()
> 
>     def _validate_segment(self, seg):
> ```

It looks like this ~exact function is already in PS, with the same name. In that case it should go into `scion_elem`, and take the RevCache to use as an argument. (And it needs a better name, too).

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)*

**Comment by worxli** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/sciond/sciond.py, line 244 at r1](https://reviewable.io/reviews/scionproto/scion/1567#-LDBbnzOCT7ymGeS4_Ju:-LDGFkhbCgwoSNBhLtxs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/415261d1a631b85540c35f150775db4037ecd9ae/python/sciond/sciond.py#L244)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It looks like this ~exact function is already in PS, with the same name. In that case it should go into `scion_elem`, and take the RevCache to use as an argument. (And it needs a better name, too).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)*

**Comment by shitz** [comment]
Reviewed 4 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/scion_elem/scion_elem.py, line 1275 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFOX2E_RuhTwD9FTO:-LDLFOX2E_RuhTwD9FTP:b-jfyid6) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1275)):*
> ```Python
>     def check_revoked_interface(self, seg, revocations):
>         """
>         Check segment for revoked upstream/downstream interfaces.
> ```

Blankline between description and params.

---

*[python/scion_elem/scion_elem.py, line 1277 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFispBgKeYievIktc:-LDLFisq3aKuiiYo6WBb:b92qdvk) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1277)):*
> ```Python
>         Check segment for revoked upstream/downstream interfaces.
>         :param seg: The PathSegment object.
>         :param revocations: A RevCache
> ```

"A RevCache containing the currently known revocations"

---

*[python/scion_elem/scion_elem.py, line 1279 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFwDt0Zkam-i4G4O6:-LDLFwDt0Zkam-i4G4O7:b-vasi3q) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1279)):*
> ```Python
>         :param revocations: A RevCache
>         :return: False, if the path segment contains a revoked
>         upstream/downstream interface (not peer). True otherwise.
> ```

Indent by 4

---

*[python/scion_elem/scion_elem.py, line 1287 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLG1ML9zgkc_xc795B:-LDLG1ML9zgkc_xc795C:b-470zv0) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1287)):*
> ```Python
>                 if srev_info:
>                     rev_info = srev_info.rev_info()
>                     logging.info("Found revoked interface (%d, %s) in segment %s." %
> ```

Not sure if this should be `info`. We are not very consistent with logging, but this seems like a debug log to me.

---

*[python/sciond/sciond.py, line 192 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLHnJO8b6vSRIp6xKO:-LDLHnJO8b6vSRIp6xKP:b-295oqm) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/sciond/sciond.py#L192)):*
> ```Python
>         Handle path reply from local path server.
>         """
>         # FIXME(kormat): sciond does not cache non-peer revocations, so if the PS gives us a path
> ```

Please remove this comment as this is not accurate anymore.

---

*[python/test/scion_elem_test.py, line 42 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLHwbT-zxMxJYlZl1o:-LDLHwbT-zxMxJYlZl1p:bjk4cgq) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/test/scion_elem_test.py#L42)):*
> ```Python
>     def _mk_pcb(self, exp=0):
>         ia = [
>             {"isdas": ISD_AS("1-1"), "ingress_if": 1, "egress_if": 2},
> ```

This should use AS number from the testing range: https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)*

**Comment by worxli** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[python/scion_elem/scion_elem.py, line 1275 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFOX2E_RuhTwD9FTO:-LDM5exLEsEc-tKkzEoi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1275)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Blankline between description and params.
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 1277 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFispBgKeYievIktc:-LDM5jH16tUdXhbSdoBg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1277)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

"A RevCache containing the currently known revocations"
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 1279 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLFwDt0Zkam-i4G4O6:-LDM5nctAonvxSeqKw_U:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1279)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Indent by 4
</blockquote></details>

Done.

---

*[python/scion_elem/scion_elem.py, line 1287 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLG1ML9zgkc_xc795B:-LDM5sICCMyjsm7LkodI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/scion_elem/scion_elem.py#L1287)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Not sure if this should be `info`. We are not very consistent with logging, but this seems like a debug log to me.
</blockquote></details>

Done.

---

*[python/sciond/sciond.py, line 192 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLHnJO8b6vSRIp6xKO:-LDM5xcZDhdre-LTugHS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/sciond/sciond.py#L192)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please remove this comment as this is not accurate anymore.
</blockquote></details>

Done.

---

*[python/test/scion_elem_test.py, line 42 at r2](https://reviewable.io/reviews/scionproto/scion/1567#-LDLHwbT-zxMxJYlZl1o:-LDM6Ge44y_jgFhny6PT:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1c3bb4d9d42852b2d6dc476c6a716e59a2ce87a/python/test/scion_elem_test.py#L42)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This should use AS number from the testing range: https://github.com/scionproto/scion/wiki/ISD-and-AS-numbering
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567#-:-LDMHEFK1LYLib5TzIG3:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 6 files at r2, 2 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1567)*

**Pull request merged**
