### PR TITLE
Support for conditional path filtering

### PR DESCRIPTION
**Pull request by scrye**
Implements support for conditional path filtering, e.g.:

```
"ActionCondFilterPaths": {
    "CondAllOf": [
        {
            "CondBool": true 
        },
        {
            "CondNot":
              {
                 "CondPathPredicate": { "PP": "2-0#0" }
             }
        }
    ]
}
```

Applying the above action to an `AppPathSet` will yield a new `AppPathSet` containing the paths that satisfy the condition.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1420)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/lib/pktcls/action.go, line 29 at r1](https://reviewable.io:443/reviews/scionproto/scion/1420#-L6WOIgxiL6Fwq7Q7oKF:-L6WOIgxiL6Fwq7Q7oKG:b-9pdimk) ([raw file](https://github.com/scionproto/scion/blob/b9f9da05524826b4eb709ea0a59ce83c50a98690/go/lib/pktcls/action.go#L29)):*
> ```Go
> 	Act(interface{}) interface{}
> 	GetName() string
> 	setName(name string)
> ```

Make this public as well.

---

*[go/lib/pktcls/action.go, line 37 at r1](https://reviewable.io:443/reviews/scionproto/scion/1420#-L6WNfnYtZXmyB9WRJz_:-L6WNfnZJRSbMGauCr10:b-tdjx39) ([raw file](https://github.com/scionproto/scion/blob/b9f9da05524826b4eb709ea0a59ce83c50a98690/go/lib/pktcls/action.go#L37)):*
> ```Go
> // Filter only paths which match the embedded PathPredicate.
> //
> // DEPRECATED, use ActionCondFilterPaths instead.
> ```

As discussed offline, don't deprecate and just make `ActionPathFilter` what now is `ActionCondPathFilter`

---

*[go/lib/pktcls/action_map_test.go, line 91 at r1](https://reviewable.io:443/reviews/scionproto/scion/1420#-L6WRAlgadmGm8lG80KC:-L6WRAlgadmGm8lG80KD:b-q54cbp) ([raw file](https://github.com/scionproto/scion/blob/b9f9da05524826b4eb709ea0a59ce83c50a98690/go/lib/pktcls/action_map_test.go#L91)):*
> ```Go
> }
> 
> func TestMarshalJSONCondActions(t *testing.T) {
> ```

Doesnt' apply to this test file, but I think you could unit test the path predicate semantics by programmatically creating some `sciond.PathEntryReply` (and members thereof) and then compare `AppPathSets`

---

*[go/lib/pktcls/action_map_test.go, line 94 at r1](https://reviewable.io:443/reviews/scionproto/scion/1420#-L6WS54arfola-aWwMAx:-L6WS54arfola-aWwMAy:bmoaf25) ([raw file](https://github.com/scionproto/scion/blob/b9f9da05524826b4eb709ea0a59ce83c50a98690/go/lib/pktcls/action_map_test.go#L94)):*
> ```Go
> 	Convey("Initialize path predicates", t, func() {
> 		ppA, err := pathmgr.NewPathPredicate("1-11#18,1-11#87")
> 		SoMsg("ppA err", err, ShouldBeNil)
> ```

These are semantically not unit test, so what we really would like to do here is to panic. Leaving this here as a reference, because I'd need to look into how to do that best with goconvey.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1420)*

**Comment by kormat** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1420)*

**Comment by scrye** [comment]
Freezing this until https://github.com/scionproto/scion/pull/1443 is merged because I want to use it for some testing stuff.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1420#-:-L75f2utehU88QTOj6ph:b-t9fxjw)*

**Comment by shitz** [comment]
Reviewed 22 of 22 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/pktcls/action_test.go, line 52 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XZmSlqnOtegGdSdBq:-L8XZmSlqnOtegGdSdBr:b4ygvsv) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/action_test.go#L52)):*
> ```Go
> 		{
> 			Name:     "AllOf(AllOf(true))",
> 			FileName: "act_allof_allof_true",
> ```

lets just call these files `act_<#>`

---

*[go/lib/pktcls/action_test.go, line 319 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XaTBsaiuQnhuUI5xM:-L8XaTBt9p6x54fm15Tz:bargyu2) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/action_test.go#L319)):*
> ```Go
> 	t.Helper()
> 
> 	g := graph.NewFromDescription(graph.DefaultGraphDescription)
> ```

There is `NewDefaultGraph`x

---

*[go/lib/pktcls/common_test.go, line 1 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XbiHEqYRLXH233jSw:-L8XbiHEqYRLXH233jSx:b-1qnqbp) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/common_test.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich
> ```

As agreed offline, make the write function a bit more general and move this out to some `xtest` package, because it will be used in many places.xx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1420)*

**Comment by scrye** [comment]
Review status: 9 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/pktcls/action_test.go, line 52 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XZmSlqnOtegGdSdBq:-L8Y5GVJJ9vKIMoogmE9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/action_test.go#L52)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

lets just call these files `act_<#>`
</blockquote></details>

Done.

---

*[go/lib/pktcls/action_test.go, line 319 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XaTBsaiuQnhuUI5xM:-L8Y5G0RV1ta3Z61A3Tl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/action_test.go#L319)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

There is `NewDefaultGraph`x
</blockquote></details>

Done.

---

*[go/lib/pktcls/common_test.go, line 1 at r2](https://reviewable.io:443/reviews/scionproto/scion/1420#-L8XbiHEqYRLXH233jSw:-L8Y5HgsTBPfp0Y11PfV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5a08d87db3e82f0e4e5608870b031204d694cb4/go/lib/pktcls/common_test.go#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

As agreed offline, make the write function a bit more general and move this out to some `xtest` package, because it will be used in many places.xx
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1420)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 15 of 27 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1420#-:-L8amL1J-4KJ1xdX2tyt:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 10 of 32 files at r2, 14 of 27 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/pktcls/cond_test.go, line 115 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1420#-L8lO5auB8Bz9yqdPLi3:-L8lO5auB8Bz9yqdPLi4:b-emzsfo) ([raw file](https://github.com/scionproto/scion/blob/0274682eb95002b59b136e687c6352506582e923/go/lib/pktcls/cond_test.go#L115)):*
> ```Go
> 				&layers.IPv4{
> 					SrcIP: net.IP{192, 168, 1, 1},
> 					DstIP: net.IP{192, 168, 1, 2},
> ```

It would be better to use a src IP that is outside the expected network, so that it's clear which one is being matched.

---

*[go/lib/xtest/helpers.go, line 74 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1420#-L8k_wuKBMVBSaQp1mRy:-L8k_wuKBMVBSaQp1mRz:bb09cbn) ([raw file](https://github.com/scionproto/scion/blob/0274682eb95002b59b136e687c6352506582e923/go/lib/xtest/helpers.go#L74)):*
> ```Go
> 
> // FailOnErr causes t to exit with a fatal error if err is non-nil.
> func FailOnErr(t *testing.T, err error) {
> ```

`t.Helper()`?

---

*[go/lib/xtest/helpers.go, line 80 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1420#-L8k_kUDB_6rfqONBqBn:-L8k_kUDB_6rfqONBqBo:bykl3ce) ([raw file](https://github.com/scionproto/scion/blob/0274682eb95002b59b136e687c6352506582e923/go/lib/xtest/helpers.go#L80)):*
> ```Go
> }
> 
> // MustMarshalToFile marshals v and writes the result to file
> ```

This should probably mention JSON in the name.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1420)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 4 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1420#-:-L9A1TH3CGxXLS6IORur:bnfp4nl)*

**Pull request merged**
