### PR TITLE
Wrapper for asym.crypto around nacl/box

### PR DESCRIPTION
**Pull request by benrothen**
This PR implements functionality for asymmetric encryption and decryption based on the currently used certificates. This will be required for the first order DRKey exchange.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)

### CODE REVIEW

**Comment by Oncilla** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/crypto/asym.go, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJGDjOBD7uWf3Ya5eE:-LEJGDjOBD7uWf3Ya5eF:b-pqyvpw) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L35)):*
> ```Go
> 	UnsupportedSignAlgo        = "Unsupported signing algorithm"
> 	InvalidSignature           = "Invalid signature"
> 	FailedToGenerateKeyPairs   = "Failed to generate key pairs"
> ```

We usually use "Unable" in the code base. 
replace with `UnableToGenerateKeyPair =  "Unable to generate key pair"`
(also, singular form)

---

*[go/lib/crypto/asym.go, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEVZYAmCc_2KIP8uE:-LEJEVZYAmCc_2KIP8uF:b1m1s50) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L39)):*
> ```Go
> 	FailedToDecrypt            = "Failed to decrypt message"
> 	UnsupportedEncAlgo         = "Unsupported encryption algorithm"
> 	UnsupportedDecAlgo         = "Unsupported decryption algorithm"
> ```

Unused constant.
I would just remove it.

---

*[go/lib/crypto/asym.go, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEwOy2yhuvmmHazqp:-LEJEwOy2yhuvmmHazqq:b3wy99i) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L75)):*
> ```Go
> }
> 
> // GenKeyPairs generates a public/private key pair
> ```

The convention is to place `.` after these kinds of comments.

Also, move function to top.

---

*[go/lib/crypto/asym.go, line 76 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJIs6KEizK1J1EElXF:-LEJIs6KEizK1J1EElXG:b-juwz5i) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L76)):*
> ```Go
> 
> // GenKeyPairs generates a public/private key pair
> func GenKeyPairs(keygenAlgo string) (common.RawBytes, common.RawBytes, error) {
> ```

`keygenAlgo` is an odd name.
Maybe just `algo`?

---

*[go/lib/crypto/asym.go, line 98 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJJzaBDU1W94Xv0r-e:-LEJJzaBDU1W94Xv0r-f:bi76rup) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L98)):*
> ```Go
> 
> // GenNonce takes an input length and returns a random nonce of the given length
> func GenNonce(len uint16) (common.RawBytes, error) {
> ```

Any particular reason len is `uint16` and not `int`?

Name should probably just be `Nonce`.

---

*[go/lib/crypto/asym.go, line 100 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJKok48bZDuTcOInNF:-LEJKok48bZDuTcOInNG:b-wtkroq) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L100)):*
> ```Go
> func GenNonce(len uint16) (common.RawBytes, error) {
> 	nonce := make([]byte, len)
> 	_, err := io.ReadFull(rand.Reader, nonce[:])
> ```

drop `[:]`

---

*[go/lib/crypto/asym.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK8bey7QQhGBf8ciMO:-LEK8bey7QQhGBf8ciMP:bh2s33p) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L113)):*
> ```Go
> 	switch strings.ToLower(algo) {
> 	case Curve25519xSalsa20Poly1305:
> 		if len(nonce) != 24 {
> ```

make this and all other magic numbers a constant.

---

*[go/lib/crypto/asym.go, line 120 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK961G3sVHbDmLp36H:-LEK961G3sVHbDmLp36I:b-rek8by) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L120)):*
> ```Go
> 		}
> 		// 192 bits of randomness should provide a sufficiently small probability of repeats.
> 		var nc *[24]byte
> ```

This will not allocate the array and segfault later on.
`var nc [24]byte` and pass `&nc` to `box.Seal`.

---

*[go/lib/crypto/asym.go, line 122 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKMdRc3AtNDl_-i_Oq:-LEKMdRc3AtNDl_-i_Or:bwh5o88) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L122)):*
> ```Go
> 		var nc *[24]byte
> 		copy(nc[:], nonce)
> 		var pubk, privk *[32]byte
> ```

same as above.

Naming is somewhat hard to read.
Maybe `pubKeyRaw`, `privKeyRaw`, `nonceRaw`?

---

*[go/lib/crypto/asym.go, line 123 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKMy7F29EaZyy87W0R:-LEKMy7G45HgAXAJw9O-:b-wwwzfx) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L123)):*
> ```Go
> 		copy(nc[:], nonce)
> 		var pubk, privk *[32]byte
> 		copy(pubk[:], pubkey[:32])
> ```

drop [:32]

---

*[go/lib/crypto/asym.go, line 143 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKNPC_-P4xQx2lDrA-:-LEKNPC_-P4xQx2lDrA0:bnj7hl0) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L143)):*
> ```Go
> 		var nc [24]byte
> 		copy(nc[:], nonce[:24])
> 		var pubk, privk *[32]byte
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by brothen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/lib/crypto/asym.go, line 35 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJGDjOBD7uWf3Ya5eE:-LEKYLZJ6OmFGqDtGoPL:b-73pdjm) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L35)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

We usually use "Unable" in the code base. 
replace with `UnableToGenerateKeyPair =  "Unable to generate key pair"`
(also, singular form)

</blockquote></details>

Ok. I'll keep that in mind.

---

*[go/lib/crypto/asym.go, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEVZYAmCc_2KIP8uE:-LEKYCTGDjVvcDXOiUbQ:bjpopow) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L39)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Unused constant.
I would just remove it.
</blockquote></details>

This is (now) used in the Decrypt function

---

*[go/lib/crypto/asym.go, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEwOy2yhuvmmHazqp:-LEKYfCV479XCRVpduxE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L75)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

The convention is to place `.` after these kinds of comments.

Also, move function to top.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 76 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJIs6KEizK1J1EElXF:-LEKYqQs1_6TrDNY1u5A:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L76)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

`keygenAlgo` is an odd name.
Maybe just `algo`?
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 98 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJJzaBDU1W94Xv0r-e:-LEKYraJB_hbf9fiqVJF:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L98)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Any particular reason len is `uint16` and not `int`?

Name should probably just be `Nonce`.

</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 100 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJKok48bZDuTcOInNF:-LEKYvwxBhfIkBfIfZSr:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L100)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

drop `[:]`
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK8bey7QQhGBf8ciMO:-LEK_Vf77dnZztWQ0UOJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L113)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

make this and all other magic numbers a constant.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 120 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK961G3sVHbDmLp36H:-LEK_Uv1DBm8D3Uj5neE:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L120)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

This will not allocate the array and segfault later on.
`var nc [24]byte` and pass `&nc` to `box.Seal`.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 122 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKMdRc3AtNDl_-i_Oq:-LEKaMQF94tHiyXINIWJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L122)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

same as above.

Naming is somewhat hard to read.
Maybe `pubKeyRaw`, `privKeyRaw`, `nonceRaw`?
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 123 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKMy7F29EaZyy87W0R:-LEK_Sfz2xwA7RN87YnL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L123)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

drop [:32]
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 143 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEKNPC_-P4xQx2lDrA-:-LEK_TyH6RmVZ-SsI7KJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L143)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by Oncilla** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/crypto/asym.go, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEVZYAmCc_2KIP8uE:-LEKd1t252aOO-hDOcWe:b-odv5on) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L39)):*
<details><summary><i>Previously, brothen wrote…</i></summary><blockquote>

This is (now) used in the Decrypt function
</blockquote></details>

I would rather have just the `UnsupportedEncAlgo` string.

---

*[go/lib/crypto/asym.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK8bey7QQhGBf8ciMO:-LEKgloy0JkrdHdIedjL:b-47ktir) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L113)):*
<details><summary><i>Previously, brothen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Name should be a bit more specific.
E.g. pubKeySize of Ed25519 is 64 byte and not 32 byte.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by Oncilla** [comment]
*[go/lib/crypto/asym.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1594#-LEKlPx38nOOKA5m7k2v:-LEKlPx38nOOKA5m7k2w:b-ozl2q1) ([raw file](https://github.com/scionproto/scion/blob/0bfd8a364ea3c709cbfa85a197496fb115edb145/go/lib/crypto/asym.go#L34)):*
> ```Go
> 
> 	Ed25519                    = "ed25519"
> 	Curve25519xSalsa20Poly1305 = "curve25519xsalsa20poly1305"
> ```

add blank line to separate const blocks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by brothen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/lib/crypto/asym.go, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEJEVZYAmCc_2KIP8uE:-LEOekrR5wkcuTrlnw4y:bc1ysrv) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L39)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

I would rather have just the `UnsupportedEncAlgo` string.
</blockquote></details>

Ok. I will remove it.

---

*[go/lib/crypto/asym.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/1594#-LEK8bey7QQhGBf8ciMO:-LEOenQE1HU2cseVggGS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/77be9e7fd101dd88782edf664cda34b66ba88343/go/lib/crypto/asym.go#L113)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Name should be a bit more specific.
E.g. pubKeySize of Ed25519 is 64 byte and not 32 byte.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1594#-LEKlPx38nOOKA5m7k2v:-LEOejzF8jKR_KFBDcPG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0bfd8a364ea3c709cbfa85a197496fb115edb145/go/lib/crypto/asym.go#L34)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

add blank line to separate const blocks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by Oncilla** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594#-:-LEOkgHg51BBVGYOEWGL:bnfp4nl)*

**Comment by Oncilla** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @Oncilla and @brothen)

---

*[go/lib/crypto/asym.go, line 1 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEisy_p-DCrMbJWQRCs:-LEisy_p-DCrMbJWQRCt:bb7pwfd) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich
> ```

undo

---

*[go/lib/crypto/asym_test.go, line 32 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEit4tA7Xk3UBKY8ZFh:-LEit4tA7Xk3UBKY8ZFi:b-vztznp) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L32)):*
> ```Go
> 		0x7d, 0xb1, 0x26, 0xd8, 0x89, 0xf6, 0xda, 0xdd}
> 	Ed25519TestPublicKey = common.RawBytes{0x77, 0xf4, 0x8b, 0x59, 0xca, 0xed, 0xa7, 0x77, 0x51,
> 		0xed, 0x13,
> ```

odd formatting

---

*[go/lib/crypto/asym_test.go, line 52 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEit8e6BjW1ZNE_RX0n:-LEit8e6BjW1ZNE_RX0o:b-cblle0) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L52)):*
> ```Go
> 		0xef, 0x7b, 0x9b, 0xcc, 0x3c, 0x40, 0xc0, 0xff, 0x75, 0x09}
> 
> 	// NaClBox test vectors
> ```

These test vectors are unused
Add some tests for NaClBox

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by Oncilla** [comment]
Review status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Oncilla and @brothen)

---

*[go/lib/crypto/asym_test.go, line 87 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEsNsUeDcMrMrGDulbp:-LEsNsUeDcMrMrGDulbq:b-t3jeu2) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L87)):*
> ```Go
> 	// multiple signing operations with the same key more efficient...""
> 	Convey("Sign should sign message correctly", t, func() {
> 		sig, err := Sign(Ed25519TestMsg, append(Ed25519TestPrivateKey, Ed25519TestPublicKey...), "Ed25519")
> ```

Since #1604 is merged, use `ed22519.NewKeyFromSeed` instead.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by brothen** [comment]
Review status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @Oncilla and @brothen)

---

*[go/lib/crypto/asym.go, line 1 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEisy_p-DCrMbJWQRCs:-LFN0cjD9c0tm7L0Ia5K:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym.go#L1)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

undo
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 32 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEit4tA7Xk3UBKY8ZFh:-LFN0dLe70HDfWJaK9Dr:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L32)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

odd formatting
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 52 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEit8e6BjW1ZNE_RX0n:-LFNXi-kAFcdPPgThYo-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L52)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

These test vectors are unused
Add some tests for NaClBox
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 87 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEsNsUeDcMrMrGDulbp:-LFN2LqQ5fW-cjmXJGkj:bvsyz) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L87)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Since #1604 is merged, use `ed22519.NewKeyFromSeed` instead.
</blockquote></details>

I would prefer to keep the current testcase as it is also included in the python 

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by brothen** [comment]
Review status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @Oncilla and @brothen)

---

*[go/lib/crypto/asym.go, line 46 at r5](https://reviewable.io/reviews/scionproto/scion/1594#-LFvL6jK--0JqqrBxfBD:-LFvS7DxBFK52WU6GDJs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a2f655f118f191660088ef4556ea0d1bcb3b28ee/go/lib/crypto/asym.go#L46)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

A wild constant appears. 
As discussed before, just remove it.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 87 at r4](https://reviewable.io/reviews/scionproto/scion/1594#-LEsNsUeDcMrMrGDulbp:-LFvSFqLCDfsC_UqkqEu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c7ea8c3df98963d63553e760df0e25ae8daa49bc/go/lib/crypto/asym_test.go#L87)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Right. I'm talking about replacing it with `ed25519.NewKeyFromSeed(Ed25519TestPrivateKey)`.
The test case stays the same.

In any case: Line length.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 53 at r5](https://reviewable.io/reviews/scionproto/scion/1594#-LFvLY7sDkZr7w-u7dh_:-LFvSC866UiOI5B-ZRBG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a2f655f118f191660088ef4556ea0d1bcb3b28ee/go/lib/crypto/asym_test.go#L53)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Line length
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 125 at r5](https://reviewable.io/reviews/scionproto/scion/1594#-LFvNtanCRnU7tOqN689:-LFvSGCM8038j7N0y-AC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a2f655f118f191660088ef4556ea0d1bcb3b28ee/go/lib/crypto/asym_test.go#L125)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 130 at r5](https://reviewable.io/reviews/scionproto/scion/1594#-LFvNwTmATuBPZb8v1CE:-LFvSGV6-HeM8H_pmwSl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a2f655f118f191660088ef4556ea0d1bcb3b28ee/go/lib/crypto/asym_test.go#L130)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[go/lib/crypto/asym_test.go, line 158 at r5](https://reviewable.io/reviews/scionproto/scion/1594#-LFvOogHEz1BhLWBxXAE:-LFvSGwL5EzGxfSKhrka:b-txoim5) ([raw file](https://github.com/scionproto/scion/blob/a2f655f118f191660088ef4556ea0d1bcb3b28ee/go/lib/crypto/asym_test.go#L158)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

I like this randomness check :100:  ;)
</blockquote></details>

:1st_place_medal: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594)*

**Comment by Oncilla** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1594#-:-LFvnCUq4-g1tX4HMeoW:bnfp4nl)*

**Pull request merged**
