### PR TITLE
scion-pki: allow referencing predecessor certificates in payload

### PR DESCRIPTION
**Pull request by oncilla**
When creating a TRC update, support referencing the predecessor certificates. This simplifies the TRC ceremony, as the already included certificates do not need to be redistributed in case they do not change.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4625)

**Review by jiceatscion — APPROVED** [review]
Seems reasonable, but then, I don't know much about the topic.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4625#-:-O74c5hc1eKIRkNbxRc1:b-vacr2k)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4625#-:-O74cMOJ1H-eV3Liqu25:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4625)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
