### PR TITLE
drkey: add control service prefetcher

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR is the 9th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.

This PR contains:

- Prefetcher object that retrieves future valid keys for frequently used keys.
- UTs

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)* status: all files reviewed, 8 unresolved discussions (waiting on @JordiSubira)

___
*[`control/drkey/prefetcher.go` line 28 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oT91V1HmYSGFQAsN1:-N7oT91V1HmYSGFQAsN2:bixd3se) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L28)):*
> ```Go
> )
> 
> var _ periodic.Task = (*Prefetcher)(nil)
> ```

move this to the test file
___
*[`control/drkey/prefetcher.go` line 49 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oU9s6CJI5DxeTfRyC:-N7oU9s6CJI5DxeTfRyD:undefined) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L49)):*
> ```Go
> // Name returns the tasks name.
> func (f *Prefetcher) Name() string {
> 	return "drkey.Prefetcher"
> ```





_Suggestion:_
```Go
fmt.Sprintf("drkey_prefetcher_%s", f.LocalIA)
```
___
*[`control/drkey/prefetcher.go` line 64 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oUb_oEn6OZZYuG02p:-N7oUb_oEn6OZZYuG02q:b-f4gw2) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L64)):*
> ```Go
> 		go func() {
> 			defer log.HandlePanic()
> 			getLevel1Key(ctx, f.Engine, key.IA, f.LocalIA, key.Proto, when, &wg)
> ```

here you should first have a `defer wg.Done()` then you also don't need to pass the `wg` into the `getLevel1Key` function.
___
*[`control/drkey/prefetcher.go` line 70 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oVUsW9f52jVLZ_Jmy:-N7oVUsW9f52jVLZ_Jmz:blp617c) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L70)):*
> ```Go
> }
> 
> func getLevel1Key(
> ```

format:
```go
func getLevel1Key(
	ctx context.Context,
	engine Level1Engine,
	srcIA, dstIA addr.IA,
	proto drkey.Protocol,
	valTime time.Time,
	wg *sync.WaitGroup,
) {
```
___
*[`control/drkey/prefetcher.go` line 85 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oV07X0u-BAC-wz_4k:-N7oV07X0u-BAC-wz_4l:bni5b8d) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L85)):*
> ```Go
> 		ProtoId:  proto,
> 	}
> 	pref_ctx := context.WithValue(ctx, fromPrefetcher{}, true)
> ```

Go variables names should not contain underlines. I would either use camelCase or even just overwrite the `ctx` variable.



_Suggestion:_
```Go
ctx
```
___
*[`control/drkey/prefetcher.go` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oVJeH08QgCWSfizV6:-N7oVJeH08QgCWSfizV7:undefined) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L86)):*
> ```Go
> 	}
> 	pref_ctx := context.WithValue(ctx, fromPrefetcher{}, true)
> 	_, err := engine.GetLevel1Key(pref_ctx, meta)
> ```





_Suggestion:_
```Go
	if _, err := engine.GetLevel1Key(pref_ctx, meta); err != nil {
```
___
*[`control/drkey/prefetcher.go` line 88 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oUx9ZDOwyd6YDAjlT:-N7oUx9_B6Zz1rbUNEAG:undefined) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher.go#L88)):*
> ```Go
> 	_, err := engine.GetLevel1Key(pref_ctx, meta)
> 	if err != nil {
> 		log.Error("Failed to prefetch the level 1 key", "remote AS", srcIA.String(),
> ```





_Suggestion:_
```Go
log.FromCtx(ctx).Error
```
___
*[`control/drkey/prefetcher_test.go` line 68 at r1](https://reviewable.io/reviews/scionproto/scion/4231#-N7oW1XG9g4OFeqoun6d:-N7oW1XG9g4OFeqoun6e:b-8ai2wu) ([raw file](https://github.com/scionproto/scion/blob/8dfa4c9ab48ab9b6ff1060e530e5a47f9dfa219e/control/drkey/prefetcher_test.go#L68)):*
> ```Go
> 	prefetcher.Run(context.Background())
> 	prefetcher.Run(context.Background())
> ```

drop empty line at the end.

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`control/drkey/prefetcher.go` line 85 at r2](https://reviewable.io/reviews/scionproto/scion/4231#-N7pSX_s16DaoemgW8eY:-N7pSX_s16DaoemgW8eZ:undefined) ([raw file](https://github.com/scionproto/scion/blob/ea49b84486142d4af437dec080c90c07919e8805/control/drkey/prefetcher.go#L85)):*
> ```Go
> 	ctx = context.WithValue(ctx, fromPrefetcher{}, true)
> 	if _, err := engine.GetLevel1Key(ctx, meta); err != nil {
> 		log.FromCtx(ctx).Error("Failed to prefetch the level 1 key", "remote AS", srcIA.String(),
> ```





_Suggestion:_
```Go
"remote_isd_as", dstIA,
```

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`control/drkey/prefetcher.go` line 85 at r2](https://reviewable.io/reviews/scionproto/scion/4231#-N7pSX_s16DaoemgW8eY:-N7pUVnq6UBE86kd__rx:b5skn6k) ([raw file](https://github.com/scionproto/scion/blob/ea49b84486142d4af437dec080c90c07919e8805/control/drkey/prefetcher.go#L85)):*
> ```Go
> 	ctx = context.WithValue(ctx, fromPrefetcher{}, true)
> 	if _, err := engine.GetLevel1Key(ctx, meta); err != nil {
> 		log.FromCtx(ctx).Error("Failed to prefetch the level 1 key", "remote AS", srcIA.String(),
> ```

In this case, the remote CS will be the fast side of the derivation (i.e. srcIA). I can rename the parameters in this function if you think it is more clear.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by JordiSubira — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
