### PR TITLE
  scion-pki: Read signing algorithm from TRC when signing new issuer cert

### LINKED ISSUE #1496: Read signing algorithm from TRC when signing a new issuer certificate

### PR DESCRIPTION
**Pull request by jinankjain**
Fixes #1496

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1517)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 151 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8MD3z2GWIZXK6jNck:-LA8MD3z2GWIZXK6jNcl:b-jyh7q6) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/certs/gen.go#L151)):*
> ```Go
> 	}
> 	// Sign the certificate.
> 	currTrcPath := conf.GetCurrentTRCPath(s.I)
> ```

This entire block needs to be changed:

```
currTrcPath = filepath.Join(pkicmn.GetIsdPath(s.I), fmt.Sprintf(pkicmn.TrcNameFmt, s.I, c.TrcVersion)
currTrc, err := trc.TRCFromFile(currTrcPath, false)
if err != nil {
    return nil, common.NewBasicError("Error reading TRC", "err", err, "path", currTrcPath)
}
coreAs, ok = currTrc.CoreASes[s]
if !ok {
    return nil, common.NewBasicError("Issuer of IssuerCert not found in Core ASes of TRC", nil, "issuer", s)
}
if err = c.Sign(issuerKey, coreAs.OnlineKeyAlg); err != nil {
    return nil, err
}
```
If this path doesn't exist certificate generation has to fail.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 156 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8NR52Bj2CsB4dnz4m:-LA8NR52Bj2CsB4dnz4n:b-hls516) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/certs/gen.go#L156)):*
> ```Go
> 	if currTrcPath != "" {
> 		currTrc, err := trc.TRCFromFile(currTrcPath, false)
> 		if err != nil {
> ```

Did you test this code? It doesn't seem correct to do something when there was an error reading the TRC.

---

*[go/tools/scion-pki/internal/conf/isd.go, line 40 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8OIPZ1d_TH0v3-Vm_:-LA8OIPZ1d_TH0v3-Vma:bt4caig) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/conf/isd.go#L40)):*
> ```Go
> }
> 
> func GetCurrentTRCPath(isd addr.ISD) string {
> ```

Can be removed

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 151 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8MD3z2GWIZXK6jNck:-LA8PiYL7EbN85uPhfNl:b-brvce4) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/certs/gen.go#L151)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This entire block needs to be changed:

```
currTrcPath = filepath.Join(pkicmn.GetIsdPath(s.I), fmt.Sprintf(pkicmn.TrcNameFmt, s.I, c.TrcVersion)
currTrc, err := trc.TRCFromFile(currTrcPath, false)
if err != nil {
    return nil, common.NewBasicError("Error reading TRC", "err", err, "path", currTrcPath)
}
coreAs, ok = currTrc.CoreASes[s]
if !ok {
    return nil, common.NewBasicError("Issuer of IssuerCert not found in Core ASes of TRC", nil, "issuer", s)
}
if err = c.Sign(issuerKey, coreAs.OnlineKeyAlg); err != nil {
    return nil, err
}
```
If this path doesn't exist certificate generation has to fail.
</blockquote></details>

This regard 'If this path doesn't exist certificate generation has to fail.'. Forgot to remove that comment. My code snippet is not tested btw, so you might need to make minor adjustments.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by jinankjain** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/isd.go, line 40 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8OIPZ1d_TH0v3-Vm_:-LA9QzW8EqSmApo7jYYc:bcez03m) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/conf/isd.go#L40)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Can be removed
</blockquote></details>

But then how can I read the current TRC to get the value of OnlineKeyAlg for the particular core AS?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/isd.go, line 40 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8OIPZ1d_TH0v3-Vm_:-LAC7u209LboywwtpbOW:b-kbj3mt) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/conf/isd.go#L40)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

But then how can I read the current TRC to get the value of OnlineKeyAlg for the particular core AS?
</blockquote></details>

`trc.TRCFromFile` does that in my proposal. The only thing that you get from your code is the TRC version, which is already in the certificate that needs to be signed.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by jinankjain** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 151 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8MD3z2GWIZXK6jNck:-LACrUXO4fVlGKI54YNT:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/certs/gen.go#L151)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This regard 'If this path doesn't exist certificate generation has to fail.'. Forgot to remove that comment. My code snippet is not tested btw, so you might need to make minor adjustments.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 156 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8NR52Bj2CsB4dnz4m:-LACrV7t-IeEBRsCAxzM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/certs/gen.go#L156)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Did you test this code? It doesn't seem correct to do something when there was an error reading the TRC.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/isd.go, line 40 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LA8OIPZ1d_TH0v3-Vm_:-LACwZYb3S_XETihMyGx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/52c99195b4769f76535b0e8e237b2b308786ad08/go/tools/scion-pki/internal/conf/isd.go#L40)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`trc.TRCFromFile` does that in my proposal. The only thing that you get from your code is the TRC version, which is already in the certificate that needs to be signed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 151 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LADHiOn32djOiB1GhPY:-LADHiOn32djOiB1GhPZ:b21jgs6) ([raw file](https://github.com/scionproto/scion/blob/a90ec6c445ba5e2f946c6b4ab793f0eaddfacae0/go/tools/scion-pki/internal/certs/gen.go#L151)):*
> ```Go
> 	}
> 	// Sign the certificate.
> 	currTrcPath := filepath.Join(pkicmn.GetIsdPath(s.I), "trcs",
> ```

Could you introduce constants in `pkicmn` for the TRCs, Certs, and Keys directories, i.e.,
```
const (
    TRCsDir = "trcs"
    CertsDir = "certs"
    KeysDir = "keys"
)
```
and use those where we use now "trcs", "certs", and "keys" directly. This will ensure correctness and consistency between the generating code and the code that needs to lookup a TRC, cert, or key.

---

*[go/tools/scion-pki/internal/certs/gen.go, line 168 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1517#-LADHU5N0SxFvZoNx9uB:-LADHU5N0SxFvZoNx9uC:b-1wyvf7) ([raw file](https://github.com/scionproto/scion/blob/a90ec6c445ba5e2f946c6b4ab793f0eaddfacae0/go/tools/scion-pki/internal/certs/gen.go#L168)):*
> ```Go
> 	switch algo := coreAs.OnlineKeyAlg; algo {
> 	case "ed25519":
> 		signAlgorithm = crypto.Ed25519
> ```

This shouldn't be needed. `crypto.Ed25519` is a string itself so you can directly use `coreAs.OnlineKeyAlg` (see my proposal)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1517#-:-LAEUq-SETC6U0KXParc:bnfp4nl)*

**Pull request merged**
