### PR TITLE
mocks: update list, fix unexported interfaces in bfd

### PR DESCRIPTION
**Pull request by matzf**
During various refactors (e.g. #3862), some of the mocks were updated without updating the list of mock targets in `tools/gomocks`. Fixed by semi-manually syncing the mock target list with the actually existing mocks.

The interfaces in `go/pkg/router/bfd/` were not directly exported and gomock refused to generate the mock code.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3878)

### CODE REVIEW

**Review by Oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3878)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go/pkg/router/bfd/export_test.go, line 48 at r1](https://reviewable.io/reviews/scionproto/scion/3878#-MHQ-P4U1FroJ10Bs6im:-MHQ-P4V9sqZdt9WSf7j:b-xiweex) ([raw file](https://github.com/scionproto/scion/blob/6a8fd3a94d1af8b6e8cdfe2469b9f5e65863c971/go/pkg/router/bfd/export_test.go#L48)):*
> ```Go
> 	State                    = state
> 	Event                    = event
> 	Source                   = source
> ```

Why are these changes needed?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3878)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[go/pkg/router/bfd/export_test.go, line 48 at r1](https://reviewable.io/reviews/scionproto/scion/3878#-MHQ-P4U1FroJ10Bs6im:-MHQ0V6v5vvlCPQ2l9ll:b20d7ko) ([raw file](https://github.com/scionproto/scion/blob/6a8fd3a94d1af8b6e8cdfe2469b9f5e65863c971/go/pkg/router/bfd/export_test.go#L48)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Why are these changes needed?
</blockquote></details>

mockgen does not see the `Source` and `IntervalGenerator` types, as they are only exported in this `_test.go` file.
It also refuses to create mocks for the unexported interfaces. I don't think there is a way to make these interfaces visible to mockgen and at the same time keep them private -- at least not in the "reflect" mode of mockgen.
Not sure how creating the checked in mocks was accomplished, maybe just manually export interface, run mockgen and then change it back to private?

**Review by Oncilla — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3878#-:-MHVIVlO2ColRwh2ZFof:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[go/pkg/router/bfd/export_test.go, line 48 at r1](https://reviewable.io/reviews/scionproto/scion/3878#-MHQ-P4U1FroJ10Bs6im:-MHVHKmm0z3yXi9Sc1q6:b-w8x5n0) ([raw file](https://github.com/scionproto/scion/blob/6a8fd3a94d1af8b6e8cdfe2469b9f5e65863c971/go/pkg/router/bfd/export_test.go#L48)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

mockgen does not see the `Source` and `IntervalGenerator` types, as they are only exported in this `_test.go` file.
It also refuses to create mocks for the unexported interfaces. I don't think there is a way to make these interfaces visible to mockgen and at the same time keep them private -- at least not in the "reflect" mode of mockgen.
Not sure how creating the checked in mocks was accomplished, maybe just manually export interface, run mockgen and then change it back to private?
</blockquote></details>

Hm, yeah this looks a bit awkward. It's a bit unfortunate that gomock does not see the `_test.go` files. But I guess it makes sense.

Conceptually, I think it is cleaner to hide these interfaces, since they solely exist for testing.

You could actually do it with a second definition of the same interface in `go/pkg/router/bfd/internal/`
and then apply mockgen on that. But IMO I don't think that is worth the effort.
___
*[go/pkg/router/bfd/jitter.go, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/3878#-MHVHzpX-pjJGlxJL-17:-MHVHzpX-pjJGlxJL-18:b-cczma5) ([raw file](https://github.com/scionproto/scion/blob/244516d17a545cf27b8cdb77ecf7da288ed077b5/go/pkg/router/bfd/jitter.go#L67)):*
> ```Go
> }
> 
> // IntervalGenerator generates integers in [x, y). It panics if x < 0 or if y <= x.
> ```

Interesting, it looks like this was public once, and then hidden. :detective: 
Same for source.

**Pull request merged**
