### PR TITLE
topodot: cluster nodes by ISD

### PR DESCRIPTION
**Pull request by oncilla**
This change adds clustering to the topodot tool.
Nodes are clustered by ISD. Furthermore, core ASes are clustered in
a sub-ISD cluster.

topo

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4073)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
:+1: 

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4073#-:-MdLn72D7M4kprg9ld14:b-8fx2u7)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @oncilla)

___
*[tools/topodot.py, line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4073#-MdLk78ACE6_StmQeu8z:-MdLk78ACE6_StmQeu9-:b-ug6iy9) ([raw file](https://github.com/scionproto/scion/blob/c72d18633b17ec44af33961d9c6315eec03a1a03/tools/topodot.py#L102)):*
> ```Python
>                 clusters["top"].append(link)
>             else:
>                 clusters["cluster_%s" % link.a.ISD()].append(link)
> ```

Nit: we could first add the individual nodes (i.e. ASes) to the clusters, then we could simply add the links to the "top" without caring about which cluster to put this in. This would lead to the exact same layout, but would be a tad simpler to understand, at least to me, because I'm usually thinking of clusters as a set of nodes, rather then edges. Example:

```dot
digraph topo {
        node [margin=0.2]
        edge [labeldistance=1.1,labelfontsize=8.0,labelfontcolor=gray40]
        graph [newrank=true]

        subgraph cluster_ISD1 {
            margin=16
            label="ISD1"

            subgraph cluster_ISD1_core {
                margin=25
                label="Core ISD1"
                "1-ff00:0:110"
                "1-ff00:0:120"
                "1-ff00:0:130"
            }
            "1-ff00:0:111"
            "1-ff00:0:112"
            "1-ff00:0:121"
            "1-ff00:0:122"
            "1-ff00:0:131"
            "1-ff00:0:132"
            "1-ff00:0:133"
        }

        subgraph cluster_ISD2 {
            margin=16
            label="ISD2"

            subgraph cluster_ISD2_core {
                margin=25
                label="Core ISD2"
                "2-ff00:0:210"
                "2-ff00:0:220"
            }
            "2-ff00:0:211"
            "2-ff00:0:212"
            "2-ff00:0:221"
            "2-ff00:0:222"
        }
        "1-ff00:0:110" -> "1-ff00:0:120"[taillabel=1;headlabel=6;dir=none]
        "1-ff00:0:110" -> "1-ff00:0:130"[taillabel=2;headlabel=104;dir=none]
        "1-ff00:0:120" -> "1-ff00:0:130"[taillabel=1;headlabel=105;dir=none]
        "1-ff00:0:120" -> "1-ff00:0:121"[taillabel=4;headlabel=3]
        "1-ff00:0:120" -> "1-ff00:0:111"[taillabel=5;headlabel=104]
        "1-ff00:0:130" -> "1-ff00:0:131"[taillabel=111;headlabel=479]
        "1-ff00:0:130" -> "1-ff00:0:111"[taillabel=112;headlabel=105]
        "1-ff00:0:130" -> "1-ff00:0:112"[taillabel=113;headlabel=495]
        "1-ff00:0:111" -> "1-ff00:0:121"[taillabel=100;headlabel=4;constraint=false;dir=none;style=dotted]
        "1-ff00:0:111" -> "1-ff00:0:112"[taillabel=103;headlabel=494]
        "1-ff00:0:121" -> "1-ff00:0:131"[taillabel=1;headlabel=480;constraint=false;dir=none;style=dotted]
        "1-ff00:0:121" -> "1-ff00:0:122"[taillabel=2;headlabel=2]
        "1-ff00:0:122" -> "1-ff00:0:133"[taillabel=1;headlabel=1;constraint=false;dir=none;style=dotted]
        "1-ff00:0:131" -> "1-ff00:0:132"[taillabel=478;headlabel=2]
        "1-ff00:0:132" -> "1-ff00:0:133"[taillabel=1;headlabel=2]
        "2-ff00:0:210" -> "2-ff00:0:220"[taillabel=450;headlabel=503;dir=none]
        "2-ff00:0:210" -> "2-ff00:0:211"[taillabel=451;headlabel=7]
        "2-ff00:0:210" -> "2-ff00:0:211"[taillabel=452;headlabel=8]
        "2-ff00:0:220" -> "2-ff00:0:221"[taillabel=500;headlabel=2]
        "2-ff00:0:211" -> "2-ff00:0:221"[taillabel=1;headlabel=3;constraint=false;dir=none;style=dotted]
        "2-ff00:0:211" -> "2-ff00:0:212"[taillabel=2;headlabel=201]
        "2-ff00:0:211" -> "2-ff00:0:212"[taillabel=3;headlabel=200]
        "2-ff00:0:211" -> "2-ff00:0:222"[taillabel=4;headlabel=301]
        "2-ff00:0:221" -> "2-ff00:0:222"[taillabel=1;headlabel=302]
        "1-ff00:0:110" -> "2-ff00:0:210"[taillabel=3;headlabel=453;dir=none]
        "1-ff00:0:120" -> "2-ff00:0:220"[taillabel=2;headlabel=501;dir=none]
        "1-ff00:0:120" -> "2-ff00:0:220"[taillabel=3;headlabel=502;dir=none]
        "1-ff00:0:111" -> "2-ff00:0:211"[taillabel=101;headlabel=5;constraint=false;dir=none;style=dotted]
        "1-ff00:0:111" -> "2-ff00:0:211"[taillabel=102;headlabel=6;constraint=false;dir=none;style=dotted]
}
```
___
*[tools/topodot.py, line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4073#-MdLfr6e6A5yR_48Zi8E:-MdLfr6e6A5yR_48Zi8F:b-b77eic) ([raw file](https://github.com/scionproto/scion/blob/c72d18633b17ec44af33961d9c6315eec03a1a03/tools/topodot.py#L140)):*
> ```Python
>     }
>     if link.type == LinkType.CORE:
>         attrs['dir'] = 'none'
> ```

Dropping the `constraint=false` for core links causes dot rank the core ASes and ISDs, which is quite arbitrary. But dot seems to handle this far better, with fewer overlapping edges and labels. So :+1:

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4073)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[tools/topodot.py, line 102 at r1](https://reviewable.io/reviews/scionproto/scion/4073#-MdLk78ACE6_StmQeu8z:-MdS52ZbAxc8H55MO1_q:b6kn064) ([raw file](https://github.com/scionproto/scion/blob/c72d18633b17ec44af33961d9c6315eec03a1a03/tools/topodot.py#L102)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: we could first add the individual nodes (i.e. ASes) to the clusters, then we could simply add the links to the "top" without caring about which cluster to put this in. This would lead to the exact same layout, but would be a tad simpler to understand, at least to me, because I'm usually thinking of clusters as a set of nodes, rather then edges. Example:

```dot
digraph topo {
        node [margin=0.2]
        edge [labeldistance=1.1,labelfontsize=8.0,labelfontcolor=gray40]
        graph [newrank=true]

        subgraph cluster_ISD1 {
            margin=16
            label="ISD1"

            subgraph cluster_ISD1_core {
                margin=25
                label="Core ISD1"
                "1-ff00:0:110"
                "1-ff00:0:120"
                "1-ff00:0:130"
            }
            "1-ff00:0:111"
            "1-ff00:0:112"
            "1-ff00:0:121"
            "1-ff00:0:122"
            "1-ff00:0:131"
            "1-ff00:0:132"
            "1-ff00:0:133"
        }

        subgraph cluster_ISD2 {
            margin=16
            label="ISD2"

            subgraph cluster_ISD2_core {
                margin=25
                label="Core ISD2"
                "2-ff00:0:210"
                "2-ff00:0:220"
            }
            "2-ff00:0:211"
            "2-ff00:0:212"
            "2-ff00:0:221"
            "2-ff00:0:222"
        }
        "1-ff00:0:110" -> "1-ff00:0:120"[taillabel=1;headlabel=6;dir=none]
        "1-ff00:0:110" -> "1-ff00:0:130"[taillabel=2;headlabel=104;dir=none]
        "1-ff00:0:120" -> "1-ff00:0:130"[taillabel=1;headlabel=105;dir=none]
        "1-ff00:0:120" -> "1-ff00:0:121"[taillabel=4;headlabel=3]
        "1-ff00:0:120" -> "1-ff00:0:111"[taillabel=5;headlabel=104]
        "1-ff00:0:130" -> "1-ff00:0:131"[taillabel=111;headlabel=479]
        "1-ff00:0:130" -> "1-ff00:0:111"[taillabel=112;headlabel=105]
        "1-ff00:0:130" -> "1-ff00:0:112"[taillabel=113;headlabel=495]
        "1-ff00:0:111" -> "1-ff00:0:121"[taillabel=100;headlabel=4;constraint=false;dir=none;style=dotted]
        "1-ff00:0:111" -> "1-ff00:0:112"[taillabel=103;headlabel=494]
        "1-ff00:0:121" -> "1-ff00:0:131"[taillabel=1;headlabel=480;constraint=false;dir=none;style=dotted]
        "1-ff00:0:121" -> "1-ff00:0:122"[taillabel=2;headlabel=2]
        "1-ff00:0:122" -> "1-ff00:0:133"[taillabel=1;headlabel=1;constraint=false;dir=none;style=dotted]
        "1-ff00:0:131" -> "1-ff00:0:132"[taillabel=478;headlabel=2]
        "1-ff00:0:132" -> "1-ff00:0:133"[taillabel=1;headlabel=2]
        "2-ff00:0:210" -> "2-ff00:0:220"[taillabel=450;headlabel=503;dir=none]
        "2-ff00:0:210" -> "2-ff00:0:211"[taillabel=451;headlabel=7]
        "2-ff00:0:210" -> "2-ff00:0:211"[taillabel=452;headlabel=8]
        "2-ff00:0:220" -> "2-ff00:0:221"[taillabel=500;headlabel=2]
        "2-ff00:0:211" -> "2-ff00:0:221"[taillabel=1;headlabel=3;constraint=false;dir=none;style=dotted]
        "2-ff00:0:211" -> "2-ff00:0:212"[taillabel=2;headlabel=201]
        "2-ff00:0:211" -> "2-ff00:0:212"[taillabel=3;headlabel=200]
        "2-ff00:0:211" -> "2-ff00:0:222"[taillabel=4;headlabel=301]
        "2-ff00:0:221" -> "2-ff00:0:222"[taillabel=1;headlabel=302]
        "1-ff00:0:110" -> "2-ff00:0:210"[taillabel=3;headlabel=453;dir=none]
        "1-ff00:0:120" -> "2-ff00:0:220"[taillabel=2;headlabel=501;dir=none]
        "1-ff00:0:120" -> "2-ff00:0:220"[taillabel=3;headlabel=502;dir=none]
        "1-ff00:0:111" -> "2-ff00:0:211"[taillabel=101;headlabel=5;constraint=false;dir=none;style=dotted]
        "1-ff00:0:111" -> "2-ff00:0:211"[taillabel=102;headlabel=6;constraint=false;dir=none;style=dotted]
}
```
</blockquote></details>

Very good point.
___
*[tools/topodot.py, line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4073#-MdLfr6e6A5yR_48Zi8E:-MdS5ALbDsFk5X8WZabP:b-e901cc) ([raw file](https://github.com/scionproto/scion/blob/c72d18633b17ec44af33961d9c6315eec03a1a03/tools/topodot.py#L140)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Dropping the `constraint=false` for core links causes dot rank the core ASes and ISDs, which is quite arbitrary. But dot seems to handle this far better, with fewer overlapping edges and labels. So :+1: 
</blockquote></details>

I was not able to get it running with the `constraint=false` and multi-nested subgraphs unfortunately.

**Review by matzf — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4073)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by matzf — COMMENTED** [review]
:100: 

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4073#-:-Me1NIqX6dOPRKLAIuQD:bmi8ppe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request closed without merging**
