### PR TITLE
deps: update a lot of dependencies

### PR DESCRIPTION
**Pull request by lukedirtwalker**
This commit updates almost all of the direct dependencies to the latest version.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 61 of 61 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323#-:-NOxyOSxAj-cyiDIpB9i:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`Makefile` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxrUGI0-iouHL5YYRe:-NOxrUGI0-iouHL5YYRf:b23lrbs) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L1)):*
> ```Makefile
> .PHONY: all antlr bazel build clean docker-images gazelle licenses mocks protobuf scion-topo test test-acceptance
> ```

Nit. Add new go mod tidy target.



_Suggestion:_
```Makefile
.PHONY: all antlr bazel clean docker-images gazelle go_mod_tidy licenses mocks protobuf scion-topo test test-integration
```
___
*[`Makefile` line 32 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxqaK41bMgiMQ-OflF:-NOxqaK41bMgiMQ-OflG:b-j88bda) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L32)):*
> ```Makefile
> 	bazel test --config=integration_all
> 
> go_mod_tidy:
> ```

Nit, targets generally use kebab-case, so maybe `go-mod-tidy? The `go_deps.bzl` is an exception because that's the actual file name.
___
*[`Makefile` line 32 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxsUC44eEq4I-rJANd:-NOxsUC44eEq4I-rJANe:brhsk0r) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L32)):*
> ```Makefile
> 	bazel test --config=integration_all
> 
> go_mod_tidy:
> ```

Nit. Could you please update the instructions to run this instead of `go mod tidy`, in `doc/build/dependencies.rst:25`?
___
*[`Makefile` line 33 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxsmUf9jqv8sCTI2mf:-NOxsmUf9jqv8sCTI2mg:b-4lhwjx) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L33)):*
> ```Makefile
> 
> go_mod_tidy:
> 	bazel run @go_sdk//:bin/go -- mod tidy
> ```

Nice! Perhaps add `--config=quiet` to silence the bazel noise.
___
*[`WORKSPACE` line 83 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxu7TY0SNtQeYS70_j:-NOxu7TY0SNtQeYS70_k:bfwco0y) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/WORKSPACE#L83)):*
> ```Starlark
>     sum = "h1:H2TDz8ibqkAF6YGhCdN3jS9O0/s90v0rJh3X/OLHEUk=",
>     version = "v0.0.0-20220907171357-04be3eba64a2",
> )
> ```

This appears to be one of these pruned dependencies now. Can we drop this override?
___
*[`private/ca/renewal/grpc/delegating_handler.go` line 148 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxwbNzCFo_O_hJDrCx:-NOxwbNzCFo_O_hJDrCy:b-83sjoh) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/private/ca/renewal/grpc/delegating_handler.go#L148)):*
> ```Go
> func (h *DelegatingHandler) parseChain(rep api.RenewalResponse) ([]*x509.Certificate, error) {
> 	chain, chainErr := rep.CertificateChain.AsCertificateChain()
> 	pkcs7, pkcs7Err := rep.CertificateChain.AsCertificateChainPKCS7()
> ```

Nice!

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`Makefile` line 32 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxsUC44eEq4I-rJANd:-NOyHKLR39UstWfbeW_P:b-awsqop) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L32)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit. Could you please update the instructions to run this instead of `go mod tidy`, in `doc/build/dependencies.rst:25`?
</blockquote></details>

This could also replace the longer commandline currently used  `.buildkite/pipeline.yml:35`.

**Review by matzf — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 6 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`Makefile` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxrUGI0-iouHL5YYRe:-NOycMngADkRMxE37a5L:bs7wumb) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit. Add new go mod tidy target.
</blockquote></details>

Done.
___
*[`Makefile` line 32 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxqaK41bMgiMQ-OflF:-NOycRw786ENxnVOs3TW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L32)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit, targets generally use kebab-case, so maybe `go-mod-tidy? The `go_deps.bzl` is an exception because that's the actual file name.
</blockquote></details>

Done.
___
*[`Makefile` line 32 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxsUC44eEq4I-rJANd:-NOyckmG9UF4HoH-_tcz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L32)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This could also replace the longer commandline currently used  `.buildkite/pipeline.yml:35`.
</blockquote></details>

Done.
___
*[`Makefile` line 33 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxsmUf9jqv8sCTI2mf:-NOycuYcCoEWQhpIHtVY:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/Makefile#L33)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nice! Perhaps add `--config=quiet` to silence the bazel noise.
</blockquote></details>

Done.
___
*[`WORKSPACE` line 83 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxu7TY0SNtQeYS70_j:-NOydZJL0qEDEigIBLYq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/WORKSPACE#L83)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This appears to be one of these pruned dependencies now. Can we drop this override?
</blockquote></details>

Done.
___
*[`private/ca/renewal/grpc/delegating_handler.go` line 148 at r1](https://reviewable.io/reviews/scionproto/scion/4323#-NOxwbNzCFo_O_hJDrCx:-NOydAON40MOjdpEmb8a:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/85484145d2de197264477970f1232917ef9bcd84/private/ca/renewal/grpc/delegating_handler.go#L148)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.

**Review by matzf — COMMENTED** [review]
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: 66 of 67 files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: 66 of 81 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`private/ca/renewal/grpc/delegating_handler.go` line 146 at r2](https://reviewable.io/reviews/scionproto/scion/4323#-NP1Jcfo5o5esWzRuXOM:-NP1Jcfo5o5esWzRuXON:b-5sjgun) ([raw file](https://github.com/scionproto/scion/blob/473cdb8cccb7c123311394a60179d9d01cbdd57e/private/ca/renewal/grpc/delegating_handler.go#L146)):*
> ```Go
> }
> 
> func (h *DelegatingHandler) parseChain(rep api.RenewalResponse) ([]*x509.Certificate, error) {
> ```

@oncilla could you please double check this?

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by oncilla — APPROVED** [review]
> Reviewed 54 of 61 files at r1, 8 of 8 files at r2, 5 of 5 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323#-:-NP1NZ8E9kmc_UtPdGAm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4323)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

**Pull request merged**
