### PR TITLE
spath: drop old header code

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Drops all code supporting the legacy header format. Also since the Path struct
is now that simple it is passed by value instead of pointer.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3909)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> Reviewed 71 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3909)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/cs/beaconing/handler_test.go, line 284 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK9-9q75R4L_ovIXd9R:-MK9-9q75R4L_ovIXd9S:b5nda5w) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/cs/beaconing/handler_test.go#L284)):*
> ```Go
> 
> func testPath(ingressIfid common.IFIDType) spath.Path {
> 	return spath.Path{}
> ```

Is this not needed anymore? It seems to be called with different args in the tests above.
___
*[go/lib/snet/path.go, line 125 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK90Did7DNts5Sltrce:-MK90Did7DNts5Sltrcf:b8ernb5) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/snet/path.go#L125)):*
> ```Go
> 		Raw:  append(p.spath.Raw[:0:0], p.spath.Raw...),
> 		Type: p.spath.Type,
> 	}
> ```

`return p.spath.Copy()`
___
*[go/lib/snet/path/path.go, line 63 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8yOJrCQrIN9JYWuz6:-MK8yOJrCQrIN9JYWuz7:b-4tw7bf) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/snet/path/path.go#L63)):*
> ```Go
> 		Raw:  append(p.SPath.Raw[:0:0], p.SPath.Raw...),
> 		Type: p.SPath.Type,
> 	}
> ```

Or just `return p.SPath.Copy()`?
___
*[go/lib/svc/svc.go, line 208 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8zAmbCqLJ32KbTH3Y:-MK8zAmbCqLJ32KbTH3Z:b-1q7dcp) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/svc/svc.go#L208)):*
> ```Go
> 		Raw:  append(path.Raw[:0:0], path.Raw...),
> 		Type: path.Type,
> 	}
> ```

Same here, `path = path.Copy()`?
___
*[go/pkg/traceroute/traceroute.go, line 294 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8zWer3anh2_np4NiR:-MK8zWer3anh2_np4NiS:bk1spvg) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/pkg/traceroute/traceroute.go#L294)):*
> ```Go
> 			IA:   pkt.Source.IA,
> 			Host: &net.UDPAddr{IP: pkt.Destination.Host.IP()},
> 			Path: spath.Path{Raw: append(pkt.Path.Raw[:0:0], pkt.Path.Raw...), Type: pkt.Path.Type},
> ```

`Path: pkt.Path.Copy()`

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3909)* status: all files reviewed, 4 unresolved discussions (waiting on @matzf)

___
*[go/cs/beaconing/handler_test.go, line 284 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK9-9q75R4L_ovIXd9R:-MK94ic56ZFGjLpKRf7v:b-32taa3) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/cs/beaconing/handler_test.go#L284)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Is this not needed anymore? It seems to be called with different args in the tests above.
</blockquote></details>

No, I removed it. In v1 we checked something on the path, which we no longer do in v2.
___
*[go/lib/snet/path.go, line 125 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK90Did7DNts5Sltrce:-MK957cY4hL-aCVUFfdL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/snet/path.go#L125)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`return p.spath.Copy()`
</blockquote></details>

Done.
___
*[go/lib/snet/path/path.go, line 63 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8yOJrCQrIN9JYWuz6:-MK95BTl-oSX2frMv-mD:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/snet/path/path.go#L63)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Or just `return p.SPath.Copy()`?
</blockquote></details>

Done.
___
*[go/lib/svc/svc.go, line 208 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8zAmbCqLJ32KbTH3Y:-MK95HDJ5dTmINHQ2VxL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/lib/svc/svc.go#L208)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Same here, `path = path.Copy()`?
</blockquote></details>

Done.
___
*[go/pkg/traceroute/traceroute.go, line 294 at r1](https://reviewable.io/reviews/scionproto/scion/3909#-MK8zWer3anh2_np4NiR:-MK95NyN6EeSIdca1ejC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8ae367c116cf0d303298093652adf5a8d1b6916f/go/pkg/traceroute/traceroute.go#L294)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`Path: pkt.Path.Copy()`
</blockquote></details>

Done.

**Review by matzf — COMMENTED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3909)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — COMMENTED** [review]
> Reviewed 66 of 71 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3909)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
