### PR TITLE
drkey: add serviceEngine and secretValueEngine

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR is the 5th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.

This PR contains:
- The `serviceEngine` for the CS
- The `secretValueEngine` for the CS
- The ARC adaptative cache to keep information about the remote keys that are fetch most frequently
- UT

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)* status: all files reviewed, 25 unresolved discussions (waiting on @JordiSubira)

___
*[`control/drkey/arc.go` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G0KCmAU54wC_ZQxtx:-N7G0KCmAU54wC_ZQxty:blajb3h) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L23)):*
> ```Go
> )
> 
> var _ Level1PrefetchListKeeper = (*Level1ARC)(nil)
> ```

In newer code we usually move those assertions into the test file.
___
*[`control/drkey/arc.go` line 26 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G5Snk0GhJloDOvMDK:-N7G5Snk0GhJloDOvMDL:bw5w9z0) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L26)):*
> ```Go
> 
> // Level1ARC maintains an Adaptative Replacement Cache, storing
> // the necessary metadata to prefetch Level1 keys
> ```

applies to all comments: Comments usually end with a period (`.`)
___
*[`control/drkey/arc.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1i_W2orLlF-CvDdD:-N7G1i_W2orLlF-CvDdE:b-2v4jgs) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L45)):*
> ```Go
> // in the ARC cache
> func (c *Level1ARC) Update(keyPair Level1PrefetchInfo) {
> 	c.cache.Add(keyPair, keyPair)
> ```

if we never care about the value we could also inserts `struct{}{}` as value here.
___
*[`control/drkey/arc.go` line 48 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1TlS9T02wdRe5d9b:-N7G1TlS9T02wdRe5d9c:b-jtq5lg) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L48)):*
> ```Go
> }
> 
> // GetCachedASes returns the list of AS currently in cache
> ```

the comment doesn't match the method signature, please fix it.
___
*[`control/drkey/arc.go` line 49 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G5Ctz2u2uea7nyoJO:-N7G5Ctz2u2uea7nyoJP:bnlvyva) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L49)):*
> ```Go
> 
> // GetCachedASes returns the list of AS currently in cache
> func (c *Level1ARC) GetLevel1InfoArray() []Level1PrefetchInfo {
> ```

I wonder if we should somehow rename this, since the struct name already contains `Level1` I wonder if we really need to repeat it here. Also we don't really need the `Get` prefix.
___
*[`control/drkey/arc_test.go` line 27 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G4W1GBy7cKXowhC46:-N7G4W1GBy7cKXowhC47:bpxh16g) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L27)):*
> ```Go
> )
> 
> func TestLevel1ARC(t *testing.T) {
> ```

I think this test would be much more readable if it would be structured as a table based test. Each test has some fill actions and some checks to be executed.

Also probably it makes more sense to split the testing of the `NewLevel1ARC` in a separate function `TestNewLevel1ARC`.

At least do the latter, the table-based is not super important and more nice to have.
___
*[`control/drkey/arc_test.go` line 28 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1qQz0qAOEUbVrmsl:-N7G1qQz0qAOEUbVrmsm:b3gnnf0) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L28)):*
> ```Go
> 
> func TestLevel1ARC(t *testing.T) {
> ```

drop the empty line.
___
*[`control/drkey/arc_test.go` line 40 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G2ceu86FMXPjgnHEQ:-N7G2ceu86FMXPjgnHER:b-uqq76h) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L40)):*
> ```Go
> 	}
> 	cache.Update(cacheKey0)
> 	assert.Len(t, cache.GetLevel1InfoArray(), 1)
> ```

Here we can simply test for the exact content.



_Suggestion:_
```Go
	assert.Equal(t, []cs_drkey.Level1PrefetchInfo{cacheKey0}, cache.GetLevel1InfoArray())
```
___
*[`control/drkey/arc_test.go` line 65 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G2lw2DzcdVnWp-qWx:-N7G2lw2DzcdVnWp-qWy:bdbrhn7) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L65)):*
> ```Go
> 	cache.Update(cacheKey0)
> 	assert.NotContains(t, cache.GetLevel1InfoArray(), cacheKey10)
> ```

drop empty line
___
*[`control/drkey/service_engine.go` line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G68aYDyQMtg7GudQ2:-N7G68aYDyQMtg7GudQ3:bk38oh) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L35)):*
> ```Go
> }
> 
> // Level1PrefetchListKeeper maintains a list for those lvl1 keys
> ```

no need to safe characters in a comment.



_Suggestion:_
```Go
 level1 
```
___
*[`control/drkey/service_engine.go` line 40 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G6IjW4KTIwTVGstzL:-N7G6IjW4KTIwTVGstzM:undefined) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L40)):*
> ```Go
> 	//Update updates the keys in Level1Cache based on the Level1Key metadata
> 	Update(key Level1PrefetchInfo)
> 	// GetLevel1InfoArray retrieves an array whose memebers contains information regarding
> ```





_Suggestion:_
```Go
members
```
___
*[`control/drkey/service_engine.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G6KW96KPVje2sIFWt:-N7G6KW96KPVje2sIFWu:undefined) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L41)):*
> ```Go
> 	Update(key Level1PrefetchInfo)
> 	// GetLevel1InfoArray retrieves an array whose memebers contains information regarding
> 	// lvl1 keys to prefetch
> ```





_Suggestion:_
```Go
level1 keys to prefetch.
```
___
*[`control/drkey/service_engine.go` line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G8HnnCoNZudIV3zNj:-N7G8HnnCoNZudIV3zNk:b3ae56f) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L52)):*
> ```Go
> 
> // ServiceEngine maintains and provides secret values, lvl1 keys and prefetching information.
> type ServiceEngine interface {
> ```

why do we need this interface? I don't really see where this would be used. for the `NewService*Cleaner` functions below we could have very specific interfaces inlined like this:
```go
func NewServiceSecretCleaner(s interface{DeleteExpiredSecrets(ctx context.Context) (int, error)}) *cleaner.Cleaner {
```

right now it's not clear to me that/why we should have this interface here.
___
*[`control/drkey/service_engine.go` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G90Le1gX-VvnizdU0:-N7G90Le1gX-VvnizdU1:bziidz0) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L86)):*
> ```Go
> 
> // serviceEngine keeps track of the level 1 drkey keys. It is backed by a drkey.DB
> type serviceEngine struct {
> ```

how do we plan to use this if the struct isn't public? Why are some of its fields public and others not?
___
*[`control/drkey/service_engine.go` line 96 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G9GSr9j_EmghJqfYC:-N7G9GSr9j_EmghJqfYD:b-2gnjsp) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L96)):*
> ```Go
> var _ ServiceEngine = (*serviceEngine)(nil)
> 
> func NewServiceEngine(localIA addr.IA,
> ```

If we make the struct public we don't really need the constructor the user can just fill the struct itself.
___
*[`control/drkey/service_engine.go` line 130 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G9WSi1bkhpZyjbBwj:-N7G9WSi1bkhpZyjbBwk:undefined) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L130)):*
> ```Go
> 
> // GetLevel1Key returns the level 1 drkey from the local DB or, if not found, by asking any CS in
> // the source AS of the key. It also updates the Level1Cache, if needed
> ```





_Suggestion:_
```Go
if needed.
```
___
*[`control/drkey/service_engine.go` line 137 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G9ldp85DSgyIOaGVi:-N7G9ldp85DSgyIOaGVj:b-dnf7a) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L137)):*
> ```Go
> 
> 	key, err := s.getLevel1Key(ctx, meta)
> 	if err == nil && ctx.Value(fromPrefetcher{}) == nil && meta.SrcIA != s.LocalIA {
> ```

who else will use this value? it's currently not very transparent maybe make a comment why we add this check.



_Code quote:_
```Go
fromPrefetcher{}
```
___
*[`control/drkey/service_engine.go` line 191 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAHhxBsVPYPU-kCiX:-N7GAHhxBsVPYPU-kCiY:b-6pcwmh) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L191)):*
> ```Go
> 	if meta.DstIA != s.LocalIA {
> 		return drkey.Level1Key{},
> 			serrors.New("Neither srcIA nor dstIA matches localIA", "srcIA", meta.SrcIA,
> ```

Error messages don't start with capital letter, because they are logged at some point and the log message will start with the sentence.



_Suggestion:_
```Go
neither
```
___
*[`control/drkey/service_engine.go` line 198 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAAkH7ARuzYUTcL0p:-N7GAAkH7ARuzYUTcL0q:baszuiv) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L198)):*
> ```Go
> 	k, err := s.DB.GetLevel1Key(ctx, meta)
> 	if err == nil {
> 		logger.Debug("L1 key found in storage")
> ```

do we want to keep that? wouldn't that lead to quite extensive logging?
___
*[`control/drkey/service_engine.go` line 258 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAn-67aZpb1BB5Yu3:-N7GAn-67aZpb1BB5Yu4:b-yo1l4e) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L258)):*
> ```Go
> 
> // DeriveASHost returns an AS-Host key based on the presented information
> func (s *serviceEngine) DeriveASHost(
> ```

please structure the file so that all public methods of the struct appear before the private ones.
___
*[`control/drkey/service_engine.go` line 277 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GBevEDXO3QVVPFKhX:-N7GBevEDXO3QVVPFKhY:b4kdddr) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L277)):*
> ```Go
> 		}
> 	} else {
> 		key, err = (&generic.Deriver{}).DeriveASHost(meta.ProtoId, meta.DstHost, lvl1Key.Key)
> ```

instead of having the `protoID` as a deriver argument we could have it as a member in the struct then both derivers would have the same interface and the code could be a bit cleaner here:
```go
	var deriver interface {
		DeriveHostAS(srcHost string, key drkey.Key) (drkey.Key, error)
	} = generic.Deriver{Proto: meta.ProtoId}

	if meta.ProtoId.IsPredefined() {
		deriver = specific.Deriver{}
	}
	key, err = deriver.DeriveHostAS(meta.SrcHost, lvl1Key.Key)
	if err != nil {
		return drkey.HostASKey{}, serrors.WrapStr("parsing derivation input", err)
	}
```

also I don't see why we need to allocate memory for the derivers those should really be objects that are created on the stack.

Same comment applies to the other derive methods.
___
*[`control/drkey/service_engine.go` line 343 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GDqrj0J0veI1hjHzM:-N7GDqrk8IPJfx96r9Jn:b65knb5) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L343)):*
> ```Go
> 	var err error
> 
> 	hostASKey, err := s.DeriveHostAS(ctx, hostASMeta)
> ```

I'm not super familiar with the whole setup, but I wonder if it wouldn't make sense to have this be required to be called separately, i.e. just take hostASKey as an argument? Or why is it done this way?

Same applies for the level1 key in the methods above.
___
*[`control/drkey/service_engine_test.go` line 53 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GF3bQ9an9O1-Sbf3I:-N7GF3bQ9an9O1-Sbf3J:bxakr3f) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L53)):*
> ```Go
> 		Validity: util.SecsToTime(0).UTC(),
> 	}
> ```

can you add a comment what we are testing below? 
___
*[`control/drkey/service_engine_test.go` line 79 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GFL-M4SDyp5_iMCh-:-N7GFL-M4SDyp5_iMCh0:b-frdh43) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L79)):*
> ```Go
> 	}
> 
> 	_, err = store.DeriveLevel1(meta)
> ```

should we check that the created key matches the meta values?
___
*[`control/drkey/service_engine_test.go` line 109 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GGO6z1KJVfm0ZHvhQ:-N7GGO6z1KJVfm0ZHvhR:b-16tfll) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L109)):*
> ```Go
> 
> 	fetcher := mock_drkey.NewMockFetcher(mctrl)
> 	firstCall := fetcher.EXPECT().Level1(gomock.Any(),
> ```

couldn't you use `gomock.InOrder` for this?
```go
	gomock.InOrder(
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(firstLevel1Key, nil),
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(secondLevel1Key, nil),
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(drkey.Level1Key{}, serrors.New("error retrieving key")),
	)
```

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)* status: 4 of 14 files reviewed, 25 unresolved discussions (waiting on @lukedirtwalker)

___
*[`control/drkey/arc.go` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G0KCmAU54wC_ZQxtx:-N7QVlhq2Xrp71Su21wc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L23)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

In newer code we usually move those assertions into the test file.
</blockquote></details>

Done.
___
*[`control/drkey/arc.go` line 26 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G5Snk0GhJloDOvMDK:-N7QVmal5oPu2SkuDxkh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L26)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

applies to all comments: Comments usually end with a period (`.`)
</blockquote></details>

Done.
___
*[`control/drkey/arc.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1i_W2orLlF-CvDdD:-N7QVnHh9ncA-EPBBX62:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L45)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

if we never care about the value we could also inserts `struct{}{}` as value here.
</blockquote></details>

Done.
___
*[`control/drkey/arc.go` line 48 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1TlS9T02wdRe5d9b:-N7QVnu03P0ACMpWallC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L48)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

the comment doesn't match the method signature, please fix it.
</blockquote></details>

Done.
___
*[`control/drkey/arc.go` line 49 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G5Ctz2u2uea7nyoJO:-N7QVohZ8HCBZ5UchAQi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc.go#L49)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I wonder if we should somehow rename this, since the struct name already contains `Level1` I wonder if we really need to repeat it here. Also we don't really need the `Get` prefix.
</blockquote></details>

Done.
___
*[`control/drkey/arc_test.go` line 27 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G4W1GBy7cKXowhC46:-N7QVrdMCSGPqzJ9XcS2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L27)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I think this test would be much more readable if it would be structured as a table based test. Each test has some fill actions and some checks to be executed.

Also probably it makes more sense to split the testing of the `NewLevel1ARC` in a separate function `TestNewLevel1ARC`.

At least do the latter, the table-based is not super important and more nice to have.
</blockquote></details>

Done.
___
*[`control/drkey/arc_test.go` line 28 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G1qQz0qAOEUbVrmsl:-N7QVsXVExybLSocSxx_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L28)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

drop the empty line.
</blockquote></details>

Done.
___
*[`control/drkey/arc_test.go` line 40 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G2ceu86FMXPjgnHEQ:-N7QVtVwAQ1Rra247Iyh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L40)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Here we can simply test for the exact content.
</blockquote></details>

Done.
___
*[`control/drkey/arc_test.go` line 65 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G2lw2DzcdVnWp-qWx:-N7QVu2P6NgyTLx-WwAk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/arc_test.go#L65)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

drop empty line
</blockquote></details>

Done.
___
*[`control/drkey/service_engine.go` line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G68aYDyQMtg7GudQ2:-N7QVv6NCYgDRbqDHRUZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L35)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

no need to safe characters in a comment.
</blockquote></details>

Done.
___
*[`control/drkey/service_engine.go` line 40 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G6IjW4KTIwTVGstzL:-N7QVvaEC9mb-6Sy3Mpf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L40)):*
> ```Go
> 	//Update updates the keys in Level1Cache based on the Level1Key metadata
> 	Update(key Level1PrefetchInfo)
> 	// GetLevel1InfoArray retrieves an array whose memebers contains information regarding
> ```

Done.
___
*[`control/drkey/service_engine.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G6KW96KPVje2sIFWt:-N7QVwQZ9qlmMmhLXsgK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L41)):*
> ```Go
> 	Update(key Level1PrefetchInfo)
> 	// GetLevel1InfoArray retrieves an array whose memebers contains information regarding
> 	// lvl1 keys to prefetch
> ```

Done.
___
*[`control/drkey/service_engine.go` line 130 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G9WSi1bkhpZyjbBwj:-N7QVyQg-CEPyFy2rTV8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L130)):*
> ```Go
> 
> // GetLevel1Key returns the level 1 drkey from the local DB or, if not found, by asking any CS in
> // the source AS of the key. It also updates the Level1Cache, if needed
> ```

Done.
___
*[`control/drkey/service_engine.go` line 191 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAHhxBsVPYPU-kCiX:-N7QVzEI-k9Ngp2Sfi_1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L191)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Error messages don't start with capital letter, because they are logged at some point and the log message will start with the sentence.
</blockquote></details>

Done.
___
*[`control/drkey/service_engine.go` line 198 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAAkH7ARuzYUTcL0p:-N7QWMg83OS-imK8cw-y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L198)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

do we want to keep that? wouldn't that lead to quite extensive logging?
</blockquote></details>

Done.
___
*[`control/drkey/service_engine.go` line 258 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GAn-67aZpb1BB5Yu3:-N7QWhxUCKWOqdjPiUXP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L258)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please structure the file so that all public methods of the struct appear before the private ones.
</blockquote></details>

Done.
___
*[`control/drkey/service_engine.go` line 277 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GBevEDXO3QVVPFKhX:-N7QWl520wjQ5iAk7Gpq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L277)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

This is probably because before the derivers used an internal buffer to receive the input for the derivation. I will change the methods to receive the struct instead of the pointer.
</blockquote></details>

Done.
___
*[`control/drkey/service_engine_test.go` line 53 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GF3bQ9an9O1-Sbf3I:-N7QXYHT2LBPpPDby2fW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L53)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

can you add a comment what we are testing below? 
</blockquote></details>

Done.
___
*[`control/drkey/service_engine_test.go` line 79 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GFL-M4SDyp5_iMCh-:-N7QXZN42uj_l47Cu0jh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L79)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

should we check that the created key matches the meta values?
</blockquote></details>

Done.
___
*[`control/drkey/service_engine_test.go` line 109 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7GGO6z1KJVfm0ZHvhQ:-N7QX_S93351kN1wzzxK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine_test.go#L109)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

couldn't you use `gomock.InOrder` for this?
```go
	gomock.InOrder(
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(firstLevel1Key, nil),
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(secondLevel1Key, nil),
		fetcher.EXPECT().Level1(gomock.Any(), gomock.Any()).
			Return(drkey.Level1Key{}, serrors.New("error retrieving key")),
	)
```
</blockquote></details>

Done.

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)* status: all files reviewed, 2 unresolved discussions (waiting on @JordiSubira)

___
*[`control/drkey/service_engine.go` line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G8HnnCoNZudIV3zNj:-N7Uag1w3wmPQcG3QgMz:b-2nj4xy) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L52)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

We decided to have one interface that hides behinds the logic to derive/get/delete keys. It will be used in the `grpc_drkey_service`, the `prefetcher the `TaskConfig` in the CS and some UT relative to those. It is true that probably will have only the serviceEngine struct implementing this interface
</blockquote></details>

I'm not against the interface per se. It's just like this seems like a misuse of the Go interface. 
Usually interfaces should be at the place where they are used (not at the place where they are defined).
In main you instantiate the concrete type and plug them in the place where an interface is expected.

So for example to me it seems that the server will likely not need access to the `DeleteExpired*` methods. So I would just define on the server the interface that I need for the server. Similar for the prefetcher.
___
*[`control/drkey/service_engine.go` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G90Le1gX-VvnizdU0:-N7UcddBBiiu08dz9sX_:b5lrcvh) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L86)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

The idea was to use the constructor that hides the secretValeBackend and the PrefetchKeeper. I can make it public if you thing that's better.
</blockquote></details>

Why do we need to hide the secretValueBackend? I'm fine with either way. But I think the Struct should be public either way otherwise it's not really usable in other packages.
___
*[`control/drkey/service_engine.go` line 137 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G9ldp85DSgyIOaGVi:-N7UcorW0JCJExoR0c8z:bdjlf4j) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L137)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

The `prefetcher` and the `serviceEngine`. The idea is not updating the `prefetchKeeper` for those keys that are prefetch, so that we avoid having always the same keys in this list. It would only be updated when keys are requested by some host.
</blockquote></details>

I see, as long at it's all local to this package it's fine.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)* status: 7 of 14 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`control/drkey/service_engine.go` line 52 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G8HnnCoNZudIV3zNj:-N7W-z-75AEmyevX5uWQ:becx5i6) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L52)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I'm not against the interface per se. It's just like this seems like a misuse of the Go interface. 
Usually interfaces should be at the place where they are used (not at the place where they are defined).
In main you instantiate the concrete type and plug them in the place where an interface is expected.

So for example to me it seems that the server will likely not need access to the `DeleteExpired*` methods. So I would just define on the server the interface that I need for the server. Similar for the prefetcher.
</blockquote></details>

You're right probably we're overusing this interface. I will remove it from this file and redefine a new interface in the server and the prefetcher.
___
*[`control/drkey/service_engine.go` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4225#-N7G90Le1gX-VvnizdU0:-N7W0JzC7u8T4qiwMYyQ:b-3b1u83) ([raw file](https://github.com/scionproto/scion/blob/b440af1227b29405dce1b572cdd2c47133650b9f/control/drkey/service_engine.go#L86)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Why do we need to hide the secretValueBackend? I'm fine with either way. But I think the Struct should be public either way otherwise it's not really usable in other packages.
</blockquote></details>

I made it public and removed the constructor.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4225)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
