### PR TITLE
python: fix type annotations

### PR DESCRIPTION
**Pull request by matzf**
Various type annotations were broken or half-broken. This prevented even
running the scripts under some setups.
In particular, the annotations for the ipaddress types used the
"construction functions" (e.g. `ip_address`) instead of the type of the
returned objects (e.g.  `IPv4Address`).

~~Enable running mypy during `scion.sh lint` and thus in CI~~

Relatedly, simplify the flake8 lint step and configuration and enable
style checks for acceptance tests and all python tools.

Additionally, fix up the last few remaining imports in order to simplify
the PYTHONPATH to only need the base directory, instead of the base
directory _and_ python/ -- mypy didn't like this.

Finally (and somewhat unrelatedly), revert some recently introduced use
of f-strings (new in python-3.6) back to plain %-interpolation. This was
breaking compatibility with python-3.5 without real benefit.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3888)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3888)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[acceptance/cert_renewal_acceptance/test, line 84 at r1](https://reviewable.io/reviews/scionproto/scion/3888#-MJfCCgUD2ZfBAoLKdWx:-MJfCCgV7U94Z4_CmZEO:b-uwehn9) ([raw file](https://github.com/scionproto/scion/blob/f063423d9370db5db46fc4539b246e47116e9a25/acceptance/cert_renewal_acceptance/test#L84)):*
> ```
> certificate
> ```
why is the `i` removed here?
___
*[python/topology/common.py, line 119 at r1](https://reviewable.io/reviews/scionproto/scion/3888#-MJfCVMk8vKt2jK1ZCQX:-MJfCVMl8PSDVILbCuF2:bejokwv) ([raw file](https://github.com/scionproto/scion/blob/8596e9afff7cad4d46821e5f78eed9d346d00806/python/topology/common.py#L119)):*
> ```Python
> def sciond_ip(docker, topo_id, networks: Mapping[IPNetwork, NetworkDescription]):
>     for net_desc in networks.values():
>         print(net_desc.ip_net)
> ```

leftover?

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3888)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3888#-MJfDFh87W3u1V3MPQFD:-MJfDFh9-28RTXDtDufr:b-koatr8) (no related file):*
thanks for doing this. It would be nice if we could bazelify the linter similar to yapf in #3901 so that no one needs to install this on the host and it works on CI.

---

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3888)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3888#-MJfDFh87W3u1V3MPQFD:-MJfHGhZ8-6zfZJAGHfh:bjribt2) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

thanks for doing this. It would be nice if we could bazelify the linter similar to yapf in #3901 so that no one needs to install this on the host and it works on CI.
</blockquote></details>

Dropped adding mypy to the lint steps, as discussed. Not keen on bazelyfing.

---
___
*[acceptance/cert_renewal_acceptance/test, line 84 at r1](https://reviewable.io/reviews/scionproto/scion/3888#-MJfCCgUD2ZfBAoLKdWx:-MJfHaT82XaBVULF_ScE:b2oxyab) ([raw file](https://github.com/scionproto/scion/blob/f063423d9370db5db46fc4539b246e47116e9a25/acceptance/cert_renewal_acceptance/test#L84)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> certificate
> ```
why is the `i` removed here?
</blockquote></details>

Must have tried to shorten the line ;) Fixed.
___
*[python/topology/common.py, line 119 at r1](https://reviewable.io/reviews/scionproto/scion/3888#-MJfCVMk8vKt2jK1ZCQX:-MJfHpkl55QG2DPEbGhS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8596e9afff7cad4d46821e5f78eed9d346d00806/python/topology/common.py#L119)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

leftover?
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3888)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
