### PR TITLE
gateway: pass path information around as a data structure

### PR DESCRIPTION
**Pull request by sustrik**
Until now it was passed around as an unstructured string.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @sustrik)

___
*[`gateway/control/engine.go` line 268 at r1](https://reviewable.io/reviews/scionproto/scion/4206#-N3K3rHK7KD61gNv_T8M:-N3K3rHK7KD61gNv_T8N:b-ttkc8h) ([raw file](https://github.com/scionproto/scion/blob/8be045f3d25c2613f68e12655a71a030482e6e9c/gateway/control/engine.go#L268)):*
> ```Go
> 				"",
> 				"",
> 				path.Path,
> ```

Not the same number of columns in the two branches. It looks like the entry for the "PATH" column is misaligned for these rejected paths.
___
*[`gateway/pathhealth/registration.go` line 55 at r1](https://reviewable.io/reviews/scionproto/scion/4206#-N3K2sH1BLOe7kTe8oBv:-N3K2sH1BLOe7kTe8oBw:b-k5bc5b) ([raw file](https://github.com/scionproto/scion/blob/8be045f3d25c2613f68e12655a71a030482e6e9c/gateway/pathhealth/registration.go#L55)):*
> ```Go
> 	Latency      util.DurWrap
> 	Jitter       util.DurWrap
> 	DropRate     float64
> ```

Unused fields?



_Code quote:_
```Go
	Latency      util.DurWrap
	Jitter       util.DurWrap
	DropRate     float64
```

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: 4 of 11 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[`gateway/control/engine.go` line 268 at r1](https://reviewable.io/reviews/scionproto/scion/4206#-N3K3rHK7KD61gNv_T8M:-N3KDLRsE6CriG2lucge:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8be045f3d25c2613f68e12655a71a030482e6e9c/gateway/control/engine.go#L268)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Not the same number of columns in the two branches. It looks like the entry for the "PATH" column is misaligned for these rejected paths.
</blockquote></details>

Done.
___
*[`gateway/pathhealth/registration.go` line 55 at r1](https://reviewable.io/reviews/scionproto/scion/4206#-N3K2sH1BLOe7kTe8oBv:-N3KDM0aB_6cczaOl_ww:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8be045f3d25c2613f68e12655a71a030482e6e9c/gateway/pathhealth/registration.go#L55)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Unused fields?
</blockquote></details>

Done.

**Review by matzf — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @sustrik)

___
*[`gateway/pathhealth/registration.go` line 74 at r2](https://reviewable.io/reviews/scionproto/scion/4206#-N3NybHA9wa_rwS9mxDN:-N3NybHA9wa_rwS9mxDO:b-o0dity) ([raw file](https://github.com/scionproto/scion/blob/f082c33e792124c10ef2030ba5d74c8ffbbc2569/gateway/pathhealth/registration.go#L74)):*
> ```Go
> }
> 
> type PathInfoEntry interface {
> ```

Did you have to add this interface to allow somehow adding the additional fields for your internal extension? If so, keeping the unused fields would seem just as well -- either way there is no obvious "local" reason for keeping it this structure.

Perhaps we could start to somehow annotate unused fields in cases like this,  e.g. `// extension (anapaya)`, so we're less likely to accidentally remove or otherwise break it. I don't have a good idea on how common this would be though. Do you think this would make sense?

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @matzf)

___
*[`gateway/pathhealth/registration.go` line 74 at r2](https://reviewable.io/reviews/scionproto/scion/4206#-N3NybHA9wa_rwS9mxDN:-N3O4gz-9EkoLeCN0IZ-:b-2qjhzs) ([raw file](https://github.com/scionproto/scion/blob/f082c33e792124c10ef2030ba5d74c8ffbbc2569/gateway/pathhealth/registration.go#L74)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Did you have to add this interface to allow somehow adding the additional fields for your internal extension? If so, keeping the unused fields would seem just as well -- either way there is no obvious "local" reason for keeping it this structure.

Perhaps we could start to somehow annotate unused fields in cases like this,  e.g. `// extension (anapaya)`, so we're less likely to accidentally remove or otherwise break it. I don't have a good idea on how common this would be though. Do you think this would make sense?
</blockquote></details>

Yes, it's because we keep those additional metrics. However, the interface approach feels cleaner. I would keep it as is and you don't have to care about anapaya extensions at all.

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @matzf)

___
*[`gateway/pathhealth/registration.go` line 74 at r2](https://reviewable.io/reviews/scionproto/scion/4206#-N3NybHA9wa_rwS9mxDN:-N3SNL1E-g_e2-8ea4sb:b-gptixe) ([raw file](https://github.com/scionproto/scion/blob/f082c33e792124c10ef2030ba5d74c8ffbbc2569/gateway/pathhealth/registration.go#L74)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

Yes, it's because we keep those additional metrics. However, the interface approach feels cleaner. I would keep it as is and you don't have to care about anapaya extensions at all.
</blockquote></details>

@matzf can you resolve this comment?

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`gateway/pathhealth/registration.go` line 74 at r2](https://reviewable.io/reviews/scionproto/scion/4206#-N3NybHA9wa_rwS9mxDN:-N3T-iLN9JfXJcKw3NoE:b-aja4rk) ([raw file](https://github.com/scionproto/scion/blob/f082c33e792124c10ef2030ba5d74c8ffbbc2569/gateway/pathhealth/registration.go#L74)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

@matzf can you resolve this comment?
</blockquote></details>

Ok for me.

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: all files reviewed, 1 unresolved discussion (waiting on @sustrik)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4206#-N3TIvHPEs-v_ZYJyOMF:-N3TIvHPEs-v_ZYJyOMG:bqyj69v) (no related file):*
blocking for now, still investigating whether we can do without the interface.

___

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4206#-N3TIvHPEs-v_ZYJyOMF:-N3UGnhe9eboB91cEAiR:b-9xqg1x) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

blocking for now, still investigating whether we can do without the interface.
</blockquote></details>

the interface is removed now

___

**Review by sustrik — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sustrik)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sustrik)

**Pull request merged**
