### PR TITLE
Simplify creation of SVC addresses

### PR DESCRIPTION
**Pull request by scrye**
This PR adds support for SVC addresses in `snet.AddrFromString`. A valid SVC address can be initialized using the `ISD-AS,[SVC]` format, e.g., `1-ff00:0:1,[PS]`.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)

### CODE REVIEW

**Comment by kormat** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[go/lib/addr/host.go, line 176 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgWXX5BIvOy2dhigCp:-LDgWXX5BIvOy2dhigCq:bbn8obc) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/addr/host.go#L176)):*
> ```Go
> // HostSVCFromString returns the SVC address corresponding to str. Valid values
> // for str are BS, PS, CS, and SB. For invalid values, SvcNone is returned.
> func HostSVCFromString(str string) HostSVC {
> ```

Is it a deliberate decision to only support the anycast form of SVC?

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/snet/addr.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgX4g45_OEa8GYmsl8:-LDgX4g45_OEa8GYmsl9:b-dh8ona) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/snet/addr.go#L52)):*
> ```Go
> 		return "<nil>"
> 	}
> 	s := fmt.Sprintf("%s,[%v]:%d", a.IA, a.Host, a.L4Port)
> ```

This should still be `%s` - `addr.HostAddr` includes `fmt.Stringer`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/addr/host.go, line 176 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgWXX5BIvOy2dhigCp:-LDjye_638y0QAeiyoI5:bgpwrny) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/addr/host.go#L176)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Is it a deliberate decision to only support the anycast form of SVC?
</blockquote></details>

Yes, anycast felt like the better match for basic service names and it was the bare minimum I needed for some sciond tests.

If you have a proposal for how multicast addresses would look like, I can add them.

---

*[go/lib/snet/addr.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgX4g45_OEa8GYmsl8:-LDjyEkG9zI2SPr3dIrh:b-mtpcc9) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/snet/addr.go#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should still be `%s` - `addr.HostAddr` includes `fmt.Stringer`.
</blockquote></details>

`%s` leads to some ugly formatting even for `fmt.Stringer` (it's how I got to find the issue). `%v` would avoid that. See https://play.golang.org/p/6BjkJ-viGor.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by kormat** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/addr/host.go, line 176 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgWXX5BIvOy2dhigCp:-LDk5aMc7CDs8WErxrXS:b40qdjp) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/addr/host.go#L176)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Yes, anycast felt like the better match for basic service names and it was the bare minimum I needed for some sciond tests.

If you have a proposal for how multicast addresses would look like, I can add them.
</blockquote></details>

In the python codebase we format them as `BS_A` and `BS_M`. We could, for example, map `BS` and `BS_A` to the anycast version, and `BS_M` to the multicast version.

---

*[go/lib/snet/addr.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgX4g45_OEa8GYmsl8:-LDk5M3HCjaIWoIsoXQ5:b-pfysu4) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/snet/addr.go#L52)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

`%s` leads to some ugly formatting even for `fmt.Stringer` (it's how I got to find the issue). `%v` would avoid that. See https://play.golang.org/p/6BjkJ-viGor.
</blockquote></details>

Oh, huh. I'm guessing that's what happens when the interface value is nil, there's no concrete type to handle `String()`. Fair enough then :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by scrye** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/addr/host.go, line 176 at r1](https://reviewable.io/reviews/scionproto/scion/1577#-LDgWXX5BIvOy2dhigCp:-LDpEd_FCLgouSJCsQdB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ab4ae02137e4009122be8b28713be86135ca0ef6/go/lib/addr/host.go#L176)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In the python codebase we format them as `BS_A` and `BS_M`. We could, for example, map `BS` and `BS_A` to the anycast version, and `BS_M` to the multicast version.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/addr/host.go, line 180 at r2](https://reviewable.io/reviews/scionproto/scion/1577#-LDvEUv5AciLccQPlbIT:-LDvdQIg8TIhuKgkI8M5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f1b4f942442ab2258e9b7fff7f31e45c2af26b48/go/lib/addr/host.go#L180)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`var m HostSVC`
</blockquote></details>

Done.

---

*[go/lib/snet/addr_test.go, line 88 at r2](https://reviewable.io/reviews/scionproto/scion/1577#-LDvEfa95H7J4KSup1_o:-LDvdqUDEKAAZ1SZXfv7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f1b4f942442ab2258e9b7fff7f31e45c2af26b48/go/lib/snet/addr_test.go#L88)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Might as well add a test for the bare version too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577)*

**Comment by kormat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1577#-:-LDve2y23XVOfwwBzUWQ:bnfp4nl)*

**Pull request merged**
