### PR TITLE
pkg/private/common: move IfIDType out of private/common and to its own package

### LINKED ISSUE #4584: pkg/private/common: move the IFIDType definition to pkg/addr
We should try and avoid throwing things in a random pile such as common/defs.go. If IFIDType is an important type we should make some API own it.

### PR DESCRIPTION
**Pull request by jiceatscion**
Given that IfIDType represents generic interface IDs as used in segments distributed by the control service, it seems that it shouldn't be private either, even if it currently can be. So the new package isn't private.

Fixes #4584

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4604)

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4604)* status: 0 of 78 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @lukedirtwalker)

___
*[`pkg/segment/iface/iface.go` line 26 at r2](https://reviewable.io/reviews/scionproto/scion/4604#-O700abP-BqNv2fZQTUs:-O700abP-BqNv2fZQTUt:b-oh1dfk) ([raw file](https://github.com/scionproto/scion/blob/6cb6c393c9e99ac8e774eff69b08d7b6e56b1478/pkg/segment/iface/iface.go#L26)):*
> ```Go
> // 64 bits. There is a lot of path-type-independent code that manipulates interface IDs without
> // interpreting them. This type is a container for them.
> type IfIDType uint64
> ```

At the usage site, this now is `iface.IfIDType`
It stutters, is barely readable, and full of redundancy.

How about we just name it `ID`? At usage site, this turns into `iface.ID` which is much easier on the eyes, and contains just as much information.



_Suggestion:_
```Go
type ID uint64
```

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4604)* status: 0 of 78 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

___
*[`pkg/segment/iface/iface.go` line 26 at r2](https://reviewable.io/reviews/scionproto/scion/4604#-O700abP-BqNv2fZQTUs:-O73GGRoDLYaTy6HmSVq:bgl3n4n) ([raw file](https://github.com/scionproto/scion/blob/6cb6c393c9e99ac8e774eff69b08d7b6e56b1478/pkg/segment/iface/iface.go#L26)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

At the usage site, this now is `iface.IfIDType`
It stutters, is barely readable, and full of redundancy.

How about we just name it `ID`? At usage site, this turns into `iface.ID` which is much easier on the eyes, and contains just as much information.
</blockquote></details>

I agree this is much better. Done

**Review by oncilla — COMMENTED** [review]
> Reviewed 2 of 78 files at r1, 29 of 76 files at r2, 47 of 47 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4604)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

**Review by oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4604#-:-O7575ji43lI5gkdF2TM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

**Review by jiceatscion — COMMENTED** [review]
> Dismissed @oncilla from a discussion.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4604)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
