### PR TITLE
Add KeyConfig

### PR DESCRIPTION
**Pull request by Oncilla**
Add key configuration to go lib.
The key configuration holds:
- AS decryption key
- AS signing key
- AS online key (for core AS)
- AS offline key (for core AS)

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1371)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/trust/key_conf.go, line 51 at r1](https://reviewable.io:443/reviews/scionproto/scion/1371#-L2ecr28I-61TXnIO_rP:-L2ecr28I-61TXnIO_rQ:b2g6kx8) ([raw file](https://github.com/scionproto/scion/blob/7fe902baf8632c3777e606f22b0a15617447d433/go/lib/trust/key_conf.go#L51)):*
> ```Go
> // LoadKeyConf loads key configuration from specified path. The loaded config is put into
> // CurrKeyConf.
> func LoadKeyConf(path string, core bool) (*KeyConf, error) {
> ```

Instead of passing a bool here `LoadKeyConf` should just check if a offline/online root key is present and if yes load it. The application using the keystore should then check itself whether there _must_ be an offline/online root key. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1371)*

**Comment by Oncilla** [comment]
*[go/lib/trust/key_conf.go, line 51 at r1](https://reviewable.io:443/reviews/scionproto/scion/1371#-L2ecr28I-61TXnIO_rP:-L2elXCpffuSygADs48Y:b-iqmij6) ([raw file](https://github.com/scionproto/scion/blob/7fe902baf8632c3777e606f22b0a15617447d433/go/lib/trust/key_conf.go#L51)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Instead of passing a bool here `LoadKeyConf` should just check if a offline/online root key is present and if yes load it. The application using the keystore should then check itself whether there _must_ be an offline/online root key. 
</blockquote></details>

This seems a bit odd to me. How about we rename core to loadRootKeys instead.
Other wise, the client has to check for error and additionally do a nil check for both online and offline root keys

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1371)*

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/trust/key_conf.go, line 51 at r1](https://reviewable.io:443/reviews/scionproto/scion/1371#-L2ecr28I-61TXnIO_rP:-L3-11dQpHMizSBRBMX7:b2nhll9) ([raw file](https://github.com/scionproto/scion/blob/7fe902baf8632c3777e606f22b0a15617447d433/go/lib/trust/key_conf.go#L51)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

This seems a bit odd to me. How about we rename core to loadRootKeys instead.
Other wise, the client has to check for error and additionally do a nil check for both online and offline root keys
</blockquote></details>

Ok.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1371)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1371#-:-L33PbvAzmssD7xk_qNT:bnfp4nl)*

**Pull request merged**
