### PR TITLE
Path test in showpaths tool

### LINKED ISSUE #2039: Add path test functionality for showpaths tool
It would be useful if `showpaths` were able to check the health of printed paths, for users to be able to differentiate between healthy, revoked, unknown, etc. This mode of operation could be enabled by specifying a flag, e.g., `-p`.

### PR DESCRIPTION
**Pull request by sustrik**
Fixes #2039

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/2108)

### CODE REVIEW

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 116 at r1](https://reviewable.io/reviews/scionproto/scion/2108#-LQniCggBkJs67r70f-c:-LQnma0H6dOCqrW7MgUb:b630l6y) ([raw file](https://github.com/scionproto/scion/blob/afe4fe7e28f42594f7ca036c2bccdec6fa46c037/go/tools/showpaths/paths.go#L116)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

you should have a timeout here in case some packets are lost and you get no reply at all
</blockquote></details>

There's a timeout set on the connection, see line 84

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 115 at r1](https://reviewable.io/reviews/scionproto/scion/2108#-LQnfiqy2J9j4EQXOR56:-LQnmuu8-gfRVGaT2Nlb:b-3xm1j4) ([raw file](https://github.com/scionproto/scion/blob/afe4fe7e28f42594f7ca036c2bccdec6fa46c037/go/tools/showpaths/paths.go#L115)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Why such a big buffer? errors should fit in 1500 Bytes packets and if it doesn't fit you should get an error from ReadFrom
</blockquote></details>

I wasn't sure what the limit is. Shrinking it to 1500.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 115 at r1](https://reviewable.io/reviews/scionproto/scion/2108#-LQnfiqy2J9j4EQXOR56:-LQnmzno8EvVZM9saDu7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afe4fe7e28f42594f7ca036c2bccdec6fa46c037/go/tools/showpaths/paths.go#L115)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

I wasn't sure what the limit is. Shrinking it to 1500.
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 116 at r1](https://reviewable.io/reviews/scionproto/scion/2108#-LQniCggBkJs67r70f-c:-LQnn37702bnQ3QFXc4_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afe4fe7e28f42594f7ca036c2bccdec6fa46c037/go/tools/showpaths/paths.go#L116)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

There's a timeout set on the connection, see line 84
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 117 at r1](https://reviewable.io/reviews/scionproto/scion/2108#-LQnghlfBkwWubLJecXp:-LQrROzL1gyDJk6la21b:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/afe4fe7e28f42594f7ca036c2bccdec6fa46c037/go/tools/showpaths/paths.go#L117)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

I don't think this is enough. You should check the SCMP error you got back, and check for the expected class/type error.
You can call SCMP() on an OpError then check  for C_Rourintg/T_R_BadHost

As discussed offline, we should check for:
1. expected SCMP error C_Rourintg/T_R_BadHost
2. print any other error
3. unexpected packet
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 77 at r2](https://reviewable.io/reviews/scionproto/scion/2108#-LQr_FxCD862i13lhXxT:-LQrdjT03Yb4v0VCP1Eh:b-uqezg8) ([raw file](https://github.com/scionproto/scion/blob/f8375d2edd7c88db2b1d2b299178e3e9bfd770bc/go/tools/showpaths/paths.go#L77)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

the code for this functionality is quite large compare to the main body itself, could you take it out of main and brake it up a bit into smaller function/functions?
</blockquote></details>

I've split the path testing into a separate function. However, splitting it further doesn't make much sense. Sending the packets alone isn't good for anything. Neither is receiving the replies.

**Comment by sgmonroy** [comment]
*[a discussion](https://reviewable.io/reviews/scionproto/scion/2108#-LQsbqRV5DhMhRQNoxBl:-LQsbqRV5DhMhRQNoxBm:b-8u3fa7) (no related file):*
Let Sergiu have a look before merging

---

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 81 at r3](https://reviewable.io/reviews/scionproto/scion/2108#-LQsf0rD5hiJDetiCoSY:-LQsu0ijDdnexbsi08Ov:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/930a21bbab5a5902467ae22efbddf1725b659792/go/tools/showpaths/paths.go#L81)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

It's not related to this PR specifically, but we can simplify two lines by doing:
```
for i, path := range reply.Entries {
  // ....
}
```
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 91 at r3](https://reviewable.io/reviews/scionproto/scion/2108#-LQsfAbp677TtWP_TTBA:-LQsu3AbCyIFLip8qQOZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/930a21bbab5a5902467ae22efbddf1725b659792/go/tools/showpaths/paths.go#L91)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

This must be removed for the previous comment to work.
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 148 at r3](https://reviewable.io/reviews/scionproto/scion/2108#-LQsgj6B9VLVZYtXm3Be:-LQsu4MmCn7xPPCdc534:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/930a21bbab5a5902467ae22efbddf1725b659792/go/tools/showpaths/paths.go#L148)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

It would be a bit easier to read this if the inside of the loop were split into a different function:
```
for _, path := range paths {
    sendTestPacket(scionConn, path)
    pathStatuses[string(path.Path.FwdPath)] = "Timeout"
}
```
</blockquote></details>

Done.

**Comment by sustrik** [comment]
___
*[go/tools/showpaths/paths.go, line 173 at r3](https://reviewable.io/reviews/scionproto/scion/2108#-LQsh7I7DY3UNXAiDbls:-LQsu5W61yhHhhexfrCp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/930a21bbab5a5902467ae22efbddf1725b659792/go/tools/showpaths/paths.go#L173)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Same suggestion as above:
```
for i := len(pathStatuses); i > 0; i-- {
    path, status := receiveNextTestReply(scionConn)
    pathStatuses[path] = status // and other global logic, like double replies
}
```
</blockquote></details>

Done.

**Pull request merged**
