### PR TITLE
scion-pki: Add unit-tests for pkicmn and conf packages

### PR DESCRIPTION
**Pull request by jinankjain**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)

### CODE REVIEW

**Comment by jinankjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn.go, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLAtri13AGjcV2H044:-LBLO_k--l07DW1CaC0r:b-1hvbz2) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn.go#L67)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

You shouldn't change this. In the `README` we also use the normal format and not the file format.
</blockquote></details>

It needs to be changed because https://github.com/scionproto/scion/blob/master/go/tools/scion-pki/internal/pkicmn/pkicmn.go#L84 expects the AS to be in FileFmt to get the directory path

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 45 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLBKgcExL0bSbQIc7E:-LBLNmR76_pJ8KxCszLc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L45)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This is not a unit test. If creating a temp directory fails it's not somehow the code that you want to test  that is broken, so what you want to do here (and in every case where you check an error that is not part of the code that you want to test)  is use `xtest.FailOnErr`.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLFBEdCUYk15UAJWfi:-LBLHMXF0XhyY7QblpsQ:b899pfz) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L71)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Hmm, so testing against specific error messages is a bit tricky, even more so if there are nested errors as well. You'd need to create constants for the actual error message strings to ensure consistency between the code and the test. This works fine as long as there are no nested errors, thus I suggest you just check for the existence/absence of an error.
</blockquote></details>

Creating constant strings for error won't really work since so of the error messages are dynamically generated. For example selector string is generated dynamically depending upon the user input. But then just checking presence/absence is not concrete as that might not give an idea which scenario triggered that error.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn.go, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLAtri13AGjcV2H044:-LBLfARiE9caJyx0OfWO:bpah8kh) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn.go#L67)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

It needs to be changed because https://github.com/scionproto/scion/blob/master/go/tools/scion-pki/internal/pkicmn/pkicmn.go#L84 expects the AS to be in FileFmt to get the directory path
</blockquote></details>

The correct thing to do is then not work with the `asTok` directly, but with the `addr.IA` object that `addr.ASFromString()` returns you. When it's used later you can then call `as.FileFmt()` to get the correct formatting.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLFBEdCUYk15UAJWfi:-LBLfeIB5poICKRAIt8o:b-qzc8l2) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L71)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Creating constant strings for error won't really work since so of the error messages are dynamically generated. For example selector string is generated dynamically depending upon the user input. But then just checking presence/absence is not concrete as that might not give an idea which scenario triggered that error.
</blockquote></details>

Ok here is what you can do. Create constants for all the error messages in the corresponding modules of `scion-pki`. Then in the test you cast the error object that you get back to a `common.BasicError` and then you can do `So(err.Msg, shouldEqual, pkicmn.InvalidSelectorErr)`. `err.Msg` will only create the error message of the outermost error, with any context (e.g., `selector=2` is context).

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by jinankjain** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 71 at r1](https://reviewable.io/reviews/scionproto/scion/1542#-LBLFBEdCUYk15UAJWfi:-LBLx_jZ79yStTtT86OP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/7e25deea3eacc423e4e928647972af1b22fa7325/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L71)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Ok here is what you can do. Create constants for all the error messages in the corresponding modules of `scion-pki`. Then in the test you cast the error object that you get back to a `common.BasicError` and then you can do `So(err.Msg, shouldEqual, pkicmn.InvalidSelectorErr)`. `err.Msg` will only create the error message of the outermost error, with any context (e.g., `selector=2` is context).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/as.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBepe3m04Jn56BSTIO3:-LBepe3m04Jn56BSTIO4:b1t5ptk) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/conf/as.go#L138)):*
> ```Go
> 	}
> 	if ac.BaseCert == nil {
> 		return common.NewBasicError(ErrBaseCertMissing, nil)
> ```

This is not an error that will help the user, since there is no `Base Certificate` section or something the user could do. You can add a `panic` here, since it is an implementation error if this ever happens.

---

*[go/tools/scion-pki/internal/conf/as.go, line 188 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBeqS9kEkh0cBKjQScc:-LBeqS9kEkh0cBKjQScd:b-bitg5p) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/conf/as.go#L188)):*
> ```Go
> 	}
> 	if int64(c.Validity) == 0 {
> 		return common.NewBasicError(ErrInvalidValidityDuration, nil, "duration", c.Validity)
> ```

This shouldn't be the same error, since this means that the validity wasn't set in the config.

---

*[go/tools/scion-pki/internal/conf/as_test.go, line 60 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBeqjSe-_AE-76ugxLW:-LBeqjSe-_AE-76ugxLX:b-3bc0b3) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/conf/as_test.go#L60)):*
> ```Go
> 			},
> 			{
> 				scenario: "With empty BaseCert inside AS Cert",
> ```

Remove this test.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 31 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBemh0-4KuNPo6x9213:-LBemh0-4KuNPo6x9214:btgdhp1) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L31)):*
> ```Go
> 
> const (
> 	ISD = "ISD1"
> ```

Define this as `ISD = addr.ISD(1)` and use it everywhere.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBenKqjCX7EtIhdKOsD:-LBenKqjCX7EtIhdKOsE:bj6xsec) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L34)):*
> ```Go
> )
> 
> var ases = []string{"ASff00_0_10", "ASff00_0_11", "ASff00_0_20",
> ```

Define this as `[]addr.AS{as.addrFromString(...), as.addrFromString(...),... }` then you are flexible in how you are using the elements during the test.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 115 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBemRI4BscDQNn2BXsk:-LBemRI4BscDQNn2BXsl:b718rze) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L115)):*
> ```Go
> 				selector: "1-ff00:0:10",
> 				isdAsMap: map[addr.ISD][]addr.IA{
> 					addr.ISD(1): getIAFromASes(addr.ISD(1), []string{ases[0]}),
> ```

You can just use `ases[:1]` here.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/conf/as.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBepe3m04Jn56BSTIO3:-LBfZZA79KWC19H5tr3S:b-6gba79) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/conf/as.go#L138)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just do `panic("ac.BaseCert is nil")` and remove the error string.

---

*[go/tools/scion-pki/internal/conf/as.go, line 36 at r3](https://reviewable.io/reviews/scionproto/scion/1542#-LBfZp5A1RDp_2IUK3eb:-LBfZp5A1RDp_2IUK3ec:b8v7pu8) ([raw file](https://github.com/scionproto/scion/blob/950ac9013450b76f70e0524dbf33a92777ef0ec2/go/tools/scion-pki/internal/conf/as.go#L36)):*
> ```Go
> 	AsSectionName              = "AS Certificate"
> 	IssuerSectionName          = "Issuer Certificate"
> 	ErrAsCertMissing           = "AS Certificate section missing"
> ```

Please put all errors in a separate `const` block and sort them alphabetically (by variable name).

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBenKqjCX7EtIhdKOsD:-LBf_0DS1gEzx2xSLhdH:bwckuhl) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L34)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Put each of them on a separate line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by jinankjain** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/tools/scion-pki/internal/conf/as.go, line 138 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBepe3m04Jn56BSTIO3:-LBqEbjo9MW3I4Q-fstx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/conf/as.go#L138)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Just do `panic("ac.BaseCert is nil")` and remove the error string.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/conf/as.go, line 36 at r3](https://reviewable.io/reviews/scionproto/scion/1542#-LBfZp5A1RDp_2IUK3eb:-LBqEaGL3qJ5LhvotZid:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/950ac9013450b76f70e0524dbf33a92777ef0ec2/go/tools/scion-pki/internal/conf/as.go#L36)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Please put all errors in a separate `const` block and sort them alphabetically (by variable name).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/scion-pki/internal/conf/as_test.go, line 53 at r4](https://reviewable.io/reviews/scionproto/scion/1542#-LBtPopR92WM2DoWVsxo:-LBtPopR92WM2DoWVsxp:b-ughh5m) ([raw file](https://github.com/scionproto/scion/blob/ca02dad9fc8a450b721400966b981faa085798af/go/tools/scion-pki/internal/conf/as_test.go#L53)):*
> ```Go
> 				as: &As{
> 					AsCert: &AsCert{
> 						Issuer:   "0-0",
> ```

The problem I have with these test is that they assume a certain order of the validation checks. If a programmer would change the order, but leave the semantics of the `validate` the same, these unit tests might fail, which is not optimal. You should always use a valid `AsCert` object with the exception of the one violation that you want to test for. The same applies to the `isd.ini` tests.

---

*[go/tools/scion-pki/internal/conf/isd_test.go, line 61 at r4](https://reviewable.io/reviews/scionproto/scion/1542#-LBtQIXu3nR7uvd9b-V1:-LBtQIXu3nR7uvd9b-V2:b-kt1azv) ([raw file](https://github.com/scionproto/scion/blob/ca02dad9fc8a450b721400966b981faa085798af/go/tools/scion-pki/internal/conf/isd_test.go#L61)):*
> ```Go
> 					CoreIAs: []addr.IA{
> 						{
> 							I: addr.ISD(0),
> ```

Use `addr.IAFromString` everywhere. Since below you are always using the same IA you can also predefine it.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBenKqjCX7EtIhdKOsD:-LBqguzN7xDaKzt9Pno3:b-f7axkq) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L34)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```
var ases = []addr.AS{
    xtest.MustParseAS(...),
    xtest.MustParseAS(...),
    ...
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by jinankjain** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/conf/isd_test.go, line 61 at r4](https://reviewable.io/reviews/scionproto/scion/1542#-LBtQIXu3nR7uvd9b-V1:-LBtcdWz0c6kdWq_bOWh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ca02dad9fc8a450b721400966b981faa085798af/go/tools/scion-pki/internal/conf/isd_test.go#L61)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Use `addr.IAFromString` everywhere. Since below you are always using the same IA you can also predefine it.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBenKqjCX7EtIhdKOsD:-LBtRmdG6ANdTn1ujlcK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L34)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

```
var ases = []addr.AS{
    xtest.MustParseAS(...),
    xtest.MustParseAS(...),
    ...
}
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by jinankjain** [comment]
Review status: 2 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/conf/as_test.go, line 53 at r4](https://reviewable.io/reviews/scionproto/scion/1542#-LBtPopR92WM2DoWVsxo:-LBtl3cfDxG49hPF3rHq:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/ca02dad9fc8a450b721400966b981faa085798af/go/tools/scion-pki/internal/conf/as_test.go#L53)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

The problem I have with these test is that they assume a certain order of the validation checks. If a programmer would change the order, but leave the semantics of the `validate` the same, these unit tests might fail, which is not optimal. You should always use a valid `AsCert` object with the exception of the one violation that you want to test for. The same applies to the `isd.ini` tests.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
Reviewed 3 of 5 files at r5.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/tools/scion-pki/internal/conf/isd.go, line 34 at r5](https://reviewable.io/reviews/scionproto/scion/1542#-LBy_MgECEPCxI5jaSCM:-LBy_MgECEPCxI5jaSCN:b-x6hpp6) ([raw file](https://github.com/scionproto/scion/blob/28bec49aa018816a8e5a545efac8035d9d36ddd3/go/tools/scion-pki/internal/conf/isd.go#L34)):*
> ```Go
> const (
> 	ErrCoreIANotSet               = "CoreIAs are not specified"
> 	ErrInvalidCoreIA              = "Invalid CoreIA"
> ```

User visible strings talk about `core ASes` not `core IAs`. Please fix here and below.

---

*[go/tools/scion-pki/internal/pkicmn/pkicmn_test.go, line 34 at r2](https://reviewable.io/reviews/scionproto/scion/1542#-LBenKqjCX7EtIhdKOsD:-LByaXpDB70iz7SfQX80:b-izmzg4) ([raw file](https://github.com/scionproto/scion/blob/d0af2bd41f33be2cfed61b36f0dbde9b334d9eed/go/tools/scion-pki/internal/pkicmn/pkicmn_test.go#L34)):*
<details><summary><i>Previously, jinankjain (Jinank Jain) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Almost ;) The closing `}` needs to go on a new line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1542#-:-LBycy7zD3dX_DDe4Z3Y:bnfp4nl)*

**Pull request merged**
