### PR TITLE
API proposal for request deduplication

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1440)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/infra/deduplicate/deduplicator.go, line 1 at r1](https://reviewable.io:443/reviews/scionproto/scion/1440#-L7PZvtsBh_XVheHlVCC:-L7PZvtsBh_XVheHlVCD:beu75yw) ([raw file](https://github.com/scionproto/scion/blob/aa23e519e399052836fe0bd9ac50824cb03abd0b/go/lib/infra/deduplicate/deduplicator.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich
> ```

The name is a bit of a mouthful, how about `dedupe`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1440)*

**Comment by scrye** [comment]
*[go/lib/infra/deduplicate/deduplicator.go, line 1 at r1](https://reviewable.io:443/reviews/scionproto/scion/1440#-L7PZvtsBh_XVheHlVCC:-L7PmW7HmmbTzcH7V8KX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/aa23e519e399052836fe0bd9ac50824cb03abd0b/go/lib/infra/deduplicate/deduplicator.go#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The name is a bit of a mouthful, how about `dedupe`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1440)*

**Comment by kormat** [comment]
Reviewed 2 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/lib/infra/dedupe/dedupe.go, line 33 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1440#-L7PnCV9-HvVX21UFJny:-L7PnCVAALrorbZOL79g:b-51sa9y) ([raw file](https://github.com/scionproto/scion/blob/cc1b43a177ddb73a527c122262d1e82dd52d2161/go/lib/infra/dedupe/dedupe.go#L33)):*
> ```Go
> // services, and the first response that we get unblocks all waiters), requests
> // can define BroadcastKeys.
> package dedupe
> ```

There's a bunch of other changes needed for the rename. Starting with `Package deduplicate implements`... :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1440)*

**Comment by scrye** [comment]
*[go/lib/infra/dedupe/dedupe.go, line 33 at r2](https://reviewable.io:443/reviews/scionproto/scion/1440#-L7PnCV9-HvVX21UFJny:-L7PpJYfy1fIcmzOXQ2_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cc1b43a177ddb73a527c122262d1e82dd52d2161/go/lib/infra/dedupe/dedupe.go#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's a bunch of other changes needed for the rename. Starting with `Package deduplicate implements`... :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1440)*

**Comment by kormat** [comment]
Reviewed 1 of 4 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[go/lib/infra/dedupe/dedupe.go, line 52 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1440#-L7Pq4KBA85kIXc5zVQt:-L7Pq4KBA85kIXc5zVQu:b-sp03i7) ([raw file](https://github.com/scionproto/scion/blob/bd6f92cd507349805115404714edbc15d7bd15f2/go/lib/infra/dedupe/dedupe.go#L52)):*
> ```Go
> 	// DedupeKey, they must have the same BroadcastKey.  BroadcastKeys allow
> 	// applications to implement anycast request/responses.  For this, define
> 	// different DedupicationKeys for the same message sent to different remote
> ```

`Dedupication` - typos foil search and replace yet again! :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1440)*

**Comment by scrye** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/infra/dedupe/dedupe.go, line 52 at r3](https://reviewable.io:443/reviews/scionproto/scion/1440#-L7Pq4KBA85kIXc5zVQt:-L7PqfRbKLuZb0IDK8Xe:b-33mfmi) ([raw file](https://github.com/scionproto/scion/blob/bd6f92cd507349805115404714edbc15d7bd15f2/go/lib/infra/dedupe/dedupe.go#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`Dedupication` - typos foil search and replace yet again! :)
</blockquote></details>

*shakes fist at past me*

Done. Hopefully there's no more tyops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1440)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r3, 1 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1440#-:-L7Pt75UCLW3TusrjG0X:bnfp4nl)*

**Pull request merged**
