### PR TITLE
doc: fixup sphinx documentation

### PR DESCRIPTION
**Pull request by FR4NK-W**
Fix sphinx build warnings
Replace wrong relative links with links to repository
Replace inexistent `txt` lexer with `text` pygments lexer
Make `outdated content` note more prominent

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3992)

### CODE REVIEW

**Review by Oncilla — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3992)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[doc/cryptography/trc-signing-ceremony-phases.rst, line 130 at r1](https://reviewable.io/reviews/scionproto/scion/3992#-MVWxzoa5KdDbfAFSdgr:-MVWxzob7PXPwu3uPd7I:bdfwtmc) ([raw file](https://github.com/scionproto/scion/blob/73497c60a6dd077b263e426fa310c6c0cd3bc1c0/doc/cryptography/trc-signing-ceremony-phases.rst#L130)):*
> ```reStructuredText
>    :start-after: LITERALINCLUDE payload_conf_sample START
>    :end-before: LITERALINCLUDE payload_conf_sample END
>    :dedent: 2
> ```

This is actually intended to over-dedent.

Is there a way to disable the warning instead?

**Review by Oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3992)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[doc/cryptography/trc-signing-ceremony-phases.rst, line 130 at r1](https://reviewable.io/reviews/scionproto/scion/3992#-MVWxzoa5KdDbfAFSdgr:-MVWzMCs2VYlXEfin6QZ:bavfg4p) ([raw file](https://github.com/scionproto/scion/blob/73497c60a6dd077b263e426fa310c6c0cd3bc1c0/doc/cryptography/trc-signing-ceremony-phases.rst#L130)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This is actually intended to over-dedent.

Is there a way to disable the warning instead?
</blockquote></details>

I.e., we do not want this to be commented out:
image

**Review by Oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3992)* status: all files reviewed, 1 unresolved discussion (waiting on @FR4NK-W)

___
*[doc/cryptography/trc-signing-ceremony-phases.rst, line 130 at r1](https://reviewable.io/reviews/scionproto/scion/3992#-MVWxzoa5KdDbfAFSdgr:-MVX-gkS8E9LfEJoz9QM:bhd8y9r) ([raw file](https://github.com/scionproto/scion/blob/73497c60a6dd077b263e426fa310c6c0cd3bc1c0/doc/cryptography/trc-signing-ceremony-phases.rst#L130)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I.e., we do not want this to be commented out:
image
</blockquote></details>

If not possible, we can change crypto_lib.sh:

```diff
diff --git a/scripts/cryptoplayground/crypto_lib.sh b/scripts/cryptoplayground/crypto_lib.sh
index 43387755..862964a1 100644
--- a/scripts/cryptoplayground/crypto_lib.sh
+++ b/scripts/cryptoplayground/crypto_lib.sh
@@ -79,26 +79,29 @@ in_docker() {
 # Config file creation
 ######################
 
-payload_conf() {
+PAYLOAD_CONF_SAMPLE=$(cat <<-END
 # LITERALINCLUDE payload_conf_sample START
-# {{.ISD}}               = 1
-# {{.Description}}       = "Test ISD"
-# {{.VotingQuorum}}      = 2
-# {{.CoreASes}}          = ["ff00:0:110", "ff00:0:111"]
-# {{.AuthoritativeASes}} = ["ff00:0:110", "ff00:0:111"]
-# {{.NotBefore}}         = 1593000000  # Seconds since UNIX Epoch
-# {{.Validity}}          = "365d"
-# {{.CertFiles}} = [
-#     "bern/sensitive-voting.crt",
-#     "bern/regular-voting.crt",
-#     "bern/cp-root.crt",
-#     "geneva/sensitive-voting.crt",
-#     "geneva/regular-voting.crt",
-#     "zürich/sensitive-voting.crt",
-#     "zürich/regular-voting.crt",
-# ]
+{{.ISD}}               = 1
+{{.Description}}       = "Test ISD"
+{{.VotingQuorum}}      = 2
+{{.CoreASes}}          = ["ff00:0:110", "ff00:0:111"]
+{{.AuthoritativeASes}} = ["ff00:0:110", "ff00:0:111"]
+{{.NotBefore}}         = 1593000000  # Seconds since UNIX Epoch
+{{.Validity}}          = "365d"
+{{.CertFiles}} = [
+    "bern/sensitive-voting.crt",
+    "bern/regular-voting.crt",
+    "bern/cp-root.crt",
+    "geneva/sensitive-voting.crt",
+    "geneva/regular-voting.crt",
+    "zürich/sensitive-voting.crt",
+    "zürich/regular-voting.crt",
+]
 # LITERALINCLUDE payload_conf_sample END
+END
+)
 
+payload_conf() {
 # LITERALINCLUDE payload_conf START
 cat << EOF > ISD-B1-S1.toml
 isd                = {{.ISD}}

```

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3992)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[doc/cryptography/trc-signing-ceremony-phases.rst, line 130 at r1](https://reviewable.io/reviews/scionproto/scion/3992#-MVWxzoa5KdDbfAFSdgr:-MVvzClmDP2LpfnGdNMU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/73497c60a6dd077b263e426fa310c6c0cd3bc1c0/doc/cryptography/trc-signing-ceremony-phases.rst#L130)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

If not possible, we can change crypto_lib.sh:

```diff
diff --git a/scripts/cryptoplayground/crypto_lib.sh b/scripts/cryptoplayground/crypto_lib.sh
index 43387755..862964a1 100644
--- a/scripts/cryptoplayground/crypto_lib.sh
+++ b/scripts/cryptoplayground/crypto_lib.sh
@@ -79,26 +79,29 @@ in_docker() {
 # Config file creation
 ######################
 
-payload_conf() {
+PAYLOAD_CONF_SAMPLE=$(cat <<-END
 # LITERALINCLUDE payload_conf_sample START
-# {{.ISD}}               = 1
-# {{.Description}}       = "Test ISD"
-# {{.VotingQuorum}}      = 2
-# {{.CoreASes}}          = ["ff00:0:110", "ff00:0:111"]
-# {{.AuthoritativeASes}} = ["ff00:0:110", "ff00:0:111"]
-# {{.NotBefore}}         = 1593000000  # Seconds since UNIX Epoch
-# {{.Validity}}          = "365d"
-# {{.CertFiles}} = [
-#     "bern/sensitive-voting.crt",
-#     "bern/regular-voting.crt",
-#     "bern/cp-root.crt",
-#     "geneva/sensitive-voting.crt",
-#     "geneva/regular-voting.crt",
-#     "zürich/sensitive-voting.crt",
-#     "zürich/regular-voting.crt",
-# ]
+{{.ISD}}               = 1
+{{.Description}}       = "Test ISD"
+{{.VotingQuorum}}      = 2
+{{.CoreASes}}          = ["ff00:0:110", "ff00:0:111"]
+{{.AuthoritativeASes}} = ["ff00:0:110", "ff00:0:111"]
+{{.NotBefore}}         = 1593000000  # Seconds since UNIX Epoch
+{{.Validity}}          = "365d"
+{{.CertFiles}} = [
+    "bern/sensitive-voting.crt",
+    "bern/regular-voting.crt",
+    "bern/cp-root.crt",
+    "geneva/sensitive-voting.crt",
+    "geneva/regular-voting.crt",
+    "zürich/sensitive-voting.crt",
+    "zürich/regular-voting.crt",
+]
 # LITERALINCLUDE payload_conf_sample END
+END
+)
 
+payload_conf() {
 # LITERALINCLUDE payload_conf START
 cat << EOF > ISD-B1-S1.toml
 isd                = {{.ISD}}

```

</blockquote></details>

Done.

**Review by Oncilla — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3992#-:-MVvzgXn8LswoMkx7NsX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FR4NK-W)

**Pull request closed without merging**
