### PR TITLE
cppki/segverifer: enforce AS certificate to cover AS entry

### LINKED ISSUE #4286: cppki: require segment lifetime fully covered by certificate chain
# Proposal

## Summary

Enforce the full lifetime of a segment/beacon is covered by the validity time of
at least one certificate chain.

### Problem

Currently, we do not enforce that the certificate chain that is used to verify a
segment is covering the full lifetime of the segment. Rather, we check that the
certificate chain is valid at verification time. This can cause issues if the
signing entity is failing to renew its certificate chains and issues segments
that with a lifetime that is not covered by any certificate chain. If the
segment life time is covered partially by a certificate chain, it can be verified
and will be inserted into segment/beacon storage. If there is a path segment request
that matches this segment, it will be part of the response. As soon as the
certificate chain expires, the segment is no longer verifiable. This causes
all future requests to fail with signature verification errors.

### How did we end up here?

Initially, there was an idea floating around that we could renew a certificate
chain for the same public key. In that world, having more lax verification rules
is nice, because the signing entity can create segments with longer lifetimes
even though its certificate chain has not been renewed yet. If the signing
entity succeeds to renew the certificate chain before the previous one expired,
the segment can be verified the whole time, without any issues.

However, this is mostly a theoretical advantage that comes with complexity
drawbacks. There are many more combinations between segment lifetime and
certificate chain validity time. The system also becomes a lot harder to reason
about. Furthermore, in practice each certificate chain authenticates a fresh
public key for better key hygiene.

## Solution

There is two sides to this problem. The signing entity and the relying party. To
make this a non-breaking change, we can start with adapting the behavior of
signing entity to ensure that no segments are created with lifetimes that are
not covered by a certificate chain. At a later stage, we can update relying
parties to not accept segments that are not covered by a certificate chain.

### Signing entity

The change to the signing entity is fairly small. When creating the hop fields
and peer fields for the AS entry, the expiration time should be chosen such that
the full lifetime is covered by the available certificate chain.

### Relying party

The change to the relying party is again fairly small. When a segment is
verified, the relying party additionally checks that the lifetime is fully
covered by the validity of the certificate chain. In theory, this is a breaking
change. However, in practice, segments that will be rejected by this change only
stem from cases where the certificate renewal fails.

## Alternatives

As an alternative, we could change the segment lookup and beaconing behavior to
filter out segments that can not be verified at the current time. This would
limit the effects of a missing certificate chain for a segment to one entity.

(Side-note: This check would be good even if we go with the proposal.)

However, this is not enough to behave correctly. Entities need to proactively
fetch certificate chains to fill in the gaps, as they might not learn the new
certificate chains passively. This is a lot of additional complexity that is
currently not implemented and will be hard to get right. It is also hard to
justify this additional complexity if in practice that feature will never be
used due to the rotated private keys on every certificate.

### PR DESCRIPTION
**Pull request by shitz**
When verifying an AS entry the verifier will now only use an AS certificate that is valid until the expiration of the AS entry. Before, the verifier would use any certificate that was valid at the time of verification but not necessarily for the entire validity of the AS entry, i.e., the hop field expiration contained in the entry.
The verifier now requests certificates that cover at least the entire validity period of the AS entry. To that end, the `ChainsRequest.date` field has been renamed to `ChainsRequest.at_least_valid_until` and a new `ChainsRequest.at_least_valid_since` field has been introduced.
Legacy clients of the API will only set the `at_least_valid_until` field (for them it's still the `date` field, but the name of the field does not matter for protobuf wire enconding). New servers will simply set `at_least_valid_since` to be equal to `at_least_valid_until` to keep the same semantics.
Legacy servers will ignore the `at_least_valid_since` field, since they don't know about it. 
This only enforces that the AS certificate is still valid at the AS entry expiration, but not that it was also valid at the start of the hop field validity. Once all trust material servers and clients have been upgraded we automatically have the desired behavior.

Fixes #4286

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)

**Review by matzf — COMMENTED** [review]
> Reviewed 9 of 22 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: 12 of 25 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @oncilla, and @shitz)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-Ntp93Xv67xI1IEfsGzQ:b-y7b9he) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
> ```proto
>     // be alternatively used to the date field. If both are set, the validity
>     // takes precedence.
>     Validity validity = 4;
> ```

Have considered this alternative approach?
Instead of keeping the "old" `date` _and_ the new `not_before`/`not_after`, we could _rename_ `date` to `not_after`. The semantics for requests to legacy servers would be identical to what is now implemented explicitly (by setting date = not_after in the request). To handle legacy clients, we can say that  if either `not_before` or `not_after` is missing, it is assumed to be identical to the other field.

The advantage would be that we won't have to revisit this later to clean up old behavior. I admit it's also slightly more obscure.



_Suggestion:_
```proto
    // Point in time that must be covered by the AS certificate's validity
    // period. In seconds since UNIX epoch.
    google.protobuf.Timestamp not_after = 3;
    google.protobuf.Timestamp not_before = 4;
```

**Review by shitz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: 12 of 25 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-NtuB5lH7iP_GaJs-FKy:b-4lcqm4) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Have considered this alternative approach?
Instead of keeping the "old" `date` _and_ the new `not_before`/`not_after`, we could _rename_ `date` to `not_after`. The semantics for requests to legacy servers would be identical to what is now implemented explicitly (by setting date = not_after in the request). To handle legacy clients, we can say that  if either `not_before` or `not_after` is missing, it is assumed to be identical to the other field.

The advantage would be that we won't have to revisit this later to clean up old behavior. I admit it's also slightly more obscure.
</blockquote></details>

Yeah that would work I guess, although I'm not sure how common it is to rename a protobuf field eventhough it does not affect the wireformat in any way. I don't have a strong preference.
Maybe @lukedirtwalker or @oncilla have something to say on this?

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 21 of 22 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-Ntua30fCz829RVM-hWl:bv0byxz) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Yeah that would work I guess, although I'm not sure how common it is to rename a protobuf field eventhough it does not affect the wireformat in any way. I don't have a strong preference.
Maybe @lukedirtwalker or @oncilla have something to say on this?
</blockquote></details>

I like the proposal, it also reduces the state space a bit, i.e. you can't have a state where both validity and date is set at the same time. Additionally, I like that the migration plan is easier, no need to deprecate a field. So overall I think there are more reasons for it, than against.

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-Ntvmi1O1KcocqHkZL2s:b2nhrg9) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

I like the proposal, it also reduces the state space a bit, i.e. you can't have a state where both validity and date is set at the same time. Additionally, I like that the migration plan is easier, no need to deprecate a field. So overall I think there are more reasons for it, than against.
</blockquote></details>

Wfm

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @shitz)

___
*[`proto/control_plane/v1/cppki.proto` line 46 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntvmr-rAABMx3F_eydK:-Ntvmr-rAABMx3F_eydL:bm3tal4) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L46)):*
> ```proto
> message Validity {
>     // NotBefore time of the certificate. In seconds since UNIX epoch.
>     google.protobuf.Timestamp not_before = 1;
> ```

Naming and comment are a bit misleading.

We are looking for certificates that contain the start and end time, not for certificates with exactly that not_before and not_after times

**Review by shitz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: 14 of 35 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-Nu0rkxN-sPkmz4Ihi64:boj4qc7) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Wfm
</blockquote></details>

Done.

I chose the names `AtLeastValidUntil` and `AtLeastValidSince` to better reflect the semantics of the fields. Open for better suggestions.
___
*[`proto/control_plane/v1/cppki.proto` line 46 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntvmr-rAABMx3F_eydK:-Nu0rzI53VTkfQPn04C0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L46)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Naming and comment are a bit misleading.

We are looking for certificates that contain the start and end time, not for certificates with exactly that not_before and not_after times
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
> Reviewed 4 of 22 files at r1, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by oncilla — APPROVED** [review]
> Reviewed 11 of 22 files at r1, 3 of 4 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4492)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @shitz)

___
*[`proto/control_plane/v1/cppki.proto` line 41 at r2](https://reviewable.io/reviews/scionproto/scion/4492#-Ntp93Xv67xI1IEfsGzP:-Nu4XLF34WZ8w0B4WQPn:b-6ew71a) ([raw file](https://github.com/scionproto/scion/blob/076abf8ae10c2e96d282a2ae07ff5f08e0209e8d/proto/control_plane/v1/cppki.proto#L41)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

Done.

I chose the names `AtLeastValidUntil` and `AtLeastValidSince` to better reflect the semantics of the fields. Open for better suggestions.
</blockquote></details>

very explicit, wfm :)

**Pull request merged**
