### PR TITLE
dep: update golang.org/x/net dependency

### PR DESCRIPTION
**Pull request by matzf**
Update `golang.org/x/net` dependency to latest master version. This includes https://github.com/golang/net/commit/f8dd838d8c7de318b0734b3f1afa78a9d976bf09 (and the subsequent fix up https://github.com/golang/net/commit/0287a6fb4125c2b83c66560a2677a4ee69a13903) which patches the allocations of temporary buffers in `ReadBatch`, which is used by the router.

This now requires a newer version of `golang.org/x/sys` than what is provided by default by `go_rules_dependencies`. Thus, override the version as suggested in the rules_go documentation.

Run `go mod tidy`

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4034)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4034)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[go.mod, line 50 at r1](https://reviewable.io/reviews/scionproto/scion/4034#-MZwUIGDDwiA1jp-HmSp:-MZwUIGDDwiA1jp-HmSq:b-ag7f4x) ([raw file](https://github.com/scionproto/scion/blob/dd6626752324e99d869f01b2c928f98a656024bd/go.mod#L50)):*
> ```XML
> 	golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
> 	golang.org/x/sync v0.0.0-20201020160332-67f06af15bc9
> 	golang.org/x/sys v0.0.0-20210309074719-68d13333faf2 // indirect
> ```

why is that removed?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4034)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[go.mod, line 50 at r1](https://reviewable.io/reviews/scionproto/scion/4034#-MZwUIGDDwiA1jp-HmSp:-MZwXabhC3DNsLbO9pc5:b-nzab6h) ([raw file](https://github.com/scionproto/scion/blob/dd6626752324e99d869f01b2c928f98a656024bd/go.mod#L50)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

why is that removed?
</blockquote></details>

`go mod tidy` removed it. If I understand correctly, the `// indirect` line was there to get a newer version of x/sys than what the old x/net (or any of the other dependencies) had declared in its module file. The latest x/net version depends on a later version than what was explicitly requested with this directive here, so it's no longer effective and it was thus removed.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4034)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[go.mod, line 50 at r1](https://reviewable.io/reviews/scionproto/scion/4034#-MZwUIGDDwiA1jp-HmSp:-MZwaG359Zom2nJUL-Z8:bl16moy) ([raw file](https://github.com/scionproto/scion/blob/dd6626752324e99d869f01b2c928f98a656024bd/go.mod#L50)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`go mod tidy` removed it. If I understand correctly, the `// indirect` line was there to get a newer version of x/sys than what the old x/net (or any of the other dependencies) had declared in its module file. The latest x/net version depends on a later version than what was explicitly requested with this directive here, so it's no longer effective and it was thus removed.
</blockquote></details>

In fact, even `go build` doesn't even allow the line to be there: if I add it back, it complains:

```
go: updates to go.mod needed; to update it:
        go mod tidy
```

**Review by lukedirtwalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request closed without merging**
