### PR TITLE
Add advanced path filtering support to pathmgr

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1472)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 6 of 20 files at r1.
Review status: 3 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9AmZ0f3oIrKEjiAjjd:b-narx1f) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // Package path implements basic types for working with SCIOND paths.
> ```

That's a _very_ generic name. We'd now have `go/lib/{path,pathdb,pathmgr,spath}`. This is also not actually specific to sciond, either. Once we have path combinator, that's perfectly capable of generating these kinds of paths, independently of sciond (at which point the types should stop being under `go/lib/sciond`, too). I'm thinking the best fit might be to actually put this under spath, e.g. `go/lib/spath/spathmeta`, and use spath.Path as the underlying form of the raw path.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9B9dzKCm55L5_Wcy_v:byp4ku2) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
Moving it to `go/lib/spath/spathmeta` sounds good (even though _spathmeta_ is an awesome name for a drug).

> and use spath.Path as the underlying form of the raw path.

As the underlying form where?  Currently `AppPath` uses sciond-style paths because code filters based on the list of interfaces; if we only have the raw path this becomes impossible.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9BAjvmEUdeqNOd_SJ1:bza8w24) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

Moving it to `go/lib/spath/spathmeta` sounds good (even though _spathmeta_ is an awesome name for a drug).

> and use spath.Path as the underlying form of the raw path.

As the underlying form where?  Currently `AppPath` uses sciond-style paths because code filters based on the list of interfaces; if we only have the raw path this becomes impossible.
</blockquote></details>

I'm talking about the _raw_ path, which AppPath/PathPred etc never process. You'd have something like:
```
type SPMeta struct {
  Path spath.Path
  Mtu uint16
  Interfaces []PathInterfaces
  NextHop NextHop
}
```
We'd then change sciond to actually demarshal the capnp into that, and use it everywhere.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
Review status: 3 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9BRLqS2tLBDgLa_MHH:b-3r29n3) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm talking about the _raw_ path, which AppPath/PathPred etc never process. You'd have something like:
```
type SPMeta struct {
  Path spath.Path
  Mtu uint16
  Interfaces []PathInterfaces
  NextHop NextHop
}
```
We'd then change sciond to actually demarshal the capnp into that, and use it everywhere.
</blockquote></details>

This creates a circular dependency. `spathmeta` needs to import `sciond` to see `PathInterface`, while `sciond` needs to import `spathmeta` to see `SPMeta`.

`sciond.PathReplyEntry` has the same contents as the `SPMeta` above, with the exception of the unparsed `spath.Path`, but most apps probably won't care about it and just opt to use the raw version. Does changing it to `spath.Path` benefit the code base that much?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9ErlHe5xLUYiPWnLtX:b-qquze) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

This creates a circular dependency. `spathmeta` needs to import `sciond` to see `PathInterface`, while `sciond` needs to import `spathmeta` to see `SPMeta`.

`sciond.PathReplyEntry` has the same contents as the `SPMeta` above, with the exception of the unparsed `spath.Path`, but most apps probably won't care about it and just opt to use the raw version. Does changing it to `spath.Path` benefit the code base that much?
</blockquote></details>

The example had `[]PathInterfaces`, not `[]sciond.PathInterfaces`, the inference being that `PathInterfaces` is also moved to `spathmeta`.

I want to move away from the assumption that these are _`sciond`_ types, and that they have to have the same "shape" as the sciond capnp protocol. E.g. `SPMeta` is flatter than `PathReplyEntry`, on purpose.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9GLSuc3EZ7opRYxG52:b-5rh94b) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The example had `[]PathInterfaces`, not `[]sciond.PathInterfaces`, the inference being that `PathInterfaces` is also moved to `spathmeta`.

I want to move away from the assumption that these are _`sciond`_ types, and that they have to have the same "shape" as the sciond capnp protocol. E.g. `SPMeta` is flatter than `PathReplyEntry`, on purpose.
</blockquote></details>

As discussed on live, we'll keep the sciond types hidden away somehow (unexported types, internal package, different package under sciond) to allow for serialization/deserialization using reflection, while exposing cleaner versions for programmers to use.

Since it's now a large-ish change that has nothing to do with path filtering, we'll add that in a different PR.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/path/apppath.go, line 15 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9AmZ0f3oIrKEjiAjjc:-L9GOHYD68zsJEPFntZU:b-85i63v) ([raw file](https://github.com/scionproto/scion/blob/ddda8d59474793978d33d4c40e4a8d6eb20a47b7/go/lib/path/apppath.go#L15)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

As discussed on live, we'll keep the sciond types hidden away somehow (unexported types, internal package, different package under sciond) to allow for serialization/deserialization using reflection, while exposing cleaner versions for programmers to use.

Since it's now a large-ish change that has nothing to do with path filtering, we'll add that in a different PR.
</blockquote></details>

LGTM.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Reviewed 4 of 20 files at r1, 15 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/pathmgr/pathmgr_test.go, line 38 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9LQPvcCHhwiJdtynJA:-L9LQPvcCHhwiJdtynJB:b-7sebc2) ([raw file](https://github.com/scionproto/scion/blob/41a262d8f5df0a47f03bc20290d04b026ae6dc67/go/lib/pathmgr/pathmgr_test.go#L38)):*
> ```Go
> 		g := graph.NewDefaultGraph()
> 		pm := NewPR(t, g, 250, 250, 100)
> 		srcIA := addr.IA{I: 1, A: 10}
> ```

Oh dear. I'm working on a huge pr that changes all these values. We'll need to talk :)

---

*[go/lib/pktcls/doc.go, line 33 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9LPtdU88JZmnj2UogJ:-L9LPtdU88JZmnj2UogK:beznuhq) ([raw file](https://github.com/scionproto/scion/blob/41a262d8f5df0a47f03bc20290d04b026ae6dc67/go/lib/pktcls/doc.go#L33)):*
> ```Go
> // Actions are marshalable objects that describe a process. Currently, the only
> // supported actions are Path Filters (ActionFilterPaths), which are containers
> // for a path.PathPredicate object.
> ```

`spathmeta`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
:stop_sign:  PR stalled until AS numbers are finalized.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472#-:-LAO1aaBCQk_vIYAFGH_:bhwazfw)*

**Comment by scrye** [comment]
Review status: 12 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/pathmgr/pathmgr_test.go, line 38 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9LQPvcCHhwiJdtynJA:-LAY4GRj4NSmtX5-jBEn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/41a262d8f5df0a47f03bc20290d04b026ae6dc67/go/lib/pathmgr/pathmgr_test.go#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Oh dear. I'm working on a huge pr that changes all these values. We'll need to talk :)
</blockquote></details>

Done.

---

*[go/lib/pktcls/doc.go, line 33 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1472#-L9LPtdU88JZmnj2UogJ:-LAY4G5O2gzXYsbxblXQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/41a262d8f5df0a47f03bc20290d04b026ae6dc67/go/lib/pktcls/doc.go#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`spathmeta`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Reviewed 2 of 20 files at r1, 5 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/pathmgr/pathmgr_test.go, line 162 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYKua87UfQWdHyFLIY:-LAYKua87UfQWdHyFLIZ:bwo9o5w) ([raw file](https://github.com/scionproto/scion/blob/7280cacd252aa41b73fb28eb7118a2354826df10/go/lib/pathmgr/pathmgr_test.go#L162)):*
> ```Go
> 		pp, err := spathmeta.NewPathPredicate("1-ff00:0:121#121122")
> 		xtest.FailOnErr(t, err)
> 		filter := pktcls.NewActionFilterPaths("test-1-15#1518", pktcls.NewCondPathPredicate(pp))
> ```

`1-15` missed there.

---

*[go/lib/pathmgr/pathmgr_test.go, line 249 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYLKTICGNT3hMtIqty:-LAYLKTICGNT3hMtIqtz:b-719dud) ([raw file](https://github.com/scionproto/scion/blob/7280cacd252aa41b73fb28eb7118a2354826df10/go/lib/pathmgr/pathmgr_test.go#L249)):*
> ```Go
> }
> 
> func MustParseIA(ia string) addr.IA {
> ```

This looks a prime candidate for `xtest/helpers`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/lib/xtest/helpers.go, line 132 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYRcjZ2tYoxXNT7gRf:-LAYRcjZ2tYoxXNT7gRg:b-z2qthq) ([raw file](https://github.com/scionproto/scion/blob/8fb48736cea20ffab1020ea05982a3ab83f18ce6/go/lib/xtest/helpers.go#L132)):*
> ```Go
> }
> 
> // MuastParseIA parses ia and returns the corresponding addr.IA object. It
> ```

"MustParseIA" :)

---

*[go/lib/xtest/helpers.go, line 134 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYRi253FWBGK9M4VnF:-LAYRi253FWBGK9M4VnG:b-axf9y6) ([raw file](https://github.com/scionproto/scion/blob/8fb48736cea20ffab1020ea05982a3ab83f18ce6/go/lib/xtest/helpers.go#L134)):*
> ```Go
> // MuastParseIA parses ia and returns the corresponding addr.IA object. It
> // panics if ia is not a valid ISD-AS representation.
> func MustParseIA(ia string) addr.IA {
> ```

I'd just call the var `s`, that way you can more naturally call the IA object `ia`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/xtest/helpers.go, line 132 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYRcjZ2tYoxXNT7gRf:-LAYSCUQEKZUmjaa6eho:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8fb48736cea20ffab1020ea05982a3ab83f18ce6/go/lib/xtest/helpers.go#L132)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"MustParseIA" :)
</blockquote></details>

Done.

---

*[go/lib/xtest/helpers.go, line 134 at r4](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYRi253FWBGK9M4VnF:-LAYSCK005HEdhUkD6sM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8fb48736cea20ffab1020ea05982a3ab83f18ce6/go/lib/xtest/helpers.go#L134)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'd just call the var `s`, that way you can more naturally call the IA object `ia`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/lib/xtest/helpers.go, line 132 at r5](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYSeSn5P3TPUzuh3qr:-LAYSeSn5P3TPUzuh3qs:bv6agbh) ([raw file](https://github.com/scionproto/scion/blob/03bc65190efee6202e4bf0b0c6b8d29d3f6a688b/go/lib/xtest/helpers.go#L132)):*
> ```Go
> }
> 
> // MustParseIA parses ia and returns the corresponding addr.IA object. It
> ```

"parses s" :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by scrye** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/xtest/helpers.go, line 132 at r5](https://beta.reviewable.io/reviews/scionproto/scion/1472#-LAYSeSn5P3TPUzuh3qr:-LAYU8cS56_kv5b3TPLv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/03bc65190efee6202e4bf0b0c6b8d29d3f6a688b/go/lib/xtest/helpers.go#L132)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"parses s" :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1472#-:-LAYUJ2xE8-IdNkJ1ZiI:bnfp4nl)*

**Pull request merged**
