### PR TITLE
Add sign/verify capability to CSGO

### PR DESCRIPTION
**Pull request by Oncilla**
Enables the go certificate server to create and verify signed payloads.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1431)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/cert_srv/main.go, line 85 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lZzZBDniFdF5Maxsu:-L8lZzZBDniFdF5Maxsv:b-s7jb9v) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/main.go#L85)):*
> ```Go
> 	}
> 	config.SetSigner(ctrl.NewBasicSigner(sign, config.GetSigningKey()))
> 	config.SetVerifier(&SigVerifier{})
> ```

This type has an embedded pointer. Not initializing that is _usually_ asking for a panic.

---

*[go/cert_srv/signed_util.go, line 71 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lXxQI2jfUvZdY4Tto:-L8lXxQI2jfUvZdY4Ttp:b-ukmtbd) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L71)):*
> ```Go
> 		return nil
> 	}
> 	diff := time.Now().Sub(time.Unix(int64(p.Sign.Timestamp), 0))
> ```

Add a method to `proto.SignS` to return the timestamp as a `time.Time`. You can also use `time.Since`, so you'd end up with: `diff := time.Since(p.Sign.Time())`, which is a lot nicer to read.

On the same note, it would be good to change `util.TimetoString` to take a `time.Time`, and add helper methods to allow easy conversion to `time.Time` for things like certs and trcs.

---

*[go/cert_srv/signed_util.go, line 74 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lYn3bCdK0Y0HSJqTj:-L8lYn3bCdK0Y0HSJqTk:b2jqte3) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L74)):*
> ```Go
> 	if diff < 0 {
> 		return common.NewBasicError("Invalid timestamp. Signed before current time", nil, "ts",
> 			util.TimeToString(p.Sign.Timestamp), "now", util.TimeToString(uint64(time.Now().Unix())))
> ```

Line length. 

Also, it's important to use the same timestamp for the error messages as was used for the check. It prevents confusion in corner-cases. So, adjusting what i said above, you'd do:

```
now := time.Now()
tstamp : = p.Sign.Time()
diff := now.Sub(tstamp)
if diff < 0 {
   ... "ts", util.TimeToString(tstamp, "now", util.TimeToString(now))
}
...
```

---

*[go/cert_srv/signed_util.go, line 95 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lZeKsEVJRNMnvwowZ:-L8lZeKsEVJRNMnvwow_:bt8uf3p) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L95)):*
> ```Go
> 	u1, _ := outer.Union()
> 	switch u1.(type) {
> 	case *cert_mgmt.Chain, *cert_mgmt.TRC, *cert_mgmt.ChainIssRep:
> ```

Why is `ChainIssRep` included?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1431)*

**Comment by Oncilla** [comment]
Review status: 1 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/cert_srv/main.go, line 85 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lZzZBDniFdF5Maxsu:-L8lr8R9BTbNs7HoA--C:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/main.go#L85)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This type has an embedded pointer. Not initializing that is _usually_ asking for a panic.
</blockquote></details>

Done.

---

*[go/cert_srv/signed_util.go, line 71 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lXxQI2jfUvZdY4Tto:-L8lue8I4lpLYJxLQFCk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L71)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add a method to `proto.SignS` to return the timestamp as a `time.Time`. You can also use `time.Since`, so you'd end up with: `diff := time.Since(p.Sign.Time())`, which is a lot nicer to read.

On the same note, it would be good to change `util.TimetoString` to take a `time.Time`, and add helper methods to allow easy conversion to `time.Time` for things like certs and trcs.
</blockquote></details>

Done.

---

*[go/cert_srv/signed_util.go, line 74 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lYn3bCdK0Y0HSJqTj:-L8lumLSAeGEBePjQFcq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L74)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length. 

Also, it's important to use the same timestamp for the error messages as was used for the check. It prevents confusion in corner-cases. So, adjusting what i said above, you'd do:

```
now := time.Now()
tstamp : = p.Sign.Time()
diff := now.Sub(tstamp)
if diff < 0 {
   ... "ts", util.TimeToString(tstamp, "now", util.TimeToString(now))
}
...
```
</blockquote></details>

Done.

---

*[go/cert_srv/signed_util.go, line 95 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L8lZeKsEVJRNMnvwowZ:-L8lunKB7GXoTXYB2fl_:bxh6maw) ([raw file](https://github.com/scionproto/scion/blob/478f22f77bf7dd9c03a13d3f28e4cc21e70126e3/go/cert_srv/signed_util.go#L95)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Why is `ChainIssRep` included?
</blockquote></details>

Because the trust store does not yet look up missing certificates. 
It could be the case that the issuer and the local AS both update their leaf certificate at the same time.
Added fix me.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1431)*

**Comment by kormat** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/cert_srv/signed_util.go, line 75 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3Sva25Sc5LjQIcB1:-L9A3Sva25Sc5LjQIcB2:b2osvgx) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/cert_srv/signed_util.go#L75)):*
> ```Go
> 	diff := now.Sub(ts)
> 	if diff < 0 {
> 		return common.NewBasicError("Invalid timestamp. Signed before current time", nil,
> ```

I think the logic is reversed - "Signature from future".

---

*[go/cert_srv/signed_util.go, line 80 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3pcUDlwjOcSaz4_q:-L9A3pcUDlwjOcSaz4_r:b-7zp6mb) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/cert_srv/signed_util.go#L80)):*
> ```Go
> 	if diff > SignatureValidity {
> 		return common.NewBasicError("Invalid timestamp. Signature expired", nil,
> 			"ts", util.TimeToString(ts), "now", util.TimeToString(now))
> ```

This should include the signature validity.

---

*[go/lib/util/time.go, line 23 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A2kLoD62nR3DIGvtX:-L9A2kLoD62nR3DIGvtY:b-iapyvm) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/lib/util/time.go#L23)):*
> ```Go
> )
> 
> func Uint64ToTime(t uint64) time.Time {
> ```

This should document that it's uint64 _seconds_. Perhaps `USecsToTime` and `SecsToTime` would be cleaener.

---

*[go/proto/sign.go, line 74 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A38KB0HWlaNKL7pj4:-L9A38KB0HWlaNKL7pj5:bnd940k) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/proto/sign.go#L74)):*
> ```Go
> func (s *SignS) Time() time.Time {
> 	if s != nil {
> 		return time.Unix(int64(s.Timestamp), 0)
> ```

`return util.SecsToTime(s.Timestamp)`?

---

*[go/proto/sign.go, line 104 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3Djh6DyIxPcBeeNf:-L9A3Djh6DyIxPcBeeNg:bj8gwn2) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/proto/sign.go#L104)):*
> ```Go
> func (s *SignS) String() string {
> 	return fmt.Sprintf("SignType: %s Timestamp: %s SignSrc: %s Signature: %s", s.Type,
> 		util.TimeToString(util.Uint64ToTime(s.Timestamp)), s.Src, s.Signature)
> ```

`util.TimeToString(s.Time())`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1431)*

**Comment by Oncilla** [comment]
Review status: 3 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/cert_srv/signed_util.go, line 75 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3Sva25Sc5LjQIcB1:-L9dr8PgD8RpRu3imkh0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/cert_srv/signed_util.go#L75)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think the logic is reversed - "Signature from future".
</blockquote></details>

Done.

---

*[go/cert_srv/signed_util.go, line 80 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3pcUDlwjOcSaz4_q:-L9drxo90g1nI4rtKVlR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/cert_srv/signed_util.go#L80)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should include the signature validity.
</blockquote></details>

Done.

---

*[go/lib/util/time.go, line 23 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A2kLoD62nR3DIGvtX:-L9ds_CvB0mHhaS4xJHm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/lib/util/time.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should document that it's uint64 _seconds_. Perhaps `USecsToTime` and `SecsToTime` would be cleaener.
</blockquote></details>

Done.

---

*[go/proto/sign.go, line 74 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A38KB0HWlaNKL7pj4:-L9dswka3HsbXo1VPZ8l:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/proto/sign.go#L74)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`return util.SecsToTime(s.Timestamp)`?
</blockquote></details>

Done.

---

*[go/proto/sign.go, line 104 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1431#-L9A3Djh6DyIxPcBeeNf:-L9dt3tG8BA5tRbkputb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/eaf5b79d835063051dd4a48b1bc237cef73e7300/go/proto/sign.go#L104)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`util.TimeToString(s.Time())`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1431)*

**Pull request merged**
