### PR TITLE
lib/pathpol: drop PathSet, use slices instead 

### PR DESCRIPTION
**Pull request by matzf**
In `pathpol.Filter`, use `[]snet.Path` slices instead of a `map[snet.PathFingerprint]snet.Path`.
This simplifies (most) callers; in the pathmgr/snetmigrate, the sets
are still used and are just created later, so no big win here.
Nevertheless the normal use case (e.g. in app/helper.go) becomes a bit simpler.

Note that internally, the pathpol still needs to use a set with path
fingerprints to compute the set union of the sub policy options.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3926)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3926)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[go/lib/pathpol/policy.go, line 65 at r1](https://reviewable.io/reviews/scionproto/scion/3926#-MLNtJNb3L2VuRAU4cv9:-MLNtJNb3L2VuRAU4cvA:bhe4ulb) ([raw file](https://github.com/scionproto/scion/blob/d9fe2818adf2b9c7582a856188bed93bf918dcbe/go/lib/pathpol/policy.go#L65)):*
> ```
> set
> ```
`paths` or `path list`
___
*[go/pkg/app/helper.go, line 60 at r1](https://reviewable.io/reviews/scionproto/scion/3926#-MLNsxGKE58oSmZVZ6zL:-MLNsxGL8Dl9ZkX_dnwN:b-bgrwzc) ([raw file](https://github.com/scionproto/scion/blob/d9fe2818adf2b9c7582a856188bed93bf918dcbe/go/pkg/app/helper.go#L60)):*
> ```Go
> 		return nil, err
> 	}
> 	ret := s.Eval(paths)
> ```

just `return s.Eval(paths),nil` directly

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3926)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[go/lib/pathpol/policy.go, line 65 at r1](https://reviewable.io/reviews/scionproto/scion/3926#-MLNtJNb3L2VuRAU4cv9:-MLNwnZREbprk6nSUcd8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d9fe2818adf2b9c7582a856188bed93bf918dcbe/go/lib/pathpol/policy.go#L65)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> set
> ```
`paths` or `path list`
</blockquote></details>

Done.
___
*[go/pkg/app/helper.go, line 60 at r1](https://reviewable.io/reviews/scionproto/scion/3926#-MLNsxGKE58oSmZVZ6zL:-MLNx1R78AktZvbyA7t-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d9fe2818adf2b9c7582a856188bed93bf918dcbe/go/pkg/app/helper.go#L60)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

just `return s.Eval(paths),nil` directly
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3926)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
