### PR TITLE
daemon/combinator: memoize calculated fingerprints (IDs)

### PR DESCRIPTION
**Pull request by lukedirtwalker**
A profile shows that ID calculation is a big part of the CPU time of the daemon:
image

Therefore this change memoizes IDs where possible.
Also re-use buffer for fingerprint calculation.
Use slices package for sorting in the combinator.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: all files reviewed, 3 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m2hqHEmXIvVZ4NK13):*
s/cominator/combinator
___
*[`private/path/combinator/combinator.go` line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m46DlAMBaLaZICFQ6:-O5m46DlAMBaLaZICFQ7:bcwe5a7) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L140)):*
> ```Go
> // take []snet.PathInterface directly.
> func fingerprint(interfaces []snet.PathInterface, sumBuf []byte) snet.PathFingerprint {
> 	h := sha256.New()
> ```

suggestion: You could save another couple of allocation by reusing the same hash.Hash 

You could bundle the sum buffer and hash.Hash together in one struct for easy passing around
___
*[`private/path/combinator/combinator.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m4O6h6BI3MncdstkP:-O5m4O6h6BI3MncdstkQ:bcbtiy0) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L149)):*
> ```Go
> 		}
> 	}
> 	return snet.PathFingerprint(h.Sum(sumBuf[:0]))
> ```

Add a comment that this is safe because snet.PathFingerprint is underlying type string.

Also, maybe it is worth to create a compiler check that enforces this. If someone changes it to byte slice -> this will go pufff.

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @oncilla)

___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m2hqHEmXIvVZ4NK13):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

s/cominator/combinator
</blockquote></details>

Done.
___
*[`private/path/combinator/combinator.go` line 140 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m46DlAMBaLaZICFQ6:-O5m7RO_3yG4AJF91SHO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L140)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

suggestion: You could save another couple of allocation by reusing the same hash.Hash 

You could bundle the sum buffer and hash.Hash together in one struct for easy passing around
</blockquote></details>

Done.
___
*[`private/path/combinator/combinator.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m4O6h6BI3MncdstkP:-O5m7gty408iRDfUuXHG:b-xwtjq7) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L149)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Add a comment that this is safe because snet.PathFingerprint is underlying type string.

Also, maybe it is worth to create a compiler check that enforces this. If someone changes it to byte slice -> this will go pufff.
</blockquote></details>

Done.

Added the comment, Don't know how to add the check.

**Review by jiceatscion — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: all files reviewed, 2 unresolved discussions (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`private/path/combinator/combinator.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m4O6h6BI3MncdstkP:-O5mfwsZAEQeTvH84mjw:b-vymwhz) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L149)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Done.

Added the comment, Don't know how to add the check.
</blockquote></details>

```

// This check ensures that the underlying type of the PathFingerprint
// is string. This is required to create a copy of the buffer. If it were
// to be moved to a []byte, we need to change the code to create
// a proper copy.
func checkUnderlyingType[S ~string](s S) bool { panic("") }

var _ = checkUnderlyingType(Fingerprint(""))
```

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @oncilla)

___
*[`private/path/combinator/combinator.go` line 149 at r1](https://reviewable.io/reviews/scionproto/scion/4608#-O5m4O6h6BI3MncdstkP:-O5mly0C69qoQhxR75q0:b-tj863z) ([raw file](https://github.com/scionproto/scion/blob/65d7af3fac6db1b3ac893dfc7b28ebe05d14e9c8/private/path/combinator/combinator.go#L149)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

```

// This check ensures that the underlying type of the PathFingerprint
// is string. This is required to create a copy of the buffer. If it were
// to be moved to a []byte, we need to change the code to create
// a proper copy.
func checkUnderlyingType[S ~string](s S) bool { panic("") }

var _ = checkUnderlyingType(Fingerprint(""))
```
</blockquote></details>

Done.

panic doesn't work ;)

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 27 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: 4 of 31 files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by oncilla — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 28 of 28 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 27 files at r3, 19 of 28 files at r6, 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4608)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Pull request merged**
