### PR TITLE
Add core signing key

### PR DESCRIPTION
**Pull request by Oncilla**
Add core signing key: (#1410 )
- Core signing keys are used to sign leaf certificates

Change CertChain/TRC request wildcard: (#1386 )
- The NEWEST_VERSION wildcard is changed to 0
- Certificates and TRCs with version 0 are not parsable/verifiable

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1414)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/trust/key_conf.go, line 75 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6QmOaoKja7HIfWfbVF:-L6QmOaoKja7HIfWfbVG:b-uc0q9m) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/go/lib/trust/key_conf.go#L75)):*
> ```Go
> }
> 
> func loadKey(file string, load bool) (common.RawBytes, error) {
> ```

`loadKeyCond` might be a better name, makes it a bit clearer what it does.

---

*[python/topology/generator.py, line 118 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6Qndk1gCPXAy_mUjgs:-L6Qndk1gCPXAy_mUjgt:b9k8co5) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L118)):*
> ```Python
> INITIAL_CERT_VERSION = 1
> INITIAL_TRC_VERSION = 1
> INITIAL_GRACE_PERIOD = 18000
> ```

Does the grace period of the initial trc have any semantic meaning? There's no preceeding trc for it to apply to.

---

*[python/topology/generator.py, line 313 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6QnOFV70aJVTSirVo8:-L6QnOFV70aJVTSirVo9:bjuwtjx) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L313)):*
> ```Python
>         self.priv_offline_root_keys = {}
>         self.priv_core_sig_keys = {}
>         self.pub_core_sig_keys = {}
> ```

The previous lines have pub/priv ordering.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414)*

**Comment by Oncilla** [comment]
Review status: 11 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/trust/key_conf.go, line 75 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6QmOaoKja7HIfWfbVF:-L6QsbbBF_WGP85GNGGU:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/go/lib/trust/key_conf.go#L75)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`loadKeyCond` might be a better name, makes it a bit clearer what it does.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 118 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6Qndk1gCPXAy_mUjgs:-L6Qsdds-SLrwkGJGmOp:bnuwu7j) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L118)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Does the grace period of the initial trc have any semantic meaning? There's no preceeding trc for it to apply to.
</blockquote></details>

Not really. 

---

*[python/topology/generator.py, line 313 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6QnOFV70aJVTSirVo8:-L6QtC4-8RZErh8Ey-Q0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L313)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The previous lines have pub/priv ordering.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[python/topology/generator.py, line 118 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6Qndk1gCPXAy_mUjgs:-L6QxLhuXVR6i594SCz-:b6ejglw) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L118)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Not really. 
</blockquote></details>

In that case i suggest we set it to `0`, to avoid confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414)*

**Comment by Oncilla** [comment]
Review status: 12 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/topology/generator.py, line 118 at r1](https://reviewable.io:443/reviews/scionproto/scion/1414#-L6Qndk1gCPXAy_mUjgs:-L6R-pfBWfMZgga6525Q:b-a2y1ip) ([raw file](https://github.com/scionproto/scion/blob/46bcd90d9e9bea35dc894127db475f7fe43475c9/python/topology/generator.py#L118)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In that case i suggest we set it to `0`, to avoid confusion.
</blockquote></details>

Done.
(Hoping people will not use it for updated TRCs)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414#-:-L6R8nRkm0kk1bqM1SvI:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1414)*

**Pull request merged**
