### PR TITLE
Remove unused QUIC config field from CS

### LINKED ISSUE #2810: QUIC config should be tested
`go/lib/env/envtest/config_test.go` should also test the QUIC config sample to prevent divergence from the sample and the actual config.
The QUIC config block should also be added to the functions in `go/lib/env/envtest/config.go`

Separately we should figure out how we could prevent such issues in the future. (Maybe use reflection or a linter?)

### PR DESCRIPTION
**Pull request by juagargi**
And the type `env.QUIC`, as it's also unused.

Also relates to #2810 
Closes #2810

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4548)

**Review by oncilla — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @juagargi)

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4548)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @juagargi)

**Review by oncilla — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4548)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @juagargi)

**Pull request merged**
