### PR TITLE
Add Copy function to Cert/Chain

### PR DESCRIPTION
**Pull request by Oncilla**
Add: 
- Copy function to certificate
- Copy function to certificate chain. 
- Default validity times for certificates.
- VerifyTime function to check if certificate is active at a given point in time.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1378)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/crypto/cert/cert.go, line 154 at r1](https://reviewable.io:443/reviews/scionproto/scion/1378#-L3UVSQw_G1dN8sjstOU:-L3UVSQw_G1dN8sjstOV:b3vv7uo) ([raw file](https://github.com/scionproto/scion/blob/34b1811f2eb1072a796c2000a4147dff00e25f3b/go/lib/crypto/cert/cert.go#L154)):*
> ```Go
> func (c *Certificate) Copy() *Certificate {
> 
> 	n := &Certificate{CanIssue: c.CanIssue, Comment: c.Comment, EncAlgorithm: c.EncAlgorithm,
> ```

Format as one item per line (even if the list is super long)

---

*[go/lib/crypto/cert/chain.go, line 37 at r1](https://reviewable.io:443/reviews/scionproto/scion/1378#-L3UV6bXbodJ2mJuT1aG:-L3UV6bXbodJ2mJuT1aH:b-2j4zh8) ([raw file](https://github.com/scionproto/scion/blob/34b1811f2eb1072a796c2000a4147dff00e25f3b/go/lib/crypto/cert/chain.go#L37)):*
> ```Go
> 	MaxChainByteLength uint32 = 1 << 20
> 	// LeafValidity is the default validity time of a leaf certificate in seconds.
> 	LeafValidity = 3 * 24 * 60 * 60
> ```

`DefaultLeafCert/CoreCertValidity`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1378)*

**Comment by Oncilla** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/crypto/cert/cert.go, line 154 at r1](https://reviewable.io:443/reviews/scionproto/scion/1378#-L3UVSQw_G1dN8sjstOU:-L3Ytrkvmkc_O9QFunSP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/34b1811f2eb1072a796c2000a4147dff00e25f3b/go/lib/crypto/cert/cert.go#L154)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Format as one item per line (even if the list is super long)
</blockquote></details>

Done.

---

*[go/lib/crypto/cert/chain.go, line 37 at r1](https://reviewable.io:443/reviews/scionproto/scion/1378#-L3UV6bXbodJ2mJuT1aG:-L3Yu8ZdjMeNWgybzY2U:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/34b1811f2eb1072a796c2000a4147dff00e25f3b/go/lib/crypto/cert/chain.go#L37)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

`DefaultLeafCert/CoreCertValidity`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1378)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1378#-:-L4QTJab_Aci3xTsWvE0:bnfp4nl)*

**Comment by Oncilla** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1378)*

**Pull request merged**
