### PR TITLE
[doc] SIG framing protocol specification

### PR DESCRIPTION
**Pull request by sustrik**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)

### CODE REVIEW

**Review by sgmonroy — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 4 unresolved discussions (waiting on @sustrik)

___
*[doc/protocols/sig.rst, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh8hU53HM5OwwjXiQ5:-MGh8hU53HM5OwwjXiQ6:by8idri) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L42)):*
> ```reStructuredText
>     |     IP (underlay)     |
>     +-----------------------+
>     |     UDP (underlay)    |
> ```

Why is the underlay relevant in this context?
___
*[doc/protocols/sig.rst, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh8pzuEd1n_yA1O1hl:-MGh8pzuEd1n_yA1O1hm:b-br23lk) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L67)):*
> ```reStructuredText
>     |                       Sequence number                         |
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
>     |                 Sequence number (continued)                   |
> ```

Usually these fields are shown as follow:
```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                                                               |
    +                       Sequence number                         +
    |                                                               |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
___
*[doc/protocols/sig.rst, line 95 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh9mpW4VmH17poubXW:-MGh9mpX6fApFf9vhx2y:barb5q3) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L95)):*
> ```
> places
> ```
typo
___
*[doc/protocols/sig.rst, line 98 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh9y1ZA1c1chdvEerO:-MGh9y1ZA1c1chdvEerP:b-fd20m3) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L98)):*
> ```reStructuredText
> 
> SIG will use IPv4/6 "payload length" field to determine the size of the packet.
> To make the processing easier, it is required that the "payload length" field
> ```

I would simplify this by never splitting the IPv4 or IPv6 header itself

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 4 unresolved discussions (waiting on @sgmonroy)

___
*[doc/protocols/sig.rst, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh8hU53HM5OwwjXiQ5:-MGhODmo-Pb_ws-JOLHd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L42)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Why is the underlay relevant in this context?
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 67 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh8pzuEd1n_yA1O1hl:-MGhOPue2pmhd_MMXzvz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L67)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Usually these fields are shown as follow:
```
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
    |                                                               |
    +                       Sequence number                         +
    |                                                               |
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 95 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh9mpW4VmH17poubXW:-MGhOXMF29BT1b-R07e-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L95)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

> ```
> places
> ```
typo
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 98 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh9y1ZA1c1chdvEerO:-MGhOlAu1-MFp_cK9DeS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L98)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

I would simplify this by never splitting the IPv4 or IPv6 header itself
</blockquote></details>

Done.

**Review by shitz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @sgmonroy and @sustrik)

___
*[doc/protocols/sig.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhNsf1B-r7AUHbuRYW:-MGhNsf1B-r7AUHbuRYX:b-x6dd3v) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L17)):*
> ```
> multiple
> ```
one or more
___
*[doc/protocols/sig.rst, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhNykRDopUExikrm5B:-MGhNykRDopUExikrm5C:b6so9d6) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L20)):*
> ```
> happen 
> ```
be sent
___
*[doc/protocols/sig.rst, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh8hU53HM5OwwjXiQ5:-MGhO7Mj8gTj0E_eFRmm:b-cthx8c) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L42)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

Why is the underlay relevant in this context?
</blockquote></details>

Agree, the underlay should be removed here.
___
*[doc/protocols/sig.rst, line 90 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhOh5p8NDoa7r-z11E:-MGhOh5p8NDoa7r-z11F:bqtlf02) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L90)):*
> ```
> SIG frame payload
> ```
Can you also include an ASCII art showing the payload (showing also that Ipv4 and Ipv6 can be mixed in the same SIG frame.
___
*[doc/protocols/sig.rst, line 97 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhO_hLB8HAmrMWhIJK:-MGhO_hLB8HAmrMWhIJL:b8uin7a) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L97)):*
> ```
> will use
> ```
uses
___
*[doc/protocols/sig.rst, line 98 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGh9y1ZA1c1chdvEerO:-MGhOcN_4TRpgsTzL2XR:b4c9lyr) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L98)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

I would simplify this by never splitting the IPv4 or IPv6 header itself
</blockquote></details>

:thumbsup:

**Review by sgmonroy — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 4 unresolved discussions (waiting on @sustrik)

**Review by shitz — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @sgmonroy and @sustrik)

___
*[doc/protocols/sig.rst, line 112 at r3](https://reviewable.io/reviews/scionproto/scion/3865#-MGhSObjA5vVQJlFsK0J:-MGhSObjA5vVQJlFsK0K:bjovvub) ([raw file](https://github.com/scionproto/scion/blob/3e0243909e7dc399f8cadc286eadbf7b541f457b/doc/protocols/sig.rst#L112)):*
> ```reStructuredText
>     +----------------------------+------------+
>     | SIG HDR Index=0xffff Seq=2 | ...payload |
>     +----------------------------+------------+
> ```

missing new line

**Review by shitz — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 5 unresolved discussions (waiting on @sustrik)

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 5 unresolved discussions (waiting on @shitz)

___
*[doc/protocols/sig.rst, line 17 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhNsf1B-r7AUHbuRYW:-MGhPgMq1wHq7MnhtFob:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L17)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> multiple
> ```
one or more
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhNykRDopUExikrm5B:-MGhPjCA4R1zbRCKdZ6r:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L20)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> happen 
> ```
be sent
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 90 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhOh5p8NDoa7r-z11E:-MGhRpS-0kWAN17mdQ28:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L90)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> SIG frame payload
> ```
Can you also include an ASCII art showing the payload (showing also that Ipv4 and Ipv6 can be mixed in the same SIG frame.
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 97 at r1](https://reviewable.io/reviews/scionproto/scion/3865#-MGhO_hLB8HAmrMWhIJK:-MGhPoF37JZWj2zlM_IV:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d01f31c9c3cdec595f0933ea4ae764e9f31f95ce/doc/protocols/sig.rst#L97)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

> ```
> will use
> ```
uses
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 112 at r3](https://reviewable.io/reviews/scionproto/scion/3865#-MGhSObjA5vVQJlFsK0J:-MGhSaXE80Py2nom8Muy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/3e0243909e7dc399f8cadc286eadbf7b541f457b/doc/protocols/sig.rst#L112)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

missing new line
</blockquote></details>

Done.

**Review by shitz — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[doc/protocols/sig.rst, line 112 at r3](https://reviewable.io/reviews/scionproto/scion/3865#-MGhSObjA5vVQJlFsK0J:-MGhTVJsDS5-zKBSHha7:b-dhpq24) ([raw file](https://github.com/scionproto/scion/blob/3e0243909e7dc399f8cadc286eadbf7b541f457b/doc/protocols/sig.rst#L112)):*
<details><summary><i>Previously, sustrik (Martin Sustrik) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now you have trailing whitespaces ;)

**Review by shitz — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865#-:-MGhUE2RC98054IijlQh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 1 unresolved discussion (waiting on @sustrik)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3865#-MGhU863CmjGDymTby35:-MGhU864Ek8hVVwwJSuV:bjp4z4m) (no related file):*
We should fix the warnings:
```
/home/luke/Programming/scion/doc/protocols/sig.rst:54: WARNING: Block quote ends without a blank line; unexpected unindent.


Schemes
======
/home/luke/Programming/scion/doc/uri.rst:111: WARNING: Title underline too short.

Encode ISD-AS and IP in ``reg-name``
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/luke/Programming/scion/doc/uri.rst:111: WARNING: Title underline too short.

Encode ISD-AS and IP in ``reg-name``
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

---

**Review by lukedirtwalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 1 unresolved discussion (waiting on @sustrik)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3865#-MGhUkjo8W41p1kR5Ohp:-MGhUkjo8W41p1kR5Ohq:bq5elmr) (no related file):*
this doesn't look good yet.

---

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 8 unresolved discussions (waiting on @sustrik)

___
*[doc/protocols/sig.rst, line 5 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhUrn89n_6FS6Ae9gV:-MGhUrn99gzCYjLyMA0E:b-4pj3ps) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L5)):*
> ```reStructuredText
> ***********************************************
> 
> .. |br| raw:: html
> ```

what is that for?
___
*[doc/protocols/sig.rst, line 35 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVFOd0c4Al5_o-WhH:-MGhVFOeEM3jKnV4A4t_:b-46ul3u) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L35)):*
> ```reStructuredText
> =========
> 
> SIG framing protocol on top of SCION and UDP.
> ```

use `::` at the end of this.
___
*[doc/protocols/sig.rst, line 37 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVJyjCQFFbvzunRmI:-MGhVJyjCQFFbvzunRmJ:b-j7ws5h) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L37)):*
> ```reStructuredText
> SIG framing protocol on top of SCION and UDP.
> 
>     +-----------------------+
> ```

Indentation of 2 spaces for this is enough.
___
*[doc/protocols/sig.rst, line 50 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVOfi-HwaaXOvILns:-MGhVOfi-HwaaXOvILnt:b-frk7i0) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L50)):*
> ```
> :
> ```
use `::`
___
*[doc/protocols/sig.rst, line 52 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVRPVDDOmjINzazVq:-MGhVQV5EYqof7RdeywG:bqp9t6q) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L52)):*
> ```reStructuredText
> Each SIG frame starts with SIG frame header with the following format:
> 
>      0                   1                   2                   3
> ```

Indentation of 2 spaces in front is enough.
___
*[doc/protocols/sig.rst, line 100 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVjKB3CeYQenrg_3P:-MGhVjKCBhWDTC10E3_c:bgcjhhd) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L100)):*
> ```reStructuredText
> =======
> 
> Following example shows three IP packets packed into three SIG frames:
> ```

Use `::` at the end
___
*[doc/protocols/sig.rst, line 102 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVlKkDhp0DvcYnl2H:-MGhVlKkDhp0DvcYnl2I:b-wn6mio) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L102)):*
> ```reStructuredText
> Following example shows three IP packets packed into three SIG frames:
> 
>     +----------------------------+---------+---------+---------+----------------+
> ```

Indentation of 2 spaces is enough.

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 7 unresolved discussions (waiting on @lukedirtwalker)

___
*[doc/protocols/sig.rst, line 5 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhUrn89n_6FS6Ae9gV:-MGhWcyuEWTxwWIFndzs:byg0y47) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L5)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

what is that for?
</blockquote></details>

Copied from scmp.rst. Removed.
___
*[doc/protocols/sig.rst, line 35 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVFOd0c4Al5_o-WhH:-MGhWnCl-wSmtLRkikc2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L35)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

use `::` at the end of this.
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 37 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVJyjCQFFbvzunRmI:-MGhWnk10TmVHmwcNQjj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L37)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Indentation of 2 spaces for this is enough.
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 50 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVOfi-HwaaXOvILns:-MGhX09l2ytKmN-3zZyj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L50)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> :
> ```
use `::`
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 52 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVRPVDDOmjINzazVq:-MGhX0Q63KDWbnWjEiEZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L52)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Indentation of 2 spaces in front is enough.
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 100 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVjKB3CeYQenrg_3P:-MGhX39U2lxf0U7YJc0f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L100)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Use `::` at the end
</blockquote></details>

Done.
___
*[doc/protocols/sig.rst, line 102 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhVlKkDhp0DvcYnl2H:-MGhX6kO5VETU2H9tQvR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L102)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

Indentation of 2 spaces is enough.
</blockquote></details>

Done.

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @sustrik)

___
*[doc/protocols/sig.rst, line 18 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhWwl-0mqx9_gg9uCG:-MGhWwl-0mqx9_gg9uCH:b1jpqiy) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L18)):*
> ```reStructuredText
> The IP packets transported via SIG are encapsulated in SIG frames.
> There can be multiple IP packets in a single SIG frame.
> Single IP packet can be also split into multiple SIG frames.
> ```

I think something is missing in this sentence.
Either `A single IP packet can also be split...` or `Single IP packets can also be split...`
___
*[doc/protocols/sig.rst, line 24 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhXLXF6L4sLlfPa20q:-MGhXLXF6L4sLlfPa20r:b-96svhp) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L24)):*
> ```
> send
> ```
sent
___
*[doc/protocols/sig.rst, line 81 at r5](https://reviewable.io/reviews/scionproto/scion/3865#-MGhXmJF-mMAiFb17f7T:-MGhXmJF-mMAiFb17f7U:b-3in435) ([raw file](https://github.com/scionproto/scion/blob/1dd99354dfcfeee1bd404626663c54aed9750378/doc/protocols/sig.rst#L81)):*
> ```
> reassembly
> ```
reassemble

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3865)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
