### PR TITLE
trust: create TLS configuration based on CPPKI

### PR DESCRIPTION
**Pull request by JordiSubira**
Add a crypto manager that provides the necessary callbacks to create a SCION CPPKI backed `tls.Conifg`.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3847)

### CODE REVIEW

**Review by Oncilla — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3847)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[go/pkg/trust/tls_handshake.go, line 102 at r2](https://reviewable.io/reviews/scionproto/scion/3847#-MFW2LvYEf2i47OyaAiW:-MFW2LvYEf2i47OyaAiX:b-soptx8) ([raw file](https://github.com/scionproto/scion/blob/2f9c38c4d6c872d546e0965e189506f0f7f5bd3d/go/pkg/trust/tls_handshake.go#L102)):*
> ```Go
> 	var errs serrors.List
> 	for _, trc := range trcs {
> 		if err := cppki.VerifyChain(chain, cppki.VerifyOptions{TRC: &trc.TRC}); err != nil {
> ```

My bad, you need to return nil error if any of the verifications is successful:

```go
func verifyChain(chain []*x509.Certificate, trcs []cppki.SignedTRC) error {
    var errs serrros.List
    for _, trc := range trcs {
        if err := cppki.VerifyChain(chain, cppki.VerifyOptions{TRC: &trc.TRC}); err != nil {
            errs = append(errs, err)
            continue
        }
        return nil
    }
    return errs.ToError()
}
```

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3847)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[go/pkg/trust/tls_handshake.go, line 102 at r2](https://reviewable.io/reviews/scionproto/scion/3847#-MFW2LvYEf2i47OyaAiW:-MFZpqAI7zDd3wJNzy-y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2f9c38c4d6c872d546e0965e189506f0f7f5bd3d/go/pkg/trust/tls_handshake.go#L102)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

My bad, you need to return nil error if any of the verifications is successful:

```go
func verifyChain(chain []*x509.Certificate, trcs []cppki.SignedTRC) error {
    var errs serrros.List
    for _, trc := range trcs {
        if err := cppki.VerifyChain(chain, cppki.VerifyOptions{TRC: &trc.TRC}); err != nil {
            errs = append(errs, err)
            continue
        }
        return nil
    }
    return errs.ToError()
}
```
</blockquote></details>

Done.

**Review by Oncilla — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3847)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3847#-:-MF_Tmub5t4SED82VpdE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
