### PR TITLE
pkg/snet: format UDPAddr to comply with net.SplitHostPort

### PR DESCRIPTION
**Pull request by oncilla**
Change the snet.UDPAddr.String() method to return the address in a format that is compatible with net.SplitHostPort. This will allow non SCION aware applications to extract the host and port part without the need to understand it is a SCION address.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4648)

**Comment by jiceatscion** [comment]
No objection, but... does SplitHostPort understand something like [**1-ff00:0:320,**2001::1%some-zone]:20000 anyway?

**Review by jiceatscion — APPROVED** [review]
LGTM, but not sure how it actually helps.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4648#-:-OAS9Jlz4sYpVbktzFAb:bsnrsb2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> No objection, but... does SplitHostPort understand something like:  
`[1-ff00:0:320,2001::1%some-zone]:20000`  
`^ ^`  
> anyway?

It does indeed, it will split it into `1-ff00:0:320,2001::1%some-zone` and `20000` thanks to the IPvFuture :rocket 

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4648#-:-OATU4gU6QEZmcLW0h8A:bl1qets)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
The reason I bumped into this is because of the caddy plugin

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4648#-:-OATUaT3-jl9UnH8rXhC:b-yyyl3m)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
Ok, super then!

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4648#-:-OAX99Ys3lmKh-w-wode:b-a8gpk0)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
