### PR TITLE
drkey: add grpc package in control

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR is the 8th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.

This PR contains:
- Protobuf to golang translation helpes for CS messages.
- gRPC service implementing the interfaces defined in `proto/control_plane` 
- UTs

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4230)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4230)* status: all files reviewed, 17 unresolved discussions (waiting on @JordiSubira)

___
*[`control/drkey/grpc/drkey_service.go` line 71 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUHZfCxtbir88KzNR:-N7pUHZfCxtbir88KzNS:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L71)):*
> ```Go
> 	dstIA, err := extractIAFromPeer(peer)
> 	if err != nil {
> 		return nil, serrors.WrapStr("retrieving info from certficate", err)
> ```





_Suggestion:_
```Go
certificate
```
___
*[`control/drkey/grpc/drkey_service.go` line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUVQl7APP18A-VwGv:-N7pUVQl7APP18A-VwGw:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L82)):*
> ```Go
> 	if !lvl1Meta.ProtoId.IsPredefined() {
> 		return nil, serrors.New("the requested protocol id is not recognized",
> 			"protoID", lvl1Meta.ProtoId)
> ```





_Suggestion:_
```Go
proto_id
```
___
*[`control/drkey/grpc/drkey_service.go` line 272 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVor-Bssjcdl1VFe9:-N7pVor-Bssjcdl1VFeA:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L272)):*
> ```Go
> 		log.Debug("Authorized delegated secret",
> 			"protocol", protoId.String(),
> 			"requester address", localAddr.String(),
> ```





_Suggestion:_
```Go
"requester_address"
```
___
*[`control/drkey/grpc/drkey_service.go` line 278 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVn438xGTskmOpr7b:-N7pVn438xGTskmOpr7c:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L278)):*
> ```Go
> 	return serrors.New("endhost not allowed for DRKey request",
> 		"protocol", protoId.String(),
> 		"requester address", localAddr.String(),
> ```





_Suggestion:_
```Go
requester_address"
```
___
*[`control/drkey/grpc/drkey_service.go` line 293 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVdGPBs6v-h8DJpl1:-N7pVdGPBs6v-h8DJpl2:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L293)):*
> ```Go
> 	if !meta.DstIA.Equal(localIA) {
> 		return serrors.New("invalid request, req.dstIA != localIA",
> 			"req.dstIA", meta.DstIA, "localIA", localIA)
> ```





_Suggestion:_
```Go
"request_dst_isd_as"
```
___
*[`control/drkey/grpc/drkey_service.go` line 293 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVjU9D_pT5FrisP6p:-N7pVjU9D_pT5FrisP6q:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L293)):*
> ```Go
> 	if !meta.DstIA.Equal(localIA) {
> 		return serrors.New("invalid request, req.dstIA != localIA",
> 			"req.dstIA", meta.DstIA, "localIA", localIA)
> ```





_Suggestion:_
```Go
"local_isd_as"
```
___
*[`control/drkey/grpc/drkey_service.go` line 338 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVu4D-xwlXZjPg24u:-N7pVu4E6YdEPa4jkrvL:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L338)):*
> ```Go
> 		return serrors.New(
> 			"invalid request",
> 			"localIA", localIA,
> ```





_Suggestion:_
```Go
"local_isd_as",
```
___
*[`control/drkey/grpc/drkey_service.go` line 339 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVxIUA85UHHKV6ayw:-N7pVxIUA85UHHKV6ayx:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L339)):*
> ```Go
> 			"invalid request",
> 			"localIA", localIA,
> 			"srcIA", meta.SrcIA,
> ```





_Suggestion:_
```Go
src_isd_as
```
___
*[`control/drkey/grpc/drkey_service.go` line 340 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pW-jN8AhV1P6CNq7-:-N7pW-jN8AhV1P6CNq70:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L340)):*
> ```Go
> 			"localIA", localIA,
> 			"srcIA", meta.SrcIA,
> 			"dstIA", meta.DstIA,
> ```





_Suggestion:_
```Go
"dst_isd_as"
```
___
*[`control/drkey/grpc/drkey_service.go` line 379 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVXoZ8Ielu6fnUBOr:-N7pVXoZ8Ielu6fnUBOs:undefined) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L379)):*
> ```Go
> 	if !ok {
> 		return 0, serrors.New("auth info is not of type TLS info",
> 			"peer", peer, "authType", peer.AuthInfo.AuthType())
> ```





_Suggestion:_
```Go
auth_type"
```
___
*[`control/drkey/grpc/protobuf.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUa-MBm9QvkujOdTO:-N7pUa-N5MvCN9JiPTjJ:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L37)):*
> ```Go
> }
> 
> func secretToProtoResp(drkey drkey.SecretValue) (*cppb.DRKeySecretValueResponse, error) {
> ```

remove the error from the signature, it never returns an error.
___
*[`control/drkey/grpc/protobuf.go` line 45 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUdEB4GCIyIiV7ba3:-N7pUdEB4GCIyIiV7ba4:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L45)):*
> ```Go
> }
> 
> func keyToLevel1Resp(drkey drkey.Level1Key) (*cppb.DRKeyLevel1Response, error) {
> ```

remove the error from the signature, it never returns an error.
___
*[`control/drkey/grpc/protobuf.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUdiP5Bq-HIFfzdi0:-N7pUdiP5Bq-HIFfzdi1:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L53)):*
> ```Go
> }
> 
> func keyToASASResp(drkey drkey.Level1Key) (*cppb.DRKeyIntraLevel1Response, error) {
> ```

remove the error from the signature, it never returns an error.
___
*[`control/drkey/grpc/protobuf.go` line 75 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUeqUDvjrrU7TbjTs:-N7pUeqUDvjrrU7TbjTt:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L75)):*
> ```Go
> }
> 
> func keyToASHostResp(drkey drkey.ASHostKey) (*cppb.DRKeyASHostResponse, error) {
> ```

remove the error from the signature, it never returns an error.
___
*[`control/drkey/grpc/protobuf.go` line 97 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUfkc83licfydS6jE:-N7pUfkc83licfydS6jF:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L97)):*
> ```Go
> }
> 
> func keyToHostASResp(drkey drkey.HostASKey) (*cppb.DRKeyHostASResponse, error) {
> ```

remove the error from the signature, it never returns an error.
___
*[`control/drkey/grpc/protobuf.go` line 120 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUgeNE7G8ZDgb2DLy:-N7pUgeNE7G8ZDgb2DLz:b-lihdl4) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L120)):*
> ```Go
> }
> 
> func keyToHostHostResp(drkey drkey.HostHostKey) (*cppb.DRKeyHostHostResponse, error) {
> ```

remove the error from the signature, it never returns an error.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4230)* status: 11 of 14 files reviewed, 16 unresolved discussions (waiting on @lukedirtwalker)

___
*[`control/drkey/grpc/drkey_service.go` line 71 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUHZfCxtbir88KzNR:-N7pgyYZ5pRTLc71WfR_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L71)):*
> ```Go
> 	dstIA, err := extractIAFromPeer(peer)
> 	if err != nil {
> 		return nil, serrors.WrapStr("retrieving info from certficate", err)
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 82 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUVQl7APP18A-VwGv:-N7pgz4DDCJw56mt-dqn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L82)):*
> ```Go
> 	if !lvl1Meta.ProtoId.IsPredefined() {
> 		return nil, serrors.New("the requested protocol id is not recognized",
> 			"protoID", lvl1Meta.ProtoId)
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 272 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVor-Bssjcdl1VFe9:-N7ph-C63R8Agxx88pw5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L272)):*
> ```Go
> 		log.Debug("Authorized delegated secret",
> 			"protocol", protoId.String(),
> 			"requester address", localAddr.String(),
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 278 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVn438xGTskmOpr7b:-N7ph-tr2BWBgyJ1IVh1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L278)):*
> ```Go
> 	return serrors.New("endhost not allowed for DRKey request",
> 		"protocol", protoId.String(),
> 		"requester address", localAddr.String(),
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 293 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVjU9D_pT5FrisP6p:-N7ph0gz01EjHLu7gKYx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L293)):*
> ```Go
> 	if !meta.DstIA.Equal(localIA) {
> 		return serrors.New("invalid request, req.dstIA != localIA",
> 			"req.dstIA", meta.DstIA, "localIA", localIA)
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 293 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVdGPBs6v-h8DJpl1:-N7ph0ozE6X_fcyO_VGw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L293)):*
> ```Go
> 	if !meta.DstIA.Equal(localIA) {
> 		return serrors.New("invalid request, req.dstIA != localIA",
> 			"req.dstIA", meta.DstIA, "localIA", localIA)
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 338 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVu4D-xwlXZjPg24u:-N7ph1_p7UWUukDl-Y4T:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L338)):*
> ```Go
> 		return serrors.New(
> 			"invalid request",
> 			"localIA", localIA,
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 339 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVxIUA85UHHKV6ayw:-N7ph2PI8yAAGuuDMFD7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L339)):*
> ```Go
> 			"invalid request",
> 			"localIA", localIA,
> 			"srcIA", meta.SrcIA,
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 340 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pW-jN8AhV1P6CNq7-:-N7ph3BSB5h87Sj0f-TB:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L340)):*
> ```Go
> 			"localIA", localIA,
> 			"srcIA", meta.SrcIA,
> 			"dstIA", meta.DstIA,
> ```

Done.
___
*[`control/drkey/grpc/drkey_service.go` line 379 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pVXoZ8Ielu6fnUBOr:-N7ph3ec8m96e28C4LTq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/drkey_service.go#L379)):*
> ```Go
> 	if !ok {
> 		return 0, serrors.New("auth info is not of type TLS info",
> 			"peer", peer, "authType", peer.AuthInfo.AuthType())
> ```

Done.
___
*[`control/drkey/grpc/protobuf.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUa-MBm9QvkujOdTO:-N7ph4YE9LdeNqTui462:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L37)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.
___
*[`control/drkey/grpc/protobuf.go` line 45 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUdEB4GCIyIiV7ba3:-N7ph4sZElu7jQz219WA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L45)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.
___
*[`control/drkey/grpc/protobuf.go` line 53 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUdiP5Bq-HIFfzdi0:-N7ph55p1cj0H075ddFR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L53)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.
___
*[`control/drkey/grpc/protobuf.go` line 75 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUeqUDvjrrU7TbjTs:-N7ph5Pq4QGUdgFhYsod:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L75)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.
___
*[`control/drkey/grpc/protobuf.go` line 97 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUfkc83licfydS6jE:-N7ph5hz9C6qYs5iVDz_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L97)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.
___
*[`control/drkey/grpc/protobuf.go` line 120 at r2](https://reviewable.io/reviews/scionproto/scion/4230#-N7pUgeNE7G8ZDgb2DLy:-N7ph6-l8hP1x70Ep65X:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/596a9db1868980c15174748463efd0a325969d00/control/drkey/grpc/protobuf.go#L120)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

remove the error from the signature, it never returns an error.
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by JordiSubira — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4230)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
