### PR TITLE
Add default SignSrc

### PR DESCRIPTION
**Pull request by Oncilla**
Add default SignSrc which includes:
- ISD-AS of singer
- Certificate chain version of signer
- TRC version of signer

Additionally:
- add Timestamp to SignS

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1399)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/ctrl/signed_util.go, line 138 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aaVpetDlTZSbN2v02:-L4aaVpetDlTZSbN2v03:bwcj4cg) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L138)):*
> ```Go
> 	SrcDefaultPrefix = "DEFAULT: "
> 	// SrcDefaultFmt is the default format for proto.SignS.Src.
> 	SrcDefaultFmt = `^` + SrcDefaultPrefix + `IA: (\d+)-(\d+) CHAIN: (\d+) TRC: (\d+)$`
> ```

`(\d+-\d+)` would get you the whole ISD-AS string, and make it easier to parse.

---

*[go/lib/ctrl/signed_util.go, line 155 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aabnEN9bfYT80eqqz:-L4aabnEN9bfYT80eqr-:b-bf3i1h) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L155)):*
> ```Go
> 	ia, err := addr.IAFromString(fmt.Sprintf("%s-%s", s[1], s[2]))
> 	if err != nil {
> 		return nil, common.NewBasicError("Unable to parse default src", err)
> ```

This error message appears 4 times, making it hard to tell where the actual error was. It's best to make each error string unique. So, e.g. `"Unable to parse default src IA"`.

---

*[go/lib/ctrl/signed_util.go, line 169 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aanCJy5_It7kiksSx:-L4aanCJy5_It7kiksSy:b-25mtdj) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L169)):*
> ```Go
> 
> func (s *SignSrcDef) Pack() common.RawBytes {
> 	return common.RawBytes(fmt.Sprintf("DEFAULT: IA: %s CHAIN: %d TRC: %d",
> ```

This could use `SrcDefaultFmt`, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1399)*

**Comment by Oncilla** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/ctrl/signed_util.go, line 138 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aaVpetDlTZSbN2v02:-L4ahsGGpVDVYcZxRsE8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L138)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`(\d+-\d+)` would get you the whole ISD-AS string, and make it easier to parse.
</blockquote></details>

Done.

---

*[go/lib/ctrl/signed_util.go, line 155 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aabnEN9bfYT80eqqz:-L4aht-7U163M2R2sJxf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L155)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This error message appears 4 times, making it hard to tell where the actual error was. It's best to make each error string unique. So, e.g. `"Unable to parse default src IA"`.
</blockquote></details>

Done.

---

*[go/lib/ctrl/signed_util.go, line 169 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aanCJy5_It7kiksSx:-L4ahttAFvIdcpuUwt8c:bb6x76c) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L169)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This could use `SrcDefaultFmt`, too.
</blockquote></details>

How?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1399)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/ctrl/signed_util.go, line 169 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aanCJy5_It7kiksSx:-L4aiMT9r1qvRjndGhnh:b4og2ks) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L169)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

How?
</blockquote></details>

`fmt.Sprintf("%s: IA...", SrcDefaultFmt, s.IA...)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1399)*

**Comment by Oncilla** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/ctrl/signed_util.go, line 169 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aanCJy5_It7kiksSx:-L4ajcKg7tTY8TljUFgD:bitqsk4) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L169)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`fmt.Sprintf("%s: IA...", SrcDefaultFmt, s.IA...)`
</blockquote></details>

Oh, you mean <code>SrcDefaultPrefix</code>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1399)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/ctrl/signed_util.go, line 169 at r1](https://reviewable.io:443/reviews/scionproto/scion/1399#-L4aanCJy5_It7kiksSx:-L4aqtVM4wD41LUTOKFH:b-mh8bne) ([raw file](https://github.com/scionproto/scion/blob/8721b8100124aedea8e2d3c44f7d9f8557b16576/go/lib/ctrl/signed_util.go#L169)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Oh, you mean <code>SrcDefaultPrefix</code>
Done.
</blockquote></details>

Oops! Yes, sorry :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1399#-:-L4aqxXO4x60D0yYQVal:bnfp4nl)*

**Pull request merged**
