### PR TITLE
scion-pki: add subjectIA flag to cert verify command

### PR DESCRIPTION
**Pull request by FR4NK-W**
Add an optional subjectIA flag to the certificate verify command.
This enables validating the IA property of the subject of the certificate against an expected value.

Invalid flag usage or a mismatching IA property of the certificate subject leads to a verification failure.

Adds a check to findIA to ensure that the ISD-AS property stored in the certificate is in the canonical string representation.
The canonical string representation of an ISD-AS is provided by the string formatting function. It is the decimal representation of the uint16 of the ISD, followed by a single dash -, followed by the string formatted representation of the AS id, which for AS ids in the BGP range is the decimal representation, and for larger AS ids consists of a colon separated hexadecimal representation of the value (see the fmtAS function in package addr).

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: all files reviewed, 2 unresolved discussions (waiting on @FR4NK-W)

___
*[pkg/scrypto/cppki/certs.go, line 550 at r1](https://reviewable.io/reviews/scionproto/scion/4179#-Mzz7NEJ0LlBIMHNXFHm:-Mzz7NEJ0LlBIMHNXFHn:b-wqhinp) ([raw file](https://github.com/scionproto/scion/blob/b77cd03c5d1ec66610a8a9daa0c034ef0d2aca21/pkg/scrypto/cppki/certs.go#L550)):*
> ```Go
> 		if ia.String() != rawIA {
> 			return nil, serrors.New("ISD-AS not in canonical form", "isd_as", ia)
> 		}
> ```

Document that this MUST be in canonical form where this attribute value is described, around doc/cryptography/certificates.rst:246.
___
*[scion-pki/certs/verify.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/4179#-Mzz92Me9q7n2TDssnko:-Mzz92Mf1wnIlCDsvFDY:b-h46x6l) ([raw file](https://github.com/scionproto/scion/blob/b77cd03c5d1ec66610a8a9daa0c034ef0d2aca21/scion-pki/certs/verify.go#L113)):*
> ```Go
> 		"Optional unix timestamp that sets the current time",
> 	)
> 	cmd.Flags().StringVar(&flags.subjectIA, "subjectIA", "",
> ```

The switches are kebab-case. We have usually spelled out IA in user-facing contexts. So I would suggest `subject-isd-as`.

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @matzf)

___
*[pkg/scrypto/cppki/certs.go, line 550 at r1](https://reviewable.io/reviews/scionproto/scion/4179#-Mzz7NEJ0LlBIMHNXFHm:-N0B-HbR49NX74S3xHdn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b77cd03c5d1ec66610a8a9daa0c034ef0d2aca21/pkg/scrypto/cppki/certs.go#L550)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Document that this MUST be in canonical form where this attribute value is described, around doc/cryptography/certificates.rst:246.
</blockquote></details>

Done.

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @matzf)

___
*[scion-pki/certs/verify.go, line 113 at r1](https://reviewable.io/reviews/scionproto/scion/4179#-Mzz92Me9q7n2TDssnko:-N0FAcBn1K1WLYuGCJve:bmai2rl) ([raw file](https://github.com/scionproto/scion/blob/1315f02e64d9ad1f2b8bd30728c5c0afd8ffb45d/scion-pki/certs/verify.go#L113)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Did you intentionally change to `scion-` instead of `subject-`, or was that perhaps a typo?
</blockquote></details>

Definitely a typo, sorry about that.
Not sure what happened.

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @FR4NK-W and @matzf)

___
*[doc/cryptography/certificates.rst, line 264 at r2](https://reviewable.io/reviews/scionproto/scion/4179#-N0F1pCbADtNE2BFAq1v:-N0FF0Yq8tY7sRAKPdTb:b-1gw9un) ([raw file](https://github.com/scionproto/scion/blob/8b76829d9e8f9a57149e7bb45b1901877a4a822f/doc/cryptography/certificates.rst#L264)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Aside; looking at `findIA` and `ExtractIA` in `scrypto/cppki/certs.go`, rejecting certificates that "include it more than once" is not implemented. Should this perhaps be fixed, @oncilla?
</blockquote></details>

I think so, yes.
___
*[scion-pki/certs/verify.go, line 2 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FFUDYEH1FH-PluqJC:-N0FFUDYEH1FH-PluqJD:undefined) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L2)):*
> ```Go
> // Copyright 2020 Anapaya Systems
> // Copyright 2022 ETH Zurich
> ```





_Suggestion:_
```Go
// Copyright 2022 ETH Zurich, Anapaya Systems
```
___
*[scion-pki/certs/verify.go, line 53 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FIeMl6pU8Bh-2iXza:-N0FIeMl6pU8Bh-2iXzb:bd6bjgd) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L53)):*
> ```Go
> The ISD-AS property of the subject identified by the certificate
> (or in the case of a certificate chain, the leaf certificate)
> can be validated by specifying the --subject-isd-as flag and
> ```

Due to the documentation generation to RST, we need to escape `--` pattern.
This will not be visible in the CLI help output because we have stripping logic.



_Suggestion:_
```Go
\--subject-isd-as
```
___
*[scion-pki/certs/verify.go, line 65 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FIyZj4di10Tk9wwi4:-N0FIyZj4di10Tk9wwi5:bwzyw4o) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L65)):*
> ```Go
> 			cmd.SilenceUsage = true
> 			chain, err := cppki.ReadPEMCerts(args[0])
> 			if err != nil || len(chain) == 0 {
> ```

This will be confusing to the user, because we report an empty error.

Add a second if condition below that reports the read chain was empty:

```
if len(chain) == 0 {
  return serrors.New("file does not contain any certificate")
}
```



_Code quote:_
```Go
|| len(chain) == 0
```
___
*[scion-pki/certs/verify.go, line 88 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FJw3xExVrMDcbm5Ha:-N0FJw3xExVrMDcbm5Hb:b-ciuk18) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L88)):*
> ```Go
> 						"err", err)
> 				}
> 				certSubjectASID, err := cppki.ExtractIA(chain[0].Subject)
> ```

`IA` vs `ASID` in the same block.


Personally, I would just call the variables `expected` and `actual`.

If you want prefer the long forms, use a consistent suffix. We usually use IA.
(Although, I'm not a big fan because it feels a lot like hungarian notation)



_Code quote:_
```Go
ASID
```

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @FR4NK-W and @matzf)

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: all files reviewed (commit messages unreviewed), 5 unresolved discussions (waiting on @FR4NK-W and @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4179#-N0FKi-k4m03Q4-8tmRu:-N0FKi-k4m03Q4-8tmRv:b-nojh78) (no related file):*
> Let me know if you think that the verify command would also benefit from having some tests.

It would benefit for sure. But from my POV it is not required to merge this PR.
The verify functionality itself is tested in the library, but It would be still nice to have some sanity tests in the scion-pki tool at some point.

---

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @oncilla)

___
*[scion-pki/certs/verify.go, line 2 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FFUDYEH1FH-PluqJC:-N0FOPkJ5Xv7Fl-du2C7:bdcu7fb) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L2)):*
> ```Go
> // Copyright 2020 Anapaya Systems
> // Copyright 2022 ETH Zurich
> ```

And drop the line above it?
___
*[scion-pki/certs/verify.go, line 53 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FIeMl6pU8Bh-2iXza:-N0FOCeeD2Z0_VOuKipI:b-5opulj) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L53)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Due to the documentation generation to RST, we need to escape `--` pattern.
This will not be visible in the CLI help output because we have stripping logic.
</blockquote></details>

Done.

I had noticed this somewhere else and wasn't sure if that was a fluke, if that applied everywhere.
Is this documented somewhere?
___
*[scion-pki/certs/verify.go, line 65 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FIyZj4di10Tk9wwi4:-N0FOWYy2kqQipSbP3ap:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L65)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This will be confusing to the user, because we report an empty error.

Add a second if condition below that reports the read chain was empty:

```
if len(chain) == 0 {
  return serrors.New("file does not contain any certificate")
}
```
</blockquote></details>

Done.
___
*[scion-pki/certs/verify.go, line 88 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FJw3xExVrMDcbm5Ha:-N0FQ0Cy1dcvCaLFd6JP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L88)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

`IA` vs `ASID` in the same block.


Personally, I would just call the variables `expected` and `actual`.

If you want prefer the long forms, use a consistent suffix. We usually use IA.
(Although, I'm not a big fan because it feels a lot like hungarian notation)

</blockquote></details>

Done.

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179#-:-N0FcyIp0b9cxCO1b-Kg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FR4NK-W)

___
*[scion-pki/certs/verify.go, line 2 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FFUDYEH1FH-PluqJC:-N0FcMnM-EvX3kHM79fm:bkz8vf9) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L2)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

And drop the line above it?
</blockquote></details>

We have kept them so far. INAL though.
___
*[scion-pki/certs/verify.go, line 53 at r3](https://reviewable.io/reviews/scionproto/scion/4179#-N0FIeMl6pU8Bh-2iXza:-N0FcWdF3F6G0EySdTyG:b-3103si) ([raw file](https://github.com/scionproto/scion/blob/1db1d3a1aeadef8a125844a5a39ab17fa5fa23cf/scion-pki/certs/verify.go#L53)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Done.

I had noticed this somewhere else and wasn't sure if that was a fluke, if that applied everywhere.
Is this documented somewhere?
</blockquote></details>

I don't think we have it documented.
But we should. 

Also, it is a bit sad that we have to do it in the first place. I think this is only a temporary solution, because it is too easy to forget.
We need a better way.

You missed it in the validate PR, but I already fixed it during the import to our closed source repo.

**Review by oncilla — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @FR4NK-W)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4179#-N0Fd-CPArHIp_M5Dpf6:-N0Fd-CPArHIp_M5Dpf7:b-dopfr4) (no related file):*
Thank you!

This will be included in our next open source run.

---

**Pull request closed without merging**
