### PR TITLE
Rename topology's LinkType to LinkTo

### LINKED ISSUE #1444: Rename topology's LinkType to LinkTo
The current `LinkType` field in the topology is hard to understand. For `CORE` and `PEER` it's fine, because those are symmetric relationships. But `PARENT` and `CHILD`, it's non-obvious which side is the parent, and which side is the child. My proposal is to change the name of the field to `LinkTo`. So you'd have `LinkTo: CORE`, `LinkTo: PEER`, `LinkTo: PARENT` and `LinkTo: CHILD`, all of which are unambigious.

### PR DESCRIPTION
**Pull request by worxli**
Rename topology's LinkType to LinkTo, fixes #1444

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1526)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[python/topology/generator.py, line 624 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1526#-LAXIfIX43HaSSOjxsDd:-LAXIfIX43HaSSOjxsDe:bd2fgdb) ([raw file](https://github.com/scionproto/scion/blob/487b1f2c5eaf9637709c39d9b2a1808ff10722a5/python/topology/generator.py#L624)):*
> ```Python
>             b = TopoID(attrs.pop("b"))
>             linkto = linkto_a = linkto_b = attrs.pop("linkto")
>             if linkto == LinkType.PARENT:
> ```

With the change in the `.topo` files, this becomes `LinkType.CHILD`.

---

*[topology/Default.topo, line 65 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1526#-LAXI4ynBoO-h9ZDZO4S:-LAXI4ynBoO-h9ZDZO4T:bitnb4w) ([raw file](https://github.com/scionproto/scion/blob/487b1f2c5eaf9637709c39d9b2a1808ff10722a5/topology/Default.topo#L65)):*
> ```
>   - {a: 1-4_295_001_010, b: 1-4_295_001_030, linkto: CORE}
>   - {a: 1-4_295_001_010, b: 2-4_295_002_010, linkto: CORE}
>   - {a: 1-4_295_001_010, b: 1-4_295_001_011, linkto: PARENT}
> ```

Proposal:
```
- {a: 1-4_295_001_010, b: 1-4_295_001_011, linkAtoB: CHILD}
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1526)*

**Comment by worxli** [comment]
Review status: 4 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[python/topology/generator.py, line 624 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1526#-LAXIfIX43HaSSOjxsDd:-LAYX4bzDfj29OpJ9rzw:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/487b1f2c5eaf9637709c39d9b2a1808ff10722a5/python/topology/generator.py#L624)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

With the change in the `.topo` files, this becomes `LinkType.CHILD`.
</blockquote></details>

Done.

---

*[topology/Default.topo, line 65 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1526#-LAXI4ynBoO-h9ZDZO4S:-LAYX5g60--WVvATSgbQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/487b1f2c5eaf9637709c39d9b2a1808ff10722a5/topology/Default.topo#L65)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Proposal:
```
- {a: 1-4_295_001_010, b: 1-4_295_001_011, linkAtoB: CHILD}
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1526)*

**Comment by kormat** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[topology/Two.topo, line 1 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1526#-LAYXG_v0uKcI3S8fR7M:-LAYXG_v0uKcI3S8fR7N:b-76iyvh) ([raw file](https://github.com/scionproto/scion/blob/ebb2a5302360eb2933db963ee1b977e6fe79a8c5/topology/Two.topo#L1)):*
> ```
> --- # Two Topology
> ```

DONOTWANT

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1526)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1526#-:-LAYXeUH0N5zNhBCY7su:bnfp4nl)*

**Pull request merged**
