### PR TITLE
doc: extend linters, manage deps via bazel

### PR DESCRIPTION
**Pull request by matzf**
- use markdownlint-cli2 instead of ruby markdownlint

  Use Node.js-based github.com/DavidAnson/markdownlint-cli2, replacing the ruby-based github.com/markdownlint/markdownlint. This tool has a cleaner configuration file and that is well supported in vs code and other editors.

  Adapted from https://github.com/scionproto/scion/pull/4328.

- add sphinx-lint, and manage the doc requirements via bazel/rules_python.

  Fix a large number of legitimage linter warnings; most cases were accidentally applying the "default role" (single backticks instead of double-backticks), or the occasional missing underscore after external links.

- add bazel run targets to run sphinx-build and sphinx-autobuild via python deps managed by bazel. This makes it easy to locally build the documentation for devs that already have bazel set up (while hopefully keeping things still relatively straight-forward).

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4503)

**Review by jiceatscion — APPROVED** [review]
Works for me.

> Reviewed 38 of 40 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4503#-:-NvBXAKe7c9KSFvve1_j:b-376tn6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by oncilla — APPROVED** [review]
> Reviewed 38 of 40 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4503)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4503#-:-NvpYguB7TCWwDvPfXCn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
