### PR TITLE
build: update quic-go version

### PR DESCRIPTION
**Pull request by oncilla**
Update the quic-go version to v0.36.3. This is the last version that does not require Go 1.20 yet.

We will upgrade the Go version in a follow up PR.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @oncilla)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEingk3s2p8zidsRL8:-NdEingk3s2p8zidsRL9:b-t92s04) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
> ```Go
> 
> 		var err error
> 		session, err = quic.Dial(ctx, d.Conn, dst, tlsConfig, quicConfig)
> ```

Multiple Dial calls on the same PacketConn are no longer allowed. This panics. We need to use a `quic.DialListener` here (see migration guide in https://github.com/quic-go/quic-go/issues/3727).
___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdEjHHBERz0z1DWbSzc:b4buqbw) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
> ```Go
> 
> 		var err error
> 		session, err = quic.Dial(ctx, d.Conn, dst, tlsConfig, quicConfig)
> ```

The SNI name is now (only) in tlsConfig.ServerName, which we don't set AFAICT.  Is this legal, and compatible with older servers?

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEingk3s2p8zidsRL8:-NdEjt2HE0fZJe1StuB2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Multiple Dial calls on the same PacketConn are no longer allowed. This panics. We need to use a `quic.DialListener` here (see migration guide in https://github.com/quic-go/quic-go/issues/3727).
</blockquote></details>

Done.
___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdEjtOO-TpAQCimLbsf:bv77kux) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The SNI name is now (only) in tlsConfig.ServerName, which we don't set AFAICT.  Is this legal, and compatible with older servers?
</blockquote></details>

Not sure, I need to double-check

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdF82zZD50ZBKCDL6rO:b-4ie62w) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Not sure, I need to double-check
</blockquote></details>

I was able to connect from new quic client to existing server without issues.
But, I did have InsecureSkipVerify enabled, so all bets are off.

I set the ServerName to be compatible with the old version for sure.

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdFDzjF5UJ6cwHQSrIQ:bn2gieg) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I was able to connect from new quic client to existing server without issues.
But, I did have InsecureSkipVerify enabled, so all bets are off.

I set the ServerName to be compatible with the old version for sure.
</blockquote></details>

Hm, i need to still investigate why drkey test is failing. Most likely due to this .

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 21 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdFd7LkCXmivsNrhvmc:b-jq9wi) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Hm, i need to still investigate why drkey test is failing. Most likely due to this .
</blockquote></details>

:bulb: server names don't have ports :facepalm: 
Should be good to go now.

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 22 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdG2Hkm0L7lxH5UFaK7:bxzj3l) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

:bulb: server names don't have ports :facepalm: 
Should be good to go now.
</blockquote></details>

Hm, big topologies are still failing. A bit too often to declare it a flake

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 24 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdGGbuRDbHXa2irfD8l:bu6js1e) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Hm, big topologies are still failing. A bit too often to declare it a flake
</blockquote></details>

0/20 vs 8/20

https://buildkite.com/scionproto/scion/builds/3683
https://buildkite.com/scionproto/scion/builds/3681

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: 10 of 22 files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`pkg/snet/squic/net.go` line 379 at r1](https://reviewable.io/reviews/scionproto/scion/4385#-NdEjHHBERz0z1DWbSzb:-NdflFDg-IMYojy_fQ4N:bu3gc28) ([raw file](https://github.com/scionproto/scion/blob/b5084d02f0083d137435bb478765f9ebb8bf396c/pkg/snet/squic/net.go#L379)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

0/20 vs 8/20

https://buildkite.com/scionproto/scion/builds/3683
https://buildkite.com/scionproto/scion/builds/3681
</blockquote></details>

Turns out receiving an unexpected error leaves the transport in a semi broken state.
I think I will file an issue with upstream to get their opinion on the matter.

Currently, it is hard for the client to detect it is in a broken state.

**Review by matzf — APPROVED** [review]
> Reviewed 2 of 7 files at r2, 9 of 10 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4385)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
