### PR TITLE
Log and Flags rework

### PR DESCRIPTION
**Pull request by sgmonroy**
- Only need to import liblog for logging
- Rename liblog as log package
- Split log file vs log console functions
- Functions to dynamically add flags for log file/console
- Setup returns error instead of directly exiting

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1426)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 6 of 90 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/log/log.go, line 32 at r2](https://reviewable.io:443/reviews/scionproto/scion/1426#-L7jAEiskTxCzKP8zmu5:-L7jAEiskTxCzKP8zmu6:buzeyrm) ([raw file](https://github.com/scionproto/scion/blob/a24d678ad6eeb67bb19e191e262270ccafd2cb7b/go/lib/log/log.go#L32)):*
> ```Go
> )
> 
> var logDir string
> ```

This can be put into one `var ()` block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1426)*

**Comment by sgmonroy** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/lib/log/log.go, line 32 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1426#-L7jAEiskTxCzKP8zmu5:-L7xMw3N5KxIaz0y9VXs:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a24d678ad6eeb67bb19e191e262270ccafd2cb7b/go/lib/log/log.go#L32)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This can be put into one `var ()` block.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1426)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 90 files at r1, 3 of 90 files at r2, 2 of 11 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1426#-:-L7y-YT_1VcHtlK3fvyZ:bnfp4nl)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1426#-:-L7yARmX-IyRPE-mitZ1:bnfp4nl)*

**Pull request merged**
