### PR TITLE
router: add test cases for malformed paths

### PR DESCRIPTION
**Pull request by matzf**
Add test cases for checks added in #4556;
- invalid (non-peer) segments with a single hop field
- hop field pointer not pointing into current segment

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4572)

**Review by jiceatscion — CHANGES_REQUESTED** [review]
Looks good to me, with the obvious caveat that if this didn't actually test what it claims to, I probably wouldn't realize it.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4572#-:-O1bEixO2qhnVQefQsT6:b-o9e5l4)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`tools/braccept/cases/malformed_path.go` line 153 at r1](https://reviewable.io/reviews/scionproto/scion/4572#-O1bFHl1BEC0pysV_UGR:-O1bFHl1BEC0pysV_UGS:b8ucr3x) ([raw file](https://github.com/scionproto/scion/blob/253a333af1166ef2a60dda5c939dfb928db02365/tools/braccept/cases/malformed_path.go#L153)):*
> ```Go
> }
> 
> // MalformedPathSingletonSegment tests an invalid combination of CurrHF and CurrINF
> ```

This comment is cut/past from the previous test case.

**Review by matzf — COMMENTED** [review]
Fair point, is there anything that I should do to make it clearer what's happening?

For whatever it's worth, I created these cases by adapting existing cases. I started with valid/working paths and checked that the packets are dropped with the expected error messages in the router log. I also checked that the test failed (or at least behaved as expected) without the checks added in #4556.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4572#-:-O1pH4B82A1UXqFxu7Nk:bgwk90a)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`tools/braccept/cases/malformed_path.go` line 153 at r1](https://reviewable.io/reviews/scionproto/scion/4572#-O1bFHl1BEC0pysV_UGR:-O1pH2gV1tG0KIQxDv0m:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fd9f9cb424038bfa25d9afdf70935f4bc7f694fe/tools/braccept/cases/malformed_path.go#L153)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

This comment is cut/past from the previous test case.
</blockquote></details>

Done.

**Review by jiceatscion — COMMENTED** [review]
Not much can be done to make the cases more intuitive; it's the nature of the beast I'm afraid. If you did test the test, that's good enough for me.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4572#-:-O1qO-hb2XChRMif0e_C:b-yrr17b)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by jiceatscion — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4572#-:-O1qOUCpA0tka7-KcPm6:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @matzf)

**Review by jiceatscion — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4572)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
