### PR TITLE
scion-pki: add --isd flag to trc verify command

### PR DESCRIPTION
**Pull request by FR4NK-W**
Add a `--isd` flag to the `trc verify` command.

This optional flag enables checking the ISD number the TRC chain that is being verified.
The new flag simplifies CLI interactions for tools that want to validate that a TRC chain is for a specific ISD.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)

### CODE REVIEW

**Comment by FR4NK-W** [comment]
Addresses issue #4170

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4171#-MyNYTOD3R8shqwO419z:-MyNYTOE5ix_mneeaL0v:b-mkp7an) (no related file):*
@fr4nk-w Could you elaborate a bit in what setting this would be useful?

TRC chain verification only makes sense if you have an initially trusted TRC, otherwise there is nothing to root your trust in.
And if that is the case, you should already know what ISD that initial TRC is for.

During the TRC chain verification we make sure that the ISD number is the same, thus it can not deviate from the initial TRC that you already trust.

---

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @FR4NK-W and @oncilla)

___
*[scion-pki/trcs/verify.go, line 38 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MyggqB6EgFRry45SJMg:-MyggqB6EgFRry45SJMh:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L38)):*
> ```Go
> 	var flags struct {
> 		anchor string
> 		isdID  uint16
> ```





_Suggestion:_
```Go
isd  uint16
```
___
*[scion-pki/trcs/verify.go, line 61 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-Mygh3-I-I3ZlH_-Am7w:-Mygh3-I-I3ZlH_-Am7x:b-uxwhu4) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L61)):*
> ```Go
> 
> 	cmd.Flags().StringVarP(&flags.anchor, "anchor", "a", "", "trust anchor (required)")
> 	cmd.Flags().Uint16VarP(&flags.isdID, "isd", "i", 0, "ISD identifier")
> ```

Let's not register a short flag for this one.



_Suggestion:_
```Go
cmd.Flags().Uint16Var(&flags.isdID, "isd", 0, "ISD identifier")
```
___
*[scion-pki/trcs/verify.go, line 67 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-Mygh_UiANcaEI8YwaLO:-Mygh_UiANcaEI8YwaLP:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L67)):*
> ```Go
> 
> // RunVerify runs verification of the TRC files from the given anchor.
> func RunVerify(files []string, anchor string, isdID uint16) error {
> ```





_Suggestion:_
```Go
isd addr.ISD
```
___
*[scion-pki/trcs/verify.go, line 76 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MygiHAc8QXDgi_Uejns:-MygiHAc8QXDgi_Uejnt:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L76)):*
> ```Go
> 		trcs = append(trcs, dec)
> 	}
> 	if len(trcs) < 1 {
> ```





_Suggestion:_
```Go
len(trcs) == 0
```
___
*[scion-pki/trcs/verify.go, line 80 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MygiKWbCcFHL3pP-tsj:-MygiKWbCcFHL3pP-tsk:b-qxnyo9) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L80)):*
> ```Go
> 	}
> 	if isdID != 0 {
> 		if err := verifyTRCid(trcs[len(trcs)-1], isdID); err != nil {
> ```

I think we should check the ISD number of the trust anchor and not just an arbitrary TRC in the list.
I think this should be done below after we have sorted the slice of TRCs and on `trcs[0]`



_Code quote:_
```Go
trcs[len(trcs)-1]
```
___
*[scion-pki/trcs/verify.go, line 139 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-Myghy9L4hvpC-zFb7DA:-Myghy9M4fIgr0dgiCzr:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L139)):*
> ```Go
> }
> 
> func verifyTRCid(trc cppki.SignedTRC, isdID uint16) error {
> ```





_Suggestion:_
```Go
isd addr.ISD
```
___
*[scion-pki/trcs/verify.go, line 139 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-Mygih7-8tMI8QthxfJa:-Mygi0SM0ejBGAI95OLU:b76pt7z) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify.go#L139)):*
> ```Go
> }
> 
> func verifyTRCid(trc cppki.SignedTRC, isdID uint16) error {
> ```

This function feels a bit overkill. We do not really reduce complexity in the calling function.
There, it could be as simple as:

```go
if anchor := trcs[0].TRC.ID.ISD; isd != 0 && anchor != isd {
  return serrors.New("TRC anchor does not match the requested ISD", "expected", isd, "actual", anchor)
}
```
___
*[scion-pki/trcs/verify_test.go, line 36 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MygjJXLEaSu_YX36KxJ:-MygjJXLEaSu_YX36KxK:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify_test.go#L36)):*
> ```Go
> 		Files        []string
> 		Anchor       string
> 		ISDid        uint16
> ```





_Suggestion:_
```Go
ISD        addr.ISD
```
___
*[scion-pki/trcs/verify_test.go, line 86 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MygjO6n7BT8_e13ZeXN:-MygjO6n7BT8_e13ZeXO:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify_test.go#L86)):*
> ```Go
> 			ErrAssertion: require.Error,
> 		},
> 		"base-ISDid-check": {
> ```





_Suggestion:_
```Go
isd
```
___
*[scion-pki/trcs/verify_test.go, line 93 at r2](https://reviewable.io/reviews/scionproto/scion/4171#-MygjPwc7rBNvp6iTu3d:-MygjPwc7rBNvp6iTu3e:undefined) ([raw file](https://github.com/scionproto/scion/blob/4b0383b5a34c529df8245fe5e9ac13e934d5ca83/scion-pki/trcs/verify_test.go#L93)):*
> ```Go
> 			ErrAssertion: require.NoError,
> 		},
> 		"base-verify-ISDid": {
> ```





_Suggestion:_
```Go
isd
```

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @FR4NK-W)

___
*[scion-pki/trcs/verify.go, line 87 at r3](https://reviewable.io/reviews/scionproto/scion/4171#-Myguo3o4FySo275N06G:-Myguo3p0vky7oGBqTMA:undefined) ([raw file](https://github.com/scionproto/scion/blob/17e5a5d9f9d1c50c4f370016c63bb065ab7b09c1/scion-pki/trcs/verify.go#L87)):*
> ```Go
> 		}
> 		if someBase != dec.TRC.ID.Base {
> 			return serrors.New("multiple someBase versions", "bases", []scrypto.Version{
> ```





_Suggestion:_
```Go
base
```

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[scion-pki/trcs/verify.go, line 87 at r3](https://reviewable.io/reviews/scionproto/scion/4171#-Myguo3o4FySo275N06G:-Mygx9uU7jCjAPV4HFxp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/17e5a5d9f9d1c50c4f370016c63bb065ab7b09c1/scion-pki/trcs/verify.go#L87)):*
> ```Go
> 		}
> 		if someBase != dec.TRC.ID.Base {
> 			return serrors.New("multiple someBase versions", "bases", []scrypto.Version{
> ```

Done.

**Review by matzf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @FR4NK-W and @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-MykilBw3gDeMqYYofwp:btp3xpr) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
> ```Go
> 			},
> 			ErrAssertion: require.NoError,
> 		},
> ```

This case is identical to the test above, just a different filename. Is this asserting that the filename does not contribute to the check? Then perhaps we should _only_ use this, especially also for the mismatch case.
Btw, please write to a temporary directory, `t.TempDir()`, not the repository, and probably `os.Link` should suffice.

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-Myko8m91wHOKwvlYGb6:b-7imlpb) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
> Btw, please write to a temporary directory, t.TempDir(), not the repository, and probably os.Link should suffice.

Done. That was a mistake, not using the TempDir. Not using a SymLink, since SymLinks could potentially be handled differently. Yes, the goal is to assert that the filename does not contribute to the check.
Renaming the test input file `"./testdata/admin/ISD1-B1-S1.trc"` (`git mv`) would be an other option.

>especially also for the mismatch case.

I do not understand. Would you drop the test case `"base-ISD-mismatch"`? This is a failing test case, `"base-ISD-check"` is a succeeding one. Or do you see a way to combine them?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-MykrpKcAiGG7NadYtCw:b396gl2) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
Ok. `Link` creates a hard link, not a symbolic Was just a thought, a full copy is fine.

> I do not understand. Would you drop the test case "base-ISD-mismatch"? This is a failing test case, "base-ISD-check" is a succeeding one. Or do you see a way to combine them?

No, what I meant is that it would make more sense for the mismatch case to use the "nondescript" filename. As it stands, the mismatch  can be detected by just looking at the filename ("ISD1-B1-S1.trc" vs ISD: 10).

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-Mykv3ez6YECmMI3ca73:b-bv4gj8) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok. `Link` creates a hard link, not a symbolic Was just a thought, a full copy is fine.

> I do not understand. Would you drop the test case "base-ISD-mismatch"? This is a failing test case, "base-ISD-check" is a succeeding one. Or do you see a way to combine them?

No, what I meant is that it would make more sense for the mismatch case to use the "nondescript" filename. As it stands, the mismatch  can be detected by just looking at the filename ("ISD1-B1-S1.trc" vs ISD: 10). 
</blockquote></details>

Done.

Doing a hard link with `Link` is not possible of the temp directory created by `TempDir` is on a different volume.

**Review by matzf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @FR4NK-W and @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-Myl0A09-W4Q4gptHa98:b-upbtr7) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

Done.

Doing a hard link with `Link` is not possible of the temp directory created by `TempDir` is on a different volume.
</blockquote></details>

Just a copy then, in both cases.

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @matzf and @oncilla)

___
*[scion-pki/trcs/verify_test.go, line 111 at r4](https://reviewable.io/reviews/scionproto/scion/4171#-MykilBw3gDeMqYYofwo:-MyrfyVU8UnCy-oZiEW2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d97fcc9cc83c5a1b6762efef47008ec68a70379f/scion-pki/trcs/verify_test.go#L111)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just a copy then, in both cases.
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4171)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Pull request closed without merging**
