### PR TITLE
build: force old timer behavior

### LINKED ISSUE #4606: build: the end-2-end tests have become extremely flaky
They have less than 20% success rate.

### PR DESCRIPTION
**Pull request by oncilla**
Until https://github.com/golang/go/issues/69312 is resolved, force the old timer behavior by specifying an older go version in the go.mod file.

Fixes #4606

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)

**Review by jiceatscion — APPROVED** [review]
Thanks for figuring it out.

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6uRbjG-CpmeLD6ZQNV:b5795wf)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
Hm, not really solved yet. 
I guess bazel does not respect the go.mod as it is not really aware of it :sad-panda:
We probably want to set the env var to disable the timer change. I will take a look eventually

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6uU7HP4Bi1MCDAa6zR:bmttesp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
There's another stop where the go version must go.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6vn9PAA47lEpIY2UHn:b-h3fc6p)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
From my old PR to set go to 1.23: https://github.com/scionproto/scion/pull/4618/files#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6vnUJ567xR-XhmSKos:bo3xmrb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
Yeah. I don't really want to revert the go version update and would rather just disable the semantic change.

Latest commit achieves that and looks promising on CI: https://buildkite.com/scionproto/scion/builds/4763

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6z0YldAnhyTkbH4KD5:bodcldb)* status: 3 of 12 files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by marcfrei — COMMENTED** [review]
But go.mod gets still reverted back to go 1.22.7. Is this intentional?

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6z1v5H9S_E8VKuuAf4:b-v0pvre)* status: 3 of 12 files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by jiceatscion — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`go.mod` line 131 at r3](https://reviewable.io/reviews/scionproto/scion/4620#-O6z7775-w1h8FRl5_1v:-O6z7775-w1h8FRl5_1w:b-3x6ryy) ([raw file](https://github.com/scionproto/scion/blob/66f2f2931d9dcc31dbb5e41c47b622aa20d727ae/go.mod#L131)):*
> ```XML
> )
> 
> go 1.22.7
> ```

I agree with Marc... revert this?

**Review by oncilla — COMMENTED** [review]
It is yes. This ensures that downstream dependents of scionproto/scion also do not use the new timer semantics as long as they are using the regular go toolchain.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zD6mxAodulKJfLEOI:b-yuiq26)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`go.mod` line 131 at r3](https://reviewable.io/reviews/scionproto/scion/4620#-O6z7775-w1h8FRl5_1v:-O6zDMf_13n1QlKY3N35:budr8o9) ([raw file](https://github.com/scionproto/scion/blob/66f2f2931d9dcc31dbb5e41c47b622aa20d727ae/go.mod#L131)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I agree with Marc... revert this?
</blockquote></details>

I don't think we should change this until the Go has patched the problem. Note that this just indicates the semantics, not the go version that is being used. See https://go.dev/doc/modules/gomod-ref#go

**Review by oncilla — COMMENTED** [review]
For more context. I wish that I could tell bazel to use go1.22 semantics when building with 1.23. I have not found a way to do so.
Using go 1.22.7 in the go.mod file is actually the proper way to handle such things, the xhack is just there for bazel.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zDhqUC1mu3id7ANWW:bqxpti5)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

**Review by marcfrei — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zGKsbAJ7IXTdJbziF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

___
*[`go.mod` line 131 at r3](https://reviewable.io/reviews/scionproto/scion/4620#-O6z7775-w1h8FRl5_1v:-O6zH-KYElMBMj4Bis-Q:b6k0co) ([raw file](https://github.com/scionproto/scion/blob/66f2f2931d9dcc31dbb5e41c47b622aa20d727ae/go.mod#L131)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I don't think we should change this until the Go has patched the problem. Note that this just indicates the semantics, not the go version that is being used. See https://go.dev/doc/modules/gomod-ref#go
</blockquote></details>

Ah, ok didn't know how that works. But then, why bother with the xhack. Would it not be simpler and clearer to force bazel to actually build with go 1.22 by setting the version in WORKSPACE? Whatever works though, it's just until the next go release. But still I'm curious.

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @marcfrei)

___
*[`go.mod` line 131 at r3](https://reviewable.io/reviews/scionproto/scion/4620#-O6z7775-w1h8FRl5_1v:-O6zHqiPDLTSTzcEEoa3:b-x2ms1n) ([raw file](https://github.com/scionproto/scion/blob/66f2f2931d9dcc31dbb5e41c47b622aa20d727ae/go.mod#L131)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Ah, ok didn't know how that works. But then, why bother with the xhack. Would it not be simpler and clearer to force bazel to actually build with go 1.22 by setting the version in WORKSPACE? Whatever works though, it's just until the next go release. But still I'm curious.
</blockquote></details>

Hm. Let me test if that works

**Review by oncilla — COMMENTED** [review]
Reached out to the bazel community. There is a draft PR that will add support very soon to rules_go https://github.com/bazelbuild/rules_go/pull/4106

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zjPm46GHcHJR8bGd2:b-ru9vru)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @marcfrei)

**Review by jiceatscion — COMMENTED** [review]
good to know. How does that affect the choice of using xhack vs. setting the go version in WORKSPACE, though. Have you decided? 

> Reviewed 1 of 2 files at r4, 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zvFct40Mojruednlo:bjjdmcw)* status: 13 of 18 files reviewed, 1 unresolved discussion (waiting on @marcfrei and @oncilla)

___
*[`go.mod` line 131 at r3](https://reviewable.io/reviews/scionproto/scion/4620#-O6z7775-w1h8FRl5_1v:-O6zwVBd8wbjlrKoYKZ2:bp8l7y0) ([raw file](https://github.com/scionproto/scion/blob/66f2f2931d9dcc31dbb5e41c47b622aa20d727ae/go.mod#L131)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Hm. Let me test if that works
</blockquote></details>

The WORKSPACE approach seems to be working (1/20 failure rate is pretty much the normal flakyness of the e2e tests).

**Review by oncilla — COMMENTED** [review]
Updated.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620#-:-O6zzxsn4ZehJ5Q7gEi_:b-bw8e14)* status: 6 of 18 files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @marcfrei)

**Review by jiceatscion — APPROVED** [review]
> Reviewed 4 of 6 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: all files reviewed, 1 unresolved discussion (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 2 files at r2, 1 of 2 files at r4, 6 of 6 files at r5, 8 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4620)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
