### PR TITLE
gateway: fix panic on data port

### LINKED ISSUE #4196: gateway: IngressServer panics when receiving probe packet on data port
When SIG A sends a probe packet to the data port of SIG B, SIG B panics with the error message `frame too short`.

This happens when the AS of SIG B is misconfigured and uses the same address for the SIG's `data_addr` and `probe_addr` fields.

topology file:
```
...
  "sigs": {
    "sig1-ff00_0_111": {
      "ctrl_addr": "127.0.0.18:30256",
      "data_addr": "127.0.0.18:30056",
      "probe_addr": "127.0.0.18:30056"
    }
  }
...
```

### PR DESCRIPTION
**Pull request by fstreun**
When receiving a malformed packet, the gateway should not panic. Rather, the packet should be discarded.

Fixes #4196

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
Thank you, @fstreun! Some nitpicky remarks added.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291#-:-NGMFcgb3WIlqMxkDRSI:b-6779xi)* status: all files reviewed, 2 unresolved discussions (waiting on @fstreun)

___
*[`gateway/dataplane/ingressserver.go` line 105 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMEebWAziYwEOgPN3e:-NGMEebWAziYwEOgPN3f:b2gtuuj) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L105)):*
> ```Go
> 							"expected", sigHdrSize, "actual", read)
> 						frame.Release()
> 					} else if frame.raw[0] != 0 {
> ```

Perhaps using `continue` for all the error cases, instead of the (nested) `else`,  would help to improve the readability here. The `frame.Release(); continue;` statements are then also easier to visually check for consistency.
___
*[`gateway/dataplane/ingressserver.go` line 124 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMAwH3A0RAE-_kIzjD:-NGMAwH3A0RAE-_kIzjE:bc18n45) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L124)):*
> ```Go
> 						"reason", "invalid"))
> 					logger.Info("IngressServer: Not a valid snet address", "address", src)
> 					frame.Release()
> ```

Wrong address type is a logic error, panic makes sense here.
In fact, I think it would be fair game to just type assert `v := src.(*snet.UDPAddr)` without the type switch, making this whole thing here a bit easier to parse.

**Review by fstreun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`gateway/dataplane/ingressserver.go` line 105 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMEebWAziYwEOgPN3e:-NGMSPSAB0ieNX5pExBt:b-lkp5ih) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L105)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Perhaps using `continue` for all the error cases, instead of the (nested) `else`,  would help to improve the readability here. The `frame.Release(); continue;` statements are then also easier to visually check for consistency.
</blockquote></details>

I agree. As far as I understand the code also the statement `frames[i] = nil` is required.
___
*[`gateway/dataplane/ingressserver.go` line 124 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMAwH3A0RAE-_kIzjD:-NGMQNPiAcsAWH3HtJxm:b-k9c31r) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L124)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Wrong address type is a logic error, panic makes sense here.
In fact, I think it would be fair game to just type assert `v := src.(*snet.UDPAddr)` without the type switch, making this whole thing here a bit easier to parse.
</blockquote></details>

If it is impossible that a packet with another address type can be received here, then I agree.
Otherwise, this would provide an easy DoS vector.

**Review by matzf — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @fstreun and @shitz)

___
*[`gateway/dataplane/ingressserver.go` line 105 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMEebWAziYwEOgPN3e:-NGMWlbj8BkLeRpi8OHt:b-riru91) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L105)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

I agree. As far as I understand the code also the statement `frames[i] = nil` is required.
</blockquote></details>

Aha, good point, I missed that. Of course we can add this to all the cases, but that seems a bit awkward. We could move that to the loop iteration clause (`for i := 0; i < n; func(){frames[i]=nil; i++}() {`), but that may be a bit nasty too.

I have to admit I don't actually understand the purpose of this statement. Certainly the frame will not be garbage collected anyway (because it is either still being processed or it was just put back into the ring buffer). If this is just a safe-guard to avoid accidental double-processing and it hampers readability, I'd remove it. Note: this was added by @shitz in #1264. 
___
*[`gateway/dataplane/ingressserver.go` line 124 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMAwH3A0RAE-_kIzjD:-NGMWCqW57FVLSSbtWVn:bmewcg1) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L124)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

If it is impossible that a packet with another address type can be received here, then I agree.
Otherwise, this would provide an easy DoS vector.
</blockquote></details>

Yes, it is my understanding that `(*snet.Conn).ReadFrom` always returns `*snet.UDPAddr`.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @fstreun)

___
*[`gateway/dataplane/ingressserver.go` line 105 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMEebWAziYwEOgPN3e:-NGMfw1w-6iRCumSNtKx:b1l20r6) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L105)):*
<details><summary><i>Previously, fstreun wrote…</i></summary><blockquote>

Done.

Added it to each case. If this is not satisfactory, please let me know.
</blockquote></details>

Ok. Or maybe just move it to the top of the loop body? Once we have the `frame` variable, we can clear `frames[i]`. :shrug:

**Review by matzf — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @fstreun)

**Review by fstreun — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @matzf)

___
*[`gateway/dataplane/ingressserver.go` line 105 at r1](https://reviewable.io/reviews/scionproto/scion/4291#-NGMEebWAziYwEOgPN3e:-NGMiOXY-J-mT6sG0oks:b-4izkyc) ([raw file](https://github.com/scionproto/scion/blob/109f5ba3f6af171634843ac3ab35b47e358c15d0/gateway/dataplane/ingressserver.go#L105)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Ok. Or maybe just move it to the top of the loop body? Once we have the `frame` variable, we can clear `frames[i]`. :shrug: 
</blockquote></details>

Done.

Thank you.

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fstreun)

**Pull request merged**
