### PR TITLE
Dependency licence audit.

### PR DESCRIPTION
**Pull request by kormat**
- scapy-python3 uses GPL, so replacing it with pypacker which is
  BSD-licensed.
- quic-go unfortunately depends on 4 repos which are unlicensed, so
  until this can be remedied, all quic-go support is disabled and the
  depdendencies are removed.

Also:
- Remove some unused Go deps.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1435)

### CODE REVIEW

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1435#-:-L6qYRN8k7HpwuYmSt-B:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[go/vendor/vendor.json, line 200 at r1](https://reviewable.io:443/reviews/scionproto/scion/1435#-L6qYkG-UpWCSgNypfW1:-L6qYkG-UpWCSgNypfW2:b8igbrb) ([raw file](https://github.com/scionproto/scion/blob/518f69cd3e55dc9db1b2b8e00db452e403b76a7a/go/vendor/vendor.json#L200)):*
> quic-go
stringer from clipperhouse has a copyrigth notice inside the file:
```
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```
with the LICENSE file being omitted.
And linkedlistwriter similarly says:
```
// List is a modification of http://golang.org/pkg/container/list/
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1435)*

**Comment by FR4NK-W** [comment]
BSD lincese is fine, right?
Then clipperhouse dep from quic-go should be fine as well, see the notices inside the source

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1435#-:-L6qZZIBfzH2FSwyyovK:bmxfj6n)*

**Comment by kormat** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vendor/vendor.json, line 200 at r1](https://reviewable.io:443/reviews/scionproto/scion/1435#-L6qYkG-UpWCSgNypfW1:-L6qe2_ASIJhGH_E-Oyr:baci5vf) ([raw file](https://github.com/scionproto/scion/blob/518f69cd3e55dc9db1b2b8e00db452e403b76a7a/go/vendor/vendor.json#L200)):*
<details><summary><i>Previously, FR4NK-W wrote…</i></summary><blockquote>

> quic-go
stringer from clipperhouse has a copyrigth notice inside the file:
```
// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```
with the LICENSE file being omitted.
And linkedlistwriter similarly says:
```
// List is a modification of http://golang.org/pkg/container/list/
// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
```
</blockquote></details>

That is correct re: clipperhouse/stringer. But, as the `LICENSE` file is ommitted, and `stringerwriter.go` doesn't have any licence text, it's still not sufficiently clear.

Re: linkedlistwriter, that's a copyright for the _generated_ code. This doesn't infer a license for the generating code (i.e. the code that's actually in the repo).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1435)*

**Comment by klausman** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1435#-:-L6qfEoXAdFiRv2bciNs:bnfp4nl)*

**Pull request merged**
