### PR TITLE
formatting: introduce yapf python formatter

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Also add pylint, not yet active.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3901)

### CODE REVIEW

**Review by Oncilla — APPROVED** [review]
:lgtm:

> Reviewed 34 of 34 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3901#-:-MJf4JFtAq-ETppSsGAT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[python/flake8.ini, line 2 at r1](https://reviewable.io/reviews/scionproto/scion/3901#-MJf4AxH4UfiYjPbn_0W:-MJf4AxH4UfiYjPbn_0X:bjym1zr) ([raw file](https://github.com/scionproto/scion/blob/0648b9efe40b881f190d460fcf28c2a266058c8d/python/flake8.ini#L2)):*
> ```INI
> [flake8]
> max - line - length = 100
> ```

wait, wut?

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3901)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[tools/lint/requirements.txt, line 5 at r1](https://reviewable.io/reviews/scionproto/scion/3901#-MJfJvnh3N8n1pJre9yU:-MJfJvniEV7ZADJHBOG8:bz4zu9o) ([raw file](https://github.com/scionproto/scion/blob/0648b9efe40b881f190d460fcf28c2a266058c8d/tools/lint/requirements.txt#L5)):*
> ```vimhelp
> # To update, run:
> #
> #    pip-compile tools/lint/requirements.txt
> ```

:+1: for `pip-compile`, but using it like this, without a `requirements.in` file, seems to make it trickier to remove direct dependencies, or even to just list the direct deps. Wouldn't you rather check in a `requirements.in` file? And add `--generate-hashes` (the other `requirements.txt` file in `env/pip` has them).

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3901)* status: 10 of 37 files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[python/flake8.ini, line 2 at r1](https://reviewable.io/reviews/scionproto/scion/3901#-MJf4AxH4UfiYjPbn_0W:-MKylGa40ALHW2SBxGmz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0648b9efe40b881f190d460fcf28c2a266058c8d/python/flake8.ini#L2)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

wait, wut?
</blockquote></details>

Done.
___
*[tools/lint/requirements.txt, line 5 at r1](https://reviewable.io/reviews/scionproto/scion/3901#-MJfJvnh3N8n1pJre9yU:-MKynmoT2Ag-r2HCfZsZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0648b9efe40b881f190d460fcf28c2a266058c8d/tools/lint/requirements.txt#L5)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

:+1: for `pip-compile`, but using it like this, without a `requirements.in` file, seems to make it trickier to remove direct dependencies, or even to just list the direct deps. Wouldn't you rather check in a `requirements.in` file? And add `--generate-hashes` (the other `requirements.txt` file in `env/pip` has them).
</blockquote></details>

Done.

**Review by scrye — APPROVED** [review]
:lgtm:

> Reviewed 31 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3901#-:-ML7Bpvo-uUapBpdAsWY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Oncilla)

**Review by lukedirtwalker — COMMENTED** [review]
> Dismissed @Oncilla from a discussion.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3901)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lukedirtwalker** [comment]
Closing this. We should instead opt for https://github.com/aspect-build/rules_lint and ruff for formatting.

**Pull request closed without merging**
