### PR TITLE
Unit test for SIG config file loading

### PR DESCRIPTION
**Pull request by scrye**
Also fixes an inconsistency in `ActionMap`/`ClassMap` unmarshaling. On master, unmarshaling from an empty object yiels an empty allocated `ActionMap` and a nil `ClassMap`. This PR fixes makes unmarshaling from an empty object yield a nil `ActionMap`/`ClassMap` in both cases.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1544)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/sig/config/config.go, line 37 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWM-yH23Cdyiayi46l:-LBWM-yH23Cdyiayi46m:bys0v4i) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config.go#L37)):*
> ```Go
> // postprocess sets the SIG IDs of the SIG objects in cfg according the keys in
> // SIGSet.
> func (cfg *Cfg) postprocess() {
> ```

As this is a method of `Cfg`, and `LoadFromFile` is a constructor for `Cfg`, i'd move this after `LoadFromFile`.

---

*[go/sig/config/config_test.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWMrly3d_xtOaz32Sm:-LBWMrly3d_xtOaz32Sn:b3t4rzs) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L30)):*
> ```Go
> 
> var (
> 	update = flag.Bool("update", false, "set to true to update reference testdata files")
> ```

It would be good to document this in `testdata/README.md`.

---

*[go/sig/config/config_test.go, line 47 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWPBMTA9caPxCSPgaa:-LBWPBMTA9caPxCSPgab:bs1eo7z) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L47)):*
> ```Go
> 						Nets: []*IPNet{
> 							{
> 								IP:   net.IP{192, 168, 1, 0},
> ```

Use documentation network ranges:
 https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml - search for Documentation. You're already using the documentation range for v6, so :+1: there.

---

*[go/sig/config/config_test.go, line 48 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWP3c44uzeIr77jRqf:-LBWP3c44uzeIr77jRqg:br42qyk) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L48)):*
> ```Go
> 							{
> 								IP:   net.IP{192, 168, 1, 0},
> 								Mask: net.CIDRMask(24, 32),
> ```

`net.IPv4len`

---

*[go/sig/config/config_test.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWP9e_-n2XitUBeYRi:-LBWP9ea4d5JPQvnwUtJ:br56c5a) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L52)):*
> ```Go
> 							{
> 								IP:   net.ParseIP("2001:DB8::"),
> 								Mask: net.CIDRMask(48, 128),
> ```

`net.IPv6len`

---

*[go/sig/config/config_test.go, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQ9Je6kc1BOX6NG2h:-LBWQ9Je6kc1BOX6NG2i:bm8pals) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L58)):*
> ```Go
> 							"remote-1": &SIG{
> 								Id:        "remote-1",
> 								Addr:      net.ParseIP("10.0.1.1"),
> ```

Doc net

---

*[go/sig/config/config_test.go, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQAQxC5dxVdN2WoHL:-LBWQAQxC5dxVdN2WoHM:bm8pals) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L64)):*
> ```Go
> 							"remote-2": &SIG{
> 								Id:        "remote-2",
> 								Addr:      net.ParseIP("10.0.1.2"),
> ```

Doc net

---

*[go/sig/config/config_test.go, line 73 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQFm49_Htwm8_JGp9:-LBWQFm49_Htwm8_JGpA:bm8pals) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L73)):*
> ```Go
> 						Nets: []*IPNet{
> 							{
> 								IP:   net.IP{2, 0, 0, 0},
> ```

Doc net

---

*[go/sig/config/config_test.go, line 74 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQGNC0nHjHKT7S2PF:-LBWQGNC0nHjHKT7S2PG:br42qyk) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L74)):*
> ```Go
> 							{
> 								IP:   net.IP{2, 0, 0, 0},
> 								Mask: net.CIDRMask(16, 32),
> ```

`net.IPv4len`

---

*[go/sig/config/config_test.go, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQWyP6gwOK996aDHf:-LBWQWyP6gwOK996aDHg:b8a1gd3) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L99)):*
> ```Go
> 
> 	Convey("Test SIG config marshal/unmarshal", t, func() {
> 		for _, tc := range testCases {
> ```

As this is a loop, there should be a Convey inside it to indicate which test case is being tested.

---

*[go/sig/config/testdata/01-loadfromfile.ref, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWJxO13PbPnSJLkQBb:-LBWJxO13PbPnSJLkQBc:b-vbwuk8) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/testdata/01-loadfromfile.ref#L1)):*
> ```
> {
> ```

A `.json` suffix would make tools happier. Same applies to `go/lib/pktcls/testdata/*.ref`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1544)*

**Comment by scrye** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[go/sig/config/config.go, line 37 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWM-yH23Cdyiayi46l:-LBaPLlL0a6mhly9y2V7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config.go#L37)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As this is a method of `Cfg`, and `LoadFromFile` is a constructor for `Cfg`, i'd move this after `LoadFromFile`.
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWMrly3d_xtOaz32Sm:-LBaPN-g7Hh0B9xqgb-q:b-qsa4hx) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L30)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be good to document this in `testdata/README.md`.
</blockquote></details>

We'll be using this pattern a lot, so putting a `README.md` in every package that does this feels excessive. We can always add a note on it in the `CONTRIBUTING.md` file (that we should add anyway).

---

*[go/sig/config/config_test.go, line 47 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWPBMTA9caPxCSPgaa:-LBaRER99ad-Qudl40-J:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L47)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Use documentation network ranges:
 https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml - search for Documentation. You're already using the documentation range for v6, so :+1: there.
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 48 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWP3c44uzeIr77jRqf:-LBaQzGg4BkMavDafzwL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L48)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`net.IPv4len`
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWP9e_-n2XitUBeYRi:-LBaQzh59Mq1KjrtFF47:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`net.IPv6len`
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 58 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQ9Je6kc1BOX6NG2h:-LBaR-YB6sticwfKp170:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L58)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Doc net
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQAQxC5dxVdN2WoHL:-LBaR-FBBd4REwvSN17M:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L64)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Doc net
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 73 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQFm49_Htwm8_JGp9:-LBaR0zHDDo0TGHQa0et:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L73)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Doc net
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 74 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQGNC0nHjHKT7S2PF:-LBaR1ID-eM0P37clYQ9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L74)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`net.IPv4len`
</blockquote></details>

Done.

---

*[go/sig/config/config_test.go, line 99 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWQWyP6gwOK996aDHf:-LBaRAxX9WJt7B46MI21:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L99)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As this is a loop, there should be a Convey inside it to indicate which test case is being tested.
</blockquote></details>

Done.

---

*[go/sig/config/testdata/01-loadfromfile.ref, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWJxO13PbPnSJLkQBb:-LBaUayLDEKMSRQbuJ9t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/testdata/01-loadfromfile.ref#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

A `.json` suffix would make tools happier. Same applies to `go/lib/pktcls/testdata/*.ref`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1544)*

**Comment by kormat** [comment]
Reviewed 28 of 32 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sig/config/config_test.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/1544#-LBWMrly3d_xtOaz32Sm:-LBe9lqk4o4RsaO_WO2J:bsgg3c8) ([raw file](https://github.com/scionproto/scion/blob/74a81aa1a02fd386c3cfad1b1b1263ff8139aa51/go/sig/config/config_test.go#L30)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

We'll be using this pattern a lot, so putting a `README.md` in every package that does this feels excessive. We can always add a note on it in the `CONTRIBUTING.md` file (that we should add anyway).
</blockquote></details>

If all testdata could use this approach, then that would probably be fine, but that's not the case (e.g.  `go/lib/hpkt/testdata/README.md` and `go/border/rpkt/testdata/README.md`). That's why i'd prefer to just document it on a case-by-case basis. It will just end up being 1-2 lines for the `-update` method, with the exact command required so it can be copy & pasted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1544)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1544#-:-LBeFkFc0bn2_O_HK4tN:bnfp4nl)*

**Pull request merged**
