### PR TITLE
colibri: advance request handling

### PR DESCRIPTION
**Pull request by juagargi**
- Segment request operations are complete
- E2E request operations with the exception of the admission one are complete

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)

### CODE REVIEW

**Review by Oncilla — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)* status: all files reviewed, 1 unresolved discussion (waiting on @juagargi)

___
*[go/cs/reservationstore/store.go, line 149 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHhz3_4WOPrdpZc2w5:-MGHhz3_4WOPrdpZc2w6:b6oshfk) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L149)):*
> ```Go
> 		return nil, serrors.WrapStr("error validating request", err, "id", req.ID)
> 	}
> 	response, err := s.prepareFailureSegmentResp(&req.Request)
> ```

more of a style comment, so feel free to ignore, since it is really subjective.

I would introduce a new line before this line, and one before `s.db.BeginTransaction` to group according to logical coherence.
___
*[go/cs/reservationstore/store.go, line 180 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHiFZx8YaFApbzbeKi:-MGHiFZx8YaFApbzbeKj:bnb2px3) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L180)):*
> ```Go
> 			"id", req.ID)
> 	}
> 	var msg base.MessageWithPath
> ```

Just do:

```go
	if req.IsLastAS() {
		return &segment.ResponseIndexConfirmationSuccess{
			Response: *morphSegmentResponseToSuccess(response),
		}, nil
	}
	return req, nil
```

same comment for all other methods where this applies.

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)* status: all files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[go/cs/reservationstore/store.go, line 149 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHhz3_4WOPrdpZc2w5:-MGIEsLR1pdNmeVIEg1A:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L149)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

more of a style comment, so feel free to ignore, since it is really subjective.

I would introduce a new line before this line, and one before `s.db.BeginTransaction` to group according to logical coherence.

</blockquote></details>

Done.
___
*[go/cs/reservationstore/store.go, line 180 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHiFZx8YaFApbzbeKi:-MGIEfgVBcMhBujxCGQK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L180)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Just do:

```go
	if req.IsLastAS() {
		return &segment.ResponseIndexConfirmationSuccess{
			Response: *morphSegmentResponseToSuccess(response),
		}, nil
	}
	return req, nil
```

same comment for all other methods where this applies.


</blockquote></details>

Done.

**Review by Oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @juagargi and @Oncilla)

___
*[go/cs/reservationstore/store.go, line 149 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHhz3_4WOPrdpZc2w5:-MGIFGAGDvJJTfgPsrmc:b-z9ecg1) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L149)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It applies to the other methods as well :) 
___
*[go/cs/reservationstore/store.go, line 180 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHiFZx8YaFApbzbeKi:-MGIFN1LCICxJBZPg3Jf:b-jco7jg) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L180)):*
<details><summary><i>Previously, juagargi (Juan A. Garcia Pardo) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

As mentioned, this applies to the other methods as well

**Review by juagargi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @Oncilla)

___
*[go/cs/reservationstore/store.go, line 149 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHhz3_4WOPrdpZc2w5:-MGIH5lq-gLFiyBuuafs:b-93yyxo) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L149)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

It applies to the other methods as well :) 
</blockquote></details>

Done. Done. Too much in a hurry :stuck_out_tongue: 
___
*[go/cs/reservationstore/store.go, line 180 at r1](https://reviewable.io/reviews/scionproto/scion/3859#-MGHiFZx8YaFApbzbeKi:-MGIH31r1L5_E4Ks3h3P:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/12dec14fbc438aed8c3f9018368532642e396dd7/go/cs/reservationstore/store.go#L180)):*
<details><summary><i>Previously, Oncilla (Dominik Roos) wrote…</i></summary><blockquote>

As mentioned, this applies to the other methods as well 
</blockquote></details>

Done.

**Review by Oncilla — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Oncilla — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3859#-:-MGII_WV13xPTbKvGHim:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
