### PR TITLE
scion-pki: moving to cobra style cli (#1490)

### LINKED ISSUE #1490: Integrate CLI library in scion-pki
Currently, the command/subcommand and flag parsing logic is hand-crafted in `scion-pki`. There are awesome libraries out there that do all the heavy-lifting and offer much more functionality. Specifically, we want to integrate https://github.com/spf13/cobra.

### PR DESCRIPTION
**Pull request by jinankjain**
All the commands are moved to commands package inside scion-pki. Closes #1490.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1507)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 8 of 19 files at r1.
Review status: 8 of 19 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/tools/scion-pki/main.go, line 22 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9egR-I1R7kxjbKid0c:-L9egR-I1R7kxjbKid0d:b-16c4o9) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/main.go#L22)):*
> ```Go
> 
> func main() {
> 	cmd.Execute()
> ```

As all of the code in this dir is only for use the `scion-pki` tool, i think i'd prefer a different layout:

- move `commands/root.go` to `internal/cmd/cmd.go`
- For each command X, put its `&cobra.Command` into `internal/x/cmd.go`
- Have `internal/cmd/cmd.go` with an `init()` like:
```
func init() {
  rootCmd.AddCommand(version.Cmd)
  rootCmd.AddCommand(cert.Cmd)
  rootCmd.AddCommand(trc.Cmd)
  ...
}
```
That way the documentation and ui for each command is in the same module as the implementation.

---

*[go/tools/scion-pki/commands/certs.go, line 123 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9eilM_0w1HItk9ARkG:-L9eilM_0w1HItk9ARkH:bw1zzfv) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/certs.go#L123)):*
> ```Go
> 	rootCmd.AddCommand(certCmd)
> 
> 	certCmd.PersistentFlags().BoolVarP(&verify, "verify", "v", true, "verify the generated/renewd certificates")
> ```

Line-length.

s/renewd/renewed/

---

*[go/tools/scion-pki/commands/root.go, line 41 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9efe0e9m7Cg3aSd3Jv:-L9efe0e9m7Cg3aSd3Jw:b-dw4w29) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/root.go#L41)):*
> ```Go
> 
> func init() {
> 	rootCmd.PersistentFlags().BoolVarP(&pkicmn.Force, "force", "f", true, "Overwrite existing certificates (and keys if -genkeys is specified).")
> ```

The default should be `false`, this is dangerous. 

The description seems out-dated. "Overwrite existing keys/certs/trcs" would be more accurate.

Also, we have a limit of 90-100 chars line length for go/python code. This means that once you hit 90 chars on a line, consider wrapping, and definitely wrap before 100 (tabs are counted as 4 spaces in Go for this rule).

---

*[go/tools/scion-pki/commands/verion.go, line 1 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9ej75CAsGICrrUqX90:-L9ej75CAsGICrrUqX91:b63liwk) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/verion.go#L1)):*
> ```Go
> // Copyright 2018 ETH Zurich
> ```

Filename is misspelt :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Comment by jinankjain** [comment]
Review status: 2 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/tools/scion-pki/main.go, line 22 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9egR-I1R7kxjbKid0c:-L9eut0U4BM_xLhMRe6S:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/main.go#L22)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

As all of the code in this dir is only for use the `scion-pki` tool, i think i'd prefer a different layout:

- move `commands/root.go` to `internal/cmd/cmd.go`
- For each command X, put its `&cobra.Command` into `internal/x/cmd.go`
- Have `internal/cmd/cmd.go` with an `init()` like:
```
func init() {
  rootCmd.AddCommand(version.Cmd)
  rootCmd.AddCommand(cert.Cmd)
  rootCmd.AddCommand(trc.Cmd)
  ...
}
```
That way the documentation and ui for each command is in the same module as the implementation.
</blockquote></details>

Done.

---

*[go/tools/scion-pki/commands/certs.go, line 123 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9eilM_0w1HItk9ARkG:-L9euvaK6gWZigKXe1CW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/certs.go#L123)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line-length.

s/renewd/renewed/
</blockquote></details>

Done.

---

*[go/tools/scion-pki/commands/root.go, line 41 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9efe0e9m7Cg3aSd3Jv:-L9euyBC0yK4FIjtMbAS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/root.go#L41)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The default should be `false`, this is dangerous. 

The description seems out-dated. "Overwrite existing keys/certs/trcs" would be more accurate.

Also, we have a limit of 90-100 chars line length for go/python code. This means that once you hit 90 chars on a line, consider wrapping, and definitely wrap before 100 (tabs are counted as 4 spaces in Go for this rule).
</blockquote></details>

Done.

---

*[go/tools/scion-pki/commands/verion.go, line 1 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9ej75CAsGICrrUqX90:-L9ev05tAtCDE_xIHYIq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/verion.go#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Filename is misspelt :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Comment by jinankjain** [comment]
Review status: 16 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/internal/tmpl/cmd.go, line 46 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9ey_qR8WkxDP2LisLJ:-L9f10Kk-sA6fo2b8xT3:bbdi90j) ([raw file](https://github.com/scionproto/scion/blob/bc935d892d514debf9cb96ef7719ac24616082ba/go/tools/scion-pki/internal/tmpl/cmd.go#L46)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The isd-only selectors should be under the `isd` Command, the isd-as selectors should be under the `as` Command.
</blockquote></details>

All selectors needs to be `commands` or `arguments` to sub-commands like as, isd

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Comment by jinankjain** [comment]
Review status: 16 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/tools/scion-pki/commands/certs.go, line 123 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9eilM_0w1HItk9ARkG:-L9f1OyF0H25Q87kXdlx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5096ae3898ae5fa8baec2f22fffc16908cfa7d40/go/tools/scion-pki/commands/certs.go#L123)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"renewd" is still mispelt - it should be "renewed".
</blockquote></details>

Done.

---

*[go/tools/scion-pki/internal/keys/cmd.go, line 40 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1507#-L9ey6ATBAjBfk__Gj6m:-L9f1N3oC4gDrh0_6EpN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bc935d892d514debf9cb96ef7719ac24616082ba/go/tools/scion-pki/internal/keys/cmd.go#L40)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'd prefer to have this above the other `.Command`s, as it's more important, and also exported.

Same logic applies to the other `cmd.go` files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 28 files at r2, 4 of 9 files at r3.
Review status: 20 of 21 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507#-:-L9f3Jx48Knt4_i2d8eM:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Comment by shitz** [comment]
Reviewed 3 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1507)*

**Pull request merged**
