### PR TITLE
launcher: run SCION as services on Windows

### PR DESCRIPTION
**Pull request by lschulz**
Currently there seems to be no way to cleanly terminate a SCION service on Windows. Typing Ctrl-C terminates the program without running cleanup code.

This PR allows running SCION as services on Windows. Applications detect automatically whether they were started as a service or as console applications and will react to control request appropriately. If running as console application Ctrl-C is handled correctly.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4657)

**Review by jiceatscion — COMMENTED** [review]
There seems to be a lot of identical between the windows and unix implementations.  For example the unix version of the Application data structure is a subset of the Windows one. Would mind trying to move more of the common code to launcher.go?

> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657#-:-OCXceiW8ZVub-3mB8zv:bd1pfwq)* status: 1 of 4 files reviewed, all discussions resolved

**Review by lschulz — COMMENTED** [review]
I moved more common code to launcher.go.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657#-:-ODauClN4Y2xu-M6Oy_6:b-bzwo6b)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @jiceatscion)

**Review by jiceatscion — CHANGES_REQUESTED** [review]
Thanks!

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657#-:-OEJGLnb5i6a3ghi-RZ3:b-ucfknh)* status: all files reviewed, 1 unresolved discussion (waiting on @lschulz)

___
*[`private/app/launcher/BUILD.bazel` line 26 at r2](https://reviewable.io/reviews/scionproto/scion/4657#-OEJG5QDCv4bjQOdLKy7:-OEJG5QDCv4bjQOdLKy8:b-8ksmht) ([raw file](https://github.com/scionproto/scion/blob/e94145d5bb3c5a192599814ce5f7ea6a8c21b97c/private/app/launcher/BUILD.bazel#L26)):*
> ```Starlark
>     ] + select({
>         "@io_bazel_rules_go//go/platform:aix": [
>             "//private/app:go_default_library",
> ```

I wonder if it would make sense to reduce all of these to the default case.

**Review by lschulz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`private/app/launcher/BUILD.bazel` line 26 at r2](https://reviewable.io/reviews/scionproto/scion/4657#-OEJG5QDCv4bjQOdLKy7:-OEJwv1984Y3POuGgRgE:b-482vx) ([raw file](https://github.com/scionproto/scion/blob/e94145d5bb3c5a192599814ce5f7ea6a8c21b97c/private/app/launcher/BUILD.bazel#L26)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I wonder if it would make sense to reduce all of these to the default case.
</blockquote></details>

Since only Windows needs the extra dependencies, it probably would make sense.
I tried to reduce the cases to
```
"@io_bazel_rules_go//go/platform:windows": [
    "@org_golang_x_sys//windows/svc:go_default_library",
    "@org_golang_x_sys//windows/svc/debug:go_default_library",
    "@org_golang_x_sys//windows/svc/eventlog:go_default_library",
],
"//conditions:default": [
    "//private/app:go_default_library",
],
```
Like that it is still building on Linux (I had no success to make the Bazel build work on Windows, I always use go build).
However, the lint-go-gazelle linter complains. gazelle wants to restore the full enumeration of every possible platform.

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lschulz)

___
*[`private/app/launcher/BUILD.bazel` line 26 at r2](https://reviewable.io/reviews/scionproto/scion/4657#-OEJG5QDCv4bjQOdLKy7:-OEP6Dy9ChO-Lx_dTp--:b-hsae7z) ([raw file](https://github.com/scionproto/scion/blob/e94145d5bb3c5a192599814ce5f7ea6a8c21b97c/private/app/launcher/BUILD.bazel#L26)):*
<details><summary><i>Previously, lschulz (Lars-Christian Schulz) wrote…</i></summary><blockquote>

Since only Windows needs the extra dependencies, it probably would make sense.
I tried to reduce the cases to
```
"@io_bazel_rules_go//go/platform:windows": [
    "@org_golang_x_sys//windows/svc:go_default_library",
    "@org_golang_x_sys//windows/svc/debug:go_default_library",
    "@org_golang_x_sys//windows/svc/eventlog:go_default_library",
],
"//conditions:default": [
    "//private/app:go_default_library",
],
```
Like that it is still building on Linux (I had no success to make the Bazel build work on Windows, I always use go build).
However, the lint-go-gazelle linter complains. gazelle wants to restore the full enumeration of every possible platform.
</blockquote></details>

Ah, yeah, silly. Nevermind then.

**Review by jiceatscion — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4657#-:-OEP6e8iCLIMx7dfMpZV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lschulz)

**Pull request merged**
