### PR TITLE
Wireshark plugin

### PR DESCRIPTION
**Pull request by FR4NK-W**
Enable plugin to match full range of ISD and AS ids possible given the packet header format

Reason: Be inclusive of SCIONlab ASes with ids > 255

Fix invalid wireshark field type in definition of scion_path_hop_mac

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1415)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/wireshark/scion.lua, line 163 at r1](https://reviewable.io:443/reviews/scionproto/scion/1415#-L6QqYMDufZqtKLJIz82:-L6QqYMECk0HlFjPs9sK:b-xk2avz) ([raw file](https://github.com/scionproto/scion/blob/dbae3df115b98ac31e6c07c88f3e9b6a3d80c2e6/tools/wireshark/scion.lua#L163)):*
> ```Lua
> local scion_path_hop_egress_if = ProtoField.uint64("scion.path.hop.egress_if",
>     "Egress IFID", base.DEC)
> local scion_path_hop_mac = ProtoField.bytes("scion.path.hop.mac", "MAC")
> ```

How is this invalid? It at least displays correctly for me.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1415)*

**Comment by FR4NK-W** [comment]
On Wireshark version 2.4.4, when opening the plugin with the `ProtoField.bytes("scion.path.hop.mac", "MAC", base.HEX)` definition, Wireshark throws the following error:
screen shot 2018-02-28 at 11 07 36

**Comment by kormat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/wireshark/scion.lua, line 163 at r1](https://reviewable.io:443/reviews/scionproto/scion/1415#-L6QqYMDufZqtKLJIz82:-L6QxWtsEGMoR9KXEGXU:bazwxun) ([raw file](https://github.com/scionproto/scion/blob/dbae3df115b98ac31e6c07c88f3e9b6a3d80c2e6/tools/wireshark/scion.lua#L163)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

How is this invalid? It at least displays correctly for me.


</blockquote></details>

Confirming that this change works for wireshark 2.2.6 too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1415#-:-L6Qx_NiURjPaY8o9ZwQ:bnfp4nl)*

**Comment by FR4NK-W** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tools/wireshark/scion.lua, line 163 at r1](https://reviewable.io:443/reviews/scionproto/scion/1415#-L6QqYMDufZqtKLJIz82:-L6ax0kCIpIMPAss05Bd:b-x7vwxi) ([raw file](https://github.com/scionproto/scion/blob/6778c618f7ec10f0e89925d876b1f153664d51fa/tools/wireshark/scion.lua#L163)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Confirming that this change works for wireshark 2.2.6 too.
</blockquote></details>

Is that affirmative from your side?
:lgtm: from my side

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1415)*

**Pull request merged**
