### PR TITLE
pkg/addr: add missing MustParseIA,AS,ISD functions

### PR DESCRIPTION
**Pull request by matzf**
Providing MustParseX along with ParseX is a typical pattern in Go. There was already addr.MustParseAddr (since #4346), but MustParseIA and MustParseAS were only defined as helper function in the internal xtest package.

Define addr.MustParseIA, MustParseAS, MustParseISD to replace the definitions in the xtest package.
Remove the rarely used plural forms, xtest.MustParseIAs/ASes; simply typing this out instead seems perfectly appropriate.

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4564)

**Review by oncilla — APPROVED** [review]
> Reviewed 173 of 173 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4564)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — APPROVED** [review]
:lgtm:

> Reviewed 173 of 173 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4564#-:-O1MesOHCMGqbEeELwOC:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4564)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
