### PR TITLE
naming: make the spelling of ifid, ifidtype, and trc compliant with our guidelines

### LINKED ISSUE #2639: Make spelling of ifid consistent
Currently, the code-base has various spellings for ifid:
`IfId` vs `IFID` vs `IfID` vs `Ifid`

We should decide on a particular spelling and use that consistently.

### PR DESCRIPTION
**Pull request by jiceatscion**
All spellings of these identifiers converted to IfID, ifID, IfIDType, trc and TRC.
Also renamed instances of intfid to ifid for consistency.

Fixes #2639

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)

**Review by matzf — COMMENTED** [review]
This is not implementing the convention that is documented in the (our) style guide: https://docs.scion.org/en/latest/dev/style/go.html#naming:

> -   Use `IfID` or `ifID` for SCION Interface Identifiers, not `IFID` or `InterfaceID`.

To me the capital `ID` spelling is a little bit nicer, its the dictionary spelling after all. Not a strong opinion, but whatever option we pick, the style guide should reflect what is in the code.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569#-:-O1p7_452ASdqt4wML1O:b-uv3quh)* status: 0 of 78 files reviewed, 1 unresolved discussion (waiting on @jiceatscion, @lukedirtwalker, and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4569#-O1pDzUn45X5rvrMG-Rv:-O1pDzUn45X5rvrMG-Rw:b-rr9ynz) (no related file):*
It could make sense to enforce this and the other naming style conventions with a linter rule -- one fewer things to check manually in code reviews.

With "forbidigo", we can forbid all the non-compliant identifer spellings e.g.:
```yaml
linters:
  enable:
    # ....
    - forbidigo
linters-settings:
  # ...
  forbidigo:
    forbid:
    - p: "([iI][fF][iI]d)|([iI]F[iI][dD])|([iI][fF]i[dD])"
      msg: "spell interface ID as ifID / IfID"
    - p: "(?i)interfaceID"  # case insensitive
      msg: "spell interface ID as ifID / IfID"
    - p: "Trc"
      msg: "spell trust root certificate as trc / TRC"
```

___

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 78 files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
According to https://go.dev/wiki/CodeReviewComments (Initialisms) I don't think `IfId` is the appropriate casing.

I also don't think there is a final agreement that the appropriate name is some casing of `ifid`. The name is pretty obscure (similar to IA) and does not mean anything to readers that are not familiar with the code. Case in point in the first SCION book "ifid" does not appear once.

IMO, in most places where ifid is used, some variation of `intf` or `interface` would suffice. When looping over interfaces, identifier could just be called id. It is clear from the context that it identifies an interface.

Finally, instead of touching the `common` package and renaming the type, I would rather get rid of the dependency on the `common` package for the type definition.



_Code quote:_
```
- 92dccfb: Make the spelling of ifidtype compliant with Go casing guidelines.

  IFIDType -> IfIdType
```

**Review by oncilla — COMMENTED** [review]
Fwiw, capital ID is required by https://go.dev/wiki/CodeReviewComments.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569#-:-O1pGwUk498Sb1DD2lW5:b9rbpjy)* status: 0 of 78 files reviewed, 2 unresolved discussions (waiting on @jiceatscion and @lukedirtwalker)

**Comment by jiceatscion** [comment]
Ok, so Go makes a special case for ID. I didn’t remember that given that it
is grammatical absurdity to treat it as an initialism. It is not; it is an
abbreviation. Anyway…. If we want to follow the go style guide why do we
have our own? I’ll take a look. We’d better agree (I thought we had as far
as this issue goes) before I mass-edit another 170 files.


JEAN-CHRISTOPHE HUGLY

Software Engineer


 +41 79 455 68 69
***@***.*** ***@***.***>
 scion.org <http://www.scion.org/>
 SCION Association <https://www.linkedin.com/company/scion-association/>


<https://www.scion.org/>

**Comment by jiceatscion** [comment]
> When looping over interfaces, identifier could just be called id

Nope, it can't, since Go requires that ID is upper case, it being an honorary initialism. I was about to give in to that suggestion when I took notice. Should we just make that "i"? (Sigh... No-one can win at this game... Godel's theorem is probably applicable to naming schemes).

In the mean-time, updated our style guide and the code to reflect what I think is the result of our present conventions.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 88 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

According to https://go.dev/wiki/CodeReviewComments (Initialisms) I don't think `IfId` is the appropriate casing.

I also don't think there is a final agreement that the appropriate name is some casing of `ifid`. The name is pretty obscure (similar to IA) and does not mean anything to readers that are not familiar with the code. Case in point in the first SCION book "ifid" does not appear once.

IMO, in most places where ifid is used, some variation of `intf` or `interface` would suffice. When looping over interfaces, identifier could just be called id. It is clear from the context that it identifies an interface.

Finally, instead of touching the `common` package and renaming the type, I would rather get rid of the dependency on the `common` package for the type definition.
</blockquote></details>

Dominik, not sure what you mean by "get rid of the dependency on the common package". Are you suggesting to just delete the type definition and simply use uint64 everywhere? Why is it a uint64 to begin with; aren't they all supposed to fit in 16 bits, per the protocol definition of hop fields?

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Dominik, not sure what you mean by "get rid of the dependency on the common package". Are you suggesting to just delete the type definition and simply use uint64 everywhere? Why is it a uint64 to begin with; aren't they all supposed to fit in 16 bits, per the protocol definition of hop fields?
</blockquote></details>

I meant to remove the dependency on a catch all `common` package.
How to achieve this, I have not thought through yet :) 

I just  have a distaste for packages like `common` or `util`. They are not single responsibility by nature, and a grab bag of things that do not fit anywhere else.

In any case, this is not very important to me right now, so I will resolve my comment.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I meant to remove the dependency on a catch all `common` package.
How to achieve this, I have not thought through yet :) 

I just  have a distaste for packages like `common` or `util`. They are not single responsibility by nature, and a grab bag of things that do not fit anywhere else.

In any case, this is not very important to me right now, so I will resolve my comment.
</blockquote></details>

FWIW, if we want to keep a type definition like IFIDType, I think `pkg/addr` would be a somewhat appropriate place; an interface identifier is a local address after all.

**Review by jiceatscion — COMMENTED** [review]
Dominik, besides the location of the IfIDType definition (which I don't mind addressing in another PR), do you find the changes acceptable?

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569#-:-O2P8JcX-dI3dCVvqvpb:bpxj6td)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

FWIW, if we want to keep a type definition like IFIDType, I think `pkg/addr` would be a somewhat appropriate place; an interface identifier is a local address after all.
</blockquote></details>

I don't mind moving this. Bug in another PR (just because the issue referenced here has a different topic).

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: 0 of 88 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/scionproto/scion/4569#-O1pEFnfETgNAG8Q51X9):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

I don't mind moving this. Bug in another PR (just because the issue referenced here has a different topic).
</blockquote></details>

Filed: https://github.com/scionproto/scion/issues/4584

**Review by oncilla — APPROVED** [review]
Sure. 

> Reviewed 85 of 86 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569#-:-O2PCp0a9CQBUerLBkbM:bzeyi24)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 67 of 86 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 32 of 32 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion)

___
*[`daemon/internal/servers/grpc.go` line 50 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YGJvG-iwWjGrROCY5:-O2YGJvG-iwWjGrROCY6:b-grv2xw) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/daemon/internal/servers/grpc.go#L50)):*
> ```Go
> 
> type Topology interface {
> 	IfIDs() []uint16
> ```

TBH I'm not a huge fan of this, why do we no longer allow this?
___
*[`scion/showpaths/showpaths.go` line 61 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YFEXP4swUX6loSpwp:-O2YFEXP4swUX6loSpwq:bckg2qu) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/scion/showpaths/showpaths.go#L61)):*
> ```Go
> // Hop represents an hop on the path.
> type Hop struct {
> 	IfID common.IfIDType `json:"ifID"`
> ```

in json we usually use snake_case. I wonder if here it would be clearer if we'd use `interface_id` or `interface` as we use in `cmd/scion/common.go`

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`daemon/internal/servers/grpc.go` line 50 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YGJvG-iwWjGrROCY5:-O2YivbwBc466qgQLsSu:b-i550uc) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/daemon/internal/servers/grpc.go#L50)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

TBH I'm not a huge fan of this, why do we no longer allow this?
</blockquote></details>

We did put an explicit directive in our style guide about it and issue #2639 specifically asks to fix it. 3 voices in favor, no objection since 2019...until I volunteered to fix it, that is :-). We no-longer allow this so that new code doesn't inadvertently violate our style guide.  I personally don't care and I am not sure such a restrictive rule was needed in the style guide. I am just trying to scrub a trivial issue from the backlog. An alternative fix would be to remove the rule from the style guide. More arguing...
___
*[`scion/showpaths/showpaths.go` line 61 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YFEXP4swUX6loSpwp:-O2Yhz7N90JaxEOzmJw2:b-sq8d55) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/scion/showpaths/showpaths.go#L61)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

in json we usually use snake_case. I wonder if here it would be clearer if we'd use `interface_id` or `interface` as we use in `cmd/scion/common.go`
</blockquote></details>

Uh, yes, I agree. It is a string, it doesn't have to comply with go style. I could make it if_id, assuming there aren't many things that depend on this particular schema. Any concerns in that regard?

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`scion/showpaths/showpaths.go` line 61 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YFEXP4swUX6loSpwp:-O2YoASB0qOTSV-uzSYj:bn7lwoi) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/scion/showpaths/showpaths.go#L61)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Uh, yes, I agree. It is a string, it doesn't have to comply with go style. I could make it if_id, assuming there aren't many things that depend on this particular schema. Any concerns in that regard?
</blockquote></details>

please use `interface` so we are consistent with the `Hop` definition in `scion/cmd/common.go`

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`daemon/internal/servers/grpc.go` line 50 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YGJvG-iwWjGrROCY5:-O2YocbWD3jS_RzCYdjj:b4li6bc) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/daemon/internal/servers/grpc.go#L50)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

We did put an explicit directive in our style guide about it and issue #2639 specifically asks to fix it. 3 voices in favor, no objection since 2019...until I volunteered to fix it, that is :-). We no-longer allow this so that new code doesn't inadvertently violate our style guide.  I personally don't care and I am not sure such a restrictive rule was needed in the style guide. I am just trying to scrub a trivial issue from the backlog. An alternative fix would be to remove the rule from the style guide. More arguing...
</blockquote></details>

yeah nevermind.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`scion/showpaths/showpaths.go` line 61 at r5](https://reviewable.io/reviews/scionproto/scion/4569#-O2YFEXP4swUX6loSpwp:-O2Z4B8M8r5tDyBdRM4t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f0d896180f370542cfbef415bc742249a4ae13c0/scion/showpaths/showpaths.go#L61)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

please use `interface` so we are consistent with the `Hop` definition in `scion/cmd/common.go`
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4569)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
