### PR TITLE
doc/design: clarify the life-cycle of a design doc and update existing accordingly

### LINKED ISSUE #4633: doc/design: update review process guidelines regarding tooling
The guidelines for the design review process are fairly precise in the abstract but lack specificity when it comes to the mechanisms to use. One specific issue is that after a proposal is approved and a design doc is submitted, it does not specify how the design document is discussed and finalized. Does the PR for the new design doc remain open (and therefore the design doc unmerged)? That is the implicit consequence of the current wording and seems inconvenient since the only version of the doc is in the PR and in the owner's private branch. It might work well if the design is almost finalized at the time the proposal is approved, but then that implies that all the refinement occurred upstream, during the proposal discussion when the only copy of the proposed design doc is embedded in the proposal issue itself, which is even less convenient.

I suggest amending the process as follows:

* At the end of the proposal review, the design's objectives and general approach are agreed upon, but there might not be an almost finished design doc.
* Following the proposal's approval, a first version of the design doc is submitted as a PR and can be merged if the reviewers think it is going in the right direction. The document is in the state WIP, which is indicated in the document's header. The document is linked to the WIP section of the design docs index.
* Following the merging of the initial revision of the design doc, the proposal issue may be closed or not; I am undecided about that - opinions especially welcome. The next step depends on that:
  * If we keep the original issue: it becomes the vehicle for discussions and subsequent updates to the design, through multiple PRs.
  * If we close the original issue: we open a new one, titled something like "doc/design: finalize xyz", and it becomes the vehicle for discussions and subsequent PRs.
* Once the design doc seems done, we have a call for objections and in the absence of such, we move the document from WIP to final (and into the Active section of the index) and that last PR closes the issue.

If that sounds good I will propose an edit to the guidelines.

Please let me know what you think and which if the two options, if any, you favor.

### PR DESCRIPTION
**Pull request by jiceatscion**
Fixes #4633

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4634)

**Review by FR4NK-W — COMMENTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4634)* status: all files reviewed, 2 unresolved discussions (waiting on @jiceatscion)

___
*[`doc/dev/contribute.rst` line 205 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8D4r1gENJx5IYs4_AK:-O8D4r1gENJx5IYs4_AL:undefined) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/contribute.rst#L205)):*
> ```reStructuredText
> 
>   Once the implementation is deemed complete, the design document's status is changed to
>   **Complete**, it is linked to the corresponding section of the index, and the
> ```





_Suggestion:_
```reStructuredText
Completed
```
___
*[`doc/dev/design/index.rst` line 35 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8D4fMlD_5r7NP89Uz0:-O8D4fMm2i8Mc3wQyAKn:b45h) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/design/index.rst#L35)):*
> ```reStructuredText
> 
>   During implementation the design may also become suspended (**Postponed**)
>   or abandonned (**Rejected** or **Outdated**).
> ```





_Suggestion:_
```reStructuredText
abandoned
```

**Comment by FR4NK-W** [comment]
The capitalization of the status in
- PathService.md
- forwarding-key-rollover.rst
- BeaconService.md
- ColibriService.md

could also be updated for consistency.

**Review by FR4NK-W — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4634)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @jiceatscion)

___
*[`doc/dev/contribute.rst` line 141 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8GV46G4VK6EdHrv61C:-O8GV46G4VK6EdHrv61D:undefined) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/contribute.rst#L141)):*
> ```reStructuredText
> Typical examples for substantial change proposals include:
> 
> * Adding, changing, or removing compontents or functionality
> ```





_Suggestion:_
```reStructuredText
components
```

**Review by jiceatscion — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4634#-:-O8GZWxt3C5trxhVc5k4:b-896fjx)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @FR4NK-W)

___
*[`doc/dev/contribute.rst` line 141 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8GV46G4VK6EdHrv61C:-O8GYg7F97mJMZuyaRZO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/contribute.rst#L141)):*
> ```reStructuredText
> Typical examples for substantial change proposals include:
> 
> * Adding, changing, or removing compontents or functionality
> ```

Done.
___
*[`doc/dev/contribute.rst` line 205 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8D4r1gENJx5IYs4_AK:-O8GYy40Ck3I58369_w1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/contribute.rst#L205)):*
> ```reStructuredText
> 
>   Once the implementation is deemed complete, the design document's status is changed to
>   **Complete**, it is linked to the corresponding section of the index, and the
> ```

Done.
___
*[`doc/dev/design/index.rst` line 35 at r2](https://reviewable.io/reviews/scionproto/scion/4634#-O8D4fMlD_5r7NP89Uz0:-O8GZ9C--OQhsEDF8r-H:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/5dbb7d0428afe09965d8f826471e2e9e63b62ca0/doc/dev/design/index.rst#L35)):*
> ```reStructuredText
> 
>   During implementation the design may also become suspended (**Postponed**)
>   or abandonned (**Rejected** or **Outdated**).
> ```

Done.

**Review by FR4NK-W — APPROVED** [review]
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4634)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
