### PR TITLE
Stricter separation of SIG egress

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)

### CODE REVIEW

**Comment by kormat** [comment]
Do you have any figures for the performance impact (if any) of using interfaces heavily in this PR?

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed, 8 unresolved discussions (waiting on @scrye)

---

*[go/sig/egress/interface.go, line 49 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHSiAF6y0PHf7ciTSX:-LFHSiAF6y0PHf7ciTSY:b-z6fi5n) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/interface.go#L49)):*
> ```Go
> var EgressFreePkts *ringbuf.Ring
> 
> type Session interface {
> ```

These interfaces should have docstrings, also for the methods on them.
Same applies to the other types in this file.

---

*[go/sig/egress/interface.go, line 62 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHSndy4oo4NH46A_sJ:-LFHSndy4oo4NH46A_sK:b-x0gww5) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/interface.go#L62)):*
> ```Go
> }
> 
> type Worker interface {
> ```

Suggestion: consolidate Worker/Reader/Dispatcher into a single interface:
```
type Runner interface {
   Run()
}
```
If they ever diverge in the future, it's easy to separate as needed.

---

*[go/sig/egress/session/session.go, line 38 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHY-IW2hs4N6eyg6lj:-LFHY-IW2hs4N6eyg6lk:b-i3i6vd) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L38)):*
> ```Go
> // Session contains a pool of paths to the remote AS, metrics about those paths,
> // as well as maintaining the currently favoured path and remote SIG to use.
> type Session struct {
> ```

Add interface assertions for types which implement interfaces from `egress/interface.go`

---

*[go/sig/egress/session/session.go, line 43 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHTIcz7ZPO0fpEkV0T:-LFHTIcz7ZPO0fpEkV0U:b-ylm4bo) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L43)):*
> ```Go
> 	SessId mgmt.SessionType
> 
> 	// FIXME(scrye): initialize pool
> ```

I suspect this is an obsolete FIXME - a (presumably initialized) pool is passed into the constructor.

---

*[go/sig/egress/session/session.go, line 63 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHWcfi0WGckHm12nfD:-LFHWcfjAyAtAruvA3DP:bjtr9z7) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L63)):*
> ```Go
> 	sigMap *siginfo.SigMap, logger log.Logger,
> 	pool egress.PathPool,
> 	factory egress.WorkerFactory) (*Session, error) {
> ```

```
func NewSession(dstIA addr.IA, sessId mgmt.SessionType, sigMap *siginfo.SigMap, logger log.Logger,
	pool egress.PathPool, factory egress.WorkerFactory) (*Session, error) {
```

---

*[go/sig/egress/session/session.go, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHXDeW7i72KWvkKlc4:-LFHXDeW7i72KWvkKlc5:b-pe3iu8) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L141)):*
> ```Go
> }
> 
> func (s *Session) ChooseSess(b common.RawBytes) egress.Session {
> ```

I'm not sure that it makes sense to define this _here_. In a system with multiple sessions `ChooseSess` would be implemented on a different type. This probably belongs on `base.ASEntry`.

---

*[go/sig/egress/session/session.go, line 155 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHXofZBrb4_QMx9qvl:-LFHXofZBrb4_QMx9qvm:bnhfb1l) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L155)):*
> ```Go
> 		return nil, common.NewBasicError("Unable to register watch", err)
> 	}
> ```

Blank line.

---

*[go/sig/egress/reader/reader.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHYhJt6pA4i4sLERBC:-LFHYhJuCXWZtvWoUWLc:biu9jd7) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/reader/reader.go#L15)):*
> ```Go
> // limitations under the License.
> 
> package reader
> ```

These packages need docstrings.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616#-:-LFHYRsK53pRGfWWGMi1:b-oh39o7)*

**Comment by scrye** [comment]
I haven't done any measurements.

When compared in a micro-benchmark manner, the interface version should be a few orders of magnitude slower due to the compiler not being able to inline (I'm seeing 20x degradation, others cited 45x https://github.com/golang/go/issues/20116). However, we're still talking about a few nanoseconds per packet, a few function calls. I think performance is mostly affected by other areas (e.g., socket I/O), until we start routing a few million packets / second at least.

In short, I believe it's premature to count how many function calls we have in our Go fastpath.

---

Review status: all files reviewed, 8 unresolved discussions (waiting on @kormat and @scrye)

---

*[go/sig/egress/interface.go, line 49 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHSiAF6y0PHf7ciTSX:-LFSpgk_195mqJLXv1HX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/interface.go#L49)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These interfaces should have docstrings, also for the methods on them.
Same applies to the other types in this file.
</blockquote></details>

Done.

---

*[go/sig/egress/interface.go, line 62 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHSndy4oo4NH46A_sJ:-LFStMMK-G4jdzR0V0li:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/interface.go#L62)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Suggestion: consolidate Worker/Reader/Dispatcher into a single interface:
```
type Runner interface {
   Run()
}
```
If they ever diverge in the future, it's easy to separate as needed.
</blockquote></details>

Done.

---

*[go/sig/egress/session/session.go, line 38 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHY-IW2hs4N6eyg6lj:-LFSyRf04jkO9Tr0Bp-1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L38)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add interface assertions for types which implement interfaces from `egress/interface.go`
</blockquote></details>

Done.

---

*[go/sig/egress/session/session.go, line 43 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHTIcz7ZPO0fpEkV0T:-LFSyUYJE20au_M9s5hf:binbgdj) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L43)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I suspect this is an obsolete FIXME - a (presumably initialized) pool is passed into the constructor.
</blockquote></details>

Correct, removed.

---

*[go/sig/egress/session/session.go, line 63 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHWcfi0WGckHm12nfD:-LFSyYjt5AKapC0Ua9NQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L63)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

```
func NewSession(dstIA addr.IA, sessId mgmt.SessionType, sigMap *siginfo.SigMap, logger log.Logger,
	pool egress.PathPool, factory egress.WorkerFactory) (*Session, error) {
```
</blockquote></details>

Done.

---

*[go/sig/egress/session/session.go, line 141 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHXDeW7i72KWvkKlc4:-LFWRQil9eLBbij2UOrF:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L141)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm not sure that it makes sense to define this _here_. In a system with multiple sessions `ChooseSess` would be implemented on a different type. This probably belongs on `base.ASEntry`.
</blockquote></details>

Done.

---

*[go/sig/egress/session/session.go, line 155 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHXofZBrb4_QMx9qvl:-LFWUbCu02ZLOlru8vZQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/session/session.go#L155)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Blank line.
</blockquote></details>

Done.

---

*[go/sig/egress/reader/reader.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1616#-LFHYhJt6pA4i4sLERBC:-LFSxfA6BtXqjRWZmmGd:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/57eddd1978d68fdd31007a063b5de4e6fdc00e7d/go/sig/egress/reader/reader.go#L15)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These packages need docstrings.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616#-:-LFSY_na1XKoGHFOglPD:b-623od9)*

**Comment by kormat** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed, 3 unresolved discussions (waiting on @scrye)

---

*[go/sig/base/selector.go, line 24 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFW_JPJ5G5AwjBvkKz1:-LFW_JPJ5G5AwjBvkKz2:b-6qvn0t) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/base/selector.go#L24)):*
> ```Go
> var _ egress.SessionSelector = (*SingleSession)(nil)
> 
> // SingleSession implements egress.SingleSession, returning the contained
> ```

"implements egress.SessionSelector"

---

*[go/sig/egress/interface.go, line 65 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFW_Yes29AnYipL9DNR:-LFW_Yes29AnYipL9DNS:bkc4g7z) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/egress/interface.go#L65)):*
> ```Go
> 	// Cleanup shuts down the session and cleans resources.
> 	Cleanup() error
> 	// Healthy returns true if the session is receiving keepalives from the remote SIG.
> ```

"Healthy returns true if the session has a remote SIG and is receiving keepalive responses from it."

---

*[go/sig/egress/dispatcher/dispatcher.go, line 87 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFWb55z0XSwi-8fjPP4:-LFWb55z0XSwi-8fjPP5:bnhfb1l) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/egress/dispatcher/dispatcher.go#L87)):*
> ```Go
> 	counters.Pkts.Inc()
> 	counters.Bytes.Add(float64(read))
> ```

Blank line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Comment by scrye** [comment]
Review status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @kormat)

---

*[go/sig/base/selector.go, line 24 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFW_JPJ5G5AwjBvkKz1:-LFX-MZBC8ons2HM9vW-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/base/selector.go#L24)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"implements egress.SessionSelector"
</blockquote></details>

Done.

---

*[go/sig/egress/interface.go, line 65 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFW_Yes29AnYipL9DNR:-LFX-Xu6CoFangGDerm0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/egress/interface.go#L65)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"Healthy returns true if the session has a remote SIG and is receiving keepalive responses from it."
</blockquote></details>

Done.

---

*[go/sig/egress/dispatcher/dispatcher.go, line 87 at r2](https://reviewable.io/reviews/scionproto/scion/1616#-LFWb55z0XSwi-8fjPP4:-LFX-cC-66sbRgCi__fL:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f08000c478a0332ac89c8299b8e7f8fb489e609b/go/sig/egress/dispatcher/dispatcher.go#L87)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Blank line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616#-:-LFX0KFu2SVZTrKLi9Ae:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed, 1 unresolved discussion (waiting on @scrye)

---

*[go/sig/base/as.go, line 73 at r4](https://reviewable.io/reviews/scionproto/scion/1616#-LFaZMR_8MTGF0do72jo:-LFaZMR_8MTGF0do72jp:bftyao1) ([raw file](https://github.com/scionproto/scion/blob/9a9837161fe78c5200537be078cba51df39136a4/go/sig/base/as.go#L73)):*
> ```Go
> 		return nil, err
> 	}
> 	if ae.Session, err = session.NewSession(ia, 0, ae.Sigs, ae.Logger, pool, worker.DefaultFactory); err != nil {
> ```

Line length.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Comment by kormat** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @scrye)

---

*[go/sig/base/as.go, line 364 at r4](https://reviewable.io/reviews/scionproto/scion/1616#-LFa_DjS7iRivqeAG6Ng:-LFa_DjS7iRivqeAG6Nh:b-g6raid) ([raw file](https://github.com/scionproto/scion/blob/9a9837161fe78c5200537be078cba51df39136a4/go/sig/base/as.go#L364)):*
> ```Go
> }
> 
> func (ae *ASEntry) setupNet() error {
> ```

The return value is always nil, so it can be dropped.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Comment by scrye** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @kormat)

---

*[go/sig/base/as.go, line 73 at r4](https://reviewable.io/reviews/scionproto/scion/1616#-LFaZMR_8MTGF0do72jo:-LFb86Dk7-KCrtWtzhGJ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9a9837161fe78c5200537be078cba51df39136a4/go/sig/base/as.go#L73)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/sig/base/as.go, line 364 at r4](https://reviewable.io/reviews/scionproto/scion/1616#-LFa_DjS7iRivqeAG6Ng:-LFb8F5J9obT2FBg2b5R:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/9a9837161fe78c5200537be078cba51df39136a4/go/sig/base/as.go#L364)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The return value is always nil, so it can be dropped.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r5.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1616)*

**Pull request merged**
