### PR TITLE
Return an error when reversing an empty SCION path

### PR DESCRIPTION
**Pull request by jcp19**
Fixes issue #4241.

I introduced a separate test `TestEmptyRawReverse` instead of adding an extra case to `TestRawReverse` because the test cases of the latter are shared with the test for reversing `Decoded` paths, which expects that reversing a `Decoded` yields a `Decoded`. Putting everything in the same test can be done with a bigger change-set though.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)

### CODE REVIEW

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)* status: all files reviewed, 1 unresolved discussion (waiting on @jcp19)

___
*[`pkg/slayers/path/scion/decoded.go` line 98 at r1](https://reviewable.io/reviews/scionproto/scion/4242#-N96dpRb7Ym1sn21KS8G:-N96dpRb7Ym1sn21KS8H:beoy2zi) ([raw file](https://github.com/scionproto/scion/blob/c9061d18780856160493ba881c013bfb8b59fec5/pkg/slayers/path/scion/decoded.go#L98)):*
> ```Go
> 	if s.NumINF == 0 {
> 		// Empty path doesn't need reversal.
> 		return empty.Path{}, nil
> ```

This is not the proper fix. A decoded path that is "empty" is not valid and reversing it should return an error. For the empty path we explicitly have the empty path type.

**Review by jcp19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @shitz)

___
*[`pkg/slayers/path/scion/decoded.go` line 98 at r1](https://reviewable.io/reviews/scionproto/scion/4242#-N96dpRb7Ym1sn21KS8G:-N96z8i63yw2aJMH-h4R:b-thfyhr) ([raw file](https://github.com/scionproto/scion/blob/3957386b60c7ca901da1005e19a08405af9a79c9/pkg/slayers/path/scion/decoded.go#L98)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

This is not the proper fix. A decoded path that is "empty" is not valid and reversing it should return an error. For the empty path we explicitly have the empty path type.
</blockquote></details>

I changed this to return an error message

**Review by shitz — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)* status: all files reviewed, 1 unresolved discussion (waiting on @jcp19)

___
*[`pkg/slayers/path/scion/raw_test.go` line 91 at r1](https://reviewable.io/reviews/scionproto/scion/4242#-N97IrhZ9A9prZ0hamSN:-N97IrhZ9A9prZ0hamSO:b-7ejxlw) ([raw file](https://github.com/scionproto/scion/blob/3957386b60c7ca901da1005e19a08405af9a79c9/pkg/slayers/path/scion/raw_test.go#L91)):*
> ```Go
> }
> 
> func TestEmptyRawReverse(t *testing.T) {
> ```

The same test is also needed for the decoded path (they internally use the same reverse logic, however, that's an implementation detail that might change at some point).

**Review by jcp19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @shitz)

___
*[`pkg/slayers/path/scion/raw_test.go` line 91 at r1](https://reviewable.io/reviews/scionproto/scion/4242#-N97IrhZ9A9prZ0hamSN:-N97S36i-cIhATCsN-20:b-896fja) ([raw file](https://github.com/scionproto/scion/blob/3957386b60c7ca901da1005e19a08405af9a79c9/pkg/slayers/path/scion/raw_test.go#L91)):*
<details><summary><i>Previously, shitz (Samuel Hitz) wrote…</i></summary><blockquote>

The same test is also needed for the decoded path (they internally use the same reverse logic, however, that's an implementation detail that might change at some point).
</blockquote></details>

Done!

**Review by shitz — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4242)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcp19)

**Pull request merged**
