### PR TITLE
Add simple show SCION paths tool

### PR DESCRIPTION
**Pull request by sgmonroy**
The tool displays the paths returned by SCIOND

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1400)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 1 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gmhCr6-ApUEUYSWOR:-L4gmhCr6-ApUEUYSWOS:bb6ht2i) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L1)):*
> ```Go
> // Copyright 2017 ETH Zurich
> ```

2018

---

*[go/tools/showpaths/paths.go, line 35 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gpGlfDqsb-MkUri3e:-L4gpGlfDqsb-MkUri3f:b-vefxna) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L35)):*
> ```Go
> 	srcIAStr       = flag.String("srcIA", "", "Source IA address: ISD-AS")
> 	sciondPath     = flag.String("sciond", "", "SCIOND socket path")
> 	dispatcherPath = flag.String("dispatcher", "/run/shm/dispatcher/default.sock",
> ```

Add loglevel flag and set the default to `INFO`

---

*[go/tools/showpaths/paths.go, line 89 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4goy73eEvK9rbL7wjf:-L4goy73eEvK9rbL7wjg:b-2gaq60) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L89)):*
> ```Go
> 	PathMgr = snet.DefNetwork.PathResolver()
> 
> 	pathSet := PathMgr.Query(srcIA, dstIA)
> ```

Also print something like `Available Paths to <IA>:`

---

*[go/tools/showpaths/Readme.md, line 5 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gpluizs2XbFgxStLo:-L4gpluizs2XbFgxStLp:b-e1xgmb) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/Readme.md#L5)):*
> ```Markdown
> Then, run the application using:
> ```
> go run paths.go -dstIA 2-26 -srcIA 1-10
> ```

I'd rather you mention `make` and then use `./bin/showpaths ...`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by kormat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 47 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l5YWfow9pC54r_0hh:-L4l5YWfow9pC54r_0hi:buo5lug) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L47)):*
> ```Go
> )
> 
> func validateFlags() {
> ```

Our coding style is to put functions/methods roughly in order of execution order/importance/etc. So i would move this below `main()`.

---

*[go/tools/showpaths/paths.go, line 51 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l5umLCONzyMYkOmLC:-L4l5umLCONzyMYkOmLD:b2o6h6a) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L51)):*
> ```Go
> 
> 	flag.Parse()
> ```

Go code tends to have lots of lines that are just `}`, so blank lines aren't often needed for readability. In general the only case i'd use them is when it's a fairly long function, and it has distinct phases (e.g. multi-step setup, use, cleanup).

---

*[go/tools/showpaths/paths.go, line 54 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l7E9VRFVDjYcYDExr:-L4l7E9WRMDHzcSp9n9e:bc0zlh0) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L54)):*
> ```Go
> 	dstIA, err = addr.IAFromString(*dstIAStr)
> 	if err != nil {
> 		LogFatal("dstIA:", err)
> ```

Our logging library expects a string followed by pairs of key/values (where the keys are strings). Otherwise you end up with logging like this:

`dstIA:                                   LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"`

The error message is also not very descriptive. Suggestion:

`LogFatal("Unable to parse destination IA", "err", err)`

---

*[go/tools/showpaths/paths.go, line 81 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l930EqUvf_kdxh1Bg:-L4l930EqUvf_kdxh1Bh:b9br1tb) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L81)):*
> ```Go
> 
> 	validateFlags()
> 	liblog.Setup(*id)
> ```

FYI only

Huh. You know, we've never had an actual simple scion client in Go before, which means `liblog` doesn't _not_ logging to a file. We should fix that, as it doesn't make sense for a simple tool like this to have a log file by default. Filed #1407 to track this.

---

*[go/tools/showpaths/paths.go, line 91 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l8OsslgELKxHLWpU8:-L4l8OsslgELKxHLWpU9:b-edcuf6) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L91)):*
> ```Go
> 		LogFatal("Initizaling SCION local networking module", "err", common.FmtError(err))
> 	}
> 	PathMgr = snet.DefNetwork.PathResolver()
> ```

The convention is that local vars start with a lower-case letter.

---

*[go/tools/showpaths/paths.go, line 103 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l7oqfhNNJmuRnbgbt:-L4l7oqfhNNJmuRnbgbu:b-fxpfis) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L103)):*
> ```Go
> 
> func LogFatal(msg string, a ...interface{}) {
> 	log.Crit(msg, a...)
> ```

The log needs to be flushed before exiting, otherwise some messages can get lost.

`liblog.Flush()` just before `os.Exit` does the trick.

Ah, and there's no flush at the end of `main()` either, so the log file doesn't get created most of the time. I suggest adding `defer liblog.Flush()` just after the existing `defer` statement in `main()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by kormat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by sgmonroy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 1 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gmhCr6-ApUEUYSWOR:-L4lB-_XM1FtvGgYEENc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L1)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

2018
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 35 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gpGlfDqsb-MkUri3e:-L4lB4sJWP9GGbmhWI0R:bwrrpra) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L35)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Add loglevel flag and set the default to `INFO`
</blockquote></details>

As it turned out, it was already adding liblog flags, so just proper setup was required.

---

*[go/tools/showpaths/paths.go, line 89 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4goy73eEvK9rbL7wjf:-L4lDKBmrReN-mJSFQvu:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/paths.go#L89)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Also print something like `Available Paths to <IA>:`
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 47 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l5YWfow9pC54r_0hh:-L4lCDl4YfvuBBNLP85I:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L47)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Our coding style is to put functions/methods roughly in order of execution order/importance/etc. So i would move this below `main()`.
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 51 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l5umLCONzyMYkOmLC:-L4lCUl1d2Q69UR-De_t:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L51)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Go code tends to have lots of lines that are just `}`, so blank lines aren't often needed for readability. In general the only case i'd use them is when it's a fairly long function, and it has distinct phases (e.g. multi-step setup, use, cleanup).
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 54 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l7E9VRFVDjYcYDExr:-L4lCmZvFJmQocSgOzb1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L54)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Our logging library expects a string followed by pairs of key/values (where the keys are strings). Otherwise you end up with logging like this:

`dstIA:                                   LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"`

The error message is also not very descriptive. Suggestion:

`LogFatal("Unable to parse destination IA", "err", err)`
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 91 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l8OsslgELKxHLWpU8:-L4lDJZ3dexfR9d0Jtps:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L91)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The convention is that local vars start with a lower-case letter.
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 103 at r2](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4l7oqfhNNJmuRnbgbt:-L4lDpmnhRGlINiRgEoj:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/bb7665a2c8efe6f6aac0cf38e463da43fb648b90/go/tools/showpaths/paths.go#L103)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The log needs to be flushed before exiting, otherwise some messages can get lost.

`liblog.Flush()` just before `os.Exit` does the trick.

Ah, and there's no flush at the end of `main()` either, so the log file doesn't get created most of the time. I suggest adding `defer liblog.Flush()` just after the existing `defer` statement in `main()`.
</blockquote></details>

Done.

---

*[go/tools/showpaths/Readme.md, line 5 at r1](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4gpluizs2XbFgxStLo:-L4lDvq72DwI-NTR-hja:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/56de14d75310b1622f6a0351a8302647faa04348/go/tools/showpaths/Readme.md#L5)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I'd rather you mention `make` and then use `./bin/showpaths ...`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400#-:-L4ohEjPmkWu_gGwQGl6:bnfp4nl)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400#-:-L4pJMQheHjJt__tedei:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 37 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPT6kTN3dpHmPwLZJ:-L4pPT6kTN3dpHmPwLZK:b-ibabq) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L37)):*
> ```Go
> 	id         = flag.String("id", "paths", "Element ID")
> 	sciondPath = flag.String("sciond", "", "SCIOND socket path")
> 	timeout    = flag.Int("timeout", 5000, "SCIOND connection timeout in ms")
> ```

This can just be `flag.Duration`.

---

*[go/tools/showpaths/paths.go, line 57 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPdHvbPdJLfDFgk0P:-L4pPdHvbPdJLfDFgk0Q:b9mpjbx) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L57)):*
> ```Go
> 
> 	sd := sciond.NewService(*sciondPath)
> 	sdConn, err := sd.ConnectTimeout(time.Duration(*timeout * 1000))
> ```

This calculation is wrong, it will actually convert it to microseconds. This goes away if you use flag.Duration, but for reference the correct thing is `time.Duration(*timeout) * time.Millisecond`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by sgmonroy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 37 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPT6kTN3dpHmPwLZJ:-L4pSSsnF601hu1zy3F1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L37)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can just be `flag.Duration`.
</blockquote></details>

Done.

---

*[go/tools/showpaths/paths.go, line 57 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPdHvbPdJLfDFgk0P:-L4pSTUmr5TIjNrxSrmy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L57)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This calculation is wrong, it will actually convert it to microseconds. This goes away if you use flag.Duration, but for reference the correct thing is `time.Duration(*timeout) * time.Millisecond`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/tools/showpaths/paths.go, line 37 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPT6kTN3dpHmPwLZJ:-L4pxThJUXdkbLT1w2Gd:b-n1ouj3) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L37)):*
<details><summary><i>Previously, sgmonroy wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, the default and description need to change, too. For a 2s timeout, that would be `2 * time.Second`.  The value supplied by the user isn't ms, it's whatever https://golang.org/pkg/time/#ParseDuration supports, so i suggest something like `"SCIOND connection timeout (e.g. 250ms)"`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by sgmonroy** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/tools/showpaths/paths.go, line 37 at r4](https://reviewable.io:443/reviews/scionproto/scion/1400#-L4pPT6kTN3dpHmPwLZJ:-L4q0EAku_A9dG5CLnsC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/8df757f707b98c7e46bf30e165814cfe7c77247e/go/tools/showpaths/paths.go#L37)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Ah, the default and description need to change, too. For a 2s timeout, that would be `2 * time.Second`.  The value supplied by the user isn't ms, it's whatever https://golang.org/pkg/time/#ParseDuration supports, so i suggest something like `"SCIOND connection timeout (e.g. 250ms)"`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1400#-:-L4q7YFSuUm7sLwi6w5F:bnfp4nl)*

**Pull request merged**
