### PR TITLE
deps: upgrade gazelle and rules_go

### PR DESCRIPTION
**Pull request by matzf**
gazelle v0.24.0 -> v0.25.0; this should bring a nice performance improvement (https://github.com/bazelbuild/bazel-gazelle/pull/1201)
rules_go: v0.31.0 -> v0.33.0

The `gomock` rule from jmhodges/bazel_gomock has been integrated into
rules_go. We now use the rules_go version.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)

### CODE REVIEW

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 61 files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-N3xqcVA-OzTvBS5dCjt:-N3xqcVA-OzTvBS5dCju:bwuh6i7) (no related file):*
We tried to switch to the new mode internally some time ago, but we were hit by this issue: https://github.com/bazelbuild/bazel-gazelle/issues/1217

___

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 61 files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-N3xqcVA-OzTvBS5dCjt:-N3xr1Ni17tzL9NB0Nyy:b-zhrado) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

We tried to switch to the new mode internally some time ago, but we were hit by this issue: https://github.com/bazelbuild/bazel-gazelle/issues/1217
</blockquote></details>

Looks like CI has is also hitting this:

```
(08:57:01) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/83f5785076a7eab6c530a6914235ae1f/external/com_github_uber_jaeger_client_go/internal/spanlog/BUILD.bazel:3:11: GoCompilePkg external/com_github_uber_jaeger_client_go/internal/spanlog/spanlog.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_uber_jaeger_client_go/internal/spanlog/json.go -embedroot '' ... (remaining 20 arguments skipped)
 
Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/83f5785076a7eab6c530a6914235ae1f/sandbox/linux-sandbox/362/execroot/com_github_scionproto_scion/external/com_github_uber_jaeger_client_go/internal/spanlog/json.go: import of "github.com/opentracing/opentracing-go/log"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
(08:57:01) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/83f5785076a7eab6c530a6914235ae1f/external/com_github_grpc_ecosystem_go_grpc_middleware/util/metautils/BUILD.bazel:3:11: GoCompilePkg external/com_github_grpc_ecosystem_go_grpc_middleware/util/metautils/metautils.a failed: (Exit 1): builder failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -src external/com_github_grpc_ecosystem_go_grpc_middleware/util/metautils/doc.go ... (remaining 24 arguments skipped)
 
Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
	/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/83f5785076a7eab6c530a6914235ae1f/sandbox/linux-sandbox/359/execroot/com_github_scionproto_scion/external/com_github_grpc_ecosystem_go_grpc_middleware/util/metautils/nicemd.go: import of "google.golang.org/grpc/metadata"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //:scion failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

___

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 62 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-N3xqcVA-OzTvBS5dCjt:-N3yRP3G3tePxoMCC1_t:b-chbyni) (no related file):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The [rules_go v0.33.0 release](https://github.com/bazelbuild/rules_go/releases/tag/v0.33.0) includes a version update for `org_golang_x_xerrors`. This is effectively the workaround that @lukedirtwalker had proposed in the issue you linked (just commented commented this there as well).

I've not figured out what problem the CI is having here with the licenses -- i cannot reproduce this locally.
</blockquote></details>

Regarding the build failure in the licenses check, I can now sort of reproduce what's happening. It's weird.

From a clean cache, `bazel build //:scion` builds fine. 
If we, however, remove _all_ of the dependencies from `go_deps.bzl` and run `gazelle update-repos ...`, getting back an unchanged `go_deps.bzl`, gazelle appears to go into a broken state. The `BUILD.bazel` files that gazelle generates for the external `go_repository`s don't list the other external dependencies in `deps` (note that this only affects the "hidden" `BUILD.bazel` files in the cache and is not visible in the repository). After a `bazel clean --expunge` and everything works again.
As far as I can tell after some experiments, this really only hits when we remove _all_ the dependencies from `go_deps.bzl`.

This also clarifies why this would happen exactly during the "check generated" CI step. The first substep there is to run `make go_deps.bzl` which, until #4213, did exactly what is described above (remove all dependencies from `go_deps.bzl` and then run `gazelle update-repos`). After that,`bazel build` on the same agent would fail.

Ater rebasing this branch on top of the now merged #4213 this no longer hits, but only by chance. I'm not sure whether this should now be considered working properly :confused: 

___

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 62 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-N3xqcVA-OzTvBS5dCjt:-N40su0M-GNOyYzH5zVR:bagvegx) (no related file):*
> @lukedirtwalker, you added that in 7decb3b. Am I guessing right that you tried upgrading to gazelle v0.25 but then gave up on this?

Yes

> The rules_go v0.33.0 release includes a version update for org_golang_x_xerrors. This is effectively the workaround that @lukedirtwalker had proposed in the issue you linked (just commented commented this there as well).

I'm not sure that this is the only problem, I think this was just the first library the error showed itself.

___

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 62 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @matzf, and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-N3xqcVA-OzTvBS5dCjt:-N40xbC63xOLy6FUjE96:bv3muaa) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> @lukedirtwalker, you added that in 7decb3b. Am I guessing right that you tried upgrading to gazelle v0.25 but then gave up on this?

Yes

> The rules_go v0.33.0 release includes a version update for org_golang_x_xerrors. This is effectively the workaround that @lukedirtwalker had proposed in the issue you linked (just commented commented this there as well).

I'm not sure that this is the only problem, I think this was just the first library the error showed itself.
</blockquote></details>

I think for now we should either set it explicitly to `external` or wait a bit to see the feedback on https://github.com/bazelbuild/bazel-gazelle/pull/1264

___

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4214)* status: 0 of 62 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4214#-NAhI8YH7IY4TNcEcWK6:-NAhI8YI9BRYYY5I146M:b-tkukss) (no related file):*
This is probably obsolete, once we merge https://github.com/scionproto/scion/pull/4248

___

**Pull request closed without merging**
