### PR TITLE
private/env: remove RunsInDocker during startup log

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR tries to remove a Linux-only dependency for running SCION applications of other platforms. The `RunsUnDocker()` method is the Linux-only call, thus we check whether we are running in Docker only in Linux platform. I am in favor of even removing this log line, supporting @matzf comment on https://reviewable.io/reviews/scionproto/scion/4344#-Nt_IGRG4RbvC-PCVToV.

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4499)

**Review by matzf — CHANGES_REQUESTED** [review]
Indeeed, I'd propose to remove `RunsInDocker` entirely; I can't quite see the usefulness of this information.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4499#-:-Nux0wfHE6t4Sbc0w0CH:b6egfz2)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira)

___
*[`private/env/logging.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4499#-Nux3HMJ0J-Klo2EVKL1:-Nux3HMJ0J-Klo2EVKL2:b-2pd7l6) ([raw file](https://github.com/scionproto/scion/blob/1e322d884a61755232e0c8566a54d2c03254072f/private/env/logging.go#L45)):*
> ```Go
> 			return serrors.WrapStr("Unable to determine if running in docker", err)
> 		}
> 	}
> ```

If we do keep the `RunsInDocker` check, I'd propose to apply the same pattern as the implementation in statuspages.go; attempt to call `RunsInDocker` and entirely omit the line if the call errors.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4499)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`private/env/logging.go` line 45 at r1](https://reviewable.io/reviews/scionproto/scion/4499#-Nux3HMJ0J-Klo2EVKL1:-NuxUc5T-6Vv9xuAfv8V:bd5oigj) ([raw file](https://github.com/scionproto/scion/blob/1e322d884a61755232e0c8566a54d2c03254072f/private/env/logging.go#L45)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

If we do keep the `RunsInDocker` check, I'd propose to apply the same pattern as the implementation in statuspages.go; attempt to call `RunsInDocker` and entirely omit the line if the call errors.
</blockquote></details>

Done, after removing it completely.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4499)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

**Review by oncilla — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4499)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4499)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
