### PR TITLE
build: update antlr version

### PR DESCRIPTION
**Pull request by oncilla**
NO_CHANGELOG

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`nogo.json` line 72 at r2](https://reviewable.io/reviews/scionproto/scion/4555#-O0Jjp9SANTjlqdyFlXI:-O0Jjp9SANTjlqdyFlXJ:b-wd7l3i) ([raw file](https://github.com/scionproto/scion/blob/157b41ca2d9eddd3fec8dc8ac3bc248440edc8ea/nogo.json#L72)):*
> ```JSON
>             "antlr": "",
>             "gazelle/pathtools/path.go": "",
>             "/com_github_antlr_antlr4_runtime_go_antlr/": "",
> ```

can this be removed then?
___
*[`nogo.json` line 228 at r2](https://reviewable.io/reviews/scionproto/scion/4555#-O0JjleQCyEtFJvjm1w0:-O0JjleRBQ6WhKHkYHEk:b-gpl7zl) ([raw file](https://github.com/scionproto/scion/blob/157b41ca2d9eddd3fec8dc8ac3bc248440edc8ea/nogo.json#L228)):*
> ```JSON
>         }
>     }
> }
> ```

add newline?
___
*[`WORKSPACE` line 60 at r2](https://reviewable.io/reviews/scionproto/scion/4555#-O0JkCZNEEOelsx_9BZu:-O0JkCZNEEOelsx_9BZv:b7punee) ([raw file](https://github.com/scionproto/scion/blob/157b41ca2d9eddd3fec8dc8ac3bc248440edc8ea/WORKSPACE#L60)):*
> ```Starlark
> go_register_toolchains(
>     nogo = "@//:nogo",
>     version = "1.21.11",
> ```

shouldn't that match the version in go.mod?

**Review by matzf — APPROVED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: all files reviewed, 3 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`WORKSPACE` line 60 at r2](https://reviewable.io/reviews/scionproto/scion/4555#-O0JkCZNEEOelsx_9BZu:-O0PFYLCAU0yUwoF0OwG:b-b5uo50) ([raw file](https://github.com/scionproto/scion/blob/157b41ca2d9eddd3fec8dc8ac3bc248440edc8ea/WORKSPACE#L60)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

shouldn't that match the version in go.mod?
</blockquote></details>

If we don't want to bump our go version as a side effect of this, note that antlr-go 4.13.0 seems to be compatible with go 1.21, and judging from the [diff between these versions](https://github.com/antlr4-go/antlr/compare/v4.13.0...v4.13.1?w=1), there is nothing too important that we'd miss.
I don't understand why they bumped the go version...

Note: the version of antlr-go is _not_ the same thing as the thing loaded by `rules_antrl_dependencies("4.13.1")` -- the version numbers are similar, but apparently not directly related.

**Review by lukedirtwalker — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555#-:-O0S4w1DE4jvl4vyueyp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @oncilla)

**Comment by jiceatscion** [comment]
We can upgrade Go anyway. See https://github.com/scionproto/scion/pull/4603

**Comment by jiceatscion** [comment]
Go has been updated. This should be good to go in.

**Comment by jiceatscion** [comment]
@oncilla Are you not going to merge this?

**Comment by oncilla** [comment]
@jiceatscion it is currently very low on my priority list. I do not have time to spend on this.
Feel free to take it over if you want this to be in soon.

**Review by jiceatscion — COMMENTED** [review]
will merge it if straighforward.

> Reviewed 6 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555#-:-O8Lzro17EgYLSTF0Obz:b-nfch0a)* status: 19 of 20 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker, @matzf, and @oncilla)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 6 of 7 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @lukedirtwalker and @matzf)

___
*[`nogo.json` line 228 at r2](https://reviewable.io/reviews/scionproto/scion/4555#-O0JjleQCyEtFJvjm1w0:-O8M0Ttw19otb4gj9T-8:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/157b41ca2d9eddd3fec8dc8ac3bc248440edc8ea/nogo.json#L228)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

add newline?
</blockquote></details>

done

**Review by lukedirtwalker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555#-:-O8MRH5NENdnnjOfjblt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by lukedirtwalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by jiceatscion — APPROVED** [review]
Thanks for standing by. For the record, I did self-approve my fixes to the lint issues.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4555#-:-O8MyEzQCipAyrv2OIrE:b1s4wd3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
