### PR TITLE
tools: add support for heuristic SCION traffic identification by wireshark

### LINKED ISSUE #4545: tools: update wireshark plugin after changes to end host port range
Follow up to #4344.

The wireshark plugin expects SCION packets in specific port ranges of the UDP underlay.
With the changes in #4344 this no longer detects all typical SCION packets.

### PR DESCRIPTION
**Pull request by jiceatscion**
Made that default, since the dispacher removal makes port-based sorting flaky.

Fixes #4545

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4582)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`tools/wireshark/scion.lua` line 1175 at r2](https://reviewable.io/reviews/scionproto/scion/4582#-O2U_CgN8VqD7ai5G0ev:-O2U_CgN8VqD7ai5G0ew:undefined) ([raw file](https://github.com/scionproto/scion/blob/6653ab30797293cdddea73ac6ed1f087115eaae1/tools/wireshark/scion.lua#L1175)):*
> ```Lua
> -- Two options are available. Identify SCION traffic by port number, or heuristically, by
> -- looking for clues in the header. The heuristic is not extremely robust. It may mistake
> -- non-SCION packet for scion packets. If you know precisely which ports carry SCION
> ```





_Suggestion:_
```Lua
SCION
```

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`tools/wireshark/scion.lua` line 1175 at r2](https://reviewable.io/reviews/scionproto/scion/4582#-O2U_CgN8VqD7ai5G0ev:-O2VQWRBDpreGV_wCVXZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/6653ab30797293cdddea73ac6ed1f087115eaae1/tools/wireshark/scion.lua#L1175)):*
> ```Lua
> -- Two options are available. Identify SCION traffic by port number, or heuristically, by
> -- looking for clues in the header. The heuristic is not extremely robust. It may mistake
> -- non-SCION packet for scion packets. If you know precisely which ports carry SCION
> ```

Done.

**Review by lukedirtwalker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582#-:-O2YEnYMEX1u3aYNoA5k:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4582#-O2YEc7D9kkgtxGj_KlB:-O2YEc7EAH0buluqC-pB:b-opvf7i) (no related file):*
additional fields that we could use:
- NextHdr
- DT/DL/ST/SL

But we can also leave it like this for now and refine later.

___

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4582#-O2YEc7D9kkgtxGj_KlB:-O2Yn8P76x_UfZE941DK:b-4nrifb) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

additional fields that we could use:
- NextHdr
- DT/DL/ST/SL

But we can also leave it like this for now and refine later.
</blockquote></details>

Good point, not many valid values for a SCION packet. Will do.

___

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4582#-O2YEc7D9kkgtxGj_KlB:-O2Z7cAE0oN1DvRPggXI:b-7rl0kd) (no related file):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Good point, not many valid values for a SCION packet. Will do.
</blockquote></details>

done

___

**Review by lukedirtwalker — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4582#-:-O2Z8cD-9fXK8AcKSs50:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
