### PR TITLE
Anapaya repository update

### PR DESCRIPTION
**Pull request by scrye**
Testing out copybara commit migration.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)

### CODE REVIEW

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 19 of 22 files at r2, 8 of 8 files at r3, 2 of 2 files at r4, 23 of 23 files at r5, 85 of 85 files at r6, 2 of 2 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by scrye — COMMENTED** [review]
> Reviewed 2 of 11 files at r1, 1 of 85 files at r6, 19 of 22 files at r10, 7 of 8 files at r11, 2 of 2 files at r12, 23 of 23 files at r13, 85 of 86 files at r14, 2 of 2 files at r15, 4 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: 144 of 145 files reviewed, all discussions resolved (waiting on @scrye)

**Review by scrye — COMMENTED** [review]
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: 145 of 146 files reviewed, all discussions resolved (waiting on @scrye)

**Review by scrye — COMMENTED** [review]
> Reviewed 7 of 152 files at r9.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: 145 of 146 files reviewed, all discussions resolved (waiting on @scrye)

**Review by scrye — COMMENTED** [review]
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: 145 of 146 files reviewed, all discussions resolved (waiting on @scrye)

**Review by scrye — COMMENTED** [review]
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: 145 of 146 files reviewed, all discussions resolved (waiting on @scrye)

**Review by scrye — COMMENTED** [review]
> Reviewed 143 of 152 files at r9, 1 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by Oncilla — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 150 of 152 files at r9.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @scrye)

**Pull request merged**
