### PR TITLE
mgmtapi: support deleting segments and beacons

### PR DESCRIPTION
**Pull request by oncilla**
Support deleting segments and beacons via the management API of the control and daemon service. This is useful for cleaning up the databases (e.g., in case the issue mentioned in #4286 occurs)

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4465)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

___
*[`spec/control/beacons.yml` line 125 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYCqFe4hSxyFgYbNNp:-NqYCqFfA5QuRSNJAe8L:b-bj11ls) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/control/beacons.yml#L125)):*
> ```YAML
>         description: The segment ID of the beacon segment.
>           If the input value is shorter than a segment ID, but matches the prefix of
>           the segment ID of exactly one beacon, then this beacon is deleted.
> ```

hm but wouldn't the query delete all the matches? Why do we need that prefix behavior?
___
*[`spec/control/beacons.yml` line 131 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYDcO3AQhW52mY5a8Z:-NqYDcO3AQhW52mY5a8_:btnabtf) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/control/beacons.yml#L131)):*
> ```YAML
>         style: simple
>         explode: false
>       responses:
> ```

the implementation seems to also return 500, do we also need to list it here?
___
*[`spec/segments/spec.yml` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYDgdhDRxke87iSB86:-NqYDgdhDRxke87iSB87:btnabtf) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L86)):*
> ```YAML
>         style: simple
>         explode: false
>       responses:
> ```

the implementation seems to also return 500, do we also need to list it here?

**Review by jiceatscion — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465)* status: all files reviewed, 3 unresolved discussions (waiting on @matzf and @oncilla)

**Review by matzf — COMMENTED** [review]
Would it make sense to add the same operations also for certs and trc databases?

> Reviewed 3 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465#-:-NqgDxm2DzVwLJWnbJhX:b-fhm9oi)* status: all files reviewed, 5 unresolved discussions (waiting on @oncilla)

___
*[`private/storage/beacon/sqlite/db.go` line 247 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgAxA_Ek3Fi5tKJyBh:-NqgAxA_Ek3Fi5tKJyBi:b4zz52w) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/private/storage/beacon/sqlite/db.go#L247)):*
> ```Go
> 	e.Lock()
> 	defer e.Unlock()
> 	_, err := e.db.ExecContext(ctx, "DELETE FROM Beacons WHERE hex(SegID) LIKE ?", partialID+"%")
> ```

In the corresponding code in the path db, you use an explicit transaction. Here, in beacons db, the DeleteExpiredBeacons also uses a transaction. Is this not needed here?
___
*[`spec/segments/spec.yml` line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgD7Dt-Dmdw7zMJfgU:-NqgD7Dt-Dmdw7zMJfgV:b-d3j8mu) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L80)):*
> ```YAML
>       parameters:
>       - in: path
>         name: segment-id
> ```

Document the prefix semantics for this too?

Note that get beacon does _not_ support the prefix semantics...

**Review by oncilla — COMMENTED** [review]
It would make sense, yes.
But I would prefer to do it in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465#-:-NqgJPWzD1EWrjXnc2Fr:b-ko74n9)* status: all files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[`private/storage/beacon/sqlite/db.go` line 247 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgAxA_Ek3Fi5tKJyBh:-NqgIwbW47Cagv6jxi-B:b-2zxc7y) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/private/storage/beacon/sqlite/db.go#L247)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In the corresponding code in the path db, you use an explicit transaction. Here, in beacons db, the DeleteExpiredBeacons also uses a transaction. Is this not needed here?
</blockquote></details>

It's technically not needed no. But for the sake of consistency, I added it here to.
___
*[`spec/control/beacons.yml` line 125 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYCqFe4hSxyFgYbNNp:-NqgFfMXCuwxODLvJonj:b-9frasi) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/control/beacons.yml#L125)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

hm but wouldn't the query delete all the matches? Why do we need that prefix behavior?
</blockquote></details>

Thing is, we do not log the full ID, thus the prefix behavior.

Added a comment. But I'm on the fence. We could also drop the behavior.
___
*[`spec/control/beacons.yml` line 131 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYDcO3AQhW52mY5a8Z:-NqgGys1Ej-iuXLHc7Zz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/control/beacons.yml#L131)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

the implementation seems to also return 500, do we also need to list it here?
</blockquote></details>

Done.
___
*[`spec/segments/spec.yml` line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgD7Dt-Dmdw7zMJfgU:-NqgH_9zD_0eSHqCbz0h:boryric) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L80)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Document the prefix semantics for this too?

Note that get beacon does _not_ support the prefix semantics...
</blockquote></details>

Done.

I'm pretty sure the beacon DB does support the prefix semantics:
https://github.com/scionproto/scion/blob/fce093e2679918171fcc7e9541d67e1128aab8bb/private/storage/beacon/sqlite/db.go#L254
___
*[`spec/segments/spec.yml` line 86 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqYDgdhDRxke87iSB86:-NqgIbzT6cXakK1wqslv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L86)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

the implementation seems to also return 500, do we also need to list it here?
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

**Review by matzf — APPROVED** [review]
:lgtm: 

> Reviewed 12 of 25 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465#-:-NqhURrG8bs8tpL_5lze:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

___
*[`spec/segments/spec.yml` line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgD7Dt-Dmdw7zMJfgU:-NqhUbOB0aSFcX3N9cAb:bj63lyv) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L80)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Done.

I'm pretty sure the beacon DB does support the prefix semantics:
https://github.com/scionproto/scion/blob/fce093e2679918171fcc7e9541d67e1128aab8bb/private/storage/beacon/sqlite/db.go#L254
</blockquote></details>

Aha, thanks. I saw this, but was confused by the string concatenation operator it seems. :sweat_smile:

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4465)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oncilla)

___
*[`spec/segments/spec.yml` line 80 at r1](https://reviewable.io/reviews/scionproto/scion/4465#-NqgD7Dt-Dmdw7zMJfgU:-NqhjLTmEqg6ZdCZTj8f:baatdlh) ([raw file](https://github.com/scionproto/scion/blob/e86667b4d812966214ffc146b1e337bf71c6518f/spec/segments/spec.yml#L80)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Aha, thanks. I saw this, but was confused by the string concatenation operator it seems. :sweat_smile:
</blockquote></details>

Yeah, flash back to theoretical computer science. The only other place I know that uses `||` for string concatenation :)

**Pull request merged**
