### PR TITLE
Dockerize applications and use docker-compose

### PR DESCRIPTION
**Pull request by worxli**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1614)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 7 of 30 files at r2.
Review status: 6 of 30 files reviewed, 5 unresolved discussions (waiting on @kormat and @worxli)

---

*[docker/zoo-container.cfg, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv4piQ2wXZqGtmZbFZ:-LFv4piQ2wXZqGtmZbF_:b6ondfj) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/zoo-container.cfg#L4)):*
> ```INI
> initLimit=10
> syncLimit=5
> dataDir=/tmp/zookeeper
> ```

This looks wrong :) Have a look at `docker/zoo.cfg` to see what it probably should look like. You need to have a `dataLogDir` on tmpfs for the normal test env, otherwise zk times out with i/o. And `dataDir` should definitely be a directory that doesn't look like it gets wiped at boot ;)

---

*[docker/perapp/.gitignore, line 2 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5AM77hA6HCGTCntv:-LFv5AM82v88VyV5LDTk:bad7khr) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/.gitignore#L2)):*
> ```
> # Ignore Vim swap files.
> .*.sw?
> ```

This can be dropped - it's covered by the top-level `.gitignore`. For that matter, `hashes/` can be moved there, too (as `/docker/perapp/hashes/`).

---

*[docker/perapp/LICENSE, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5JDB5kiyrdR3x0cl:-LFv5JDB5kiyrdR3x0cm:b-894hk6) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/LICENSE#L1)):*
> ```
>                                  Apache License
> ```

Drop.

---

*[docker/perapp/Makefile, line 8 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv8s9cBmevBQ5A5f7D:-LFv8s9cBmevBQ5A5f7E:bw5bif1) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/Makefile#L8)):*
> ```Makefile
> ALL_TARGETS = base apps debug
> .PHONY: $(ALL_TARGETS)
> $(ALL_TARGETS): | scion_hash
> ```

`all` needs to be the first target.

---

*[docker/perapp/README.md, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5RnpEYw5RlRtOp14:-LFv5RnpEYw5RlRtOp15:b-3zll42) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/README.md#L1)):*
> ```Markdown
> # scion-distroless
> ```

This line isn't accurate any more, i'd just replace it with
```
# Per-application Docker images for SCION
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1614)*

**Comment by kormat** [comment]
Reviewed 23 of 30 files at r2.
Review status: 29 of 30 files reviewed, 8 unresolved discussions (waiting on @kormat and @worxli)

---

*[docker/docker-compose.yml, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv99eo6Lmg8us9g7hP:-LFv99eo6Lmg8us9g7hQ:btk71ym) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L22)):*
> ```YAML
>     image: scion_border
>     network_mode: "host"
>     cap_add:
> ```

I think we came to the conclusion that this doesn't do anything useful for us.

---

*[docker/docker-compose.yml, line 31 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv9IlzDx1Q764cG4gu:-LFv9IlzDx1Q764cG4gv:b-mjjn4z) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L31)):*
> ```YAML
>       - "../gen/ISD1/ASff00_0_110/br1-ff00_0_110-1:/share/conf"
>       - "../logs:/share/logs"
>     command: ["-id=br1-ff00_0_110-1", "-prom=[127.0.0.49]:30093", "-overlay.conn.sizeIgnore=false"]
> ```

Drop the last argument, we don't require it outside of production environments.

---

*[docker/docker-compose.yml, line 51 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv9YMBDGntiMCbS5Jn:-LFv9YMBDGntiMCbS5Jo:bskpdxi) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L51)):*
> ```YAML
>       - "../go/sig/config/testdata:/share/sig"
>       - "../logs:/share/logs"
>     command: ["-id=sig1", "-config=/share/sig/01-loadfromfile.json", "-log.dir=logs", "-log.level=debug", "-ip=192.168.6.244", "-ia=64-196722", "-sciond=/run/shm/sciond/sd1-ff00_0_110.sock", "-prom=:9504"]
> ```

FIXME.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1614)*

**Comment by worxli** [comment]
Review status: 24 of 29 files reviewed, 8 unresolved discussions (waiting on @kormat and @worxli)

---

*[docker/docker-compose.yml, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv99eo6Lmg8us9g7hP:-LFv9yRYCxMTa-FCDLO1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L22)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I think we came to the conclusion that this doesn't do anything useful for us.
</blockquote></details>

Done.

---

*[docker/docker-compose.yml, line 31 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv9IlzDx1Q764cG4gu:-LFvA-0x9HY1G5HH217Z:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L31)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Drop the last argument, we don't require it outside of production environments.
</blockquote></details>

Done.

---

*[docker/docker-compose.yml, line 51 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv9YMBDGntiMCbS5Jn:-LFvA02xA-sElyVC1DlT:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/docker-compose.yml#L51)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

FIXME.
</blockquote></details>

Done.

---

*[docker/perapp/Makefile, line 8 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv8s9cBmevBQ5A5f7D:-LFvAAmi5wxQ2aAYYzEA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/Makefile#L8)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`all` needs to be the first target.
</blockquote></details>

Done.

---

*[docker/perapp/README.md, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5RnpEYw5RlRtOp14:-LFvAF7o0bZ7Kb8ufEOF:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/README.md#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This line isn't accurate any more, i'd just replace it with
```
# Per-application Docker images for SCION
```
</blockquote></details>

Done.

---

*[docker/perapp/.gitignore, line 2 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5AM77hA6HCGTCntv:-LFvAVe58vLpt7nkNekq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/.gitignore#L2)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be dropped - it's covered by the top-level `.gitignore`. For that matter, `hashes/` can be moved there, too (as `/docker/perapp/hashes/`).
</blockquote></details>

Done.

---

*[docker/perapp/LICENSE, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv5JDB5kiyrdR3x0cl:-LFvAA5kBp71FENbXief:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/perapp/LICENSE#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Drop.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1614)*

**Comment by worxli** [comment]
Review status: 24 of 29 files reviewed, 8 unresolved discussions (waiting on @kormat)

---

*[docker/zoo-container.cfg, line 4 at r2](https://reviewable.io/reviews/scionproto/scion/1614#-LFv4piQ2wXZqGtmZbFZ:-LFvKP0UAuNgAOAu-cu3:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/be412dc0cd4e9c3622fc38c15d7d1d15096f4465/docker/zoo-container.cfg#L4)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This looks wrong :) Have a look at `docker/zoo.cfg` to see what it probably should look like. You need to have a `dataLogDir` on tmpfs for the normal test env, otherwise zk times out with i/o. And `dataDir` should definitely be a directory that doesn't look like it gets wiped at boot ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1614)*

**Pull request merged**
