### PR TITLE
pkg/private: cleanup common, util, xtest packages

### LINKED ISSUE #4262: checksum: re-evaluate library
The util.Checksum code uses unsafe pointer: https://github.com/scionproto/scion/blob/15d455f11eb8d717f3a91880506cbabdf780b21c/pkg/private/util/checksum.go#L43

We should re-evaluate if it is truly faster compared to an implementation like:
https://github.com/google/gopacket/blob/403ca653c45d1cde891a99c417c2b4b7fe93dce7/layers/tcpip.go#L52
And if it is really worth using it.

The layers approach does not pass the pseudo headers across package boundaries. My guess is that this means less allocations as the pseudo header will be put on the stack.

### PR DESCRIPTION
**Pull request by matzf**
The pkg/private/common, util and xtest packages have rather fuzzy scope, and have accumulated a bit of cruft and unused or outdated functionality. Clean this up a bit:

* pkg/private/common: 
    * remove unused constants
    * remove outdated error handling helpers and replace remaining use
    * remove NativeOrder and IsBigEndian: No longer needed.
      Native byte order is not often needed, but will eventually show up in standard library anyway (golang/go#57237).
* pkg/private/util:
    * remove unused helper functionality
    * remove Checksum: only used to compute reference value in slayers test cases. Use a simpler, non-optimized implementation for this. Closes #4262.
    * move RunsInDocker to private/env
    * move ASList to tools/integration
* pkg/private/xtest: 
    * remove unused helpers
    * remove unused Callback and MockCallback
    * replace FailOnErr with require.NoError
    * replace AssertErrorsIs with assert.ErrorIs

There are still more things to clean up in `pkg/private`, in future PRs, in particular: 
* `common.ErrMsg` should be integrated in `serrors`
* `common.IFIDType` should be removed or renamed and moved somewhere more appropriate
* Merge the remainder of `util` and `common` 
* Clean up  `LinkType` and `RevInfo` from `pkg/private/ctrl`

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4311)

### CODE REVIEW

**Review by marcfrei — APPROVED** [review]
:lgtm:

> Reviewed 59 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311#-:-NN1pD_L-C_OrvDtxaUp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 59 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf and @oncilla)

___
*[`tools/integration/integration.go` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4311#-NN7TFUbBeffWOv3Nuvc:-NN7TFUbBeffWOv3Nuvd:b4wldmm) ([raw file](https://github.com/scionproto/scion/blob/2aaadecadb3466144870199fbcef6f645df60bb1/tools/integration/integration.go#L1)):*
> ```Go
> // Copyright 2018 Anapaya Systemduring
> ```

revert that



_Suggestion:_
```Go
Systems
```

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311)* status: 58 of 59 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @marcfrei, and @oncilla)

___
*[`tools/integration/integration.go` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4311#-NN7TFUbBeffWOv3Nuvc:-NNGS3ek1Wf3cREmZtz_:b-9uo4ng) ([raw file](https://github.com/scionproto/scion/blob/2aaadecadb3466144870199fbcef6f645df60bb1/tools/integration/integration.go#L1)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

revert that
</blockquote></details>

Yes, oops! Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 58 of 59 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311#-:-NNaHZM1-8wg0tdeIQxM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

___
*[`pkg/private/util/checksum.go` line 25 at r3](https://reviewable.io/reviews/scionproto/scion/4311#-NNaGWjH9BJemYXTqkbv:-NNaGWjH9BJemYXTqkbw:bqppqiz) ([raw file](https://github.com/scionproto/scion/blob/a0fcc9e754698f97d180edfb8b7a8497eacb5575/pkg/private/util/checksum.go#L25)):*
> ```Go
> // Calculate RFC1071 checksum of supplied data chunks. If a chunk has
> // an odd length, it is padded with a 0 during checksum computation.
> func Checksum(srcs ...[]byte) uint16 {
> ```

Just as an FYI, this implementation was ~2 times as fast as the slayers implementation the last time I benchmarked.
But given it is not used, we don't need to keep it around.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4311)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
