### PR TITLE
Blocked: Implement QUIC transport

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Contributes to #1670

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1680)

### CODE REVIEW

**Comment by lukedirtwalker** [comment]
depends on https://github.com/scionproto/scion/pull/1682

**Comment by scrye** [comment]
Disregard ^, somehow this window had focus. I was wondering where my key presses went.

**Comment by lukedirtwalker** [comment]
Currently on Hold:
This quic transport should actually use squic. But this would trigger an import cycle. We first need to clean up the code base (create interfaces), once we have that we can finally end the implementation of this.

**Comment by scrye** [comment]
QUIC is now plugged directly in our RPC package as of https://github.com/scionproto/scion/pull/2664, and this is no longer needed.

**Pull request closed without merging**
