### PR TITLE
testing: extend router benchmark tooling

### PR DESCRIPTION
**Pull request by jiceatscion**
Enables the benchmarking of a SCION router running on an external device.
A packaged test config exists only for openwrt at the moment.

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 2 of 41 files at r1, 53 of 54 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)* status: 54 of 56 files reviewed, 17 unresolved discussions (waiting on @jiceatscion)

___
*[`BUILD.bazel` line 189 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubuX7cAooRdnAjJE9c:-NubuX7cAooRdnAjJE9d:buk047l) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/BUILD.bazel#L189)):*
> ```Starlark
>     name = "scion",
>     srcs = [
>         "//acceptance/router_benchmark/brload",
> ```

Move this to `scion-ci` below .
___
*[`acceptance/router_benchmark/benchmark.py` line 106 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NucAUCaBZXC-szmseNm:-NucAUCaBZXC-szmseNn:b9sserr) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/benchmark.py#L106)):*
> ```Python
>         if excl:
>             return self.availInterfaces.pop()
>         
> ```

Nit: trailing whitespace
___
*[`acceptance/router_benchmark/benchmark.py` line 458 at r3](https://reviewable.io/reviews/scionproto/scion/4496#-NuwupzkBtQSTq5NETus:-NuwupzkBtQSTq5NETut:b-h586v6) ([raw file](https://github.com/scionproto/scion/blob/d9e8ab9f2b4add85a98dde061e5057cfb055b84d/acceptance/router_benchmark/benchmark.py#L458)):*
> ```Python
> 
>         # No CI_check. We have no particular expectations here.
>         # Output the performance in human-friendly form...
> ```

CI_check is currently not called at all, if I'm not mistaken; I guess the idea is that this will be called for the "test.py" variant of this script, right?

Would it make sense to read the expected result from the CI check from a json file / python dict that is formatted like the results that we create here? This would allow a relatively straight forward workflow to run the experiment and use the results as comparison for the next run.
This would make the "CI check" more general; when running in the CI we'd merely set some additional parameter / environment variable or whatever to trigger the check with the "ci_expectation" data.
___
*[`acceptance/router_benchmark/test.py` line 547 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc0Clh9Weker2jUwGY:-Nuc0Clh9Weker2jUwGZ:b-gl4de2) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L547)):*
> ```Python
>         try:
>             coremarkExe = self.get_executable("coremark")
>             output = sudo("taskset", "-c", self.router_cpus[0], coremarkExe.executable)
> ```

I don't think this needs sudo.
___
*[`acceptance/router_benchmark/test.py` line 558 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc0ZATEYGoiRwHSBGe:-Nuc0ZAU0SUXUuuI9-3A:bzg5hxw) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L558)):*
> ```Python
>         try:
>             mmbmExe = self.get_executable("mmbm")
>             output = mmbmExe()
> ```

Also run this with cpu affinity mask?
___
*[`acceptance/router_benchmark/test.py` line 577 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubzTflCtkXNR8XHppH:-NubzTflCtkXNR8XHppI:b-4zqtil) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L577)):*
> ```Python
>         coremarkstr = str(coremark or "Unavailable")
>         mmbmstr = str(mmbm or "Unavailable")
>         logger.info(f"Coremark: {coremarkstr}")
> ```

Nit: just because it's cute: `logger.info(f"Coremark: {coremark or 'Unavailable'}")` actually works.
___
*[`acceptance/router_benchmark/test.py` line 597 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NucOFLH6dIxb7YVngYy:-NucOFLI-i56k-qHC3Mw:bbeweoo) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L597)):*
> ```Python
>             droppageMap[testCase] = dropped
> 
>         cores = self.core_count()
> ```

This is expected to match `len(self.router_cores)`, correct? Could make sense to assert this.
___
*[`dist/openwrt/BUILD.external.bazel` line 118 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nubwwgc99MBurlZZoIX:-Nubwwgc99MBurlZZoIY:b-8myt6l) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/BUILD.external.bazel#L118)):*
> ```
>     pkg = "bmtools",
>     visibility = ["//visibility:public"],
>     deps = ["bmconfig_ipk"],  # Force sequential build; openwrt make isn't reentrant.
> ```

Broken sequence, should be`testconfig_ipk`?
___
*[`dist/openwrt/initds/bmtools` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubyjYJ9sOv8J6U4vS6:-NubyjYKBOWEn9_nL_bj:b-v5vtyg) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L13)):*
> ```
> APP=scion-control
> SERVICE_WRITE_PID=1
> SERVICE_DAEMONIZE=1
> ```

Without having looked this up, setting WRITE_PID and DAEMONIZE to true (?) seems surprising for a script that is supposed to be a one-off. Is this correct?
___
*[`dist/openwrt/initds/bmtools` line 20 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubwYmM78-bnO6IG593:-NubwYmM78-bnO6IG594:boioqsl) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L20)):*
> ```
>     /usr/bin/scion-coremark > /tmp/coremark.$u.out
>     if grep -q "Correct operation validated" /tmp/coremark.$u.out; then
> 	coremark=$(grep -s "CoreMark [0-9.]* :" /tmp/coremark.$u.out | awk '{ print $4 }' 2>/dev/null) 
> ```

Nit: mixed tabs and spaces. Below: trailing spaces
___
*[`dist/openwrt/initds/bmtools` line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubxZLU01PXoCTxbcK7:-NubxZLU01PXoCTxbcK8:b-l6geli) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L34)):*
> ```
>     
>     # Publish
>     echo "{\"coremark\": $coremark, $mmbm}" > /www/horsepower.txt
> ```

`.json`?
___
*[`dist/openwrt/initds/router` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc1FtZEB2WTjacqjQr:-Nuc1FtZEB2WTjacqjQs:b-d7r2h1) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/router#L13)):*
> ```
> 
> start() {
>     export GOMAXPROCS=3
> ```

Is this intentionally set in the "release" package?
___
*[`doc/dev/design/routerPerfModel.md` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc2CkyEwBSNniu7NDv:-Nuc2CkyEwBSNniu7NDw:b8kk0a1) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L1)):*
> ```Markdown
> # Router benchmark observations and predictive model
> ```

Please add metadata:

```md
- Author(s): [Author Name(s)]
- Last updated: [Date (Year-Month-Day)]
- Discussion at: [#NNNN](https://github.com/scionproto/scion/issues/NNNN)
```
___
*[`doc/dev/design/routerPerfModel.md` line 11 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc3q3-CmXpC0caIY_t:-Nuc3q3-CmXpC0caIY_u:briu8qq) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L11)):*
> ```Markdown
> * rate: The benchmark result of the router on the platform, using three cores (in pkts/s)
> * M: an experimentally determined constant of value 18500
> * I: a dimensionless number reflecting the router code's performance
> ```

Nit: in the rendered document, `I` and `l` are basically indistinguishable.
___
*[`doc/dev/design/routerPerfModel.md` line 307 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc3MzR0ymcX897G5Pt:-Nuc3MzS3W0TPcibFTcj:b-6t8hrm) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L307)):*
> ```Markdown
> * pbm = 1 / (122.42 * coremark) + M * 8 * l / C
>       = 1 / (122 * 2972) + 18500 * 8 * 172 / 9.8G
> 	  = .00002405
> ```

Tab?
Btw, this is now all rendered on a single line. I _think_ you can use a trailing backslash to force a line break.
___
*[`doc/dev/design/routerPerfModel.md` line 314 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc398I-9GnTKA-EJpS:-Nuc398I-9GnTKA-EJpT:btmcual) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L314)):*
> ```Markdown
> * pbm = 1 / (127 * coremark) + M * 8 * l / C
> *     = 1 / (127 * 29866 * 3) + 18500 8 * 172 / 128G
> *     = 0.000001817
> ```

Rendering is somewhat messed up here; some lines are rendered as code blocks, perhaps because of the leading spaces.
___
*[`tools/mmbm/main.go` line 21 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubvKAr5LE3-w2aJHNS:-NubvKAr5LE3-w2aJHNT:bh7z68k) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/tools/mmbm/main.go#L21)):*
> ```Go
> // to that of glibc's and it has the advantages of being independent from any given libc
> // implementation. musl_libc's implementation, for example performs much worse.
> ```

Nit: remove empty line here between documentation and `package`, so it can be picked up by godoc.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)* status: 52 of 57 files reviewed, 9 unresolved discussions (waiting on @matzf)

___
*[`BUILD.bazel` line 189 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubuX7cAooRdnAjJE9c:-Nv2onHf0PORoT_s-7vO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/BUILD.bazel#L189)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Move this to `scion-ci` below .
</blockquote></details>

Done.
___
*[`acceptance/router_benchmark/benchmark.py` line 106 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NucAUCaBZXC-szmseNm:-Nv2ol5v4opY4TqejVPZ:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/benchmark.py#L106)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: trailing whitespace
</blockquote></details>

done
___
*[`acceptance/router_benchmark/benchmark.py` line 458 at r3](https://reviewable.io/reviews/scionproto/scion/4496#-NuwupzkBtQSTq5NETus:-Nv2ougH-18XhEaVQ1uh:b9lf7ta) ([raw file](https://github.com/scionproto/scion/blob/d9e8ab9f2b4add85a98dde061e5057cfb055b84d/acceptance/router_benchmark/benchmark.py#L458)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

CI_check is currently not called at all, if I'm not mistaken; I guess the idea is that this will be called for the "test.py" variant of this script, right?

Would it make sense to read the expected result from the CI check from a json file / python dict that is formatted like the results that we create here? This would allow a relatively straight forward workflow to run the experiment and use the results as comparison for the next run.
This would make the "CI check" more general; when running in the CI we'd merely set some additional parameter / environment variable or whatever to trigger the check with the "ci_expectation" data.
</blockquote></details>

I've done quite a bit of cleanup in that area. You might find that you like the Results.CI_chek() method. Yeah, we could use the same format for expectations but I'm not sure it's so beneficial. We only need a {case:rate} map and check the saturation.
___
*[`acceptance/router_benchmark/test.py` line 547 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc0Clh9Weker2jUwGY:-Nv2tb0G2KdHlwGv4n2E:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L547)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I don't think this needs sudo.
</blockquote></details>

done
___
*[`acceptance/router_benchmark/test.py` line 558 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc0ZATEYGoiRwHSBGe:-Nv2td8I8qUsFJjT7G74:bjtc731) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L558)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Also run this with cpu affinity mask?
</blockquote></details>

correct. Proved quite important. I now have to recompute my magic constant :-(
___
*[`acceptance/router_benchmark/test.py` line 577 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubzTflCtkXNR8XHppH:-Nv2ttcD0QOXPkRWE9GE:bw76e93) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L577)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: just because it's cute: `logger.info(f"Coremark: {coremark or 'Unavailable'}")` actually works.
</blockquote></details>

Yeah, it's pretty convenient that all the placeholders get stringified. Using it everywhere now.
Thanks.
___
*[`acceptance/router_benchmark/test.py` line 597 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NucOFLH6dIxb7YVngYy:-Nv2uAlwC2XZ4ROo31ET:bk0rhoa) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/acceptance/router_benchmark/test.py#L597)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is expected to match `len(self.router_cores)`, correct? Could make sense to assert this.
</blockquote></details>

Good point. The expected core count is not always defined by router_cpus, though. That is the case for test.py but not for the external benchmark tool, which depends on the router config. In theory you can benchmark as many cores as you want. Now that this code is going to be common, I cannot but the check here, but I put it in the caller.
___
*[`dist/openwrt/BUILD.external.bazel` line 118 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nubwwgc99MBurlZZoIX:-Nv2xrjd2F2iXB5gzaTB:b5qdke6) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/BUILD.external.bazel#L118)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Broken sequence, should be`testconfig_ipk`?
</blockquote></details>

Yes. Don't know how I didn't hit that earlier. Fixed.
___
*[`dist/openwrt/initds/bmtools` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubyjYJ9sOv8J6U4vS6:-Nv2y7ou28MK583Bsvgo:b-jjz5tg) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L13)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Without having looked this up, setting WRITE_PID and DAEMONIZE to true (?) seems surprising for a script that is supposed to be a one-off. Is this correct?
</blockquote></details>

Possibly. The particular version of procd that they're using isn't particularly documented. I cargo-culted from the existing. I'll see if it just works without it.
___
*[`dist/openwrt/initds/bmtools` line 20 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubwYmM78-bnO6IG593:-Nv2ypW_ECrlpzcGh2ez:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L20)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: mixed tabs and spaces. Below: trailing spaces
</blockquote></details>

done
___
*[`dist/openwrt/initds/bmtools` line 34 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubxZLU01PXoCTxbcK7:-Nv2z5B76RNfvlCF0Quu:b9jmckk) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L34)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`.json`?
</blockquote></details>

indeed.
Done.
___
*[`dist/openwrt/initds/router` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc1FtZEB2WTjacqjQr:-Nv2zfoh8h-oIHvQo35M:b-a7n4og) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/router#L13)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Is this intentionally set in the "release" package?
</blockquote></details>

Ouch. No. I forgot that this wasn't a benchmark-only config file. I'll have to find some other way. I knew it was going to be trouble to rely on a env var :-(
Stay tuned.
___
*[`doc/dev/design/routerPerfModel.md` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc2CkyEwBSNniu7NDv:-Nv3-wDD7TVkDALsiZUv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L1)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Please add metadata:

```md
- Author(s): [Author Name(s)]
- Last updated: [Date (Year-Month-Day)]
- Discussion at: [#NNNN](https://github.com/scionproto/scion/issues/NNNN)
```
</blockquote></details>

Done.
___
*[`doc/dev/design/routerPerfModel.md` line 11 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc3q3-CmXpC0caIY_t:-Nv3-xrMBXrKmoYSIAjd:b-4he0oe) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L11)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: in the rendered document, `I` and `l` are basically indistinguishable.
</blockquote></details>

Fixed, among other things.
___
*[`doc/dev/design/routerPerfModel.md` line 307 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc3MzR0ymcX897G5Pt:-Nv303k06B_j-ALD5iZn:belduit) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L307)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Tab?
Btw, this is now all rendered on a single line. I _think_ you can use a trailing backslash to force a line break.
</blockquote></details>

One line is fine. If it fits.
___
*[`doc/dev/design/routerPerfModel.md` line 314 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc398I-9GnTKA-EJpS:-Nv30MqlB1xpfe7rVn83:b-h07yjc) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L314)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Rendering is somewhat messed up here; some lines are rendered as code blocks, perhaps because of the leading spaces.
</blockquote></details>

Yeah, still working on that. Stay tuned.
___
*[`tools/mmbm/main.go` line 21 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubvKAr5LE3-w2aJHNS:-Nv30w3oC-b9YibRqzK9:b-7rl0kd) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/tools/mmbm/main.go#L21)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: remove empty line here between documentation and `package`, so it can be picked up by godoc.
</blockquote></details>

done

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)* status: 41 of 58 files reviewed, 7 unresolved discussions (waiting on @matzf)

___
*[`dist/openwrt/initds/bmtools` line 13 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubyjYJ9sOv8J6U4vS6:-Nv6vu1G76FMgbZCtNZV:b6d4yst) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L13)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Possibly. The particular version of procd that they're using isn't particularly documented. I cargo-culted from the existing. I'll see if it just works without it.
</blockquote></details>

Yeah, it's fine without.
Done
___
*[`doc/dev/design/routerPerfModel.md` line 314 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-Nuc398I-9GnTKA-EJpS:-Nv6w8KB80G69IY4AuOJ:bb6un1j) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/doc/dev/design/routerPerfModel.md#L314)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Yeah, still working on that. Stay tuned.
</blockquote></details>

Done

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r5, 11 of 16 files at r6, 8 of 9 files at r7, 3 of 4 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)* status: all files reviewed, 4 unresolved discussions (waiting on @jiceatscion)

___
*[`acceptance/router_benchmark/BUILD.bazel` line 42 at r9](https://reviewable.io/reviews/scionproto/scion/4496#-Nw8l-To5GdMj4T_tV0b:-Nw8l-Tp32LiYI2O_PWO:b-c8s5mm) ([raw file](https://github.com/scionproto/scion/blob/80041d90ca3c66ccfffe4b0b1343a4b5baf32b69/acceptance/router_benchmark/BUILD.bazel#L42)):*
> ```Starlark
>     # This test uses sudo and accesses /var/run/netns.
>     local = True,
> )
> ```

Add py_library and py_binary for the benchmark, so that the linter will cover it. Needs #4513, otherwise the linter chokes on the syntax.

```
load("//tools/lint:py.bzl", "py_library", "py_binary")

raw_test(
    name = "test",
    ....
     deps = ["benchmarklib"],   # XXX: shouldn't the test crash without this? I don't quite understand why bazel lets this run wihtout explicit dependency
)

py_library(
    name = "benchmarklib",
    srcs = ["benchmarklib.py"],
)

# XXX placeholder, to ensure that the linter runs over this. Cannot actually be run with bazel run.
py_binary(
    name = "benchmark",
    srcs = ["benchmark.py"],
    deps = [ "benchmarklib", requirement("plumbum") ],
)
```

Note: for some reason `bazel run //....:benchmark` trips up (on my machine) on the python syntax, even though it's supposedly running with python 3.10. Possibly this is bazels internal python interpreter. It doesn't work anyway, because bin/brload cannot be found when running from bazel.
___
*[`acceptance/router_benchmark/test.py` line 183 at r9](https://reviewable.io/reviews/scionproto/scion/4496#-Nw8rO5M3Yyc9FNTwnYc:-Nw8rO5N1XtrhWYlkgMh:b-gtr50w) ([raw file](https://github.com/scionproto/scion/blob/80041d90ca3c66ccfffe4b0b1343a4b5baf32b69/acceptance/router_benchmark/test.py#L183)):*
> ```Python
>     router_cpus: list[int] = [0]
> 
>     # Used by the RouterBM mixin:
> ```

As noted before, keeping state in the Test object does not play well with the `setup`/`run`/`teardown` subcommands. Not a new problem and not a deal breaker; maybe just add a comment, so that perhaps it can be addressed the next time someone makes pass over this.
___
*[`dist/openwrt/initds/bmtools` line 20 at r2](https://reviewable.io/reviews/scionproto/scion/4496#-NubwYmM78-bnO6IG593:-Nva2ZSTBI01cRUl2IGB:b-qqlgz1) ([raw file](https://github.com/scionproto/scion/blob/ffaab5fe4ee0bae82ff8267d3020dd0047af1e61/dist/openwrt/initds/bmtools#L20)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

done
</blockquote></details>

There are still some trailing spaces below.
___
*[`dist/openwrt/initds/bmtools` line 35 at r7](https://reviewable.io/reviews/scionproto/scion/4496#-Nw4r33U1oWZ07iX1bfx:-Nw4r33U1oWZ07iX1bfy:bl7efux) ([raw file](https://github.com/scionproto/scion/blob/c08d3ae43d4c7247a67ec7bb59231ff9cc8cb7da/dist/openwrt/initds/bmtools#L35)):*
> ```
>     echo "\"coremark\": $coremark," >> /www/horsepower.json
>     echo "$mmbm" >> /www/horsepower.json
>     echo "}" >> /www/horsepower.json
> ```

Nit: single echo/printf? Or subhsell and only one redirect: 
```
(
   echo "{"
   echo "..."
   ...
) > /www/horsepower.json
```

**Review by matzf — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4496)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
