### PR TITLE
DRKey: representation of first order messages

### PR DESCRIPTION
**Pull request by benrothen**
- Mapping of `drkey_mgmt.capnp` to go/lib.
- Update of `drkey_mgmt.capnp` to reflect the changes in book
- Remove signature and timestamp as they are abstracted in SignedPld.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)

### CODE REVIEW

**Comment by Oncilla** [comment]
Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---

*[go/lib/ctrl/drkey_mgmt/drkey_mgmt.go, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LE9ziR8-X2DbMx9CElB:-LE9ziR8-X2DbMx9CElC:b-j79m9l) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_mgmt.go#L64)):*
> ```Go
> }
> 
> // NewPld creates a new cert mgmt payload, containing the supplied Cerealizable instance.
> ```

s/cert/drkey

---

*[go/lib/ctrl/drkey_mgmt/drkey_mgmt.go, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LE9zuMvBTPbG8tpdk_C:-LE9zuMvBTPbG8tpdk_D:b-vryjml) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_mgmt.go#L75)):*
> ```Go
> 
> func (p *Pld) ProtoId() proto.ProtoIdType {
> 	return proto.CertMgmt_TypeID
> ```

s/CertMgmt_TypeID/DRKeyMgmt_TypeID

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA-mNN5nStaWtmJIEN:-LEA-mNN5nStaWtmJIEO:b5r0n0l) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // This file contains the Go representation of Certificate Chain requests.
> ```

comment does not match file

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 46 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA0cTQ2nxkHT03-BnF:-LEA0cTQ2nxkHT03-BnG:b-4nfs75) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L46)):*
> ```Go
> 
> func (c *DRKeyRep) String() string {
> 	return fmt.Sprintf("Src ISD-AS: %s ExpTime: %v CertVerSig: %v CertVerEnc: %v",
> ```

Field names do not match string.
Use `%d` for `ExpTime`, `CertVerSrc` and `CertVerDst`.
Also, use `util.TimeToString` to print the expiration time human readable.

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA24OzBsMAIfiiuTDp:-LEA24OzBsMAIfiiuTDq:b58dzo9) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L15)):*
> ```Go
> // limitations under the License.
> 
> // This file contains the Go representation of Certificate Chain requests.
> ```

s/Certificate Chain/DRKey

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA4DkM9w5THj1CX0-E:-LEA4DkM9w5THj1CX0-F:b-yjjvtv) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L42)):*
> ```Go
> 
> func (c *DRKeyReq) String() string {
> 	return fmt.Sprintf("Src ISD-AS: %s ValTime: %v",
> ```

I would rename `Src ISD-AS` to `SrcIA`.
Also, pretty print `ValTime`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by brothen** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/lib/ctrl/drkey_mgmt/drkey_mgmt.go, line 64 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LE9ziR8-X2DbMx9CElB:-LEAArVeCeyzY2q6OE0A:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_mgmt.go#L64)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

s/cert/drkey
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_mgmt.go, line 75 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LE9zuMvBTPbG8tpdk_C:-LEAB-jO4RngIuyXGcUC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_mgmt.go#L75)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

s/CertMgmt_TypeID/DRKeyMgmt_TypeID
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA-mNN5nStaWtmJIEN:-LEABGcSDj4hODScHrNS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L15)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

comment does not match file
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 46 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA0cTQ2nxkHT03-BnF:-LEAUzV1-IL9tNeeNWZa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L46)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Field names do not match string.
Use `%d` for `ExpTime`, `CertVerSrc` and `CertVerDst`.
Also, use `util.TimeToString` to print the expiration time human readable.

</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 15 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA24OzBsMAIfiiuTDp:-LEABJZf865hJztjy9Cn:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L15)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

s/Certificate Chain/DRKey
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA4DkM9w5THj1CX0-E:-LEAUuMz1DiiFKmOtmER:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L42)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

I would rename `Src ISD-AS` to `SrcIA`.
Also, pretty print `ValTime`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by Oncilla** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 46 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA0cTQ2nxkHT03-BnF:-LEJ1ewN45UJJBIvJE95:bfv8m0v) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L46)):*
<details><summary><i>Previously, brothen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would add the following function.:

    // Time returns the expiration time.
    func (c *DRKeyRep) Time() time.Time {
	return util.USecsToTime(uint64(c.ExpTime))
    }

(same forDRKeyReq )

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA4DkM9w5THj1CX0-E:-LEJ2uWYCJoTgSnNHStO:b-ia41wb) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L42)):*
<details><summary><i>Previously, brothen wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same comment as above

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by brothen** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/ctrl/drkey_mgmt/drkey_rep.go, line 46 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA0cTQ2nxkHT03-BnF:-LEJARyO8_V_TZ_aMduW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_rep.go#L46)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

I would add the following function.:

    // Time returns the expiration time.
    func (c *DRKeyRep) Time() time.Time {
	return util.USecsToTime(uint64(c.ExpTime))
    }

(same forDRKeyReq )
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 42 at r1](https://reviewable.io/reviews/scionproto/scion/1588#-LEA4DkM9w5THj1CX0-E:-LEJAVrWAX-h1jkCgxkq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/39f81da7c4da16be00db44864d84f62bd68f06fd/go/lib/ctrl/drkey_mgmt/drkey_req.go#L42)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

same comment as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by Oncilla** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588#-:-LEJCZwZ6LFEL04NZEUs:bnfp4nl)*

**Comment by Oncilla** [comment]
Reviewed 6 of 7 files at r4.
Review status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Oncilla and @brothen)

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 28 at r4](https://reviewable.io/reviews/scionproto/scion/1588#-LFwOSId0nq9uZBJb7cu:-LFwOSId0nq9uZBJb7cv:b834h63) ([raw file](https://github.com/scionproto/scion/blob/f3627022245989a1199c0c19840383876f39cf57/go/lib/ctrl/drkey_mgmt/drkey_req.go#L28)):*
> ```Go
> )
> 
> var _ proto.Cerealizable = (*DRKeyLvl1Rep)(nil)
> ```

s/Rep/Req

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 49 at r4](https://reviewable.io/reviews/scionproto/scion/1588#-LFwPLam3Q5Ziad0MYd7:-LFwPLam3Q5Ziad0MYd8:beiwe0m) ([raw file](https://github.com/scionproto/scion/blob/f3627022245989a1199c0c19840383876f39cf57/go/lib/ctrl/drkey_mgmt/drkey_req.go#L49)):*
> ```Go
> 
> func (c *DRKeyLvl1Req) String() string {
> 	return fmt.Sprintf("SrcIA: %s ValTime: %v",
> ```

fits on one line

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by brothen** [comment]
Review status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Oncilla)

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 28 at r4](https://reviewable.io/reviews/scionproto/scion/1588#-LFwOSId0nq9uZBJb7cu:-LFwR4Cn5B4UAs-qVnFp:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f3627022245989a1199c0c19840383876f39cf57/go/lib/ctrl/drkey_mgmt/drkey_req.go#L28)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

s/Rep/Req
</blockquote></details>

Done.

---

*[go/lib/ctrl/drkey_mgmt/drkey_req.go, line 49 at r4](https://reviewable.io/reviews/scionproto/scion/1588#-LFwPLam3Q5Ziad0MYd7:-LFwSC4k-H5yD68iKQqH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f3627022245989a1199c0c19840383876f39cf57/go/lib/ctrl/drkey_mgmt/drkey_req.go#L49)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

fits on one line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588)*

**Comment by Oncilla** [comment]
:lgtm:

---

Review status: 7 of 8 files reviewed, all discussions resolved (waiting on @Oncilla)

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1588#-:-LFwkH7TDuVKOOpZFnyk:bnfp4nl)*

**Pull request closed without merging**
