### PR TITLE
Generate docker topology

### LINKED ISSUE #1635: Docker: Update topology generator
Update the topology generator, such that it creates docker per app configs (based on a flag). And also create a compose config.

### PR DESCRIPTION
**Pull request by worxli**
Fixes #1635.

Let the topology generator generate docker-compose files.

- When `-d` is passed to the generator a docker-compose file is created.
- `./scion.sh` {start|status|stop} will run the topology with docker-compose if `gen/docker-compose.yml` is present

This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1641)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed, 7 unresolved discussions (waiting on @worxli)

---

*[scion.sh, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQSFe55yweREvdnBl-:-LGQSFe63bmg6-M16MYG:b-9npnaj) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L44)):*
> ```Shell
>     fi
>     echo "Running the network..."
>     if [ -e gen/zk_datalog_dirs.sh ]; then
> ```

This can be dropped, we don't generate that anymore.

What we do need to do is create `/run/shm/dispatcher and `/run/shm/sciond` before starting docker compose (and changing the ownership if they already exist and are owned by root).

---

*[scion.sh, line 49 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQRvWL3MSPf5UPwnGe:-LGQRvWL3MSPf5UPwnGf:b-6b5m6s) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L49)):*
> ```Shell
>     python/integration/set_ipv6_addr.py -a
>     if [ -f gen/docker-compose.yml ]; then
>         systemctl is-active --quiet zookeeper && service zookeeper stop
> ```

Two things:
- Don't mix `systemctl` and `service`
- This seems to assume it's running as root.

---

*[python/topology/generator.py, line 1001 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQd9Mw7vzCXkwAiSai:-LGQd9Mw7vzCXkwAiSaj:bpvjbro) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1001)):*
> ```Python
>         self.out_dir = out_dir
>         self.topo_dicts = topo_dicts
>         self.dc_conf = {'version': '3', 'services': {}}
> ```

The default retry interval is far too long (1m). As an example:
```
2018-07-02 15:36:37.901860+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-02 15:36:37.901957+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-02 15:37:38.196908+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-02 15:37:38.197002+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
```
Can we make it 5s?

---

*[python/topology/generator.py, line 1018 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQVkN-CzcdQosfPvbt:-LGQVkN-CzcdQosfPvbu:b-o9i35q) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1018)):*
> ```Python
>     def _br_conf(self, topo, base):
>         raw_entry = {
>             'image': 'scionproto/border',
> ```

I don't think the `scionproto` prefix is correct. If someone hasn't built any local images, this will download ones from dockerhub which are unrelated to whatever is checked out locally. So, i would use `scion_border` instead, with no prefix.

---

*[python/topology/generator.py, line 1030 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQWNqaBKC2T6sagyOj:-LGQWNqaBKC2T6sagyOk:b-u75arv) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1030)):*
> ```Python
>             ],
>             'command': [
>                 '-log.dir=logs'
> ```

This is the default.

---

*[python/topology/generator.py, line 1062 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQacWwEioaIBqiJl2Y:-LGQacWx-c4Esfjf8iJR:b-sfqb5c) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1062)):*
> ```Python
>             ],
>             'command': [
>                 '--log_dir=logs',
> ```

Also the default.

---

*[topology/Default.topo, line 7 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQTIDt86CjAiEP-ntU:-LGQTIDt86CjAiEP-ntV:bysky05) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/topology/Default.topo#L7)):*
> ```
>       addr: 127.0.0.1
>   docker-zks:
>     1:  
> ```

Trailing whitespace. Same for the other two .topo files.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1641)*

**Comment by kormat** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @worxli)

---

*[scion.sh, line 72 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQfglX98leGnRp7KZQ:-LGQfglX98leGnRp7KZR:b-7is17c) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L72)):*
> ```Shell
> cmd_status() {
>     if [ -f gen/docker-compose.yml ]; then
>         docker-compose -f gen/docker-compose.yml ps | grep -v Up
> ```

`\<Up\>`

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1641)*

**Comment by worxli** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @worxli and @kormat)

---

*[scion.sh, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQSFe55yweREvdnBl-:-LGU0FAd87W7SKAUpeZv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This can be dropped, we don't generate that anymore.

What we do need to do is create `/run/shm/dispatcher and `/run/shm/sciond` before starting docker compose (and changing the ownership if they already exist and are owned by root).
</blockquote></details>

Done.

---

*[scion.sh, line 49 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQRvWL3MSPf5UPwnGe:-LGU5WJc4KpiHGT3gCRM:be2cii5) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L49)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Two things:
- Don't mix `systemctl` and `service`
- This seems to assume it's running as root.
</blockquote></details>

No, it will prompt the user for a password (at least when there is a GUI). Would it be better to run it with sudo instead?

---

*[scion.sh, line 72 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQfglX98leGnRp7KZQ:-LGU6_86DjZcCuVaIo0_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L72)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`\<Up\>`
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 1001 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQd9Mw7vzCXkwAiSai:-LGU9Qit8f0uaPOfrDcG:b-u5cl8v) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1001)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

The default retry interval is far too long (1m). As an example:
```
2018-07-02 15:36:37.901860+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-02 15:36:37.901957+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-02 15:37:38.196908+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-02 15:37:38.197002+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
```
Can we make it 5s?
</blockquote></details>

It seems to have a back-off mechanism. For me it starts with 1s.

```
2018-07-03 07:58:34.693304+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:34.693387+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:35.004058+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:35.004122+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:35.401317+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:35.401392+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:36.017704+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:36.017773+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:37.052402+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:37.052492+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:38.923787+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:38.923858+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:42.364324+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:42.364409+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:48.986994+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:48.987082+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:59:02.048925+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:59:02.049024+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:59:27.873972+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:59:27.874037+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 08:00:19.480419+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 08:00:19.480616+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 08:01:19.786508+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 08:01:19.786600+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
```

---

*[python/topology/generator.py, line 1018 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQVkN-CzcdQosfPvbt:-LGU7OtF7_tARlz5vAAv:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1018)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I don't think the `scionproto` prefix is correct. If someone hasn't built any local images, this will download ones from dockerhub which are unrelated to whatever is checked out locally. So, i would use `scion_border` instead, with no prefix.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 1030 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQWNqaBKC2T6sagyOj:-LGU7ZWJ8fmYmbFq2-jC:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1030)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is the default.
</blockquote></details>

Done.

---

*[python/topology/generator.py, line 1062 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQacWwEioaIBqiJl2Y:-LGU7ZI735Pj2RjzeqV2:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1062)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Also the default.
</blockquote></details>

Done.

---

*[topology/Default.topo, line 7 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQTIDt86CjAiEP-ntU:-LGU7hPVA9Sxz_A2fbNM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/topology/Default.topo#L7)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Trailing whitespace. Same for the other two .topo files.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1641)*

**Comment by kormat** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @kormat and @worxli)

---

*[scion.sh, line 49 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQRvWL3MSPf5UPwnGe:-LGUNzfNCajCfNHtZHt3:b-l7yvlc) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/scion.sh#L49)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

No, it will prompt the user for a password (at least when there is a GUI). Would it be better to run it with sudo instead?
</blockquote></details>

Yes, much better. If there is no gui, it will just error out otherwise:
```
$ service zookeeper stop
Failed to stop zookeeper.service: Connection timed out
See system logs and 'systemctl status zookeeper.service' for details.
```

---

*[scion.sh, line 48 at r2](https://reviewable.io/reviews/scionproto/scion/1641#-LGUNaE3Ail7oO9u--dx:-LGUNaE3Ail7oO9u--dy:b-yzhbo8) ([raw file](https://github.com/scionproto/scion/blob/65e74437238900ba15d153c53f80111d6b2bf440/scion.sh#L48)):*
> ```Shell
>     local disp_dir="/run/shm/dispatcher"
>     [ -d "$disp_dir" ] || mkdir "$disp_dir"
>     [ $(stat -c "%U" "$disp_dir") != "root" ] || sudo chown $USER:$USER "$disp_dir"
> ```

`chown $LOGNAME:`. `$LOGNAME` is the standard env var, and `chmod user:` means "change the group to the default group of `user`". You shouldn't assume a user has a group with the same name.

---

*[python/topology/generator.py, line 1001 at r1](https://reviewable.io/reviews/scionproto/scion/1641#-LGQd9Mw7vzCXkwAiSai:-LGUOMUbAnGM_5HTh8dw:bf4fe4j) ([raw file](https://github.com/scionproto/scion/blob/e2825011fa1ddc2a9873e7d49ebfa52ac5567124/python/topology/generator.py#L1001)):*
<details><summary><i>Previously, worxli (Lukas Bischofberger) wrote…</i></summary><blockquote>

It seems to have a back-off mechanism. For me it starts with 1s.

```
2018-07-03 07:58:34.693304+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:34.693387+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:35.004058+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:35.004122+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:35.401317+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:35.401392+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:36.017704+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:36.017773+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:37.052402+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:37.052492+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:38.923787+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:38.923858+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:42.364324+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:42.364409+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:58:48.986994+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:58:48.987082+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:59:02.048925+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:59:02.049024+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 07:59:27.873972+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 07:59:27.874037+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 08:00:19.480419+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 08:00:19.480616+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
2018-07-03 08:01:19.786508+0000 [INFO] (1:dispatcher:dispatcher.c:205) dispatcher with zlog starting up
2018-07-03 08:01:19.786600+0000 [FATAL] (1:dispatcher:dispatcher.c:356) failed to bind app socket to /run/shm/dispatcher/default.sock
```
</blockquote></details>

Ok, but 1min is still too long.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1641)*

**Pull request merged**
