### PR TITLE
Handling of extension headers

### PR DESCRIPTION
**Pull request by jcp19**
I believe I may have come across two minor issues related to how extension headers are handled:
- the first one is demonstrated by the tests `TestHopByHopExtnDecodeReuse`. Basically, if we try to decode an HopByHopExtn into a receiver `e`, then we never erase the field `e.Options` and this slice will accumulate all the Options parsed in previous calls to `DecodeFromBytes`. The same seems to happen with `EndToEndExtn` and is demonstrated in the test `TestEndToEndExtnDecodeReuse`.
- in the function `nextHdr` in the router, we match the type of `layer` with both `EndToEndExtn` and `HopByHopExtn`, but judging from the only place from where this function is called, these comparisons can never succeed. Instead, it seems to me that we should compare them to `EndToEndExtnSkipper` and `HopByHopExtnSkipper` (both of which could succeed). These correspond to the types of  `p.e2eLayer` and `p.hbhLayer` in the method `processPkt`, respectively.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4308)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
These are great findings, thanks for this contribution!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4308#-:-NM0NZpK8Ffnrh364mAa:bczv5mm)* status: all files reviewed, 1 unresolved discussion (waiting on @jcp19)

___
*[`pkg/slayers/extn.go` line 256 at r1](https://reviewable.io/reviews/scionproto/scion/4308#-NM0IP3n0RZ55vcX9OE5:-NM0IP3n0RZ55vcX9OE6:b-4jrpdn) ([raw file](https://github.com/scionproto/scion/blob/b281645cc36488a58fcfcc4caf59bb67a80b581b/pkg/slayers/extn.go#L256)):*
> ```Go
> 	// Ignore Options that may have been parsed in previous calls to
> 	// DecodeFromBytes (potentially with different values of `data`).
> 	h.Options = nil
> ```

I think the statement to reset the `Options` value, even thought it has previously been missing by mistake, is fairly self-explanatory in this context. I would omit the comment in the interest of brevity, both here and below in EndToEndExtn.
___
*[`router/dataplane.go` line 1669 at r1](https://reviewable.io/reviews/scionproto/scion/4308#-NM0JBur5zJlRPw3VBL1:-NM0JBur5zJlRPw3VBL2:bjrnn5c) ([raw file](https://github.com/scionproto/scion/blob/b281645cc36488a58fcfcc4caf59bb67a80b581b/router/dataplane.go#L1669)):*
> ```Go
> 	case *slayers.EndToEndExtnSkipper:
> 		return v.NextHdr
> 	case *slayers.HopByHopExtnSkipper:
> ```

Great catch! Luckily this only used for diagnostics. 
This functions seems rather ill-conceived now, the type assertions are clearly very brittle. Perhaps we should add a common interface `NextHdr` field instead.

**Review by jcp19 — COMMENTED** [review]
happy to help :)

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4308#-:-NM0dHH07o8hrfaccXPh:b-gxqcqa)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`pkg/slayers/extn.go` line 256 at r1](https://reviewable.io/reviews/scionproto/scion/4308#-NM0IP3n0RZ55vcX9OE5:-NM0dMUP0UV_qTdMsJVN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b281645cc36488a58fcfcc4caf59bb67a80b581b/pkg/slayers/extn.go#L256)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

I think the statement to reset the `Options` value, even thought it has previously been missing by mistake, is fairly self-explanatory in this context. I would omit the comment in the interest of brevity, both here and below in EndToEndExtn.
</blockquote></details>

Done.

**Review by jcp19 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4308)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`router/dataplane.go` line 1669 at r1](https://reviewable.io/reviews/scionproto/scion/4308#-NM0JBur5zJlRPw3VBL1:-NM0dfPQ9dzX9htlbHt5:bj6yaoh) ([raw file](https://github.com/scionproto/scion/blob/b281645cc36488a58fcfcc4caf59bb67a80b581b/router/dataplane.go#L1669)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Great catch! Luckily this only used for diagnostics. 
This functions seems rather ill-conceived now, the type assertions are clearly very brittle. Perhaps we should add a common interface `NextHdr` field instead.
</blockquote></details>

I do agree that this is very brittle. I would however do that in a separate PR (I am a bit in a time-crunch for the VerifiedSCION project right now)

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4308#-:-NM2tz0w8I94RsqjYoU4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcp19)

___
*[`router/dataplane.go` line 1669 at r1](https://reviewable.io/reviews/scionproto/scion/4308#-NM0JBur5zJlRPw3VBL1:-NM2t_4H-f_2LaQwOdUM:b-8nl7j3) ([raw file](https://github.com/scionproto/scion/blob/b281645cc36488a58fcfcc4caf59bb67a80b581b/router/dataplane.go#L1669)):*
<details><summary><i>Previously, jcp19 (João Pereira) wrote…</i></summary><blockquote>

I do agree that this is very brittle. I would however do that in a separate PR (I am a bit in a time-crunch for the VerifiedSCION project right now)
</blockquote></details>

Yes, that's perfectly fine. :thumbsup:  That was also what I had in mind; sorry, I should have phrased this more clearly.

**Pull request merged**
