### PR TITLE
Improve some checks in c code

### PR DESCRIPTION
**Pull request by sgmonroy**
Only return address length if the given type is supported, otherwise return 0.

Also improve checks in tcpmw_bind and tcpmw_connect by checking for
allowed address type.

This change depends on a PR in scion-lwip.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @sgmonroy)

---

*[c/GRTAGS, line 0 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsWGwE10wDTG3xedZH:-LEsWGwE10wDTG3xedZI:b-gl5vhf) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/GRTAGS#L0)):*
These files shouldn't be in git.

---

*[c/lib/scion/address.h, line 93 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsWNA7-gXeSVpiNpzS:-LEsWNA7-gXeSVpiNpzT:bso5gtq) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/scion/address.h#L93)):*
> ```objc
> void format_host(int, uint8_t *, char *, int);
> void print_addresses(uint8_t *buf);
> char *addr_type_str(int addr_type);
> ```

`int` here vs `uint8_t` in `get_addr_len`?

---

*[c/lib/scion/address.c, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsZB3W8rnYtvd3JV5C:-LEsZB3W8rnYtvd3JV5D:bykz2rh) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/scion/address.c#L1)):*
> ```C
> #include <inttypes.h>
> ```

This PR should include updating the `sub/lwip` submodule to https://github.com/scionproto/scion-lwip/commit/0e82be5ab4db1f78c844735e73135daf4cf400b1

---

*[c/lib/tcp/middleware.c, line 222 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsXATC3RCRWkdx7aQt:-LEsXATC3RCRWkdx7aQu:b-uyclzi) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L222)):*
> ```C
>     char *p = buf;
>     s8_t lwip_err = 0;
>     const int HEADER_LEN =5;
> ```

` = 5;`

---

*[c/lib/tcp/middleware.c, line 279 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsXwsqCUNZ753OYVOd:-LEsXwsqCUNZ753OYVOe:b-8jfc4n) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L279)):*
> ```C
>     if (len < HEADER_LEN){  /* Minimum length (with empty path and haddr) */
>         lwip_err = ERR_MW;
>         zlog_error(zc_tcp, "tcpmw_connect(): wrong payload length: %dB", len);
> ```

It would be good to have different log messages for the 3 length checks.

---

*[c/lib/tcp/middleware.c, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsYkJt0h27nC8cFvji:-LEsYkJt0h27nC8cFvjj:bqol20b) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L307)):*
> ```C
>     /* Add path to the TCP/IP state */
>     spath_t *path = malloc(sizeof *path);
>     path->raw_path = malloc(path_len);
> ```

These two mallocs leak if the length check fails.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)*

**Comment by sgmonroy** [comment]
*[c/lib/tcp/middleware.c, line 279 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsXwsqCUNZ753OYVOd:-LEsfXUVEaScqmr1t4bG:b-pqtyuq) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L279)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

It would be good to have different log messages for the 3 length checks.
</blockquote></details>

I thought about it but then again what extra info can we provide? 
It seems too much related to implementation and the order of fields that we do these many checks, basically because we have variable length fields.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)*

**Comment by sgmonroy** [comment]
*[c/lib/tcp/middleware.c, line 307 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsYkJt0h27nC8cFvji:-LEsgMlW9lVqNRe5bXdM:b-y34nxx) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L307)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

These two mallocs leak if the length check fails.
</blockquote></details>

mmm how is it that they leaked if the check fails and not otherwise?  even if it does not fail the checked, there is no free in this function.
I didn't follow the code that much, I just expected to be done somewhere else.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)*

**Comment by kormat** [comment]
Review status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @sgmonroy and @kormat)

---

*[c/lib/tcp/middleware.c, line 279 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsXwsqCUNZ753OYVOd:-LEsqsKN9b7KTYWrbJK3:b-bqq7o2) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L279)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

I thought about it but then again what extra info can we provide? 
It seems too much related to implementation and the order of fields that we do these many checks, basically because we have variable length fields.
</blockquote></details>

My aim here is not so much that a user can instantly know what the problem is, but that if they send us a log snippet, we at least know which of the length checks have failed. We already know the function, as that's included at the start of the log messages. So maybe something like:
```
"payload length below minimum: min: %dB, actual: %dB"
"path length too long for payload: ..."
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)*

**Comment by kormat** [comment]
Review status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @sgmonroy and @kormat)

---

*[c/lib/tcp/middleware.c, line 279 at r1](https://reviewable.io/reviews/scionproto/scion/1608#-LEsXwsqCUNZ753OYVOd:-LEt1KguDtpnrzuxSBlY:b-nme11f) ([raw file](https://github.com/scionproto/scion/blob/925019d74ddd5381dcd6f9a74e877140b9ac4530/c/lib/tcp/middleware.c#L279)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

My aim here is not so much that a user can instantly know what the problem is, but that if they send us a log snippet, we at least know which of the length checks have failed. We already know the function, as that's included at the start of the log messages. So maybe something like:
```
"payload length below minimum: min: %dB, actual: %dB"
"path length too long for payload: ..."
```
</blockquote></details>

Upon reflection, we're going to be dropping this code ASAP anyway, so nevermind :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 5 of 7 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @kormat)

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1608#-:-LEt7BnZ7sNKV2vxy3sD:bnfp4nl)*

**Pull request merged**
