### PR TITLE
LWIP removal

### PR DESCRIPTION
**Pull request by sgmonroy**
SCIONTCP is currently unsupported so this change removes
the LWIP git submodules and related SCION code.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1629)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @sgmonroy)

---

*[Makefile, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/1629#-LG-QOE41sujzPSwc0GN:-LG-QOE41sujzPSwc0GO:bmlbyrm) ([raw file](https://github.com/scionproto/scion/blob/2f97d9a63e47a535ac54c89bb9bf34539671be8e/Makefile#L44)):*
> ```Makefile
> 	$(foreach var,$(SRC_DIRS),$(MAKE) -C $(var) uninstall || exit 1;)
> 
> tags:
> ```

Don't remove this :P Just drop the `git submodule` part.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1629)*

**Comment by sgmonroy** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @kormat)

---

*[Makefile, line 44 at r1](https://reviewable.io/reviews/scionproto/scion/1629#-LG-QOE41sujzPSwc0GN:-LG-WdpmDSqUBlZTPnY9:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/2f97d9a63e47a535ac54c89bb9bf34539671be8e/Makefile#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Don't remove this :P Just drop the `git submodule` part.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1629)*

**Comment by sgmonroy** [comment]
Review status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @kormat)

---

*[Makefile, line 10 at r3](https://reviewable.io/reviews/scionproto/scion/1629#-LGPWK11-u-E9PW5fhdV:-LGPXzb4D0z9KDLKCN4v:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d1e1331a611a0b7032747575cf8c3867156cdbcf/Makefile#L10)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`rm -f bin/* tags`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1629)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1629#-:-LGPY6iPBOyvG1LFH3yp:bnfp4nl)*

**Pull request merged**
