### PR TITLE
scion.sh: do a more complete shutdown by default

### PR DESCRIPTION
**Pull request by jiceatscion**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4382)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4382)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`scion.sh` line 21 at r1](https://reviewable.io/reviews/scionproto/scion/4382#-NcabDXF36HWuSWk6lFL:-NcabDXF36HWuSWk6lFM:b-xame50) ([raw file](https://github.com/scionproto/scion/blob/4ade8a5d69ed56880d5379a9b52edfc5033ef82d/scion.sh#L21)):*
> ```Shell
>         run_teardown
>     fi
>     stop_jaeger
> ```

This is now (almost) equivalent to `cmd_stop`, the only difference is ignoring the error of docker-compose down. Can we replace this with `cmd_stop || true` to simplify?



_Code quote:_
```Shell
    if is_docker_be; then
        echo "Shutting down dockerized topology..."
        ./tools/quiet ./tools/dc down || true
    else
        ./tools/quiet tools/supervisor.sh shutdown
        run_teardown
    fi
    stop_jaeger
```

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4382)* status: all files reviewed, 1 unresolved discussion (waiting on @matzf)

___
*[`scion.sh` line 21 at r1](https://reviewable.io/reviews/scionproto/scion/4382#-NcabDXF36HWuSWk6lFL:-NcaeddZ8S90Xpon7JxH:bv3qucw) ([raw file](https://github.com/scionproto/scion/blob/4ade8a5d69ed56880d5379a9b52edfc5033ef82d/scion.sh#L21)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is now (almost) equivalent to `cmd_stop`, the only difference is ignoring the error of docker-compose down. Can we replace this with `cmd_stop || true` to simplify?
</blockquote></details>

Sure. I had not noticed. Is there a meaningful difference between "tools/cd down" and "tools/dc/down scion*" ?

**Review by matzf — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4382)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion)

___
*[`scion.sh` line 21 at r1](https://reviewable.io/reviews/scionproto/scion/4382#-NcabDXF36HWuSWk6lFL:-Ncarr4x-1cH5UylN1EZ:b-7jsslt) ([raw file](https://github.com/scionproto/scion/blob/4ade8a5d69ed56880d5379a9b52edfc5033ef82d/scion.sh#L21)):*
> Is there a meaningful difference between "tools/cd down" and "tools/dc/down scion\*" ?

`tools/dc down` ignores all arguments, so no difference. Perhaps it'd be better to remove this argument for clarity.

FWIW, for `stop` the script explicitly does a globbing for matching services. Thus, the `tools/dc stop 'scion*'` left the "tester" containers up. I don't think that we need to keep this.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4382)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @matzf)

___
*[`scion.sh` line 21 at r1](https://reviewable.io/reviews/scionproto/scion/4382#-NcabDXF36HWuSWk6lFL:-Ncay512CbyRagQT7hR6:b-896fjx) ([raw file](https://github.com/scionproto/scion/blob/4ade8a5d69ed56880d5379a9b52edfc5033ef82d/scion.sh#L21)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> Is there a meaningful difference between "tools/cd down" and "tools/dc/down scion\*" ?

`tools/dc down` ignores all arguments, so no difference. Perhaps it'd be better to remove this argument for clarity.

FWIW, for `stop` the script explicitly does a globbing for matching services. Thus, the `tools/dc stop 'scion*'` left the "tester" containers up. I don't think that we need to keep this.
</blockquote></details>

Done

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4382#-:-Ncazrpy2Lv9ndtW5R_Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Comment by jiceatscion** [comment]
Thanks for the approval. Just a reminder. I'm not allowed to merge PRs yet (probably just as well).

**Pull request merged**
