### PR TITLE
Dockerfile Licenses

### LINKED ISSUE #1627: Docker: Licensing
Each docker container must also contain the relevant licenses, e.g. the Go license for anything from golang.org/x/: https://golang.org/LICENSE
Also: https://github.com/spf13/pflag/blob/master/LICENSE

### PR DESCRIPTION
**Pull request by worxli**
Adds licenses to Dockerfiles, fixes #1627.
- Copy license for toybox, su-exec
- Copy copyright files for all debian packages
- Add pip package licenses in `env/pip3/licenses`, with `env/pip3/licenses.txt` as index, located at `/LICENSES/pip/` in the python Docker containers
- Add go license tree to all Docker containers at `/LICENSES/go`

Removes `nose-descriptionfixer` as it has no license.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed, 8 unresolved discussions (waiting on @worxli)

---

*[docker/perapp/base/Dockerfile.base, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0RYtL9gV426y5fVCV:-LG0RYtL9gV426y5fVCW:b5sig89) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.base#L18)):*
> ```
> 
> # Collect go licenses
> RUN set -e; mkdir go-licenses; \
> ```

Might as well copy direct to `/rootfs/LICENSES/go`.

---

*[docker/perapp/base/Dockerfile.base, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0SjSL2-OXCIf5Fzxo:-LG0SjSL2-OXCIf5Fzxp:b-s1xa6z) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.base#L20)):*
> ```
> RUN set -e; mkdir go-licenses; \
>     cd /home/scion/go/src/github.com/scionproto/scion/go/vendor; \
>     find . -name '*LICENSE*' -exec cp --parents \{\} /root/scion-docker/go-licenses \; ; \
> ```

```
find . -iregex '.*\(LICENSE\|COPYING\).*' -exec cp --parents '{}' /rootfs/LICENSES/go ';'
```

---

*[docker/perapp/base/Dockerfile.debug, line 8 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0LB5o0Jp5CIeIeL60:-LG0LB5o0Jp5CIeIeL61:bcj169n) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.debug#L8)):*
> ```
> RUN ./copy_package strace '/usr/share'
> ARG TOYBOX_SHA=b6fbc37f93c504fcf4520b4121ebfde651f917ff4c62b72130a92041f1d23914
> ARG TOYBOX_VERSION=0.7.6
> ```

I'd reverse the order of these two, the SHA is because of the version, not the other way around.

---

*[docker/perapp/base/Dockerfile.debug, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0Lpd-5rWwPdXiyQC-:-LG0Lpd-5rWwPdXiyQC0:boebxsh) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.debug#L18)):*
> ```
> # Download LICENSE
> RUN set -ex; mkdir -p /usr/share/doc/toybox; \
>     curl -SL "https://landley.net/toybox/downloads/toybox-${TOYBOX_VERSION}.tar.gz" | tar xz "toybox-${TOYBOX_VERSION}/LICENSE" -O > /usr/share/doc/toybox/LICENSE
> ```

A less torturous way: `curl -sSL https://github.com/landley/toybox/blob/0.7.6/LICENSE --create-dirs -o /rootfs/LICENSES/toybox/LICENSE`

---

*[docker/perapp/files/copy_package, line 11 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0TLU_6VP55_-Mht71:-LG0TLU_6VP55_-Mht72:b-sf1a0n) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/files/copy_package#L11)):*
> ```
> copyright=/usr/share/doc/"$1"/copyright
> if [ -e "$copyright" ]; then
>     files+=" $copyright"
> ```

```
mkdir -p /rootfs/LICENSES/"$1"
cp "$copyright" /rootfs/"$1"/
```

---

*[env/pip3/licenses.txt, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0975L8gfQdVPCaz7G:-LG0975M05N47FnQLbmr:b-1mnnz1) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses.txt#L1)):*
> ```
> pycapnp: licenses/BSD-2-Clause
> ```

I'm now wondering - does `requirements.txt` allow full-line comments? If so we could merge these two like:
```
# pycapnp: licenses/BSD-2-Clause
pycapnp==0.6.1 --hash=sha256:ea60837533307849e98bb3494555cea28a52ea0c301cfdf32bce661931940696 # Direct dependency
# PyDbLite: licenses/BSD-3-Clause
PyDbLite==3.0.4 --hash=sha256:79ed97d17b5954c6fa8927d9f36033cb4486d1304005057d506ac1dee999bad6 # Direct dependency
...
```

---

*[env/pip3/licenses/prometheus-client, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0VDUoCfdOiBQRHa_Q:-LG0VDUoCfdOiBQRHa_R:bc75yg1) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses/prometheus-client#L1)):*
> ```
>                                  Apache License
> ```

Has this been customized?

---

*[env/pip3/licenses/pypacker, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0VI7GDTqltXTqjKLL:-LG0VI7GDTqltXTqjKLM:bc75yg1) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses/pypacker#L1)):*
> ```
> 		    GNU GENERAL PUBLIC LICENSE
> ```

Has this been customized?

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by worxli** [comment]
Review status: all files reviewed, 8 unresolved discussions (waiting on @kormat and @worxli)

---

*[docker/perapp/base/Dockerfile.base, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0RYtL9gV426y5fVCV:-LG0XH21BPMWLQEgphIY:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.base#L18)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Might as well copy direct to `/rootfs/LICENSES/go`.
</blockquote></details>

Done.

---

*[docker/perapp/base/Dockerfile.base, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0SjSL2-OXCIf5Fzxo:-LG0XNtYCdEiz3mwc60Y:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.base#L20)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

```
find . -iregex '.*\(LICENSE\|COPYING\).*' -exec cp --parents '{}' /rootfs/LICENSES/go ';'
```
</blockquote></details>

Done.

---

*[docker/perapp/base/Dockerfile.debug, line 8 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0LB5o0Jp5CIeIeL60:-LG0Y6znEvAJ8mC6G4bf:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.debug#L8)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'd reverse the order of these two, the SHA is because of the version, not the other way around.
</blockquote></details>

Done.

---

*[docker/perapp/base/Dockerfile.debug, line 18 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0Lpd-5rWwPdXiyQC-:-LG0YSQO2Vb2gIYowxtg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/base/Dockerfile.debug#L18)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

A less torturous way: `curl -sSL https://github.com/landley/toybox/blob/0.7.6/LICENSE --create-dirs -o /rootfs/LICENSES/toybox/LICENSE`
</blockquote></details>

Done.

---

*[docker/perapp/files/copy_package, line 11 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0TLU_6VP55_-Mht71:-LG0YrgN9NFLML8ljPGc:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/docker/perapp/files/copy_package#L11)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

```
mkdir -p /rootfs/LICENSES/"$1"
cp "$copyright" /rootfs/"$1"/
```
</blockquote></details>

Done.

---

*[env/pip3/licenses.txt, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0975L8gfQdVPCaz7G:-LG0_5x83xJHE5NJ5SOg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses.txt#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I'm now wondering - does `requirements.txt` allow full-line comments? If so we could merge these two like:
```
# pycapnp: licenses/BSD-2-Clause
pycapnp==0.6.1 --hash=sha256:ea60837533307849e98bb3494555cea28a52ea0c301cfdf32bce661931940696 # Direct dependency
# PyDbLite: licenses/BSD-3-Clause
PyDbLite==3.0.4 --hash=sha256:79ed97d17b5954c6fa8927d9f36033cb4486d1304005057d506ac1dee999bad6 # Direct dependency
...
```
</blockquote></details>

Done.

---

*[env/pip3/licenses/prometheus-client, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0VDUoCfdOiBQRHa_Q:-LG0aWj44ldGiKJS9gWQ:bjt7be1) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses/prometheus-client#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Has this been customized?
</blockquote></details>

No, they did not even remove the: How to apply the Apache License to your work

---

*[env/pip3/licenses/pypacker, line 1 at r1](https://reviewable.io/reviews/scionproto/scion/1628#-LG0VI7GDTqltXTqjKLL:-LG0azWv9B_3Mup9Yjz7:bzg4p) ([raw file](https://github.com/scionproto/scion/blob/15c4078c91831748853a71626f66266db4fae49f/env/pip3/licenses/pypacker#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Has this been customized?
</blockquote></details>

Same here...

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by kormat** [comment]
Reviewed 8 of 9 files at r2.
Review status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @kormat and @worxli)

---

*[env/pip3/licenses/GPL, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1628#-LG0imeP9GfcTRqWJ6Zs:-LG0imeQBBRmnNuYyUt2:b-c6btxg) ([raw file](https://github.com/scionproto/scion/blob/a7ac20977b769ec257b23cd6516bf5e51cd725e0/env/pip3/licenses/GPL#L1)):*
> ```
> pypacker
> ```

`GPLv2`

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by worxli** [comment]
Review status: 11 of 15 files reviewed, 2 unresolved discussions (waiting on @kormat)

---

*[env/pip3/licenses/GPL, line 1 at r2](https://reviewable.io/reviews/scionproto/scion/1628#-LG0imeP9GfcTRqWJ6Zs:-LG0nG3yD1lfPrptoSa-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a7ac20977b769ec257b23cd6516bf5e51cd725e0/env/pip3/licenses/GPL#L1)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`GPLv2`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by kormat** [comment]
Reviewed 1 of 9 files at r2, 3 of 3 files at r3.
Review status: all files reviewed, 1 unresolved discussion (waiting on @worxli)

---

*[docker/perapp/base/Dockerfile.python, line 32 at r3](https://reviewable.io/reviews/scionproto/scion/1628#-LG0uCWg-LlWOu0jvIMB:-LG0uCWg-LlWOu0jvIMC:b9o5t1i) ([raw file](https://github.com/scionproto/scion/blob/d9ddfffd7e390dfc7112cd3404d47e58d7b88fd6/docker/perapp/base/Dockerfile.python#L32)):*
> ```
> # Copy pip packages
> COPY --from=0 /home/scion/.local/lib/python3.5/site-packages /usr/lib/python3.5
> COPY --from=0 /home/scion/go/src/github.com/scionproto/scion/env/pip3/licenses /LICENSES/pip
> ```

You need to copy the `requirements.txt` file too, as that provides the list of deps, and the mapping to the licenses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by worxli** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @kormat)

---

*[docker/perapp/base/Dockerfile.python, line 32 at r3](https://reviewable.io/reviews/scionproto/scion/1628#-LG0uCWg-LlWOu0jvIMB:-LG40INbDscMVDgVPKqo:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/d9ddfffd7e390dfc7112cd3404d47e58d7b88fd6/docker/perapp/base/Dockerfile.python#L32)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

You need to copy the `requirements.txt` file too, as that provides the list of deps, and the mapping to the licenses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1628#-:-LG4uUojE0eC4yiE_HCr:bnfp4nl)*

**Pull request merged**
