### PR TITLE
epic: wireshark dissector

### PR DESCRIPTION
**Pull request by mawyss**
Add dissector for the EPIC path type header to the Wireshark SCION plugin.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4083)

### CODE REVIEW

**Review by sgmonroy — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4083)* status: all files reviewed, 1 unresolved discussion (waiting on @mawyss)

___
*[tools/wireshark/scion.lua, line 482 at r1](https://reviewable.io/reviews/scionproto/scion/4083#-MgoYu05-11TqmX1LM0V:-MgoYu06CswWTxjTi3t2:b3us2b3) ([raw file](https://github.com/scionproto/scion/blob/065e3e04831f699387f369f142e9cf0f5a25317f/tools/wireshark/scion.lua#L482)):*
> ```Lua
> 
>     -- Parse the SCION path type fields
>     ok = scion_path_dissect(tvbuf(16), pktinfo, root)
> ```

moving this after you parse the EPIC specific fields, which are currently before the standard SCION path, would at least show this fields in case of error on the SCION path.

**Review by mawyss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4083)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sgmonroy)

___
*[tools/wireshark/scion.lua, line 482 at r1](https://reviewable.io/reviews/scionproto/scion/4083#-MgoYu05-11TqmX1LM0V:-MgpvYr-5ewDvBRZXIHK:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/065e3e04831f699387f369f142e9cf0f5a25317f/tools/wireshark/scion.lua#L482)):*
<details><summary><i>Previously, sgmonroy (Sergio Gonzalez Monroy) wrote…</i></summary><blockquote>

moving this after you parse the EPIC specific fields, which are currently before the standard SCION path, would at least show this fields in case of error on the SCION path.
</blockquote></details>

Done.

**Review by sgmonroy — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4083#-:-MhUy1I45h6xby9B8VlL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mawyss)

**Pull request closed without merging**
