### PR TITLE
underlay: support SockOptInt on all platforms incl Windows

### PR DESCRIPTION
**Pull request by martenwallewein**
Hey all,

I  tried to build all the major SCION binaries for windows to see if it's possible to run an AS also on this platform. However, there is an issue that `syscall.GetsockoptInt` and `syscall.SetsockoptInt` have different signatures on windows than on all other platforms. One fix is to have extra windows code to support this, but I'm not sure what you prefer, so let me know if this fits or if I can do some other changes. In the end it would be great to have Windows support for all SCION services, too.

PS: The issue popped up when building the router, not sure if it affects other services.

Cheers,
Marten

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4610)

**Review by jiceatscion — CHANGES_REQUESTED** [review]
Sounds good. No objection to a couple of os-specific files for such low-level issues. If that causes build issues, the CI will tell us.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4610#-:-O65WM0V0Oes6vW6UwpY:b-568bsy)* status: all files reviewed, 4 unresolved discussions (waiting on @martenwallewein)

___
*[`private/underlay/sockctrl/sockctrl.go` line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4610#-O65VPtR7mYJUkRhTIs2:-O65VPtR7mYJUkRhTIs3:b5loak8) ([raw file](https://github.com/scionproto/scion/blob/b5bad585066e0b86a45515cf7c638f00d88f18e2/private/underlay/sockctrl/sockctrl.go#L17)):*
> ```Go
> // In Windows, SetSockOptInt and GetSockOptInt require syscall.Handle instead of int.
> //go:build !windows
> // +build !windows
> ```

+build is obsolete enough that we no  don't use it any more. go:build is sufficient.
___
*[`private/underlay/sockctrl/sockctrl_windows.go` line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4610#-O65VhRs5x_KQnf3BNcA:-O65VhRs5x_KQnf3BNcB:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/b5bad585066e0b86a45515cf7c638f00d88f18e2/private/underlay/sockctrl/sockctrl_windows.go#L17)):*
> ```Go
> // In Windows, SetSockOptInt and GetSockOptInt require syscall.Handle instead of int.
> //go:build windows
> // +build windows
> ```

ditto
___
*[`private/underlay/sockctrl/sockopt.go` line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4610#-O65Vw-UEvau3OCoHLLS:-O65Vw-UEvau3OCoHLLT:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/b5bad585066e0b86a45515cf7c638f00d88f18e2/private/underlay/sockctrl/sockopt.go#L17)):*
> ```Go
> // In Windows, SetSockOptInt and GetSockOptInt require syscall.Handle instead of int.
> //go:build !windows
> // +build !windows
> ```

ditto
___
*[`private/underlay/sockctrl/sockopt_windows.go` line 17 at r1](https://reviewable.io/reviews/scionproto/scion/4610#-O65WCGZE6TloNLhUXUZ:-O65WCG_6gd6Dr90YUID:b-7ropln) ([raw file](https://github.com/scionproto/scion/blob/b5bad585066e0b86a45515cf7c638f00d88f18e2/private/underlay/sockctrl/sockopt_windows.go#L17)):*
> ```Go
> // In Windows, SetSockOptInt and GetSockOptInt require syscall.Handle instead of int.
> //go:build windows
> // +build windows
> ```

ditto

**Review by jiceatscion — COMMENTED** [review]
Could you run "make gazelle" to update the deps/src in the build file? That will make the CI checks happy.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4610#-:-O65m1K_4MVhl6tNSPaw:bemq7v2)* status: all files reviewed, 4 unresolved discussions (waiting on @martenwallewein)

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4610)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @martenwallewein)

**Review by marcfrei — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4610#-:-O662hLe0V8yqE8hJ99g:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @martenwallewein)

___
*[`private/underlay/sockctrl/sockctrl_windows.go` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4610#-O662Uyt1X-A8qopY2L3:-O662Uyt1X-A8qopY2L4:bb6ht39) ([raw file](https://github.com/scionproto/scion/blob/23207a15ee0970a7bc5b2fb714e604f2a881cd20/private/underlay/sockctrl/sockctrl_windows.go#L1)):*
> ```Go
> // Copyright 2017 ETH Zurich
> ```

2024
___
*[`private/underlay/sockctrl/sockopt_windows.go` line 1 at r2](https://reviewable.io/reviews/scionproto/scion/4610#-O662_Zz2p9oxVcjC-qz:-O662_Zz2p9oxVcjC-r-:bb6ht39) ([raw file](https://github.com/scionproto/scion/blob/23207a15ee0970a7bc5b2fb714e604f2a881cd20/private/underlay/sockctrl/sockopt_windows.go#L1)):*
> ```Go
> // Copyright 2017 ETH Zurich
> ```

2024

**Comment by martenwallewein** [comment]
Hey guys, thanks a lot for the quick feedback! I updated the copyright and ran "make gazelle" as suggested.

**Comment by martenwallewein** [comment]
Hey guys, I resolved all the comments but the CI still fails. It says end-to-end test failed. I ran this locally, there it worked. Could this be related to this: https://github.com/scionproto/scion/issues/4606?

I'm not sure how to proceed to fix the CI issue, so open for any suggestion.

**Review by jiceatscion — COMMENTED** [review]
Yes, it looks that way. I hot the retry button on that one test. Sometimes it takes 2 o 3 attempts. I have a PR in the pipeline that includes a temporary patch for it. It should makes things acceptable until we find the root cause.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4610#-:-O6KxTz85IUAxuveJCU6:bu8f8n4)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @marcfrei)

**Comment by martenwallewein** [comment]
Thanks @jiceatscion and @marcfrei for taking care of this! :blush:

**Pull request merged**
