### PR TITLE
deps: upgrade to Go 1.18.5

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Also upgrade:
- rules_go to v0.34
- gazelle to v0.26
- quic-go to v0.27.2

Also drop the dependency on the custom gomock bazel library, instead use
the rules_go gomock rule.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4248)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
:lgtm:

CI fails only because the protobuf files need to be regenerated (header changed) and some line numbers for the stacktrace in the in the `serrors` test golden files have changed (golden file just needs to be updated).

> Reviewed 56 of 56 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4248#-:-NAdxLhl-i4wowfR5PLb:b5adi69)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`go_deps.bzl` line 997 at r1](https://reviewable.io/reviews/scionproto/scion/4248#-NAdwBELAiXpeIrnGINQ:-NAdwBELAiXpeIrnGINR:b-rd0mss) ([raw file](https://github.com/scionproto/scion/blob/a0dc7c42420e4d237f46a005e6e915394ffe3552/go_deps.bzl#L997)):*
> ```Starlark
>     go_repository(
>         name = "com_github_marten_seemann_qtls_go1_18",
>         build_directives = ["gazelle:exclude generate_cert.go"],  # XXX(matzf): this file has a "// go:build ignore" instruction that gazelle does not understand
> ```

This should no longer be necessary with the patched gazelle. :tada: 
___
*[`patches/README.md` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4248#-NAdwlix0f_jLUu0E7D6:-NAdwlix0f_jLUu0E7D7:br3xz16) ([raw file](https://github.com/scionproto/scion/blob/a0dc7c42420e4d237f46a005e6e915394ffe3552/patches/README.md#L6)):*
> ```Markdown
> that simplify the migration when breaking changes to library packages are
> introduced. Furthermore it contains patches to dependencies in subdirectories,
> the remainder of this document is only about the patches for migrations. 
> ```

Trailing whitespace (lint error)

**Review by lukedirtwalker — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4248#-:-NAhJQmi3ijngIcVTkVx:b-896fix)* status: 54 of 76 files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @matzf)

___
*[`go_deps.bzl` line 997 at r1](https://reviewable.io/reviews/scionproto/scion/4248#-NAdwBELAiXpeIrnGINQ:-NAhJNwv2bXCXIJmbQn8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a0dc7c42420e4d237f46a005e6e915394ffe3552/go_deps.bzl#L997)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This should no longer be necessary with the patched gazelle. :tada: 
</blockquote></details>

Done.



_Code quote:_
```Starlark
com_github_marten_seemann_qtls_go1_18
```
___
*[`patches/README.md` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4248#-NAdwlix0f_jLUu0E7D6:-NAhJ1n-5tLJ5lXUmIRN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a0dc7c42420e4d237f46a005e6e915394ffe3552/patches/README.md#L6)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Trailing whitespace (lint error)
</blockquote></details>

Done.

**Review by matzf — APPROVED** [review]
Oh there also seem to be some new "nogo" errors in external libraries that now need to be excluded.

> Reviewed 22 of 22 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4248#-:-NAhUIAz4k0U_LjtPtY2:b-n9l3ap)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — COMMENTED** [review]
Fixed now. There was a failing e2e test, which I assume was a flake.

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4248#-:-NAiOjYrCGpEN3iYGpNR:b-gi14ay)* status: 76 of 81 files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4248#-:-NAiQD_UEfPvjJXShpk9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Pull request merged**
