### PR TITLE
Restrict HF ExpTime to the validity period of CertChain/TRC

### PR DESCRIPTION
**Pull request by Oncilla**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1374)

### CODE REVIEW

**Comment by shitz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/beacon_server/base.py, line 244 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aKqS1Pi-60ffFCgKZ:-L2aKqS1Pi-60ffFCgK_:bd4l4vh) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/beacon_server/base.py#L244)):*
> ```Python
>         """
>         cert = self._get_my_cert()
>         exp = min(self._get_my_trc().exp_time, cert.as_cert.expiration_time,
> ```

Hmm does it even make sense to have a certificate signed by a core-as cert with a lower expiration time (same for TRC and core-as cert)?

---

*[python/beacon_server/base.py, line 246 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aNZe6wazbzBlIg4Ff:-L2aNZe6wazbzBlIg4Fg:b-2mljyr) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/beacon_server/base.py#L246)):*
> ```Python
>         exp = min(self._get_my_trc().exp_time, cert.as_cert.expiration_time,
>                   cert.core_as_cert.expiration_time)
>         max_exp_time = int((exp-ts)/EXP_TIME_UNIT)
> ```

whitespaces around `/`

---

*[python/scion_elem/scion_elem.py, line 667 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aOxH9S7M5R5Utq_nS:-L2aOxH9S7M5R5Utq_nT:b-qgy3g9) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/scion_elem/scion_elem.py#L667)):*
> ```Python
>         :raises SCIONVerificationError
>         """
>         if trc.exp_time < exp_time:
> ```

I'm fine with these checks, but we should really make sure that `TRC.exp_time > CoreASCert.exp_time > ASCert.exp_time` or is that not feasible?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374)*

**Comment by Oncilla** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/beacon_server/base.py, line 244 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aKqS1Pi-60ffFCgKZ:-L2aPY8zsSUgafK0y9DM:bh0p7ml) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/beacon_server/base.py#L244)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Hmm does it even make sense to have a certificate signed by a core-as cert with a lower expiration time (same for TRC and core-as cert)?
</blockquote></details>

It does not. I will include this in PR #1373

---

*[python/scion_elem/scion_elem.py, line 667 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aOxH9S7M5R5Utq_nS:-L2aPnhWRylL41pBdYbr:b-vywjcr) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/scion_elem/scion_elem.py#L667)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

I'm fine with these checks, but we should really make sure that `TRC.exp_time > CoreASCert.exp_time > ASCert.exp_time` or is that not feasible?
</blockquote></details>

I have that implemented locally, will push it to PR #1373 tomorrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374)*

**Comment by Oncilla** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[python/beacon_server/base.py, line 246 at r1](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2aNZe6wazbzBlIg4Ff:-L2dVk7UCkZXOdLlKIH4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e20f93d9aaacd5a026cf3e160f7a72309828dbde/python/beacon_server/base.py#L246)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

whitespaces around `/`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374)*

**Comment by shitz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/beacon_server/base.py, line 246 at r2](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2eRMGMxxF_8KUOCIHk:-L2eRDmHfDeIrTN9FgUq:b-hwqjm8) ([raw file](https://github.com/scionproto/scion/blob/ba0f4c526b8207c10be4bf34c6a0df791db5ae9a/python/beacon_server/base.py#L246)):*
> ```Python
>         max_exp_time = int((cert_exp-ts) / EXP_TIME_UNIT)
>         exp_time = min(max_exp_time, self.default_hof_exp_time)
>         if exp_time <= 0:
> ```

This check shouldn't be here. Instead this should be checked in `_create_pcbm` and in case of `0` log an error and  do not disseminate a beacon with 0 ttl.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374)*

**Comment by Oncilla** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[python/beacon_server/base.py, line 246 at r2](https://reviewable.io:443/reviews/scionproto/scion/1374#-L2eRMGMxxF_8KUOCIHk:-L2eXfQujStZyBTwbwEP:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ba0f4c526b8207c10be4bf34c6a0df791db5ae9a/python/beacon_server/base.py#L246)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This check shouldn't be here. Instead this should be checked in `_create_pcbm` and in case of `0` log an error and  do not disseminate a beacon with 0 ttl.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1374#-:-L2e_dp7CqUtsltfet5F:bnfp4nl)*

**Pull request merged**
