### PR TITLE
spao: Update timestamp / Sequence Number field

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR introduces modification on the SPAO header. More concretely, the changes concerning the Timestamp / Sequence Number field specified in https://github.com/scionproto/scion/pull/4300.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)

### CODE REVIEW

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: all files reviewed, 16 unresolved discussions (waiting on @JordiSubira)

___
*[`control/config/drkey.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yd8OE7rmg1C6Fu4uR:-N_Yd8OE7rmg1C6Fu4uS:b-4tq6q7) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L41)):*
> ```Go
> 	// Picking the value equal or shorter than half of the drkey Grace Period ensures
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowOffset = 2*time.Second + 500*time.Millisecond
> ```

Naming inconsistency; this definition has `Offset`, but other definitions with the exact same interpretation are just "acceptance window". This naming inconsistency could be confusing, as it's not super obvious everywhere whether this is the half-window or the full window duration.
___
*[`control/config/drkey.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YTzUG-jmVn4RL7Oc5:-N_YTzUG-jmVn4RL7Oc6:undefined) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L42)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowOffset = 2*time.Second + 500*time.Millisecond
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```





_Suggestion:_
```Go
	EnvVarAcceptanceWindow
```
___
*[`control/config/drkey.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YU0Xb0xbr6a24_BGo:-N_YU0Xc0qSnASTJ5Mab:brk1xn9) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L42)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowOffset = 2*time.Second + 500*time.Millisecond
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```

As these are now read by the router, having these definitions in `control/config` does not seem appropriate.
Perhaps the new `private/drkey` package that you've added would be a good place for these things? Then you could keep all constants local and expose only the function that returns the effective value (and by that avoid the duplication of the logic for parsing the environment variable, that we now have).
___
*[`pkg/slayers/pkt_auth.go` line 171 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YDLLC0MCaltP0jHBV:-N_YDLLC0MCaltP0jHBW:undefined) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/slayers/pkt_auth.go#L171)):*
> ```Go
> 
> 	if p.TimestampSN >= (1 << 48) {
> 		return serrors.New("Timestamp value should be smaller than 2^24")
> ```





_Suggestion:_
```Go
should be smaller than 2^48
```
___
*[`pkg/slayers/pkt_auth.go` line 187 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YDg-W9Pj7RnIbz3RH:-N_YDg-W9Pj7RnIbz3RI:bdzqrfb) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/slayers/pkt_auth.go#L187)):*
> ```Go
> 	o.OptData[6] = byte(p.TimestampSN >> 40)
> 	o.OptData[7] = byte(p.TimestampSN >> 32)
> 	binary.BigEndian.PutUint32(o.OptData[8:12], uint32(p.TimestampSN))
> ```

Nit: separately reading/writing the first two bytes seems a bit awkward and looks like it could easily be forgotten. I'd either handle all six bytes explicitly here, or create simple helper functions to do this (something like `bigEndianPutUint48` and `bigEndianUint48`).
___
*[`pkg/slayers/pkt_auth_test.go` line 65 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YFAD22du4j81IQCmO:-N_YFAD22du4j81IQCmP:b-tzf8j) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/slayers/pkt_auth_test.go#L65)):*
> ```Go
> 			spiFunc: initSPI,
> 			algo:    algo,
> 			ts: binary.LittleEndian.Uint64(
> ```

Aside: the value is big-endian (right!?), so the `LittleEndian` here seems a bit odd. It's probably clearer to just specify a uint64 value anyway (like `ts` in the global var-block).
I remember that we had discussed and changed this in the original PR, put it seems we missed some places.
___
*[`pkg/spao/mac.go` line 133 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YWflX3Qa3vvhqEcIk:-N_YWflX3Qa3vvhqEcIl:b-9swtdj) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/mac.go#L133)):*
> ```Go
> 	buf[6] = byte(opt.TimestampSN() >> 40)
> 	buf[7] = byte(opt.TimestampSN() >> 32)
> 	binary.BigEndian.PutUint32(buf[8:12], uint32(opt.TimestampSN()))
> ```

Same as above, create helper function for 48 bit write
___
*[`pkg/spao/timestamp.go` line 26 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YZMOu96l-3EU7O1EO:-N_YZMOu96l-3EU7O1EP:b-313pcv) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/timestamp.go#L26)):*
> ```Go
> // RelativeTimestamp returns the relative timestamp (RelTime) as the time diference from
> // time instant t to the beginning of the drkey epoch.
> func RelativeTimestamp(key drkey.ASHostKey, t time.Time) (uint64, error) {
> ```

Shouldn't this also be usable for `HostHostKey`? If so, just pass the `Epoch` directly? 
___
*[`pkg/spao/timestamp.go` line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YGTpCDI3GM-WCtdRR:-N_YGTpCDI3GM-WCtdRS:undefined) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/timestamp.go#L35)):*
> ```Go
> 
> // AbsoluteTimestamp returns the absolute timestamp (AbsTime) based on the
> // relTime (Timestamp / Sequence Number field in SPAO hedaer) and the DRKey
> ```





_Suggestion:_
```Go
header
```
___
*[`private/drkey/BUILD.bazel` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yi0HWB2RjTmLukqPM:-N_Yi0HWB2RjTmLukqPN:bez9sl) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/BUILD.bazel#L6)):*
> ```Starlark
>     name = "go_default_library",
>     srcs = ["provider.go"],
>     importpath = "github.com/scionproto/scion/private/drkey",
> ```

Seems to be imported as `drkeytools` everywhere, so perhaps create this as `private/drkey/drkeytools` directly?

Maybe `drkeyutil` would be slightly more conventional than `...tools`  (standard library has ioutil, httputil) , but ok for me either way.
___
*[`private/drkey/provider.go` line 27 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YTI523Kt2Bxeh1yB3:-N_YTI523Kt2Bxeh1yB4:b-wm56xu) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L27)):*
> ```Go
> 
> type FakeProvider struct {
> 	KeyDuration      time.Duration
> ```

`EpochDuration`
___
*[`private/drkey/provider.go` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YZtBGD3eYjqbXBCjB:-N_YZtBGD3eYjqbXBCjC:b-lq77bl) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L58)):*
> ```Go
> 	}
> 
> 	awBegin := t.Add(-(p.AcceptanceWindow + time.Nanosecond))
> ```

Use `! Before` instead of subtracting `Nanosecond` and `After`?

Btw, is it intentional that the awEnd is not included in the allowed range?

FWIW, you could use `cppki.Validity` to represent the acceptance window, then the expressions below can be simplified a bit by using `.Contains`.
___
*[`private/drkey/provider.go` line 78 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YRxvt4wLp9xypPc5w:-N_YRxvt4wLp9xypPc5x:b-phjpk4) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L78)):*
> ```Go
> }
> 
> func (p *FakeProvider) getASHostTreble(
> ```

Triple?
___
*[`router/dataplane.go` line 1816 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yarl871lILhgJ4AUV:-N_Yarl871lILhgJ4AUW:b-mp3fpq) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/router/dataplane.go#L1816)):*
> ```Go
> 	)
> 	if err != nil {
> 		log.Error("Selecting key to authenticate the incoming packet", "err", err)
> ```

`log.Debug`
___
*[`tools/braccept/main.go` line 79 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Ygafj1TTQFh9zvmLS:-N_Ygafj1TTQFh9zvmLT:b10na1x) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/tools/braccept/main.go#L79)):*
> ```Go
> 
> 	// Set acceptance window to longer than default value to handle with test time fluctuation
> 	err = os.Setenv(config.EnvVarAccpetanceWindow, "1m")
> ```

The +/- 2.5 seconds are _not_ enough for the tests to pass otherwise? Any idea where so much delay is added?
___
*[`tools/braccept/cases/scmp_expired_hop.go` line 197 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YhU1P12sy4oukff6F:-N_YhU1P12sy4oukff6G:b-dza7g1) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/tools/braccept/cases/scmp_expired_hop.go#L197)):*
> ```Go
> // SCMPExpiredHopMessageBack tests a packet with an expired hop field. The relative timestamp
> // can be encoded in the SPAO header and sent back to the src.
> func SCMPExpiredHopMessageBack(artifactsDir string, mac hash.Hash) runner.Case {
> ```

Can this case now be removed?

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: 3 of 24 files reviewed, 14 unresolved discussions (waiting on @matzf)

___
*[`control/config/drkey.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yd8OE7rmg1C6Fu4uR:-NboPp-A6lAIwE9rARcH:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L41)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Naming inconsistency; this definition has `Offset`, but other definitions with the exact same interpretation are just "acceptance window". This naming inconsistency could be confusing, as it's not super obvious everywhere whether this is the half-window or the full window duration.
</blockquote></details>

Done.
___
*[`control/config/drkey.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YTzUG-jmVn4RL7Oc5:-NboMJ4P3JKe31YGd0u4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L42)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowOffset = 2*time.Second + 500*time.Millisecond
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```

Done.
___
*[`control/config/drkey.go` line 42 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YU0Xb0xbr6a24_BGo:-NboMKDJ0M0YH_FUQCCm:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/control/config/drkey.go#L42)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

As these are now read by the router, having these definitions in `control/config` does not seem appropriate.
Perhaps the new `private/drkey` package that you've added would be a good place for these things? Then you could keep all constants local and expose only the function that returns the effective value (and by that avoid the duplication of the logic for parsing the environment variable, that we now have).
</blockquote></details>

Done.
___
*[`pkg/slayers/pkt_auth.go` line 171 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YDLLC0MCaltP0jHBV:-NboMMdk3sN6at0SEcys:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/slayers/pkt_auth.go#L171)):*
> ```Go
> 
> 	if p.TimestampSN >= (1 << 48) {
> 		return serrors.New("Timestamp value should be smaller than 2^24")
> ```

Done.
___
*[`pkg/slayers/pkt_auth_test.go` line 65 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YFAD22du4j81IQCmO:-NboMSgL6lGmyFz7YGvN:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/slayers/pkt_auth_test.go#L65)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Aside: the value is big-endian (right!?), so the `LittleEndian` here seems a bit odd. It's probably clearer to just specify a uint64 value anyway (like `ts` in the global var-block).
I remember that we had discussed and changed this in the original PR, put it seems we missed some places.
</blockquote></details>

Done.
___
*[`pkg/spao/mac.go` line 133 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YWflX3Qa3vvhqEcIk:-NboMUKrAyDg0mvuJLMe:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/mac.go#L133)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Same as above, create helper function for 48 bit write
</blockquote></details>

Done.
___
*[`pkg/spao/timestamp.go` line 26 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YZMOu96l-3EU7O1EO:-NboMWYi4Zi42ViyzTiW:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/timestamp.go#L26)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Shouldn't this also be usable for `HostHostKey`? If so, just pass the `Epoch` directly? 
</blockquote></details>

Done.
___
*[`pkg/spao/timestamp.go` line 35 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YGTpCDI3GM-WCtdRR:-NboMY_L48BIig8t0Ine:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/pkg/spao/timestamp.go#L35)):*
> ```Go
> 
> // AbsoluteTimestamp returns the absolute timestamp (AbsTime) based on the
> // relTime (Timestamp / Sequence Number field in SPAO hedaer) and the DRKey
> ```

Done.
___
*[`router/dataplane.go` line 1816 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yarl871lILhgJ4AUV:-NboMiB_8fz4KmAlIF8I:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/router/dataplane.go#L1816)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`log.Debug`
</blockquote></details>

Done.
___
*[`tools/braccept/main.go` line 79 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Ygafj1TTQFh9zvmLS:-Nbn4H_DDogDV1Lk9J-p:byjub0f) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/tools/braccept/main.go#L79)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The +/- 2.5 seconds are _not_ enough for the tests to pass otherwise? Any idea where so much delay is added?
</blockquote></details>

Done. At the time, some test were not passing for me, however, now they seem to consistently pass.
___
*[`tools/braccept/cases/scmp_expired_hop.go` line 197 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YhU1P12sy4oukff6F:-NboMm4I4Xmg4qdwQX4m:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/tools/braccept/cases/scmp_expired_hop.go#L197)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Can this case now be removed?
</blockquote></details>

Done.
___
*[`private/drkey/BUILD.bazel` line 6 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_Yi0HWB2RjTmLukqPM:-NboMam12XxQv-aE2Ugk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/BUILD.bazel#L6)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Seems to be imported as `drkeytools` everywhere, so perhaps create this as `private/drkey/drkeytools` directly?

Maybe `drkeyutil` would be slightly more conventional than `...tools`  (standard library has ioutil, httputil) , but ok for me either way.
</blockquote></details>

Done.
___
*[`private/drkey/provider.go` line 27 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YTI523Kt2Bxeh1yB3:-NboMcPh0KqEhmbjxzeg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

`EpochDuration`
</blockquote></details>

Done.
___
*[`private/drkey/provider.go` line 58 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YZtBGD3eYjqbXBCjB:-Nb_lDmz0sD7hkIjGW9q:b-t16qc6) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L58)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Use `! Before` instead of subtracting `Nanosecond` and `After`?

Btw, is it intentional that the awEnd is not included in the allowed range?

FWIW, you could use `cppki.Validity` to represent the acceptance window, then the expressions below can be simplified a bit by using `.Contains`.
</blockquote></details>

Yes, there's a reason. In the specification we say that a (the width of the acceptance window, can be smaller or equal to the minimum DRKey epoch length. If the case is that a it is equal and we take awEnd as included we can fall into the following situation:
- e.g. current epoch E_i, starts at t_i, next epoch E_i+1 starts at t_i+1.
- Relative timestamp is 0.
- We are exactly in E_i/2 (E_i being in the exact middle point of epoch i).
- Then instants t_i and t_i+1 would be within the acceptance window. This is not how is described in "Absolute time and DRKey selection".

In any case, I can change the sentence in the specification and use here the `validity.Contains` function. Instead of "The acceptance window is equal or smaller than the minimum DRKey epoch length" only "The acceptance window is smaller than the minimum DRKey epoch length".
___
*[`private/drkey/provider.go` line 78 at r1](https://reviewable.io/reviews/scionproto/scion/4366#-N_YRxvt4wLp9xypPc5w:-Nbn3DFX6RCavrwgGY2S:b-cb8pc3) ([raw file](https://github.com/scionproto/scion/blob/b21027852f930941fabf783cefffc4dd89c60806/private/drkey/provider.go#L78)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Triple?
</blockquote></details>

Done. Although, I think treble is valid as well, meaning three times something...

**Review by matzf — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: all files reviewed, 7 unresolved discussions (waiting on @JordiSubira)

___
*[`pkg/slayers/pkt_auth.go` line 217 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-Ndnk7Lx5prqhuFnpQZz:-Ndnk7Lx5prqhuFnpQ_-:bfg060o) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/pkg/slayers/pkt_auth.go#L217)):*
> ```Go
> }
> 
> func bigEndian(b []byte) uint64 {
> ```

Nit, `bigEndianUint48` maybe?
___
*[`pkg/spao/timestamp_test.go` line 36 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnkNo16ZkCR6rLAIrT:-NdnkNo16ZkCR6rLAIrU:b-arah4x) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/pkg/spao/timestamp_test.go#L36)):*
> ```Go
> 		"valid": {
> 			currentTime: time.Now().UTC(),
> 			epoch:       getEpoch(time.Now()),
> ```

In contrast to the other calls here, This `time.Now()` does not have the `.UTC()`. Is this still correct? Could we drop all of the others as well?
___
*[`private/drkey/drkeyutil/drkey.go` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdniAwY61iFKBdIjKnw:-NdniAwY61iFKBdIjKnx:b-7r7eq2) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L27)):*
> ```Go
> 	// DefaultEpochDuration is the default duration for the drkey SecretValue and derived keys
> 	DefaultEpochDuration   = 24 * time.Hour
> 	DefaultPrefetchEntries = 10000
> ```

This one seems to be a bit out of place here, I'd leave this in `control/config/drkey.go`.
___
*[`private/drkey/drkeyutil/drkey.go` line 36 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnlMLh6M6KHekRBI6J:-NdnlMLh6M6KHekRBI6K:bezq3ik) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L36)):*
> ```Go
> 	// Picking the value equal or shorter than half of the drkey Grace Period ensures
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowLength = 5 * time.Minute
> ```

The description is incorrect now, as the length defines the full acceptance window size.
I'd also rename the `DefaultAcceptanceWindowLength` to just `DefaultAcceptanceWindow` to avoid having two different names.

- widown -> window
- acceptanceWindowOffset -> acceptance window
___
*[`private/drkey/drkeyutil/drkey.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnfpD23_juwEZVt82B:-NdnfpD23_juwEZVt82C:undefined) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L37)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowLength = 5 * time.Minute
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```





_Suggestion:_
```Go
EnvVarAcceptanceWindow
```
___
*[`private/drkey/drkeyutil/drkey.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-Ndnl_lwEvWJ2WMUhtOw:-Ndnl_lwEvWJ2WMUhtOx:b976yqn) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L37)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowLength = 5 * time.Minute
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```

Could you please add a short documentation for `SCION_TESTING_ACCEPTANCE_WINDWO`  to the envvar section in the router, `doc/manuals/router.rst`.
The `SCION_TESTING_EPOCH_DURATION` is also missing in the router documentation -- please copy this over `control.rst`.
___
*[`private/drkey/drkeyutil/provider.go` line 70 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnmiIjDc8sgp-D-B5h:-NdnmiIjDc8sgp-D-B5i:barnpqt) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/provider.go#L70)):*
> ```Go
> 	absTimeNext := spao.AbsoluteTimestamp(keys[2].Epoch, timestamp)
> 	switch {
> 	// case absTimeCurrent.After(awBegin) && absTimeCurrent.Before(awEnd):
> ```

Nit, remove commented line?

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: 17 of 25 files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[`pkg/spao/timestamp_test.go` line 36 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnkNo16ZkCR6rLAIrT:-NervSO5-19EN0mRDI55:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/pkg/spao/timestamp_test.go#L36)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

In contrast to the other calls here, This `time.Now()` does not have the `.UTC()`. Is this still correct? Could we drop all of the others as well?
</blockquote></details>

Done.
___
*[`private/drkey/drkeyutil/drkey.go` line 27 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdniAwY61iFKBdIjKnw:-NeryR4yDm1TMfiR9fIe:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L27)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This one seems to be a bit out of place here, I'd leave this in `control/config/drkey.go`.
</blockquote></details>

Done.
___
*[`private/drkey/drkeyutil/drkey.go` line 36 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnlMLh6M6KHekRBI6J:-NeryWhA0YGxEF2LOF8H:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L36)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

The description is incorrect now, as the length defines the full acceptance window size.
I'd also rename the `DefaultAcceptanceWindowLength` to just `DefaultAcceptanceWindow` to avoid having two different names.

- widown -> window
- acceptanceWindowOffset -> acceptance window
</blockquote></details>

Done.
___
*[`private/drkey/drkeyutil/drkey.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-NdnfpD23_juwEZVt82B:-NeryYbhC5k3a_Aqg8nz:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L37)):*
> ```Go
> 	// that we accept packets for active keys only.
> 	DefaultAcceptanceWindowLength = 5 * time.Minute
> 	EnvVarAccpetanceWindow        = "SCION_TESTING_ACCEPTANCE_WINDOW"
> ```

Done.
___
*[`private/drkey/drkeyutil/drkey.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-Ndnl_lwEvWJ2WMUhtOw:-NeryZ3QE6SCECfY96tF:b73v5ct) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L37)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Could you please add a short documentation for `SCION_TESTING_ACCEPTANCE_WINDWO`  to the envvar section in the router, `doc/manuals/router.rst`.
The `SCION_TESTING_EPOCH_DURATION` is also missing in the router documentation -- please copy this over `control.rst`.
</blockquote></details>

I've changed it in https://github.com/scionproto/scion/pull/4300

**Review by matzf — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

___
*[`private/drkey/drkeyutil/drkey.go` line 37 at r2](https://reviewable.io/reviews/scionproto/scion/4366#-Ndnl_lwEvWJ2WMUhtOw:-NevlMkDAlC3AbUed7h6:b89im0r) ([raw file](https://github.com/scionproto/scion/blob/0e11255c4408821d69e20e5b3b5c9815aac24a1a/private/drkey/drkeyutil/drkey.go#L37)):*
<details><summary><i>Previously, JordiSubira wrote…</i></summary><blockquote>

I've changed it in https://github.com/scionproto/scion/pull/4300
</blockquote></details>

Ok, sure that works. Generally, the idea would be to update the (usage-)documentation directly together with the implementation.

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366#-:-New8lBf9qDeeppmjnG8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by matzf — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
