### PR TITLE
router: return SCMP on invalid dst address

### PR DESCRIPTION
**Pull request by jcp19**
This PR fixes issue #4126.

Currently, it is missing a test in `braccept`.

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4506)

**Review by matzf — COMMENTED** [review]
Hey @jcp19, sorry for not replying sooner and thanks for this contribution. So far this looks good to me. As this PR is still marked as a Draft, I understand that you intended to add tests for this behavior? Is this something that you still want to work on?

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4506#-:-O-5dA200EYAf6uWVAmP:b-a134de)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jcp19)

**Comment by jcp19** [comment]
@matzf Yes, that's the plan. However, I haven't add enough time yet to look into how to test for this particular behaviour.

**Comment by jiceatscion** [comment]
In router/dataplane_internal_test, there's a series of test cases for SCMP responses: TestSlowPathProcessing().
You might be able to add one test case in-there with not too much fuss.

**Comment by jcp19** [comment]
I finally took a look at this and added a test now. should be ready for review

**Review by matzf — APPROVED** [review]
Excellent, thank you :thumbsup: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4506#-:-O0SlQpWClEnl-pY7bG3:b7rhqu4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiceatscion)

**Pull request merged**
