### PR TITLE
Log rework

### PR DESCRIPTION
**Pull request by sgmonroy**
The basic idea is to split log console and log file functionality, both flags and setup, by providing more fine grained APIs.
It also reworks the code so that scion code other than log library does not need to import log15.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 90 files at r1.
Review status: 1 of 90 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/lib/log/log.go, line 70 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8CNR8vL_w8hP8yd-:-LBz8CNR8vL_w8hP8yd0:b-ar9v5o) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L70)):*
> ```Go
> }
> 
> func setHandlers() {
> ```

This should come after `SetupLogFile`/`SetupLogConsole` as they both call it.

---

*[go/lib/log/log.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8LTC2sn0PerYDIO3:-LBz8LTC2sn0PerYDIO4:bftyao1) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L83)):*
> ```Go
> }
> 
> func SetupLogFile(name string, logDir string, logLevel string, logSize int, logAge int, logFlush int) error {
> ```

Line length.

---

*[go/lib/log/log.go, line 89 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8OkF8kyTFE_xYOgT:-LBz8OkF8kyTFE_xYOgU:bftyao1) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L89)):*
> ```Go
> 	}
> 	logBuf = newSyncBuf(mkLogfile(name))
> 	logFileHandler = log15.LvlFilterHandler(logLvl, log15.StreamHandler(logBuf, fmt15.Fmt15Format(nil)))
> ```

Line length.

---

*[go/lib/log/log.go, line 111 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz97zpCH78NZWt_pat:-LBz97zpCH78NZWt_pau:biczosg) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L111)):*
> ```Go
> 
> func AddLogConsFlags() {
> 	flag.StringVar(&logConsole, "log.console", "crit", "Console logging level")
> ```

"Console logging level: debug|info|warn|error|crit"

---

*[go/lib/log/log.go, line 116 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8uK4AV7d9GmsgOJd:-LBz8uK4AV7d9GmsgOJe:b-l6txjz) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L116)):*
> ```Go
> func AddLogFileFlags() {
> 	flag.StringVar(&logDir, "log.dir", "logs", "Log directory")
> 	flag.StringVar(&logLevel, "log.level", "debug", "Logging level")
> ```

"File logging level: debug|info|warn|error|crit"

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)*

**Comment by kormat** [comment]
Reviewed 43 of 90 files at r1.
Review status: 44 of 90 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/border/main.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9YvD4cbzzF_iSmzd:-LBz9YvE1SUq4_mXNtFw:blib15p) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/main.go#L30)):*
> ```Go
> 	"syscall"
> 
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion section below.

---

*[go/border/main.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9lEG4Yf059vlJLh2:-LBz9lEG4Yf059vlJLh3:bn3zaj9) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/main.go#L52)):*
> ```Go
> 		os.Exit(1)
> 	}
> 	os.Setenv("TZ", "UTC")
> ```

This should be at the top of `main()`

---

*[go/border/revinfo.go, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9ydQ5Y1WFXyY4zgU:-LBz9ydQ5Y1WFXyY4zgV:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/revinfo.go#L20)):*
> ```Go
> 
> import (
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/border/setup-hsr.go, line 29 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzA3Xh3JHSRFqFuRz_:-LBzA3Xh3JHSRFqFuRza:bz8uf8c) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/setup-hsr.go#L29)):*
> ```Go
> 	"strings"
> 
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

There's no need to keep these commented out lines any more, as the import line is now "obvious" (and also this would go in the scion import block).

---

*[go/border/ifstate/ifstate.go, line 33 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzADlr4goPr7ApSW0W:-LBzADlr4goPr7ApSW0X:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/ifstate/ifstate.go#L33)):*
> ```Go
> 	"github.com/prometheus/client_golang/prometheus"
> 
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/border/netconf/interface.go, line 27 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAFj_3XR7Cb3Wx0tT:-LBzAFj_3XR7Cb3Wx0tU:b-jbl8bu) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/netconf/interface.go#L27)):*
> ```Go
> 	"fmt"
> 
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

Can be dropped.

---

*[go/border/rpkt/extn_onehoppath.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAJ3j4cnrMpki6lKq:-LBzAJ3j4cnrMpki6lKr:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_onehoppath.go#L23)):*
> ```Go
> 	"hash"
> 
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/border/rpkt/extn_packet_security.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAK51E4wvyGWHDG8w:-LBzAK51E4wvyGWHDG8x:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_packet_security.go#L23)):*
> ```Go
> 	"fmt"
> 
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/border/rpkt/extn_scmp.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzALZW0R08fM_4gEog:-LBzALZW0R08fM_4gEoh:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_scmp.go#L21)):*
> ```Go
> 
> import (
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/border/rpkt/extns.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAMgr8vFfNK6CAvoh:-LBzAMgr8vFfNK6CAvoi:b-jbl8bu) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extns.go#L21)):*
> ```Go
> 
> import (
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

Can be dropped.

---

*[go/border/rpkt/payload_ctrl.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAO8L6pfC1c9HglRC:-LBzAO8MAmpzfBtTFer4:b-jbl8bu) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/payload_ctrl.go#L21)):*
> ```Go
> 
> import (
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

Can be dropped.

---

*[go/border/rpkt/process.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAPXkArK4UIfbcoQe:-LBzAPXkArK4UIfbcoQf:b-jbl8bu) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/process.go#L23)):*
> ```Go
> 	"time"
> 
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

Can be dropped.

---

*[go/border/rpkt/route.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzARTL5s7iIeJnyyA6:-LBzARTL5s7iIeJnyyA7:b-jbl8bu) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/route.go#L23)):*
> ```Go
> 	"math/rand"
> 
> 	//"github.com/scionproto/scion/go/lib/log"
> ```

Can be dropped.

---

*[go/border/rpkt/rpkt.go, line 27 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzATJ47KU3LnSuk3dZ:-LBzATJ47KU3LnSuk3d_:bi8a4d3) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/rpkt.go#L27)):*
> ```Go
> 	"time"
> 
> 	"github.com/scionproto/scion/go/lib/log"
> ```

This should be in the scion import block.

---

*[go/sig/main.go, line 19 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAwHoDwJowKZf9bfN:-LBzAwHoDwJowKZf9bfO:b-894hk6) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/sig/main.go#L19)):*
> ```Go
> import (
> 	"flag"
> 	//	"fmt"
> ```

Drop.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)*

**Comment by sgmonroy** [comment]
Review status: 24 of 106 files reviewed at latest revision, 20 unresolved discussions.

---

*[go/border/main.go, line 30 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9YvD4cbzzF_iSmzd:-LC4PfQx2Iu5EKhBpebI:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/main.go#L30)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion section below.
</blockquote></details>

Done.

---

*[go/border/main.go, line 52 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9lEG4Yf059vlJLh2:-LC4PqTJAh7aQiKAPrAZ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/main.go#L52)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be at the top of `main()`
</blockquote></details>

Done.

---

*[go/border/revinfo.go, line 20 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz9ydQ5Y1WFXyY4zgU:-LC4PrMZC6suAbIAYr3C:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/revinfo.go#L20)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/border/setup-hsr.go, line 29 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzA3Xh3JHSRFqFuRz_:-LC4T35a2V4tcMm-0O6N:bs7wumb) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/setup-hsr.go#L29)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's no need to keep these commented out lines any more, as the import line is now "obvious" (and also this would go in the scion import block).
</blockquote></details>

Done.

---

*[go/border/ifstate/ifstate.go, line 33 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzADlr4goPr7ApSW0W:-LC4QBZa0LeohnY7UO2f:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/ifstate/ifstate.go#L33)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/border/netconf/interface.go, line 27 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAFj_3XR7Cb3Wx0tT:-LC4QDeJEms5Ttp03gGl:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/netconf/interface.go#L27)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be dropped.
</blockquote></details>

Done.

---

*[go/border/rpkt/extn_onehoppath.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAJ3j4cnrMpki6lKq:-LC4QEIvE3eDbsnvbSlh:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_onehoppath.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/border/rpkt/extn_packet_security.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAK51E4wvyGWHDG8w:-LC4QFnKAzu1Kb9P4qW1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_packet_security.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/border/rpkt/extn_scmp.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzALZW0R08fM_4gEog:-LC4QGBM-zuvz1JrRVn5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extn_scmp.go#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/border/rpkt/extns.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAMgr8vFfNK6CAvoh:-LC4QHL-51dB3j_Sf9H-:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/extns.go#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be dropped.
</blockquote></details>

Done.

---

*[go/border/rpkt/payload_ctrl.go, line 21 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAO8L6pfC1c9HglRC:-LC4QHdPAhOCrqg4vGU1:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/payload_ctrl.go#L21)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be dropped.
</blockquote></details>

Done.

---

*[go/border/rpkt/process.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAPXkArK4UIfbcoQe:-LC4QKT_0C9LHOgYknrR:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/process.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be dropped.
</blockquote></details>

Done.

---

*[go/border/rpkt/route.go, line 23 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzARTL5s7iIeJnyyA6:-LC4QL6DD4-Z98s7yciy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/route.go#L23)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Can be dropped.
</blockquote></details>

Done.

---

*[go/border/rpkt/rpkt.go, line 27 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzATJ47KU3LnSuk3dZ:-LC4QMmE-Eqgfpfv-Wm7:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/border/rpkt/rpkt.go#L27)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be in the scion import block.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 70 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8CNR8vL_w8hP8yd-:-LC4S-bEANgIHHVgDTu0:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L70)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should come after `SetupLogFile`/`SetupLogConsole` as they both call it.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 83 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8LTC2sn0PerYDIO3:-LC4S4B77fFdXrdwaZ6V:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L83)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 89 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8OkF8kyTFE_xYOgT:-LC4SBvJ13PyN_jbGR8m:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L89)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 111 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz97zpCH78NZWt_pat:-LC4SOuD9Gy4ysfK025n:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L111)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"Console logging level: debug|info|warn|error|crit"
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 116 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBz8uK4AV7d9GmsgOJd:-LC4SVFI9nopc60gNX4x:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/lib/log/log.go#L116)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

"File logging level: debug|info|warn|error|crit"
</blockquote></details>

Done.

---

*[go/sig/main.go, line 19 at r1](https://reviewable.io/reviews/scionproto/scion/1546#-LBzAwHoDwJowKZf9bfN:-LC4SnIb4z4ikC58Dl-_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/fbd584aca6ce22aa072bc15973786d8382857034/go/sig/main.go#L19)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Drop.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)*

**Comment by kormat** [comment]
Reviewed 1 of 90 files at r1, 81 of 81 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[go/cert_srv/main.go, line 68 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTeXdY0R9wxxJPzWzn:-LCTeXdY0R9wxxJPzWzo:b649iux) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/cert_srv/main.go#L68)):*
> ```Go
> 		os.Exit(1)
> 	}
> 	os.Setenv("TZ", "UTC")
> ```

This should be at the top of `main()`.

---

*[go/lib/log/log.go, line 114 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTdx550b7BtYP96F5T:-LCTdx550b7BtYP96F5U:bftyao1) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/lib/log/log.go#L114)):*
> ```Go
> 
> func AddLogConsFlags() {
> 	flag.StringVar(&logConsole, "log.console", "crit", "Console logging level: debug|info|warn|error|crit")
> ```

Line length.

---

*[go/lib/log/log.go, line 119 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTdyS-A8PodTkM8NI2:-LCTdyS-A8PodTkM8NI3:bftyao1) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/lib/log/log.go#L119)):*
> ```Go
> func AddLogFileFlags() {
> 	flag.StringVar(&logDir, "log.dir", "logs", "Log directory")
> 	flag.StringVar(&logLevel, "log.level", "debug", "File logging level: debug|info|warn|error|crit")
> ```

Line length.

---

*[go/sig/main.go, line 66 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTfIxA5ci475ubs6TV:-LCTfIxA5ci475ubs6TW:b649iux) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/sig/main.go#L66)):*
> ```Go
> 		os.Exit(1)
> 	}
> 	os.Setenv("TZ", "UTC")
> ```

This should be at the top of `main()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)*

**Comment by sgmonroy** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[go/cert_srv/main.go, line 68 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTeXdY0R9wxxJPzWzn:-LCXTaxL-Yz7is9Ji9O4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/cert_srv/main.go#L68)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be at the top of `main()`.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 114 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTdx550b7BtYP96F5T:-LCXTgql-46LxbZ96AFe:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/lib/log/log.go#L114)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/lib/log/log.go, line 119 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTdyS-A8PodTkM8NI2:-LCXToni4F1tQOov9VIA:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/lib/log/log.go#L119)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length.
</blockquote></details>

Done.

---

*[go/sig/main.go, line 66 at r2](https://reviewable.io/reviews/scionproto/scion/1546#-LCTfIxA5ci475ubs6TV:-LCXTqfYAxpQ6U24tWjb:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd9eed6e0db751bab735ec97963dea694a29d3b8/go/sig/main.go#L66)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should be at the top of `main()`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1546#-:-LCmBKDZ0gYLuip3U5TJ:bnfp4nl)*

**Pull request merged**
