### PR TITLE
gateway: etags added to prefix discovery protobuf

### PR DESCRIPTION
**Pull request by sustrik**
Etags can be used so as not to transfer large prefix sets over and over again.

Etags may or may not be supported by a particular gateway implementation. This change is fully forward and backward compatible. Implementations that do not support etags should just ignore the field.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)

### CODE REVIEW

**Review by oncilla — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sustrik)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)* status: all files reviewed, 1 unresolved discussion (waiting on @sustrik)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4461#-NnIBWgGEQ4z4sF-k_Re:-NnIBWgGEQ4z4sF-k_Rf:bi9hohj) (no related file):*
does it make sense to add this without the implementation? Or will that come in a follow-up PR?

___

**Review by sustrik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4461#-NnIBWgGEQ4z4sF-k_Re:-NnIIjD34wZLJcUmpHhv:bypjo21) (no related file):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

does it make sense to add this without the implementation? Or will that come in a follow-up PR?
</blockquote></details>

That was the decision, AFAIU. I am fine also with closing the PR though.

___

**Review by lukedirtwalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4461)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @sustrik)

**Pull request merged**
