### PR TITLE
posix_router: move to canonical directory

### PR DESCRIPTION
**Pull request by Oncilla**
Also rename generated binaries and docker containers to posix_router.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3880)

### CODE REVIEW

**Review by Oncilla — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3880)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by matzf — COMMENTED** [review]
Personally, I find this binary name rather non-descriptive. It's not a "posix router", but rather the posix version of the scion router. Also, unix binary names "traditionally" prefer kebab case (as already used here too, e.g. `scion-pki`).
I'd propose `scion-router` :man_shrugging: 

> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3880#-:-MHPyfvRBr7QNlCCNnyB:bqzxgf6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by cmeury** [comment]
Or `scion-open-router`?

**Comment by Oncilla** [comment]
Moved to `posix-router` instead.

The reasoning for the naming here, is that we plan to package applications in docker containers, and thus they are name spaced by them.

If you feel the name is still not expressive enough, we can add another bazel target that creates the binary name of your choosing in a follow-up PR.

**Review by Oncilla — COMMENTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3880)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
