### PR TITLE
drkey: add grpc pkg in daemon

### PR DESCRIPTION
**Pull request by JordiSubira**
This PR is the 11th in a series of PRs that add support for DRKey started with https://github.com/scionproto/scion/pull/4217.

This PR contains:

- gRPC package for the SCION Daemon
- UTs and mocks

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)* status: all files reviewed, 4 unresolved discussions (waiting on @JordiSubira)

___
*[`daemon/drkey/grpc/fetching_test.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7ydE_F21mZLNdSqIpG:-N7ydE_F21mZLNdSqIpH:b93l3zr) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/daemon/drkey/grpc/fetching_test.go#L41)):*
> ```Go
> var _ sd_drkey.Fetcher = (*sd_grpc.Fetcher)(nil)
> 
> func dialer(drkeyServer cppb.DRKeyIntraServiceServer) func(
> ```

this is not needed see comments below.
___
*[`daemon/drkey/grpc/fetching_test.go` line 85 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7ydahYD4OIBv99Rsf1:-N7ydahYD4OIBv99Rsf2:b-wdtdyq) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/daemon/drkey/grpc/fetching_test.go#L85)):*
> ```Go
> 	)
> 
> 	conn, err := grpc.DialContext(context.Background(),
> ```

this can be simplified quite a bit, by using the `xtest` helper:



_Suggestion:_
```Go
	server := xtest.NewGRPCService()
	cppb.RegisterDRKeyIntraServiceServer(server.Server(), daemonSrv)
	server.Start(t)

	fetcher := sd_grpc.Fetcher{
		Dialer: server,
	}
```
___
*[`pkg/grpc/mock_grpc/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7yd4D38QTlWOnpvasL:-N7yd4D48t7ovHkKLumn:b-vkho5d) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/pkg/grpc/mock_grpc/BUILD.bazel#L1)):*
> ```Starlark
> load("//tools/lint:go.bzl", "go_library")
> ```

this should not be needed, please drop it.
___
*[`pkg/grpc/mock_grpc/mock.go` line 2 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7yd7De-swYEU2snrMa:-N7yd7De-swYEU2snrMb:b-k5nsix) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/pkg/grpc/mock_grpc/mock.go#L2)):*
> ```Go
> // Code generated by MockGen. DO NOT EDIT.
> // Source: github.com/scionproto/scion/pkg/grpc (interfaces: Dialer)
> ```

should not be needed, please drop it.

**Review by JordiSubira — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @lukedirtwalker)

___
*[`daemon/drkey/grpc/fetching_test.go` line 41 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7ydE_F21mZLNdSqIpG:-N7ymQnh4P0mE4NQ7g7P:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/daemon/drkey/grpc/fetching_test.go#L41)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this is not needed see comments below.
</blockquote></details>

Done.
___
*[`daemon/drkey/grpc/fetching_test.go` line 85 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7ydahYD4OIBv99Rsf1:-N7ymTDl5KRGFooNK4gO:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/daemon/drkey/grpc/fetching_test.go#L85)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this can be simplified quite a bit, by using the `xtest` helper:
</blockquote></details>

Done.
___
*[`pkg/grpc/mock_grpc/BUILD.bazel` line 1 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7yd4D38QTlWOnpvasL:-N7ymTpw5NqyPbX4U6Fk:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/pkg/grpc/mock_grpc/BUILD.bazel#L1)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

this should not be needed, please drop it.
</blockquote></details>

Done.
___
*[`pkg/grpc/mock_grpc/mock.go` line 2 at r1](https://reviewable.io/reviews/scionproto/scion/4233#-N7yd7De-swYEU2snrMa:-N7ymUJqDDd_GNxRYzyS:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/82f7a9804f6a4e2ba2cbdaae57e2160d954b1450/pkg/grpc/mock_grpc/mock.go#L2)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

should not be needed, please drop it.
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by JordiSubira — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
