### PR TITLE
Support bind and svc address

### PR DESCRIPTION
**Pull request by Oncilla**
Add support for single bind address
Add support for svc address

(addresses #1334)

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1341)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 10 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/lib/sock/reliable/reliable.go, line 160 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2TJKX3_KhGVqntB-o:-L-2TJKX3_KhGVqntB-p:bn9ybcl) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L160)):*
> ```Go
> 	svcLen, bindLen := 0, 0
> 	if bind != nil {
> 		bindLen = 3 + bind.Addr.Size()
> ```

There should be a const for `3`. `regBindHdrLen` or similar.

---

*[go/lib/sock/reliable/reliable.go, line 169 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2VVM4mbbTg0iow0t5:-L-2VVM4mbbTg0iow0t6:bb6snxx) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L169)):*
> ```Go
> 	// Enable SCMP
> 	request[offset] = regCommandField
> 	if bind != nil {
> ```

There's 3 of these checks; this one could be folded into the third one below.

---

*[go/lib/sock/reliable/reliable.go, line 180 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2VKDr619Cngw8wDNZ:-L-2VKDr619Cngw8wDN_:b7rwbot) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L180)):*
> ```Go
> 	if err != nil {
> 		conn.Close()
> 		return nil, 0, common.NewCError("Cannot register public address", "err", err)
> ```

I would say instead "Invalid public address", and include the addr in the error. Same for bind addr below. Otherwise it sounds like the dispatcher is rejecting the addresses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1341)*

**Comment by kormat** [comment]
Reviewed 3 of 10 files at r1.
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/snet/conn.go, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2ZBRbC6_gNnwMJrWo:-L-2ZBRbC6_gNnwMJrWp:b-mnnxf3) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/snet/conn.go#L69)):*
> ```Go
> 	laddr *Addr
> 	raddr *Addr
> 	baddr *Addr
> ```

This and svc need to be exposed via the API.

---

*[go/lib/snet/snet.go, line 124 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2WfuFhDhvQzdj63tL:-L-2WfuFhDhvQzdj63tM:bdt09e0) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/snet/snet.go#L124)):*
> ```Go
> // Read and Write methods can be used to receive and send SCION packets.
> func (n *Network) DialSCION(network string, laddr, raddr, baddr *Addr,
> 	svc addr.HostSVC) (*Conn, error) {
> ```

In terms of keeping the api fairly simple, i would go for 2 methods here: 

`DialSCION(network string, laddr, raddr *Addr)`
`DialSCIONWithBindSVC(network string, laddr, raddr *Addr, baddr *Addr, svc addr.HostSVC)`

and have the former call the latter internally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1341)*

**Comment by Oncilla** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/lib/snet/conn.go, line 69 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2ZBRbC6_gNnwMJrWo:-L-6SKRrtFIRkf05t5aW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/snet/conn.go#L69)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This and svc need to be exposed via the API.
</blockquote></details>

Done.

---

*[go/lib/snet/snet.go, line 124 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2WfuFhDhvQzdj63tL:-L-6Wsi_Dd9eo4DCHmnc:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/snet/snet.go#L124)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

In terms of keeping the api fairly simple, i would go for 2 methods here: 

`DialSCION(network string, laddr, raddr *Addr)`
`DialSCIONWithBindSVC(network string, laddr, raddr *Addr, baddr *Addr, svc addr.HostSVC)`

and have the former call the latter internally.
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 160 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2TJKX3_KhGVqntB-o:-L-6WtEis1fHh0Nis5Lj:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L160)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There should be a const for `3`. `regBindHdrLen` or similar.
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 169 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2VVM4mbbTg0iow0t5:-L-6Xi00TAcgFMq9LmlW:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L169)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's 3 of these checks; this one could be folded into the third one below.
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 180 at r1](https://reviewable.io:443/reviews/netsec-ethz/scion/1341#-L-2VKDr619Cngw8wDNZ:-L-72q5WGFgei4Cj9JrZ:b-896fix) ([raw file](https://github.com/netsec-ethz/scion/blob/502fcbe1b6c7cc17ee219a16aead5b1f07b5611a/go/lib/sock/reliable/reliable.go#L180)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

I would say instead "Invalid public address", and include the addr in the error. Same for bind addr below. Otherwise it sounds like the dispatcher is rejecting the addresses.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion/1341)*

**Comment by kormat** [comment]
Reviewed 4 of 10 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[go/cert_srv/io.go, line 39 at r2](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-XMmUwVghALcWidySy:-L-XMmUwVghALcWidySz:bm5sf2a) ([raw file](https://github.com/scionproto/scion/blob/cef1c5b931d0d09be2e7a949647b52ab566f6207/go/cert_srv/io.go#L39)):*
> ```Go
> // NewDispatcher creates a new dispatcher listening to SCION traffic on the specified address.
> func NewDispatcher(a *snet.Addr) (*Dispatcher, error) {
> 	conn, err := snet.ListenSCIONWithBindSVC("udp4", a, nil, addr.SvcCS)
> ```

This should also supply the bind address from the topology file, if present.

---

*[go/lib/snet/conn.go, line 96 at r2](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-XDvfR45B8lO-cE59N:-L-XDvfR45B8lO-cE59O:b7d7tee) ([raw file](https://github.com/scionproto/scion/blob/cef1c5b931d0d09be2e7a949647b52ab566f6207/go/lib/snet/conn.go#L96)):*
> ```Go
> 
> // DialSCIONWithBindSVC calls DialSCIONWithBindSVC on the default networking context.
> func DialSCIONWithBindSVC(network string, laddr, raddr, baddr *Addr, svc addr.HostSVC) (*Conn, error) {
> ```

Line length. (To wrap this you'll need to put the newline inside the arguments, e.g. just before `svc`).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341)*

**Comment by Oncilla** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/cert_srv/io.go, line 39 at r2](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-XMmUwVghALcWidySy:-L-_hq0mkRjpLtpeWYd4:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cef1c5b931d0d09be2e7a949647b52ab566f6207/go/cert_srv/io.go#L39)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This should also supply the bind address from the topology file, if present.
</blockquote></details>

Done.

---

*[go/lib/snet/conn.go, line 96 at r2](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-XDvfR45B8lO-cE59N:-L-_j0OnnkFn6JIbsdC_:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cef1c5b931d0d09be2e7a949647b52ab566f6207/go/lib/snet/conn.go#L96)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Line length. (To wrap this you'll need to put the newline inside the arguments, e.g. just before `svc`).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341)*

**Comment by kormat** [comment]
Reviewed 1 of 10 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/cert_srv/main.go, line 117 at r3](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-a1Urjh2qRlO1g2_2s:-L-a1UrkLbjpk1LSFqNH:b8e0es0) ([raw file](https://github.com/scionproto/scion/blob/f6602274afeae85604432982c1841798bf506337/go/cert_srv/main.go#L117)):*
> ```Go
> 	}
> 	bindInfo := topoAddr.BindAddrInfo(topo.Overlay)
> 	publicInfo := topoAddr.PublicAddrInfo(topo.Overlay)
> ```

Just to make the order a little clearer, i'd put `publicInfo :=` and `public =` before the bind handling.

---

*[go/lib/sock/reliable/reliable.go, line 147 at r3](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-a2ksx4zTVGxJqrcsf:-L-a2ksx4zTVGxJqrcsg:b5rcwci) ([raw file](https://github.com/scionproto/scion/blob/f6602274afeae85604432982c1841798bf506337/go/lib/sock/reliable/reliable.go#L147)):*
> ```Go
> // To check for timeout errors, type assert the returned error to *net.OpError and
> // call method Timeout().
> func RegisterTimeout(dispatcher string, ia *addr.ISD_AS, a, bind *AppAddr, svc addr.HostSVC,
> ```

`a` should be renamed to `public`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341)*

**Comment by Oncilla** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/cert_srv/main.go, line 117 at r3](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-a1Urjh2qRlO1g2_2s:-L-a5nssp1xhGf1GsXin:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f6602274afeae85604432982c1841798bf506337/go/cert_srv/main.go#L117)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Just to make the order a little clearer, i'd put `publicInfo :=` and `public =` before the bind handling.
</blockquote></details>

Done.

---

*[go/lib/sock/reliable/reliable.go, line 147 at r3](https://reviewable.io:443/reviews/scionproto/scion/1341#-L-a2ksx4zTVGxJqrcsf:-L-a5osocq_4X5eogfEX:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/f6602274afeae85604432982c1841798bf506337/go/lib/sock/reliable/reliable.go#L147)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

`a` should be renamed to `public`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341#-:-L-a6KCYTM0rief4g-UK:bnfp4nl)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1341)*

**Pull request merged**
