### PR TITLE
build: drop @cgrindel_bazel_starlib//updatesrc

### PR DESCRIPTION
**Pull request by oncilla**
Refactor the remaining targets that depended on @cgrindel_bazel_starlib//updatesrc. The repository has now been completely migrated to @aspect_bazel_lib//lib:write_source_files.

During the refactor, we dropped the functionality to write the source files in rules_openapi. Instead, the caller side can decide how to write the source files. This makes the rules more composable and easier to use. The functionality has been moved to a macro in private/mgmtapi/api.bzl, which is used inside of scionproto/scion.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)

### CODE REVIEW

**Review by matzf — APPROVED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427#-:-Ni1KDT2BpEuK9fH-Hrx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker and @oncilla)

___
*[`private/mgmtapi/api.bzl` line 53 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1EGvl36M6hxgKfGsp:-Ni1EGvmC994PuEGqlwl:bqvbq26) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/private/mgmtapi/api.bzl#L53)):*
> ```Starlark
>         name = name,
>         srcs = out_files,
>     )
> ```

Nit. This filegroup and the `out_files` seems redundant, it's identical to the files returned by `_opeanpi_generate_go`. I'd suggest to remove this for clarity and change the name of `_openapi_generate_go` to `name`.
___
*[`rules_openapi/defs.bzl` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1IMysDmxyemJomRqc:-Ni1IMysDmxyemJomRqd:b7w235a) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/rules_openapi/defs.bzl#L23)):*
> ```Starlark
>             '$(location " + name + "-no-header)' \
>             '$(location " + name + ".bzl.gen.yml)' \
>             '# GENERATED FILE DO NOT EDIT' \
> ```

Nit: can use `$<` and `$@` shorthand for input and output files to make this shorter. Also, might not need the helper script, just

```
cmd = "(echo '# GENERATED FILE DO NOT EDIT'; cat $<) > $@",
```

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)* status: all files reviewed, 2 unresolved discussions (waiting on @matzf)

___
*[`private/mgmtapi/api.bzl` line 53 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1EGvl36M6hxgKfGsp:-Ni3SDlx1zKtKtRWrp85:b32v57) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/private/mgmtapi/api.bzl#L53)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit. This filegroup and the `out_files` seems redundant, it's identical to the files returned by `_opeanpi_generate_go`. I'd suggest to remove this for clarity and change the name of `_openapi_generate_go` to `name`.
</blockquote></details>

+1
___
*[`rules_openapi/defs.bzl` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1IMysDmxyemJomRqc:-Ni3SB_N0XAK2zA5DYcH:b32v57) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/rules_openapi/defs.bzl#L23)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Nit: can use `$<` and `$@` shorthand for input and output files to make this shorter. Also, might not need the helper script, just

```
cmd = "(echo '# GENERATED FILE DO NOT EDIT'; cat $<) > $@",
```
</blockquote></details>

+1

**Review by oncilla — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

___
*[`private/mgmtapi/api.bzl` line 53 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1EGvl36M6hxgKfGsp:-Ni3mdNj53A0doSmPf14:b3tce3x) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/private/mgmtapi/api.bzl#L53)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Neat.

Done.
___
*[`rules_openapi/defs.bzl` line 23 at r1](https://reviewable.io/reviews/scionproto/scion/4427#-Ni1IMysDmxyemJomRqc:-Ni3n1vH4zYOdeVe0_-U:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/28ec3228470e32a713ce790b06a9ea0c7b2fe400/rules_openapi/defs.bzl#L23)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @oncilla)

**Review by oncilla — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oncilla)

**Pull request merged**
