### PR TITLE
deps: update bazel & bazel libs

### PR DESCRIPTION
**Pull request by lukedirtwalker**
Drop the `go_embed_data` custom rules, those were deprecated for a long time.
Drop most of the custom `rules_openapi` bazel rules.
Users are recommended to use their own invocations of the JS tools.

- - -
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4426)

### CODE REVIEW

**Review by oncilla — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4426#-:-Nhzxcwn9L1dqi3NVwCd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by oncilla — APPROVED** [review]
> Reviewed 43 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by oncilla — APPROVED** [review]
> Reviewed 3 of 3 files at r3, 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

**Review by matzf — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 42 of 43 files at r2, 3 of 3 files at r3, 15 of 15 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4426)* status: all files reviewed, 2 unresolved discussions (waiting on @lukedirtwalker)

___
*[`private/mgmtapi/api.bzl` line 28 at r4](https://reviewable.io/reviews/scionproto/scion/4426#-Ni4bH3j1KTpuCZ9m00t:-Ni4bH3j1KTpuCZ9m00u:b-6776sx) ([raw file](https://github.com/scionproto/scion/blob/ba52034761c1ab748c7aa662ba230c64b0510b7a/private/mgmtapi/api.bzl#L28)):*
> ```Starlark
>         srcs = [src],
>         outs = [out],
>         args = ["build-docs", "--output", "../../../$@", "../../../$(location {})".format(src)],
> ```

What are these paths? Can we instead change the working directory?
___
*[`spec/ca/BUILD.bazel` line 9 at r4](https://reviewable.io/reviews/scionproto/scion/4426#-Ni4aq1L9HL2OoS0XZkh:-Ni4aq1L9HL2OoS0XZki:b25be8a) ([raw file](https://github.com/scionproto/scion/blob/ba52034761c1ab748c7aa662ba230c64b0510b7a/spec/ca/BUILD.bazel#L9)):*
> ```Starlark
> )
> 
> copy_to_bin(
> ```

Just out of curiosity; what is the difference to a filegroup here?

**Review by lukedirtwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4426)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukedirtwalker)

___
*[`private/mgmtapi/api.bzl` line 28 at r4](https://reviewable.io/reviews/scionproto/scion/4426#-Ni4bH3j1KTpuCZ9m00t:-Ni4giRv9Eh6y53s589L:biveucv) ([raw file](https://github.com/scionproto/scion/blob/ba52034761c1ab748c7aa662ba230c64b0510b7a/private/mgmtapi/api.bzl#L28)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

What are these paths? Can we instead change the working directory?
</blockquote></details>

https://docs.aspect.build/guides/rules_js_migration/#account-for-change-to-working-directory It's needed because rules_js is a bit awkward in that respect. I don't think we could change directory.
___
*[`spec/ca/BUILD.bazel` line 9 at r4](https://reviewable.io/reviews/scionproto/scion/4426#-Ni4aq1L9HL2OoS0XZkh:-Ni4hEHb-X6hUW2AfgqH:bxlg6bw) ([raw file](https://github.com/scionproto/scion/blob/ba52034761c1ab748c7aa662ba230c64b0510b7a/spec/ca/BUILD.bazel#L9)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Just out of curiosity; what is the difference to a filegroup here?
</blockquote></details>

It's required to copy the files to bin dir for rules_js. See https://docs.aspect.build/rulesets/aspect_rules_js#running-nodejs-programs for more details (the last bullet point)

**Pull request merged**
