### PR TITLE
Use platform-independent print formats in checksum_bench.c

### LINKED ISSUE #1262: Need to adjust format strings in checksum_bench.c and dispatcher.c on 32bit ARM
As discussed with @perrig on 32bit ARM the following changes are necessary

Edit: c/lib/scion/checksum_bench.c
Need to adjust format strings in lines 43 and 60 so those lines then read:
printf("simple_test(%u = %uB): %ju in %ds (%.2lfM calls/s)\n",
printf("complex_test(8+8+2+12+1391 = 1421B): %ju in %ds (%.2lfM calls/s)\n",

In file: c/dispatcher/dispatcher.c
Edit line 872, replacing %lu with %ju:
zlog_warn(zc, "Dropped UDP packets: %ju", drop_count);

### PR DESCRIPTION
**Pull request by shitz**
Fixes #1262.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1475)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[c/lib/scion/checksum_bench.c, line 43 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FpzFzDd6WuNRxpOeV:-L9FpzFzDd6WuNRxpOeW:b-z42pfo) ([raw file](https://github.com/scionproto/scion/blob/669a4682f6e339639ccd2598755c6d1ba64c91f1/c/lib/scion/checksum_bench.c#L43)):*
> ```C
>         checksum(input);
>     }
>     printf("simple_test(%"PRIu64" = %"PRIu64"B): %"PRIu64" in %"PRId32"s (%.2lfM calls/s)\n",
> ```

There should be a space on each side of the formatting macros. E.g. `%" PRIu64 "`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[c/lib/scion/checksum_bench.c, line 43 at r1](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FpzFzDd6WuNRxpOeV:-L9Ft0eM69HeOQxEwbAg:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/669a4682f6e339639ccd2598755c6d1ba64c91f1/c/lib/scion/checksum_bench.c#L43)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There should be a space on each side of the formatting macros. E.g. `%" PRIu64 "`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[c/lib/scion/checksum_bench.c, line 44 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FtXCj0UCd4RbOIvyo:-L9FtXCj0UCd4RbOIvyp:bm0pkhu) ([raw file](https://github.com/scionproto/scion/blob/b48532b0e63ff282faa6edbe7207ab63c8e47376/c/lib/scion/checksum_bench.c#L44)):*
> ```C
>     }
>     printf("simple_test(%" PRIu64 " = %" PRIu64 "B): %" PRIu64 " in %" PRId32 "s"
> 		   " (%.2lfM calls/s)\n", sizeof(data), sizeof(data), i, RUN_TIME, 
> ```

Tabs? How could you.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by shitz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[c/lib/scion/checksum_bench.c, line 44 at r2](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FtXCj0UCd4RbOIvyo:-L9FwvWn6xrfYIX7820B:b-1g4g8v) ([raw file](https://github.com/scionproto/scion/blob/b48532b0e63ff282faa6edbe7207ab63c8e47376/c/lib/scion/checksum_bench.c#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Tabs? How could you.
</blockquote></details>

misconfigured editor fail

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[c/lib/scion/checksum_bench.c, line 44 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FyUy-AcRn31oSRJgS:-L9FyUy-AcRn31oSRJgT:b-415yq6) ([raw file](https://github.com/scionproto/scion/blob/e895436387525f87faafca6f33b5511c9f6cd2a6/c/lib/scion/checksum_bench.c#L44)):*
> ```C
>     }
>     printf("simple_test(%" PRIu64 " = %" PRIu64 "B): %" PRIu64 " in %" PRId32 "s"
>            " (%.2lfM calls/s)\n", sizeof(data), sizeof(data), i, RUN_TIME, 
> ```

Trailing whitespace.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by shitz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[c/lib/scion/checksum_bench.c, line 44 at r3](https://beta.reviewable.io/reviews/scionproto/scion/1475#-L9FyUy-AcRn31oSRJgS:-L9Fyy1E0uJR14rGEDGM:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/e895436387525f87faafca6f33b5511c9f6cd2a6/c/lib/scion/checksum_bench.c#L44)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Trailing whitespace.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/scionproto/scion/1475#-:-L9Fz66kCLYXI2Icdpyt:bnfp4nl)*

**Pull request merged**
