### PR TITLE
Publish manuals for SCION apps

### PR DESCRIPTION
**Pull request by scrye**
Also includes some Hidden Paths work and miscellaneous
fixes.

Co-authored-by: <hitz@anapaya.net>
Co-authored-by: <karampogias@anapaya.net>
Co-authored-by: <roos@anapaya.net>
Co-authored-by: <vogel@anapaya.net>

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)

### CODE REVIEW

**Review by matzf — COMMENTED** [review]
> Reviewed 14 of 105 files at r1.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 14 of 105 files reviewed, 2 unresolved discussions (waiting on @scrye)

___
*[go/pkg/gateway/pathhealth/selector.go, line 127 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAHcM6Gwu3puIL_SB:-MMyAHcM6Gwu3puIL_SC:b-kyxvyj) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/gateway/pathhealth/selector.go#L127)):*
> ```Go
> 	for i := 0; i < pathCount; i++ {
> 		paths = append(paths, allowed[i].Path)
> 	}
> ```

This change does not _look_ right. I don't know the context here, so I may be wrong, but it _looks_ wrong.
___
*[go/pkg/sciond/internal/servers/grpc.go, line 267 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAtkY6UxxVD_Mo7yJ:-MMyAtkZ8t8Y1JHPqwZi:b-w73e9a) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/sciond/internal/servers/grpc.go#L267)):*
> ```Go
> 	}
> 	topo := s.TopoProvider.Get()
> 	serviceTypes := []topology.ServiceType{topology.Control, topology.Gateway}
> ```

This is a breaking change, isn't it? The strings are different.

**Review by scrye — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 14 of 105 files reviewed, 2 unresolved discussions (waiting on @matzf and @scrye)

___
*[go/pkg/gateway/pathhealth/selector.go, line 127 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAHcM6Gwu3puIL_SB:-MMyJGQCBSJDnWNQKezx:b-nga64j) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/gateway/pathhealth/selector.go#L127)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This change does not _look_ right. I don't know the context here, so I may be wrong, but it _looks_ wrong.
</blockquote></details>

Oh, wow, great catch! That is indeed a mistake, I'll fix it when I fix the gateway tests.
___
*[go/pkg/sciond/internal/servers/grpc.go, line 267 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAtkY6UxxVD_Mo7yJ:-MMyHyDl7OnP1jTUnXYD:bhahqni) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/sciond/internal/servers/grpc.go#L267)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This is a breaking change, isn't it? The strings are different.
</blockquote></details>

It shouldn't be breaking, because those strings are never used directly in topology files/packets. Our file generator tests didn't see any diffs after this change.

It's breaking on some low-level package APIs (the topology package API, for example), but those have never been stable anyway.

Hope I understood what you meant, but if not, please let me know.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 14 of 105 files reviewed, 2 unresolved discussions (waiting on @matzf and @scrye)

___
*[go/pkg/sciond/internal/servers/grpc.go, line 267 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAtkY6UxxVD_Mo7yJ:-MMyOQvF0Pq4mr9pwQXe:bx00lmo) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/sciond/internal/servers/grpc.go#L267)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

It shouldn't be breaking, because those strings are never used directly in topology files/packets. Our file generator tests didn't see any diffs after this change.

It's breaking on some low-level package APIs (the topology package API, for example), but those have never been stable anyway.

Hope I understood what you meant, but if not, please let me know.

</blockquote></details>

Sorry, my comment should have been clearer.
It was meant as a comment here on the Services request of sciond; as far as I understand, the reply to this request uses the service type strings as keys (`reply.Services[t.String()] = ...`, just below this comment). As these strings are changed here, an "old" application may not be able to understand the response of a "new" sciond.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 14 of 105 files reviewed, 3 unresolved discussions (waiting on @matzf and @scrye)

___
*[doc/manuals/gateway.rst, line 385 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyUI_r3ORyVdpDNUBG:-MMyUI_s6GFwnH-hV87L:b-yfro4j) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/doc/manuals/gateway.rst#L385)):*
> ```reStructuredText
> announced, accepted, and rejected. For more information about dynamic IP prefix
> discovery in the gateway, have a look at the `design document
> <src/dev/design_docs/gateway-ip-exchange.html>`_.
> ```

This document does not seem to be publicly available.

**Comment by scrye** [comment]
___
*[go/pkg/sciond/internal/servers/grpc.go, line 267 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyAtkY6UxxVD_Mo7yJ:-MMyahIr19M8zRVPW9-K:bpbz6h0) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/go/pkg/sciond/internal/servers/grpc.go#L267)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

Sorry, my comment should have been clearer.
It was meant as a comment here on the Services request of sciond; as far as I understand, the reply to this request uses the service type strings as keys (`reply.Services[t.String()] = ...`, just below this comment). As these strings are changed here, an "old" application may not be able to understand the response of a "new" sciond. 
</blockquote></details>

You're right! I didn't realize that this was protocol-breaking.

As per our discussion on Slack, I've created https://github.com/scionproto/scion/issues/3939 to prevent this from happening in the future. PTAL and let me know if it matches what we discussed.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 13 of 104 files reviewed, 4 unresolved discussions (waiting on @matzf and @scrye)

___
*[doc/manuals/gateway.rst, line 66 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyf23Y5S9hQwWb_ia-:-MMyf23Y5S9hQwWb_ia0:b-1hk2e1) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/doc/manuals/gateway.rst#L66)):*
> ```
>  The default is latency.
> ```
For the `LegacySessionPolicyAdapter` the default seems to "fingerprint order" -- which luckily seems to be ignored and the shorter paths (number of hops) are preferred.

**Comment by scrye** [comment]
___
*[doc/manuals/gateway.rst, line 385 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyUI_r3ORyVdpDNUBG:-MMykk6EDu9hTJ69I3lk:bc4l91m) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/doc/manuals/gateway.rst#L385)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

This document does not seem to be publicly available.
</blockquote></details>

Removed the link because we're probably not going to release that doc (too hard to keep it up to date, so it might be misleading).

**Review by scrye — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: 13 of 104 files reviewed, 4 unresolved discussions (waiting on @matzf and @scrye)

___
*[doc/manuals/gateway.rst, line 66 at r1](https://reviewable.io/reviews/scionproto/scion/3938#-MMyf23Y5S9hQwWb_ia-:-MMym2Sp4VvvPuxuvRLU:bk0x8mh) ([raw file](https://github.com/scionproto/scion/blob/fb1f3404cf77683473e2173317eee45c75621964/doc/manuals/gateway.rst#L66)):*
<details><summary><i>Previously, matzf (Matthias Frei) wrote…</i></summary><blockquote>

> ```
>  The default is latency.
> ```
For the `LegacySessionPolicyAdapter` the default seems to "fingerprint order" -- which luckily seems to be ignored and the shorter paths (number of hops) are preferred.
</blockquote></details>

Removed the sentence because it doesn't belong in a nomenclature section.

**Review by scrye — COMMENTED** [review]
> Reviewed 102 of 105 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3938)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
