### PR TITLE
Change sciond default listening socket, FIXES #1644

### LINKED ISSUE #1644: sciond: python sciond should default to default.sock
As of recently, applications expect sciond to be listening on `/run/shm/sciond/default.sock`, but that is _not_ sciond's default. It defaults to `/run/shm/sciond/<ISD>-<AS>.sock`. We should fix that.

### PR DESCRIPTION
**Pull request by lukedirtwalker**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646)

### CODE REVIEW

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646#-:-LGVCkr-4RbjOe8Il8y6:bnfp4nl)*

**Comment by kormat** [comment]
Ah, don't put the "fixes" in the subject line, put that in the commit body instead.

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646#-:-LGVCseS3X9Td0YuV7V0:b-aeu41y)*

**Comment by shitz** [comment]
Review status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker)

---

*[python/bin/sciond, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1646#-LGVDFcq-8a4WgIZkqVL:-LGVDFcq-8a4WgIZkqVM:b-sr20mj) ([raw file](https://github.com/scionproto/scion/blob/c301b3f662c10589fdf1f1664da399a718d44b4b/python/bin/sciond#L39)):*
> ```
>     parser.add_argument('--api-addr',
>                         help='Address to bind to (Default: %s)' %
>                         os.path.join(SCIOND_API_SOCKDIR, "default.sock"))
> ```

Use `get_default_sciond_path()` from `python/lib/app/sciond.py` instead of `os.path.join(...)`

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646)*

**Comment by lukedirtwalker** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kormat and @shitz)

---

*[python/bin/sciond, line 39 at r1](https://reviewable.io/reviews/scionproto/scion/1646#-LGVDFcq-8a4WgIZkqVL:-LGVI8GG7H_xK8SxhNoq:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/c301b3f662c10589fdf1f1664da399a718d44b4b/python/bin/sciond#L39)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Use `get_default_sciond_path()` from `python/lib/app/sciond.py` instead of `os.path.join(...)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646)*

**Comment by shitz** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/scionproto/scion/1646#-:-LGVIHk064J7RUqvsswZ:bnfp4nl)*

**Pull request merged**
