### PR TITLE
acceptance: bazelify remaining tests, cleanup python framework

### PR DESCRIPTION
**Pull request by matzf**
* drop the `reconnecting` case -- this was a false positive that cannot be fixed easily.

  The test tried to restart the dispatcher for the control service, to see that reconnecting to the dispatcher works. Unfortunately, with the docker-compose file created by topogen, the control service container uses the dispatcher's network context (`network_mode: service:scion_disp_cs_...`). In this configuration, network access never recovers after referenced container goes away. This test cannot be made to work without changing the topogen docker-compose setup, which does not seem to be worth the trouble.
    
  The test had been passing because it used a bad regex to that failed to match the dispatchers it tried restart.
  
  This test could be replaced with a more focused integration test that checks the interaction of the reconnector logic with a restarted dispatcher.
  
* bazelify remaining acceptance test case `trc_update`

* remove bash-based legacy acceptance framework

* simplification and cleanup pass over the acceptance/common python framework

Based on #4182

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4183)

### CODE REVIEW

**Review by oncilla — CHANGES_REQUESTED** [review]
> Reviewed 12 of 43 files at r1, 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4183)* status: 12 of 43 files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker, @matzf, and @oncilla)

___
*[`acceptance/common/base.py` line 177 at r4](https://reviewable.io/reviews/scionproto/scion/4183#-N3Djf9G6qXYS9EPHxzp:-N3Djf9G6qXYS9EPHxzq:b-uh5tfs) ([raw file](https://github.com/scionproto/scion/blob/36ac616cb98acd96db2c91784fcc5845d04ac894/acceptance/common/base.py#L177)):*
> ```Python
>         """Starts the docker containers in the topology.
>         """
>         self.dc = docker.Compose(compose_file=self.artifacts / "gen/scion-dc.yml")
> ```

This will only set up docker compose for the setup target if you run the individual steps with bazel run.

```
$ bazel run //acceptance/cert_renewal:test_run
...
2022-05-29 09:35:37,327 [INFO    ] ==> Start renewal process
2022-05-29 09:35:37,328 [INFO    ] ===> Start renewal: 1-ff00:0:110
Traceback (most recent call last):
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/common/base.py", line 232, in main
    self._run()
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/cert_renewal/test.py", line 64, in _run
    self._renewal_request(isd_as)
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/cert_renewal/test.py", line 123, in _renewal_request
    "echo $SCION_DAEMON").strip(),
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/common/base.py", line 200, in execute_tester
    return self.dc.execute("tester_%s" % isd_as.file_fmt(), cmd, *args)
AttributeError: '_TestRun' object has no attribute 'dc'
```

I suggest we do the following:

```py
class TestBase:

    # ...

    def _cmd_prepare(self):
        pass

class TestTopogen(TestBase):

    # ...

    def _cmd_prepare(self):
        self.dc = docker.Compose(compose_file=self.artifacts /
                                 "gen/scion-dc.yml")

def main(test_class):
    log.init_log()

    class _TestMain(test_class, cli.Application):
        __doc__ = test_class.__doc__

        def main(self):
            if self.nested_command:
                return
            try:
                self._cmd_prepare()
                self.setup()
                self._run()
            except Exception:
                traceback.print_exc()
                return 1
            finally:
                self.teardown()

    class _TestSetup(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self.setup()
            except Exception:
                traceback.print_exc()
                return 1

    class _TestRun(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self._run()
            except Exception:
                traceback.print_exc()
                return 1

    class _TestTeardown(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self.teardown()
            except Exception:
                traceback.print_exc()
                return 1
```

**Review by oncilla — COMMENTED** [review]
> Reviewed 17 of 43 files at r1, 2 of 3 files at r2, 1 of 2 files at r3, 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @matzf)

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @lukedirtwalker and @oncilla)

___
*[`acceptance/common/base.py` line 177 at r4](https://reviewable.io/reviews/scionproto/scion/4183#-N3Djf9G6qXYS9EPHxzp:-N3IsKC51huu0lKsOn4-:b-o1c9wz) ([raw file](https://github.com/scionproto/scion/blob/36ac616cb98acd96db2c91784fcc5845d04ac894/acceptance/common/base.py#L177)):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

This will only set up docker compose for the setup target if you run the individual steps with bazel run.

```
$ bazel run //acceptance/cert_renewal:test_run
...
2022-05-29 09:35:37,327 [INFO    ] ==> Start renewal process
2022-05-29 09:35:37,328 [INFO    ] ===> Start renewal: 1-ff00:0:110
Traceback (most recent call last):
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/common/base.py", line 232, in main
    self._run()
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/cert_renewal/test.py", line 64, in _run
    self._renewal_request(isd_as)
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/cert_renewal/test.py", line 123, in _renewal_request
    "echo $SCION_DAEMON").strip(),
  File "/home/roosd/.cache/bazel/_bazel_roosd/116cb6780c33e2c551cf52a759380c7b/execroot/com_github_scionproto_scion/bazel-out/k8-fastbuild/bin/acceptance/cert_renewal/test_run.runfiles/com_github_scionproto_scion/acceptance/common/base.py", line 200, in execute_tester
    return self.dc.execute("tester_%s" % isd_as.file_fmt(), cmd, *args)
AttributeError: '_TestRun' object has no attribute 'dc'
```

I suggest we do the following:

```py
class TestBase:

    # ...

    def _cmd_prepare(self):
        pass

class TestTopogen(TestBase):

    # ...

    def _cmd_prepare(self):
        self.dc = docker.Compose(compose_file=self.artifacts /
                                 "gen/scion-dc.yml")

def main(test_class):
    log.init_log()

    class _TestMain(test_class, cli.Application):
        __doc__ = test_class.__doc__

        def main(self):
            if self.nested_command:
                return
            try:
                self._cmd_prepare()
                self.setup()
                self._run()
            except Exception:
                traceback.print_exc()
                return 1
            finally:
                self.teardown()

    class _TestSetup(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self.setup()
            except Exception:
                traceback.print_exc()
                return 1

    class _TestRun(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self._run()
            except Exception:
                traceback.print_exc()
                return 1

    class _TestTeardown(test_class, cli.Application):
        def main(self):
            try:
                self._cmd_prepare()
                self.teardown()
            except Exception:
                traceback.print_exc()
                return 1
```


</blockquote></details>

Ah, you're right of course, this is a mistake.

The intention was that (in the normal "full" test execution), we avoid attempting to run the full docker-compose teardown if something fails in `setup_prepare` (e.g. the topogen scripts, or test-specific custom code). In such a case, trying to do the docker-compose teardown will just create more errors, distracting from the original issue.

I've now added a `try` block around `setup_prepare` to explicitly deal with this case. I've slightly restructured a bunch of tests, making them overwrite `setup_prepare` and `setup_start` individually, instead of `setup`, to make this exception handler logic apply.
Now this works as expected for `bazel run //...:run` and `bazel run //...:teardown`, and still handles "prepare failures" somewhat gracefully when just running the full test with `bazel test //...:test`.

Instead of `_cmd_prepare`, I've called the new initialization point `init`.

**Review by lukedirtwalker — APPROVED** [review]
Agreed on removing the `plumbum.cli`, I think we should eventually get rid of the dependency all-together.

> Reviewed 24 of 43 files at r1, 3 of 3 files at r2, 1 of 2 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4183#-:-N3J3czR7CV8uXOz2raT:b58lma5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Pull request merged**
