### PR TITLE
Export SIG config version as uint

### PR DESCRIPTION
**Pull request by scrye**
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1434)

### CODE REVIEW

**Comment by kormat** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/sig/sig.go, line 151 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHDyDs0Txq2YvcI5_:-L6qHDyDs0Txq2YvcI5a:bwyngvv) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/sig.go#L151)):*
> ```Go
> 		return false
> 	}
> 	atomic.StoreUint64(&metrics.ConfigVersion, cfg.ConfigVersion)
> ```

There's a disconnect here between "last config version read from disk", and "config applied". The latter is more likely to be useful, which implies doing `ReloadConfig` and checking it succeeded before updating the exported version.

---

*[go/sig/metrics/metrics.go, line 42 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHYmKEdESfCpQYmTP:-L6qHYmKEdESfCpQYmTQ:bjevrgu) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L42)):*
> ```Go
> // Declare prometheus metrics to export.
> var (
> 	ConfigVersion      uint64 // write this atomically
> ```

This is not a prometheus metric, so at a minimum it shouldn't be in this `var` block.

---

*[go/sig/metrics/metrics.go, line 106 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHhktwXJ3GcyZuvuZ:-L6qHhktwXJ3GcyZuvu_:b9rgo77) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L106)):*
> ```Go
> 	}
> 	log.Info("Exporting prometheus metrics", "addr", *promAddr)
> 	http.HandleFunc("/version", func(w http.ResponseWriter, req *http.Request) {
> ```

This url is a bit generic, it would be easy to assume it refers to the _software_ version, rather than config version.

---

*[go/sig/metrics/metrics.go, line 107 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qIs4P9bpgc5zcldOh:-L6qIs4P9bpgc5zcldOi:b-u5nusu) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L107)):*
> ```Go
> 	log.Info("Exporting prometheus metrics", "addr", *promAddr)
> 	http.HandleFunc("/version", func(w http.ResponseWriter, req *http.Request) {
> 		fmt.Fprint(w, ConfigVersion)
> ```

Add a newline to the end, to make it a little easier to work with by hand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1434)*

**Comment by scrye** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/sig/sig.go, line 151 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHDyDs0Txq2YvcI5_:-L6qJP1do7epfZIl080u:b-a17m43) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/sig.go#L151)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

There's a disconnect here between "last config version read from disk", and "config applied". The latter is more likely to be useful, which implies doing `ReloadConfig` and checking it succeeded before updating the exported version.
</blockquote></details>

There's no rollback though, so you end up with some changes from the new config, but the number is the old one.

---

*[go/sig/metrics/metrics.go, line 42 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHYmKEdESfCpQYmTP:-L6qJVHMjtmmc3A9Njam:b-1e3w2l) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L42)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This is not a prometheus metric, so at a minimum it shouldn't be in this `var` block.
</blockquote></details>

`http` server runs from here, so I left it in the file.

---

*[go/sig/metrics/metrics.go, line 106 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHhktwXJ3GcyZuvuZ:-L6qJjfUxzIUkQRykLYx:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L106)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

This url is a bit generic, it would be easy to assume it refers to the _software_ version, rather than config version.
</blockquote></details>

Done.

---

*[go/sig/metrics/metrics.go, line 107 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qIs4P9bpgc5zcldOh:-L6qJjXhk3SfLkJscoUG:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/metrics/metrics.go#L107)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Add a newline to the end, to make it a little easier to work with by hand.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1434)*

**Comment by kormat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sig/sig.go, line 151 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHDyDs0Txq2YvcI5_:-L6qJu_srMwjHlFztdnw:b-xb7x2p) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/sig.go#L151)):*
<details><summary><i>Previously, scrye (Sergiu Costea) wrote…</i></summary><blockquote>

There's no rollback though, so you end up with some changes from the new config, but the number is the old one.
</blockquote></details>

Right. But this is being used to check if the new config version was deployed succesfully. In the case of a partial update, displaying the old number would at least signal there was a problem, and prompt an investigation. Updating the number regardless of whether the config loaded or not means it's not useful for that purpose. Alternatively, we export two pieces of data: the last config version loaded, and a bool indicating loading success. A json format would make this easy to work with.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1434)*

**Comment by scrye** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sig/sig.go, line 151 at r1](https://reviewable.io:443/reviews/scionproto/scion/1434#-L6qHDyDs0Txq2YvcI5_:-L6qKhP6cYLAp-CLOdEG:blq4bpy) ([raw file](https://github.com/scionproto/scion/blob/cd01323f1d31fb1239c56e57095388e3612ae489/go/sig/sig.go#L151)):*
<details><summary><i>Previously, kormat (Stephen Shirley) wrote…</i></summary><blockquote>

Right. But this is being used to check if the new config version was deployed succesfully. In the case of a partial update, displaying the old number would at least signal there was a problem, and prompt an investigation. Updating the number regardless of whether the config loaded or not means it's not useful for that purpose. Alternatively, we export two pieces of data: the last config version loaded, and a bool indicating loading success. A json format would make this easy to work with.
</blockquote></details>

Having a single number is simpler. It's now only updated on success.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1434)*

**Comment by kormat** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1434#-:-L6qMC2NYl_WbfGS6qBu:bnfp4nl)*

**Pull request merged**
