### PR TITLE
topology: allow peering links between core ASes

### LINKED ISSUE #4484: topology: allow peering links between core-ASes
Currently, the topology loader forbids core ASes from having peering links (i.e. links with `"link_to": "peer"`). The validation check is here: https://github.com/scionproto/scion/blob/4a8bc98ec7d969dd622c5a90fe677e3c980aaa88/private/topology/topology.go#L544-L550.
As far as I'm aware, there is no technical reason why core ASes cannot have peering links. 
Core ASes should be able to have peering links to any other AS, i.e. to both core or non-core ASes in both the same or different ISDs.

### PR DESCRIPTION
**Pull request by jiceatscion**
Fixes #4484

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @jiceatscion)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5s3rSN0i7QcdclKMLW:b90j8du) (no related file):*
Could we get a test that ensures it actually works end to end too?

We need to ensure beaconing actually includes these links, and that the path combinator finds them.

___

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5s6IIA9hWFRpKf4UEL:b-x9bpny) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

Could we get a test that ensures it actually works end to end too?

We need to ensure beaconing actually includes these links, and that the path combinator finds them.
</blockquote></details>

Fair request. While I do that, would you happen to have an idea why the end-2-end tests have become so flaky. It's getting near impossible to get them to pass. What I've found so far is that right after "awaitconnectivity" it still takes up to 20 seconds for all the up segments to get turned around and registered as down segments (something that awaitconnectivity does not check"). I still do not know what's taking so long. I'm adding a 20s sleep at the end of awaitconnectivity in the mean-time so we can continue making PRs.

___

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @jiceatscion)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5s7IIt6IK3w29akJvI:bzfells) (no related file):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Fair request. While I do that, would you happen to have an idea why the end-2-end tests have become so flaky. It's getting near impossible to get them to pass. What I've found so far is that right after "awaitconnectivity" it still takes up to 20 seconds for all the up segments to get turned around and registered as down segments (something that awaitconnectivity does not check"). I still do not know what's taking so long. I'm adding a 20s sleep at the end of awaitconnectivity in the mean-time so we can continue making PRs.
</blockquote></details>

I do not know, what you could try to do is to look at the distributed traces.
There should be a jaeger instance running, and all RPCs + control internal processes are tracked there.

___

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5sA11t7tmS8oCng_YO:b-2upu05) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

I do not know, what you could try to do is to look at the distributed traces.
There should be a jaeger instance running, and all RPCs + control internal processes are tracked there.
</blockquote></details>

Yup...I's trying not to get to that :-)

___

**Review by oncilla — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @jiceatscion)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5sG5Vf82XPJwyJBMjh:b-pydz0h) (no related file):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Yup...I's trying not to get to that :-)
</blockquote></details>

It is the first place I reach for if things don't work. Really powerful tool.

___

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4605)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @FR4NK-W and @oncilla)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/4605#-O5s3rSN0i7QcdclKMLV:-O5y4ZDq4_9M7I-fes00:b5zll4y) (no related file):*
<details><summary><i>Previously, oncilla (Dominik Roos) wrote…</i></summary><blockquote>

It is the first place I reach for if things don't work. Really powerful tool.
</blockquote></details>

Back to the main topic. Your suspicion was right. Adding a beaconning test revealed that core ASes assume they don't have peering links to include. That's now fixed. Plus the tests. The combinator had no issue.

___

**Pull request merged**
