### PR TITLE
Add CertChain verification based on TRC

### PR DESCRIPTION
**Pull request by Oncilla**
Verify core certificate based on a trusted TRC.

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/1373)

### CODE REVIEW

**Comment by shitz** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/crypto/cert/chain.go, line 92 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eYJowSC943FZvT9R_:-L2eYJowSC943FZvT9Ra:b-gaj8oi) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/go/lib/crypto/cert/chain.go#L92)):*
> ```Go
> 	if c.Leaf.IssuingTime < c.Core.IssuingTime || c.Leaf.ExpirationTime > c.Core.ExpirationTime {
> 		return common.NewBasicError(LeafCertInvalid, nil, "err",
> 			"validity period not covered by core certificate")
> ```

This should include the validity period for the leaf and the core AS cert. Same for the Python code.

---

*[python/lib/crypto/certificate_chain.py, line 90 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eY8dwYRZ8KfTvv1yP:-L2eY8dwYRZ8KfTvv1yQ:bigpu8w) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/python/lib/crypto/certificate_chain.py#L90)):*
> ```Python
>     def __init__(self, cert_list):
>         """
>         :param [Certificate] cert_list: certificate chain as list.
> ```

This you would write as `list(Certificate)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373)*

**Comment by Oncilla** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/lib/crypto/cert/chain.go, line 92 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eYJowSC943FZvT9R_:-L2elu9k9bU38QP-GqK8:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/go/lib/crypto/cert/chain.go#L92)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This should include the validity period for the leaf and the core AS cert. Same for the Python code.
</blockquote></details>

Done.

---

*[python/lib/crypto/certificate_chain.py, line 90 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eY8dwYRZ8KfTvv1yP:-L2elukJv6b_OGu9BbHa:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/python/lib/crypto/certificate_chain.py#L90)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

This you would write as `list(Certificate)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373)*

**Comment by shitz** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/crypto/cert/chain.go, line 92 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eYJowSC943FZvT9R_:-L3-2WyQg_D0jrhhrUwH:bf7zicw) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/go/lib/crypto/cert/chain.go#L92)):*
<details><summary><i>Previously, Oncilla wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually I would prefer if you'd separate these two checks, i.e., you'd first check for `c.Leaf.IssuingTime < c.Core.IssuingTime` and emit and error `"leaf certificate issued before core certificate", "leaf", timeToString(c.Leaf.IssuingTime), "core", timeToString(c.Core.IssuingTime)` and the analog for the other condition. Then also get rid of `ValPeriodString()`. Same for python.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373)*

**Comment by Oncilla** [comment]
Review status: 2 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/lib/crypto/cert/chain.go, line 92 at r1](https://reviewable.io:443/reviews/scionproto/scion/1373#-L2eYJowSC943FZvT9R_:-L3-J9WMgrgGjDzKA7fy:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/a5994abbce50e7301c5db38716b5fa6096b0b7c7/go/lib/crypto/cert/chain.go#L92)):*
<details><summary><i>Previously, shitz wrote…</i></summary><blockquote>

Actually I would prefer if you'd separate these two checks, i.e., you'd first check for `c.Leaf.IssuingTime < c.Core.IssuingTime` and emit and error `"leaf certificate issued before core certificate", "leaf", timeToString(c.Leaf.IssuingTime), "core", timeToString(c.Core.IssuingTime)` and the analog for the other condition. Then also get rid of `ValPeriodString()`. Same for python.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373)*

**Comment by shitz** [comment]
:lgtm:

---

Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373#-:-L3-Jr8HKkXFV4wLtDOd:bnfp4nl)*

**Comment by shitz** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/scionproto/scion/1373)*

**Pull request merged**
