### PR TITLE
doc: update beacon metadata extension docs

### PR DESCRIPTION
**Pull request by matzf**
Update beacon metadata docs after various changes to the implementation,
in particular changes done to the data representation when converting the
beacon extension to protobuf/gRPC.

Rewrite parts of the introduction, add (better) illustrations for the data included in the beacons.
The new figures were created with draw.io, the source file is `beacon-metadata.xml`.

[doc]

---
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)

### CODE REVIEW

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3963#-MR4Swhe4flV_8e-O-zZ:-MR4Swhe4flV_8e-O-z_:bxhuuzv) (no related file):*
hi @matzf thanks for the PR, we currently have a few high prio tasks internally, so we will only be able to review this later, I estimate roughly in 1.5 weeks.

---

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)* status: all files reviewed, 5 unresolved discussions (waiting on @matzf)

___
*[doc/beacon-metadata.rst, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4ct0mDtDrsHkSHB7d:-MT4ct0n2cnaBoldyhN2:b36i2rx) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L22)):*
> ```
> is typically this is on the order
> ```
is typically on the order

or 

typically is on the order
___
*[doc/beacon-metadata.rst, line 46 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4eI444HDJlb0FkmrK:-MT4eI444HDJlb0FkmrL:bu05hne) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L46)):*
> ```
> end-end
> ```
end-to-end ?
___
*[doc/beacon-metadata.rst, line 47 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4ePh_0PLGS2LB5NR4:-MT4ePh_0PLGS2LB5NR5:btg0mmd) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L47)):*
> ```
> corresponding
> ```
correspond
___
*[doc/beacon-metadata.rst, line 174 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4gheZ9iOpOWAjW6xK:-MT4gheZ9iOpOWAjW6xL:b-6h8jxx) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L174)):*
> ```
> black list.
> ```
block list
___
*[doc/conf.py, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4kfYYDVdpmHJyFPZF:-MT4kfYZ4lP1HZ9raqnB:b-z9yrrq) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/conf.py#L22)):*
> ```
> 2020
> ```
maybe also update that.

**Review by matzf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @lukedirtwalker)

___
*[doc/beacon-metadata.rst, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4ct0mDtDrsHkSHB7d:-MT4sQC0DdlOfdxrWTe5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L22)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> is typically this is on the order
> ```
is typically on the order

or 

typically is on the order
</blockquote></details>

Done.
___
*[doc/beacon-metadata.rst, line 46 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4eI444HDJlb0FkmrK:-MT4ssWs93Ffqb_e5KFi:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L46)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> end-end
> ```
end-to-end ?
</blockquote></details>

Done.
___
*[doc/beacon-metadata.rst, line 47 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4ePh_0PLGS2LB5NR4:-MT4sUS1BugCuFCDy0Y5:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L47)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> corresponding
> ```
correspond
</blockquote></details>

Done.
___
*[doc/beacon-metadata.rst, line 174 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4gheZ9iOpOWAjW6xK:-MT4sXbiDeVbgItMB1vQ:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/beacon-metadata.rst#L174)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> black list.
> ```
block list
</blockquote></details>

Done.
___
*[doc/conf.py, line 22 at r2](https://reviewable.io/reviews/scionproto/scion/3963#-MT4kfYYDVdpmHJyFPZF:-MT4sdt5E7Djtyzzxsso:b-896fix) ([raw file](https://github.com/scionproto/scion/blob/ea4457ee3b6cdfbcb6c72f42e16e67ef507d2d52/doc/conf.py#L22)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

> ```
> 2020
> ```
maybe also update that.
</blockquote></details>

Done.

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukedirtwalker — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/3963)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matzf)

*[a discussion](https://reviewable.io/reviews/scionproto/scion/3963#-MT5Jk2K1vck7KSX3978:-MT5Jk2K1vck7KSX3979:b-8ze53i) (no related file):*
Thanks, :lgtm:, I'll merge it shortly.

---

**Pull request closed without merging**
