### PR TITLE
lint: update flake8 linter

### PR DESCRIPTION
**Pull request by matzf**
Update flake8 from antiquated 3.8.4 to latest version 7.0.0. 
This allows to use modern python syntax that the old flake8 was choking on; in particular, the old version broke on expressions with a backslash in f-strings (which were forbidden in python 3.6, but allowed later).

### CODE REVIEW

**Comment by matzf** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4513)

**Review by jiceatscion — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Review by jiceatscion — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4513)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @matzf)

**Comment by matzf** [comment]
Note for posterity: this needed a fixup, #4514. Also, to make this doubly embarrassing, it does not achieve what I claimed; the f-strings with backslashes still raise a syntax error. This will accepted only once we update to Python 3.12 (currently 3.10).

**Pull request merged**
