### PR TITLE
build: do not run pip install outside the bazel build framework

### PR DESCRIPTION
**Pull request by jiceatscion**
I was sick and tired of stepping on that Lego every time I built on a new machine...

make mocks, was running mocks.py directly instead of calling bazel run. That used whatever ambient python and libraries to match instead of the python env specified by WORKSPACE, which meant that we had to include pip install in the tools/install_deps process, which often enough would fail or require no-end of messy work-arounds (e.g. create a python venv and remember to activate it before building - but just the mocks).

### CODE REVIEW

**Comment by jiceatscion** [comment]
This change is [Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Review by lukedirtwalker — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: all files reviewed, 1 unresolved discussion (waiting on @jiceatscion and @JordiSubira)

___
*[`tools/supervisorctl.py` line 5 at r5](https://reviewable.io/reviews/scionproto/scion/4647#-OATEz4Q7O-RNksVrU_B:-OATEz4Q7O-RNksVrU_C:b-a7v15e) ([raw file](https://github.com/scionproto/scion/blob/7e647f7588aee0781424a0ac58121adbc8e2e748/tools/supervisorctl.py#L5)):*
> ```Python
> 
> # This is exact replica of supervisord's entry point because I haven't
> # found an intelligible way of creating a py_binary target that doesn't
> ```

have you seen https://rules-python.readthedocs.io/en/latest/api/rules_python/python/entry_points/py_console_script_binary.html#py_console_script_binary.binary_rule ?

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: all files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @lukedirtwalker)

___
*[`tools/supervisorctl.py` line 5 at r5](https://reviewable.io/reviews/scionproto/scion/4647#-OATEz4Q7O-RNksVrU_B:-OATG3VXB2m920hBYe3z:beq4zvb) ([raw file](https://github.com/scionproto/scion/blob/7e647f7588aee0781424a0ac58121adbc8e2e748/tools/supervisorctl.py#L5)):*
<details><summary><i>Previously, lukedirtwalker (Lukas Vogel) wrote…</i></summary><blockquote>

have you seen https://rules-python.readthedocs.io/en/latest/api/rules_python/python/entry_points/py_console_script_binary.html#py_console_script_binary.binary_rule ?
</blockquote></details>

Had seen the page but not recognized this section as relevant to my case. (I was also seriously running out of patience with the whole thing). I'll give that a try. See if I can make it work.

**Review by jiceatscion — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @JordiSubira and @lukedirtwalker)

___
*[`tools/supervisorctl.py` line 5 at r5](https://reviewable.io/reviews/scionproto/scion/4647#-OATEz4Q7O-RNksVrU_B:-OATJGGs9KTH1aJ-yUPV:b-a2mh6s) ([raw file](https://github.com/scionproto/scion/blob/7e647f7588aee0781424a0ac58121adbc8e2e748/tools/supervisorctl.py#L5)):*
<details><summary><i>Previously, jiceatscion wrote…</i></summary><blockquote>

Had seen the page but not recognized this section as relevant to my case. (I was also seriously running out of patience with the whole thing). I'll give that a try. See if I can make it work.
</blockquote></details>

seems to work. so, done

**Review by lukedirtwalker — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/scionproto/scion/4647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JordiSubira)

**Pull request merged**
